// packages/ui-kit/src/data/PixelKbd.tsx
import React from 'react';
import { kbdClasses } from '@pxlkit/ui-kit-core';
import { Surface, useEffectiveSurface } from '../common';

/* ─────────────────────────────────────────────────────────────────────────
   PixelKbd — styled keyboard shortcut indicator.
   ───────────────────────────────────────────────────────────────────────── */

export interface PixelKbdProps {
  /** Key label (e.g. "⌘", "K", "Esc"). */
  children: React.ReactNode;
  /** Visual surface override. */
  surface?: Surface;
}

export function PixelKbd({
  children,
  surface: surfaceProp,
}: PixelKbdProps) {
  const surface = useEffectiveSurface(surfaceProp);
  return (
    <kbd className={kbdClasses(surface)}>
      {children}
    </kbd>
  );
}

// packages/ui-kit-vue/src/data/PixelKbd.vue
<script setup lang="ts">
import { computed, type VNode } from 'vue';
import { kbdClasses, type Surface } from '@pxlkit/ui-kit-core';
import { useEffectiveSurface } from '../composables/surface.js';

/** Keyboard key (`<kbd>`) drawn as a keycap, framed and shadowed per surface. */
export interface PixelKbdProps {
  /** Visual surface override. */
  surface?: Surface;
}

const props = withDefaults(defineProps<PixelKbdProps>(), { surface: undefined });
defineSlots<{
  /** Key label (`⌘`, `K`, `Esc`). */
  default?(): VNode[];
}>();

const surface = useEffectiveSurface(() => props.surface);
const classes = computed(() => kbdClasses(surface.value));
</script>

<template>
  <kbd :class="classes"><slot /></kbd>
</template>
