// packages/ui-kit/src/data/PixelColorSwatch.tsx
import React from 'react';
import { colorSwatchClasses, colorSwatchFill } from '@pxlkit/ui-kit-core';
import { Surface, useEffectiveSurface } from '../common';

/* ─────────────────────────────────────────────────────────────────────────
   PixelColorSwatch — design token preview with CSS var label.
   ───────────────────────────────────────────────────────────────────────── */

export interface PixelColorSwatchProps {
  /** Display name for the token (e.g. "Cyan 500"). */
  name: string;
  /** CSS variable to preview (e.g. "--retro-cyan"). */
  cssVar: string;
  /** Visual surface override. */
  surface?: Surface;
}

export function PixelColorSwatch({
  name,
  cssVar,
  surface: surfaceProp,
}: PixelColorSwatchProps) {
  const surface = useEffectiveSurface(surfaceProp);
  const classes = colorSwatchClasses(surface);
  return (
    <div className={classes.root}>
      <div
        className={classes.sample}
        style={{ backgroundColor: colorSwatchFill(cssVar) }}
      />
      <div>
        <p className={classes.name}>{name}</p>
        <p className={classes.variable}>{cssVar}</p>
      </div>
    </div>
  );
}

// packages/ui-kit-vue/src/data/PixelColorSwatch.vue
<script setup lang="ts">
import { computed } from 'vue';
import { colorSwatchClasses, colorSwatchFill, type Surface } from '@pxlkit/ui-kit-core';
import { useEffectiveSurface } from '../composables/surface.js';

/**
 * Design-token preview: a square filled from a CSS custom property — so it
 * follows the active theme — beside the token name and the variable.
 */
export interface PixelColorSwatchProps {
  /** Display name of the token (e.g. "Cyan 500"). */
  name: string;
  /** CSS variable to preview (e.g. "--color-retro-cyan"). */
  cssVar: string;
  /** Visual surface override. */
  surface?: Surface;
}

const props = withDefaults(defineProps<PixelColorSwatchProps>(), { surface: undefined });

const surface = useEffectiveSurface(() => props.surface);
const classes = computed(() => colorSwatchClasses(surface.value));
</script>

<template>
  <div :class="classes.root">
    <div :class="classes.sample" :style="{ backgroundColor: colorSwatchFill(cssVar) }" />
    <div>
      <p :class="classes.name">{{ name }}</p>
      <p :class="classes.variable">{{ cssVar }}</p>
    </div>
  </div>
</template>
