// packages/ui-kit-angular/src/lib/data/pixel-carousel-item.ts
import {
  ChangeDetectionStrategy,
  Component,
  HostAttributeToken,
  ViewEncapsulation,
  computed,
  inject,
} from '@angular/core';
import { carouselItemClasses, carouselSlideLabel } from '@pxlkit/ui-kit-core';
import { PIXEL_CAROUSEL } from './carousel-context';

/**
 * One slide of a `<pxl-carousel>`: a group (`aria-roledescription="slide"`)
 * named "Slide N of M" by its position, unless it has an `aria-label` of its
 * own. The host is the slide.
 *
 * @example
 * <pxl-carousel-item><img src="/one.png" alt="One" /></pxl-carousel-item>
 */
@Component({
  selector: 'pxl-carousel-item',
  changeDetection: ChangeDetectionStrategy.OnPush,
  // The host stands for React's <div>: a block box, in the base layer, so
  // display utilities set on it still win.
  encapsulation: ViewEncapsulation.None,
  styles: '@layer base { pxl-carousel-item { display: block; } }',
  host: {
    role: 'group',
    'aria-roledescription': 'slide',
    '[attr.aria-label]': 'label()',
    '[class]': 'classes',
  },
  template: '<ng-content />',
})
export class PixelCarouselItem {
  private readonly context = inject(PIXEL_CAROUSEL, { optional: true });
  private readonly ownLabel = inject(new HostAttributeToken('aria-label'), { optional: true });

  /** @internal */
  protected readonly classes = carouselItemClasses;
  /** @internal An own `aria-label` wins. */
  protected readonly label = computed(() => {
    if (this.ownLabel !== null) return this.ownLabel;
    const items = this.context?.items() ?? [];
    const index = items.indexOf(this);
    return index < 0 ? null : carouselSlideLabel(index, items.length);
  });
}

// packages/ui-kit-vue/src/data/PixelCarouselItem.vue
<script setup lang="ts">
import { computed, type VNode } from 'vue';
import { carouselItemClasses, carouselSlideLabel } from '@pxlkit/ui-kit-core';
import { useCarouselPosition } from './_internal/carousel-context.js';

/**
 * One slide of a `PixelCarousel`: a group (`aria-roledescription="slide"`)
 * named "Slide N of M" by its position. Attributes go to the slide.
 */
defineSlots<{
  /** The slide's content. */
  default?(): VNode[];
}>();

const position = useCarouselPosition();
const label = computed(() => (position ? carouselSlideLabel(position.index, position.total) : undefined));
</script>

<template>
  <div role="group" aria-roledescription="slide" :aria-label="label" :class="carouselItemClasses"><slot /></div>
</template>
