// packages/ui-kit/src/feedback/PixelSkeleton.examples.tsx
import { PixelSkeleton } from '../feedback';

export function Default() {
  return <PixelSkeleton width="12rem" height="1rem" />;
}

export function TextBlock() {
  return (
    <div className="flex flex-col gap-2">
      <PixelSkeleton width="14rem" height="0.75rem" />
      <PixelSkeleton width="11rem" height="0.75rem" />
      <PixelSkeleton width="9rem" height="0.75rem" />
    </div>
  );
}

export function Rounded() {
  return (
    <div className="flex items-center gap-3">
      <PixelSkeleton width="2.5rem" height="2.5rem" rounded />
      <div className="flex flex-col gap-1.5">
        <PixelSkeleton width="8rem" height="0.75rem" />
        <PixelSkeleton width="5rem" height="0.75rem" />
      </div>
    </div>
  );
}

export function Surfaces() {
  return (
    <div className="flex flex-col gap-3">
      <PixelSkeleton surface="linear" width="14rem" height="1rem" />
      <PixelSkeleton surface="pixel" width="14rem" height="1rem" />
    </div>
  );
}

export function CardPlaceholder() {
  return (
    <div className="flex w-72 flex-col gap-3 rounded border border-retro-border/60 p-4">
      <PixelSkeleton width="100%" height="8rem" />
      <PixelSkeleton width="80%" height="0.875rem" />
      <PixelSkeleton width="60%" height="0.75rem" />
    </div>
  );
}

export function CustomLabel() {
  return <PixelSkeleton width="10rem" height="1rem" ariaLabel="Loading user profile" />;
}

// packages/ui-kit-angular/examples/feedback/pixel-skeleton.examples.ts
import { Component } from '@angular/core';
import { PixelSkeleton } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelSkeleton],
  template: `<pxl-skeleton width="12rem" height="1rem" />`,
})
export class Default {}

@Component({
  imports: [PixelSkeleton],
  template: `
    <div class="flex flex-col gap-2">
      <pxl-skeleton width="14rem" height="0.75rem" />
      <pxl-skeleton width="11rem" height="0.75rem" />
      <pxl-skeleton width="9rem" height="0.75rem" />
    </div>
  `,
})
export class TextBlock {}

@Component({
  imports: [PixelSkeleton],
  template: `
    <div class="flex items-center gap-3">
      <pxl-skeleton width="2.5rem" height="2.5rem" rounded />
      <div class="flex flex-col gap-1.5">
        <pxl-skeleton width="8rem" height="0.75rem" />
        <pxl-skeleton width="5rem" height="0.75rem" />
      </div>
    </div>
  `,
})
export class Rounded {}

@Component({
  imports: [PixelSkeleton],
  template: `
    <div class="flex flex-col gap-3">
      <pxl-skeleton surface="linear" width="14rem" height="1rem" />
      <pxl-skeleton surface="pixel" width="14rem" height="1rem" />
    </div>
  `,
})
export class Surfaces {}

@Component({
  imports: [PixelSkeleton],
  template: `
    <div class="flex w-72 flex-col gap-3 rounded border border-retro-border/60 p-4">
      <pxl-skeleton width="100%" height="8rem" />
      <pxl-skeleton width="80%" height="0.875rem" />
      <pxl-skeleton width="60%" height="0.75rem" />
    </div>
  `,
})
export class CardPlaceholder {}

@Component({
  imports: [PixelSkeleton],
  template: `<pxl-skeleton width="10rem" height="1rem" ariaLabel="Loading user profile" />`,
})
export class CustomLabel {}
