// packages/ui-kit/src/feedback/PixelAlert.examples.tsx
import React from 'react';
import { PixelAlert } from '../feedback';
import { PixelButton } from '../actions';

export function Default() {
  return (
    <PixelAlert
      title="Something went wrong"
      message="Your session expired. Please sign in again to continue."
    />
  );
}

const InfoIcon = () => (
  <span
    aria-hidden
    style={{
      width: 14,
      height: 14,
      borderRadius: 9999,
      background: 'currentColor',
      display: 'inline-block',
    }}
  />
);

export function Tones() {
  return (
    <div className="flex flex-col gap-3">
      <PixelAlert tone="neutral" title="Heads up" message="Neutral informational banner." />
      <PixelAlert tone="green" title="Saved" message="Your changes have been persisted." />
      <PixelAlert tone="cyan" title="New feature" message="Try the redesigned inbox." />
      <PixelAlert tone="gold" title="Warning" message="Storage is almost full." />
      <PixelAlert tone="red" title="Error" message="Failed to upload the file." />
      <PixelAlert tone="purple" title="Tip" message="Use ⌘K to jump anywhere." />
      <PixelAlert tone="pink" title="Highlight" message="You unlocked a new badge." />
    </div>
  );
}

export function Surfaces() {
  return (
    <div className="flex flex-col gap-3">
      <PixelAlert
        surface="linear"
        tone="cyan"
        title="Linear surface"
        message="Soft border with rounded corners."
      />
      <PixelAlert
        surface="pixel"
        tone="cyan"
        title="Pixel surface"
        message="Chamfered border with a left accent stripe."
      />
    </div>
  );
}

export function WithIcon() {
  return (
    <PixelAlert
      tone="cyan"
      title="Pro tip"
      message="You can drag-and-drop files anywhere on the page."
      icon={<InfoIcon />}
    />
  );
}

export function WithAction() {
  return (
    <PixelAlert
      tone="red"
      title="Connection lost"
      message="We couldn't reach the server. Check your network and retry."
      icon={<InfoIcon />}
      action={
        <PixelButton size="sm" tone="red" variant="outline">
          Retry
        </PixelButton>
      }
    />
  );
}

export function PoliteLive() {
  return (
    <PixelAlert
      tone="green"
      live="polite"
      title="Auto-saved"
      message="Drafts are saved every few seconds."
    />
  );
}

// packages/ui-kit-angular/examples/feedback/pixel-alert.examples.ts
import { Component } from '@angular/core';
import { PixelAlert, PixelButton } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelAlert],
  template: `<pxl-alert title="Something went wrong" message="Your session expired. Please sign in again to continue." />`,
})
export class Default {}

@Component({
  imports: [PixelAlert],
  template: `
    <div class="flex flex-col gap-3">
      <pxl-alert tone="neutral" title="Heads up" message="Neutral informational banner." />
      <pxl-alert tone="green" title="Saved" message="Your changes have been persisted." />
      <pxl-alert tone="cyan" title="New feature" message="Try the redesigned inbox." />
      <pxl-alert tone="gold" title="Warning" message="Storage is almost full." />
      <pxl-alert tone="red" title="Error" message="Failed to upload the file." />
      <pxl-alert tone="purple" title="Tip" message="Use ⌘K to jump anywhere." />
      <pxl-alert tone="pink" title="Highlight" message="You unlocked a new badge." />
    </div>
  `,
})
export class Tones {}

@Component({
  imports: [PixelAlert],
  template: `
    <div class="flex flex-col gap-3">
      <pxl-alert surface="linear" tone="cyan" title="Linear surface" message="Soft border with rounded corners." />
      <pxl-alert surface="pixel" tone="cyan" title="Pixel surface" message="Chamfered border with a left accent stripe." />
    </div>
  `,
})
export class Surfaces {}

@Component({
  imports: [PixelAlert],
  template: `
    <pxl-alert tone="cyan" title="Pro tip" message="You can drag-and-drop files anywhere on the page." [icon]="info" />
    <ng-template #info>
      <span
        aria-hidden="true"
        style="width: 14px; height: 14px; border-radius: 9999px; background: currentColor; display: inline-block"
      ></span>
    </ng-template>
  `,
})
export class WithIcon {}

@Component({
  imports: [PixelAlert, PixelButton],
  template: `
    <pxl-alert
      tone="red"
      title="Connection lost"
      message="We couldn't reach the server. Check your network and retry."
      [icon]="info"
      [action]="retry"
    />
    <ng-template #info>
      <span
        aria-hidden="true"
        style="width: 14px; height: 14px; border-radius: 9999px; background: currentColor; display: inline-block"
      ></span>
    </ng-template>
    <ng-template #retry><button pxlButton size="sm" tone="red" variant="outline">Retry</button></ng-template>
  `,
})
export class WithAction {}

@Component({
  imports: [PixelAlert],
  template: `<pxl-alert tone="green" live="polite" title="Auto-saved" message="Drafts are saved every few seconds." />`,
})
export class PoliteLive {}
