// packages/ui-kit-angular/src/lib/layout/pixel-center.ts
import { Directive, computed, input } from '@angular/core';
import {
  centerClasses,
  type CenterAlign,
  type ContainerWidth,
  type PageGutter,
  type Surface,
} from '@pxlkit/ui-kit-core';
import { booleanOr, withDefault } from '../_internal/coercion';
import { injectEffectiveSurface } from '../overlay-foundation/pxl-kit-surface-provider';

/**
 * Horizontally centred column: width cap, page gutter and text alignment.
 * Put it on whichever element you need (the counterpart of the React kit's
 * `as` prop).
 *
 * @example
 * <div pxlCenter maxWidth="3xl" align="center">…</div>
 * <section pxlCenter maxWidth="4xl" gutter="lg">…</section>
 */
@Directive({
  selector: '[pxlCenter]',
  host: {
    '[class]': 'classes()',
    // `align` is a legacy presentational attribute: left on a block element
    // it would still align the content.
    '[attr.align]': 'null',
  },
})
export class PixelCenter {
  /** Width cap (`containerWidth`). */
  readonly maxWidth = input<ContainerWidth, ContainerWidth | undefined>('5xl', {
    transform: withDefault<ContainerWidth>('5xl'),
  });
  /** Horizontal padding (`pageGutter`). */
  readonly gutter = input<PageGutter, PageGutter | undefined>('lg', { transform: withDefault<PageGutter>('lg') });
  /** Text alignment of the centred content. */
  readonly align = input<CenterAlign>();
  /** @deprecated Use `align`. */
  readonly text = input<CenterAlign>();
  /** `inline-block` instead of `block`. */
  readonly inline = input(false, { transform: booleanOr(false) });
  /** Surface override; defaults to the nearest provider. */
  readonly surface = input<Surface>();
  /** Surface border and radius. */
  readonly bordered = input(false, { transform: booleanOr(false) });

  private readonly effectiveSurface = injectEffectiveSurface(() => this.surface());

  /** @internal */
  protected readonly classes = computed(() =>
    centerClasses(this.effectiveSurface(), {
      maxWidth: this.maxWidth(),
      gutter: this.gutter(),
      align: this.align() ?? this.text(),
      inline: this.inline(),
      bordered: this.bordered(),
    }),
  );
}

// packages/ui-kit-vue/src/layout/PixelCenter.vue
<script setup lang="ts">
import { computed, type VNode } from 'vue';
import {
  centerClasses,
  type CenterAlign,
  type ContainerWidth,
  type PageGutter,
  type Surface,
} from '@pxlkit/ui-kit-core';
import { useEffectiveSurface } from '../composables/surface.js';

/** Horizontally centred column: width cap, page gutter and text alignment. */
export interface PixelCenterProps {
  /** Width cap (`containerWidth`). */
  maxWidth?: ContainerWidth;
  /** Horizontal padding (`pageGutter`). */
  gutter?: PageGutter;
  /** Text alignment of the centred content. */
  align?: CenterAlign;
  /** @deprecated Use `align`. */
  text?: CenterAlign;
  /** `inline-block` instead of `block`. */
  inline?: boolean;
  /** Element to render. */
  as?: string;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
  /** Surface border and radius. */
  bordered?: boolean;
}

const props = withDefaults(defineProps<PixelCenterProps>(), {
  maxWidth: '5xl',
  gutter: 'lg',
  align: undefined,
  text: undefined,
  inline: false,
  as: 'div',
  surface: undefined,
  bordered: false,
});
defineSlots<{ default?(): VNode[] }>();

const surface = useEffectiveSurface(() => props.surface);
const classes = computed(() =>
  centerClasses(surface.value, {
    maxWidth: props.maxWidth,
    gutter: props.gutter,
    align: props.align ?? props.text,
    inline: props.inline,
    bordered: props.bordered,
  }),
);
</script>

<template>
  <component :is="as" :class="classes"><slot /></component>
</template>
