// packages/ui-kit/src/layout/PixelScrollArea.tsx
'use client';

import React, { forwardRef } from 'react';
import {
  scrollAreaClasses,
  scrollAreaNameWarning,
  scrollAreaStyle,
  type ScrollAreaVariant,
} from '@pxlkit/ui-kit-core';
import { cn, Surface, useEffectiveSurface } from '../common';

export interface PixelScrollAreaProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'type'> {
  /** Height cap before the content scrolls: pixels, or any CSS length. */
  maxHeight?: string | number;
  /** Canonical structural variant (scrollbar visibility mode). */
  variant?: ScrollAreaVariant;
  /**
   * @deprecated Use `variant` instead. Retained as alias for one minor.
   */
  type?: ScrollAreaVariant;
  /** Keep the scrollbar's room reserved, so content never shifts. */
  offsetScrollbars?: boolean;
  /** Scrollbar thickness in pixels. */
  scrollbarSize?: number;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
  /** Render with surface-aware border + radius chrome. Defaults to false (no chrome). */
  bordered?: boolean;
  /**
   * Accessible name for the scrollable region. Required for keyboard users to
   * understand what they've landed on. Provide either `aria-label` or
   * `aria-labelledby`. In dev, a missing label logs a warning.
   */
  'aria-label'?: string;
  /** Id of the element that names the region, in place of `aria-label`. */
  'aria-labelledby'?: string;
  /** The content that scrolls. */
  children: React.ReactNode;
}

/**
 * Surface-aware scroll container with styled scrollbar (CSS `scrollbar-width`
 * + `::-webkit-scrollbar`). Use `type` to control scrollbar visibility,
 * `maxHeight` to cap height before content scrolls.
 *
 * The styled scrollbar palette is owned by `styles.css` `.pxl-scroll-*`
 * classes; this component only wires the variant + dimensions.
 */
export const PixelScrollArea = forwardRef<HTMLDivElement, PixelScrollAreaProps>(function PixelScrollArea(
  {
    maxHeight,
    variant,
    type,
    offsetScrollbars = false,
    scrollbarSize,
    surface: surfaceProp,
    bordered = false,
    className,
    children,
    style,
    ...rest
  },
  ref,
) {
  const surface = useEffectiveSurface(surfaceProp);
  const resolvedVariant: ScrollAreaVariant = variant ?? type ?? 'auto';

  const inlineStyle: React.CSSProperties = {
    ...style,
    ...scrollAreaStyle({ maxHeight, scrollbarSize, offsetScrollbars }),
  };

  const ariaLabel = (rest as { 'aria-label'?: string })['aria-label'];
  const ariaLabelledBy = (rest as { 'aria-labelledby'?: string })['aria-labelledby'];
  const explicitTabIndex = (rest as { tabIndex?: number }).tabIndex;
  const explicitRole = (rest as { role?: string }).role;

  if (process.env.NODE_ENV !== 'production') {
    const warning = scrollAreaNameWarning({ label: ariaLabel, labelledBy: ariaLabelledBy, tabIndex: explicitTabIndex });
    // eslint-disable-next-line no-console
    if (warning) console.warn(warning);
  }

  return (
    <div
      ref={ref}
      data-scrollbar={resolvedVariant}
      data-surface={surface}
      role={explicitRole ?? 'region'}
      tabIndex={explicitTabIndex ?? 0}
      className={cn(scrollAreaClasses(surface, { variant: resolvedVariant, bordered }), className)}
      style={inlineStyle}
      {...rest}
    >
      {children}
    </div>
  );
});

PixelScrollArea.displayName = 'PixelScrollArea';

// packages/ui-kit-vue/src/layout/PixelScrollArea.vue
<script setup lang="ts">
import { computed, useAttrs, warn, type VNode } from 'vue';
import {
  scrollAreaClasses,
  scrollAreaNameWarning,
  scrollAreaStyle,
  type ScrollAreaVariant,
  type Surface,
} from '@pxlkit/ui-kit-core';
import { useEffectiveSurface } from '../composables/surface.js';

/**
 * Focusable scroll region (`role="region"`, `tabindex="0"`) with a styled
 * scrollbar: keyboard users can reach it and scroll it with the arrow and
 * page keys. Name it with `aria-label` or `aria-labelledby` — without either
 * (or a `tabindex` of your own) it warns in development. An own `role` or
 * `tabindex` replaces the default.
 */
export interface PixelScrollAreaProps {
  /** Height cap before the content scrolls: pixels, or any CSS length. */
  maxHeight?: string | number;
  /** When the scrollbar shows. */
  variant?: ScrollAreaVariant;
  /** @deprecated Use `variant`. */
  type?: ScrollAreaVariant;
  /** Keep the scrollbar's room reserved, so content never shifts. */
  offsetScrollbars?: boolean;
  /** Scrollbar thickness in pixels. */
  scrollbarSize?: number;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
  /** Surface border and radius. */
  bordered?: boolean;
}

const props = withDefaults(defineProps<PixelScrollAreaProps>(), {
  maxHeight: undefined,
  variant: undefined,
  type: undefined,
  offsetScrollbars: false,
  scrollbarSize: undefined,
  surface: undefined,
  bordered: false,
});
defineSlots<{
  /** The content that scrolls. */
  default?(): VNode[];
}>();

const attrs = useAttrs();
const surface = useEffectiveSurface(() => props.surface);
const variant = computed<ScrollAreaVariant>(() => props.variant ?? props.type ?? 'auto');
const classes = computed(() => scrollAreaClasses(surface.value, { variant: variant.value, bordered: props.bordered }));
const style = computed(() =>
  scrollAreaStyle({
    maxHeight: props.maxHeight,
    scrollbarSize: props.scrollbarSize,
    offsetScrollbars: props.offsetScrollbars,
  }),
);

const warning = scrollAreaNameWarning({
  label: attrs['aria-label'],
  labelledBy: attrs['aria-labelledby'],
  tabIndex: attrs.tabindex ?? attrs.tabIndex,
});
if (warning) warn(warning);
</script>

<template>
  <div :data-scrollbar="variant" :data-surface="surface" role="region" tabindex="0" :class="classes" :style="style">
    <slot />
  </div>
</template>
