// packages/ui-kit/src/layout/PixelContainer.tsx
'use client';

import React, { forwardRef } from 'react';
import {
  containerClasses,
  resolveContainerPadding,
  type ContainerElement,
  type ContainerPadding,
} from '@pxlkit/ui-kit-core';
import { cn, Surface, useEffectiveSurface } from '../common';
import { ContainerWidth } from '../tokens';
import { PixelCenter } from './PixelCenter';

export interface PixelContainerProps extends React.HTMLAttributes<HTMLElement> {
  /** Width cap of the inner column (`containerWidth`). */
  maxWidth?: ContainerWidth;
  /**
   * Vertical rhythm (`sectionRhythm`), or `{ x, y }`: the gutter of the inner column (`pageGutter`)
   * and the rhythm. Both default to `lg`.
   */
  padding?: ContainerPadding;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
  /** Element to render — a landmark wants an `aria-label` or `aria-labelledby`. */
  as?: ContainerElement;
}

export const PixelContainer = forwardRef<HTMLElement, PixelContainerProps>(function PixelContainer(
  {
    maxWidth = 'xl',
    padding,
    surface: surfaceProp,
    as = 'section',
    className,
    children,
    ...rest
  },
  ref,
) {
  const surface = useEffectiveSurface(surfaceProp);
  const { x, y } = resolveContainerPadding(padding);
  const Comp = as as 'section';

  return (
    <Comp
      ref={ref}
      className={cn(containerClasses(surface, y), className)}
      {...rest}
    >
      <PixelCenter maxWidth={maxWidth} gutter={x} surface={surface}>
        {children}
      </PixelCenter>
    </Comp>
  );
});

PixelContainer.displayName = 'PixelContainer';

// packages/ui-kit-vue/src/layout/PixelContainer.vue
<script setup lang="ts">
import { computed, type VNode } from 'vue';
import {
  containerClasses,
  resolveContainerPadding,
  type ContainerElement,
  type ContainerPadding,
  type ContainerWidth,
  type Surface,
} from '@pxlkit/ui-kit-core';
import { useEffectiveSurface } from '../composables/surface.js';
import PixelCenter from './PixelCenter.vue';

/**
 * Full-width page band: vertical rhythm around a centred, width-capped
 * column (a `PixelCenter`) that holds the content.
 */
export interface PixelContainerProps {
  /** Width cap of the inner column (`containerWidth`). */
  maxWidth?: ContainerWidth;
  /**
   * Vertical rhythm (`sectionRhythm`), or `{ x, y }`: the gutter of the inner
   * column (`pageGutter`) and the rhythm. Both default to `lg`.
   */
  padding?: ContainerPadding;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
  /** Element to render — a landmark wants an `aria-label` or `aria-labelledby`. */
  as?: ContainerElement;
}

const props = withDefaults(defineProps<PixelContainerProps>(), {
  maxWidth: 'xl',
  padding: undefined,
  surface: undefined,
  as: 'section',
});
defineSlots<{ default?(): VNode[] }>();

const surface = useEffectiveSurface(() => props.surface);
const padding = computed(() => resolveContainerPadding(props.padding));
const classes = computed(() => containerClasses(surface.value, padding.value.y));
</script>

<template>
  <component :is="as" :class="classes">
    <PixelCenter :max-width="maxWidth" :gutter="padding.x" :surface="surface"><slot /></PixelCenter>
  </component>
</template>
