// packages/ui-kit/src/layout/PixelStack.tsx
'use client';

import React, { forwardRef } from 'react';
import {
  stackAlignClasses,
  stackDirectionClasses,
  stackJustifyClasses,
  type StackAlign,
  type StackDirection,
  type StackJustify,
} from '@pxlkit/ui-kit-core';
import { cn, Surface, useEffectiveSurface, surfaceClasses } from '../common';
import { stackGap, StackGapKey } from '../tokens';

export interface PixelStackProps extends React.HTMLAttributes<HTMLDivElement> {
  /** Main axis. */
  direction?: StackDirection;
  /** Gap token (`stackGap`). */
  gap?: StackGapKey;
  /** Cross-axis alignment. */
  align?: StackAlign;
  /** Main-axis distribution. */
  justify?: StackJustify;
  /** Wrap onto multiple lines. */
  wrap?: boolean;
  /** `inline-flex` instead of `flex`. */
  inline?: boolean;
  /** Element to render. */
  as?: keyof React.JSX.IntrinsicElements;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
}

export const PixelStack = forwardRef<HTMLDivElement, PixelStackProps>(function PixelStack(
  {
    direction = 'col',
    gap = 4,
    align,
    justify,
    wrap = false,
    inline = false,
    as,
    surface: surfaceProp,
    className,
    children,
    ...rest
  },
  ref,
) {
  const surface = useEffectiveSurface(surfaceProp);
  const s = surfaceClasses(surface);
  const Comp = (as ?? 'div') as 'div';

  return (
    <Comp
      ref={ref}
      className={cn(
        inline ? 'inline-flex' : 'flex',
        stackDirectionClasses[direction],
        stackGap[gap],
        align && stackAlignClasses[align],
        justify && stackJustifyClasses[justify],
        wrap && 'flex-wrap',
        s.transition,
        className,
      )}
      {...rest}
    >
      {children}
    </Comp>
  );
});

PixelStack.displayName = 'PixelStack';

// packages/ui-kit-vue/src/layout/PixelStack.vue
<script setup lang="ts">
import { computed, type VNode } from 'vue';
import {
  cn,
  stackAlignClasses,
  stackDirectionClasses,
  stackGap,
  stackJustifyClasses,
  surfaceClasses,
  type StackAlign,
  type StackDirection,
  type StackGapKey,
  type StackJustify,
  type Surface,
} from '@pxlkit/ui-kit-core';
import { useEffectiveSurface } from '../composables/surface.js';

/** Flexbox stack: direction, gap token, alignment, distribution and wrapping. */
export interface PixelStackProps {
  /** Main axis. */
  direction?: StackDirection;
  /** Gap token (`stackGap`). */
  gap?: StackGapKey;
  /** Cross-axis alignment. */
  align?: StackAlign;
  /** Main-axis distribution. */
  justify?: StackJustify;
  /** Wrap onto multiple lines. */
  wrap?: boolean;
  /** `inline-flex` instead of `flex`. */
  inline?: boolean;
  /** Element to render. */
  as?: string;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
}

const props = withDefaults(defineProps<PixelStackProps>(), {
  direction: 'col',
  gap: 4,
  align: undefined,
  justify: undefined,
  wrap: false,
  inline: false,
  as: 'div',
  surface: undefined,
});
defineSlots<{ default?(): VNode[] }>();

const surface = useEffectiveSurface(() => props.surface);
const classes = computed(() =>
  cn(
    props.inline ? 'inline-flex' : 'flex',
    stackDirectionClasses[props.direction],
    stackGap[props.gap],
    props.align && stackAlignClasses[props.align],
    props.justify && stackJustifyClasses[props.justify],
    props.wrap && 'flex-wrap',
    surfaceClasses(surface.value).transition,
  ),
);
</script>

<template>
  <component :is="as" :class="classes"><slot /></component>
</template>
