// packages/ui-kit/src/layout/PixelBox.tsx
'use client';

import React, { forwardRef, useEffect } from 'react';
import {
  boxClasses,
  boxLandmarkWarning,
  type BoxElement,
  type BoxPadding,
  type BoxRadius,
} from '@pxlkit/ui-kit-core';
import { cn, Surface, Tone, Variant, useEffectiveSurface } from '../common';

export interface PixelBoxProps
  extends Omit<React.HTMLAttributes<HTMLDivElement>, 'color'> {
  /** Tone of the fill and border. */
  tone?: Tone;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
  /** `solid` and `soft` fill; `outline` and `ghost` stay transparent. */
  variant?: Variant;
  /** Padding scale. */
  padding?: BoxPadding;
  /** Fixed radius; the surface's large radius when unset. */
  radius?: BoxRadius;
  /**
   * Whether to render a border. Defaults to `true` when `variant === 'outline'`
   * (outlines without a border are meaningless), `false` otherwise. Pass `true`
   * to force a border on `solid`/`soft`/`ghost`; pass `false` to force-off on
   * outline. Note: when polymorphic `as` is a landmark element (`section`,
   * `nav`, `aside`, `main`), supply `aria-label` or `aria-labelledby` for a11y.
   */
  border?: boolean;
  /**
   * Surface drop shadow. On pixel it shows with a `radius` only: the
   * default corners are cut, and a drop shadow cannot show past them.
   */
  shadow?: boolean;
  /** Element to render. */
  as?: BoxElement;
}

/**
 * Surface-aware container box.
 *
 * Polymorphic ref note: the ref is typed `HTMLDivElement` because that's the
 * default render target. When you set `as="nav"` / `"section"` etc, the
 * underlying element is still focusable/queryable via the ref — TypeScript
 * just won't know the narrower subtype. If you need a narrower type, cast at
 * the call site or use `React.useRef<HTMLElement>()`.
 */
export const PixelBox = forwardRef<HTMLDivElement, PixelBoxProps>(function PixelBox(
  {
    tone = 'neutral',
    surface: surfaceProp,
    variant = 'solid',
    padding = 'md',
    radius,
    border,
    shadow = false,
    as,
    className,
    children,
    ...rest
  },
  ref,
) {
  const surface = useEffectiveSurface(surfaceProp);
  const Comp = (as ?? 'div') as 'div';

  useEffect(() => {
    if (process.env.NODE_ENV === 'production') return;
    const r = rest as Record<string, unknown>;
    const warning = boxLandmarkWarning(as, {
      label: r['aria-label'],
      labelledBy: r['aria-labelledby'],
      title: r['title'],
    });
    // eslint-disable-next-line no-console
    if (warning) console.warn(warning);
  }, [as, rest]);

  return (
    <Comp
      ref={ref}
      className={cn(boxClasses(surface, { tone, variant, padding, radius, border, shadow }), className)}
      {...rest}
    >
      {children}
    </Comp>
  );
});

PixelBox.displayName = 'PixelBox';

// packages/ui-kit-vue/src/layout/PixelBox.vue
<script setup lang="ts">
import { computed, onMounted, useAttrs, warn, type VNode } from 'vue';
import {
  boxClasses,
  boxLandmarkWarning,
  type BoxElement,
  type BoxPadding,
  type BoxRadius,
  type Surface,
  type Tone,
  type Variant,
} from '@pxlkit/ui-kit-core';
import { useEffectiveSurface } from '../composables/surface.js';

/**
 * Surface-aware container: padding, radius, a tone fill (`solid`, `soft`),
 * an optional border and shadow. Rendered as a landmark (`section`, `nav`,
 * `aside`, `main`) it needs an `aria-label`, `aria-labelledby` or `title`;
 * without one it warns in development.
 */
export interface PixelBoxProps {
  /** Tone of the fill and border. */
  tone?: Tone;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
  /** `solid` and `soft` fill; `outline` and `ghost` stay transparent. */
  variant?: Variant;
  /** Padding scale. */
  padding?: BoxPadding;
  /** Fixed radius; the surface's large radius when unset. */
  radius?: BoxRadius;
  /** Draw the tone border; on for `outline`, off otherwise, when unset. */
  border?: boolean;
  /**
   * Surface drop shadow. On pixel it shows with a `radius` only: the
   * default corners are cut, and a drop shadow cannot show past them.
   */
  shadow?: boolean;
  /** Element to render. */
  as?: BoxElement;
}

const props = withDefaults(defineProps<PixelBoxProps>(), {
  tone: 'neutral',
  surface: undefined,
  variant: 'solid',
  padding: 'md',
  radius: undefined,
  border: undefined,
  shadow: false,
  as: 'div',
});
defineSlots<{
  /** Box content. */
  default?(): VNode[];
}>();

const attrs = useAttrs();
const surface = useEffectiveSurface(() => props.surface);
const classes = computed(() =>
  boxClasses(surface.value, {
    tone: props.tone,
    variant: props.variant,
    padding: props.padding,
    radius: props.radius,
    border: props.border,
    shadow: props.shadow,
  }),
);

onMounted(() => {
  const warning = boxLandmarkWarning(props.as, {
    label: attrs['aria-label'],
    labelledBy: attrs['aria-labelledby'],
    title: attrs.title,
  });
  if (warning) warn(warning);
});
</script>

<template>
  <component :is="as" :class="classes"><slot /></component>
</template>
