// packages/ui-kit-angular/src/lib/layout/pixel-equal-height-grid.ts
import { Directive, ElementRef, Renderer2, computed, inject, input, type AfterContentChecked } from '@angular/core';
import {
  cn,
  equalHeightGridAlign,
  equalHeightGridClasses,
  equalHeightGridItemClasses,
  gridClasses,
  type EqualHeightGridRowAlign,
} from '@pxlkit/ui-kit-core';
import { withDefault } from '../_internal/coercion';
import { PixelGridBase } from './pixel-grid';

const ITEM_CLASSES = equalHeightGridItemClasses.split(' ');

/**
 * A `pxlGrid` whose items share their row's height: each child element is
 * laid out as an auto header, a stretching body and an auto footer
 * (`grid-rows-[auto_1fr_auto]`), so footers line up across a row. Takes the
 * inputs of `pxlGrid` except `align`; put it on whichever element you need.
 *
 * @example
 * <div pxlEqualHeightGrid [cols]="{ base: 1, sm: 3 }" [gap]="4">
 *   <article>…</article>
 *   <article>…</article>
 * </div>
 */
@Directive({
  selector: '[pxlEqualHeightGrid]',
  host: {
    '[class]': 'classes()',
    '[style.grid-template-columns]': 'templateColumns()',
  },
})
export class PixelEqualHeightGrid extends PixelGridBase implements AfterContentChecked {
  /** `stretch` gives every item of a row the row's height; `top` keeps their own. */
  readonly rowAlign = input<EqualHeightGridRowAlign, EqualHeightGridRowAlign | undefined>('stretch', {
    transform: withDefault<EqualHeightGridRowAlign>('stretch'),
  });

  private readonly host = inject<ElementRef<HTMLElement>>(ElementRef).nativeElement;
  private readonly renderer = inject(Renderer2);

  /** @internal */
  protected readonly classes = computed(() => {
    const surface = this.effectiveSurface();
    return cn(gridClasses(surface, this.gridOptions(equalHeightGridAlign(this.rowAlign()))), equalHeightGridClasses(surface));
  });

  // The items are the element's children, whoever renders them, so they are
  // styled where they are: on the server too, and again whenever the content
  // changes.
  ngAfterContentChecked(): void {
    for (const item of Array.from(this.host.children)) {
      for (const name of ITEM_CLASSES) this.renderer.addClass(item, name);
    }
  }
}

// packages/ui-kit-vue/src/layout/PixelEqualHeightGrid.vue
<script setup lang="ts">
import { cloneVNode, computed, type VNode } from 'vue';
import {
  equalHeightGridAlign,
  equalHeightGridClasses,
  equalHeightGridItemClasses,
  type EqualHeightGridRowAlign,
} from '@pxlkit/ui-kit-core';
import { slotNodes } from '../_internal/Slot.js';
import { useEffectiveSurface } from '../composables/surface.js';
import PixelGrid, { type PixelGridProps } from './PixelGrid.vue';

/**
 * A `PixelGrid` whose items share their row's height: each element of the
 * default slot is laid out as an auto header, a stretching body and an auto
 * footer (`grid-rows-[auto_1fr_auto]`), so footers line up across a row. A
 * component item receives those classes like any attribute — it must render
 * them on its root.
 */
export interface PixelEqualHeightGridProps extends Omit<PixelGridProps, 'align'> {
  /** `stretch` gives every item of a row the row's height; `top` keeps their own. */
  rowAlign?: EqualHeightGridRowAlign;
}

const props = withDefaults(defineProps<PixelEqualHeightGridProps>(), {
  cols: undefined,
  rows: undefined,
  gap: 4,
  colGap: undefined,
  rowGap: undefined,
  autoFit: false,
  autoFill: false,
  minColWidth: '16rem',
  justify: undefined,
  as: 'div',
  surface: undefined,
  rowAlign: 'stretch',
});
const slots = defineSlots<{
  /** The items: each element or component, laid out as header, body and footer. */
  default?(): VNode[];
}>();

const surface = useEffectiveSurface(() => props.surface);
const classes = computed(() => equalHeightGridClasses(surface.value));

// Like React's cloneElement: elements and components get the item classes,
// text passes through as is.
const Items = () =>
  slotNodes(slots.default?.()).map((node) =>
    typeof node.type === 'symbol' ? node : cloneVNode(node, { class: equalHeightGridItemClasses }),
  );
</script>

<template>
  <PixelGrid
    :cols="cols"
    :rows="rows"
    :gap="gap"
    :col-gap="colGap"
    :row-gap="rowGap"
    :auto-fit="autoFit"
    :auto-fill="autoFill"
    :min-col-width="minColWidth"
    :align="equalHeightGridAlign(rowAlign)"
    :justify="justify"
    :as="as"
    :surface="surface"
    :class="classes"
  >
    <Items />
  </PixelGrid>
</template>
