// packages/ui-kit/src/navigation/PixelTabs.tsx
import React, {
  forwardRef,
  useCallback,
  useEffect,
  useId,
  useMemo,
  useRef,
  useState,
} from 'react';
import { Surface, TabItem, cn, useEffectiveSurface } from '../common';
import { useControllableState } from '../hooks/useControllableState';
import {
  PixelTabsContext,
  PixelTabsContextValue,
  TabsActivationMode,
  TabsOrientation,
} from './_internal/tabsContext';
import { PixelTabsList } from './PixelTabsList';
import { PixelTabsTrigger } from './PixelTabsTrigger';
import { PixelTabsPanel } from './PixelTabsPanel';

/* ─────────────────────────────────────────────────────────────────────────
   PixelTabs — tabbed panel with roving tabindex + keyboard nav.
   Sugar API (items[]) + compositional API (List/Trigger/Panel).
   ───────────────────────────────────────────────────────────────────────── */

/** Public prop bag for {@link PixelTabs}. */
export interface PixelTabsProps {
  /** The tabs as data. Without them, compose `PixelTabs.List`, `PixelTabs.Trigger` and `PixelTabs.Panel`. */
  items?: TabItem[];
  /** Uncontrolled initial active tab id. Canonical name; aliases `defaultTab`. */
  defaultValue?: string;
  /**
   * @deprecated Use `defaultValue` instead. Retained as alias for one minor.
   */
  defaultTab?: string;
  /** Controlled active tab id. When set, `defaultValue` is ignored. */
  value?: string;
  /** Fires whenever the active tab changes (controlled or uncontrolled). */
  onChange?: (id: string) => void;
  /** Visual surface treatment override. */
  surface?: Surface;
  /** Accessible label for the tablist. */
  ariaLabel?: string;
  /** Layout direction for the tab list + keyboard nav. */
  orientation?: TabsOrientation;
  /** When true, all panels render in the DOM (hidden via CSS). */
  keepMounted?: boolean;
  /** When true, the tablist scrolls horizontally with a fade-mask. Ignored for vertical orientation. */
  scrollable?: boolean;
  /** 'automatic' (default) selects on focus. 'manual' requires Enter/Space. */
  activationMode?: TabsActivationMode;
  /** Compositional children. Ignored when `items` is provided. */
  children?: React.ReactNode;
}

function PixelTabsRoot(
  {
    items,
    defaultValue,
    defaultTab,
    value,
    onChange,
    surface: surfaceProp,
    ariaLabel = 'Tabs',
    orientation = 'horizontal',
    keepMounted = false,
    scrollable = false,
    activationMode = 'automatic',
    children,
  }: PixelTabsProps,
  ref: React.Ref<HTMLDivElement>,
) {
  const surface = useEffectiveSurface(surfaceProp);
  const sugar = items && items.length > 0;
  const seedDefault = defaultValue ?? defaultTab ?? items?.[0]?.id;
  const [active, setActive] = useControllableState<string | undefined>({
    value,
    defaultValue: seedDefault,
    onChange: onChange ? ((next) => { if (next !== undefined) onChange(next); }) : undefined,
  });
  // Track sync changes for auto-seed compat below
  const isControlled = value !== undefined;
  const internal = isControlled ? undefined : active;
  const setInternal = (id: string) => setActive(id);
  const baseId = useId();

  const triggerRefs = useRef<Map<string, HTMLButtonElement | null>>(new Map());
  const triggerOrder = useRef<string[]>([]);

  const select = useCallback(
    (id: string) => {
      setActive(id);
    },
    [setActive],
  );

  const registerTrigger = useCallback((id: string, el: HTMLButtonElement | null) => {
    triggerRefs.current.set(id, el);
    if (el && !triggerOrder.current.includes(id)) {
      triggerOrder.current.push(id);
    }
    // Auto-seed: compositional API with no defaultTab/value → activate the first
    // registered trigger so a panel renders + tablist is keyboard-reachable.
    if (el && !sugar && !isControlled && internal === undefined && triggerOrder.current[0] === id) {
      setInternal(id);
    }
  }, [sugar, isControlled, internal]);

  const unregisterTrigger = useCallback((id: string) => {
    triggerRefs.current.delete(id);
    triggerOrder.current = triggerOrder.current.filter((x) => x !== id);
  }, []);

  const focusTriggerById = useCallback((id: string) => {
    triggerRefs.current.get(id)?.focus();
  }, []);

  const focusByOffset = useCallback((currentId: string, offset: number) => {
    const order = triggerOrder.current;
    const len = order.length;
    if (!len) return;
    const idx = order.indexOf(currentId);
    const fromIdx = idx === -1 ? 0 : idx;
    const nextIdx = ((fromIdx + offset) % len + len) % len;
    const nextId = order[nextIdx];
    triggerRefs.current.get(nextId)?.focus();
  }, []);

  const focusEdge = useCallback((edge: 'first' | 'last') => {
    const order = triggerOrder.current;
    if (!order.length) return;
    const id = edge === 'first' ? order[0] : order[order.length - 1];
    triggerRefs.current.get(id)?.focus();
  }, []);

  // Pre-register sugar items so triggerOrder reflects them even before mount.
  useEffect(() => {
    if (!sugar) return;
    triggerOrder.current = items!.map((i) => i.id);
  }, [sugar, items]);

  const ctx = useMemo<PixelTabsContextValue>(
    () => ({
      baseId,
      active,
      select,
      registerTrigger,
      unregisterTrigger,
      triggerOrder,
      focusTriggerById,
      focusByOffset,
      focusEdge,
      orientation,
      activationMode,
      keepMounted,
      surface,
    }),
    [
      baseId,
      active,
      select,
      registerTrigger,
      unregisterTrigger,
      focusTriggerById,
      focusByOffset,
      focusEdge,
      orientation,
      activationMode,
      keepMounted,
      surface,
    ],
  );

  return (
    <PixelTabsContext.Provider value={ctx}>
      <div
        ref={ref}
        className={cn(
          orientation === 'horizontal' ? 'space-y-3' : 'flex gap-3',
        )}
        data-orientation={orientation}
      >
        {sugar ? (
          <>
            <PixelTabsList ariaLabel={ariaLabel} scrollable={scrollable}>
              {items!.map((item) => (
                <PixelTabsTrigger key={item.id} value={item.id} icon={item.icon}>
                  {item.label}
                </PixelTabsTrigger>
              ))}
            </PixelTabsList>
            <div className={cn(orientation === 'vertical' && 'flex-1 min-w-0')}>
              {items!.map((item) => (
                <PixelTabsPanel key={item.id} value={item.id}>
                  {item.content}
                </PixelTabsPanel>
              ))}
            </div>
          </>
        ) : (
          children
        )}
      </div>
    </PixelTabsContext.Provider>
  );
}

const PixelTabsRootFwd = forwardRef<HTMLDivElement, PixelTabsProps>(PixelTabsRoot);
PixelTabsRootFwd.displayName = 'PixelTabs';

type PixelTabsComponent = typeof PixelTabsRootFwd & {
  List: typeof PixelTabsList;
  Trigger: typeof PixelTabsTrigger;
  Panel: typeof PixelTabsPanel;
};

export const PixelTabs = PixelTabsRootFwd as PixelTabsComponent;
PixelTabs.List = PixelTabsList;
PixelTabs.Trigger = PixelTabsTrigger;
PixelTabs.Panel = PixelTabsPanel;

// packages/ui-kit-vue/src/navigation/PixelTabs.vue
<script setup lang="ts">
import { computed, provide, ref, useId, type VNode } from 'vue';
import { cn, type Surface } from '@pxlkit/ui-kit-core';
import { RenderNode, type PxlNode } from '../_internal/render-node.js';
import { useControllableState } from '../composables/controllable.js';
import { useEffectiveSurface } from '../composables/surface.js';
import { PIXEL_TABS, type TabsActivationMode, type TabsOrientation } from './_internal/tabs-context.js';
import PixelTabsList from './PixelTabsList.vue';
import PixelTabsPanel from './PixelTabsPanel.vue';
import PixelTabsTrigger from './PixelTabsTrigger.vue';

/** One tab of the `items` shorthand. */
export interface TabItem {
  id: string;
  label: string;
  icon?: PxlNode;
  content?: PxlNode;
}

/**
 * Tabbed panels with roving tabindex and arrow-key navigation. Pass `items`
 * for the shorthand, or compose `PixelTabsList` / `PixelTabsTrigger` /
 * `PixelTabsPanel` in the default slot. Bind the active tab with `v-model`.
 */
export interface PixelTabsProps {
  /** Shorthand; leave out to compose List / Trigger / Panel yourself. */
  items?: TabItem[];
  /** Active tab id (`v-model`); leave unset for uncontrolled tabs. */
  modelValue?: string;
  /** Initial active tab while uncontrolled. */
  defaultValue?: string;
  /** @deprecated Use `defaultValue`. */
  defaultTab?: string;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
  /** Accessible label of the tablist. */
  ariaLabel?: string;
  /** Layout direction of the tab list and of arrow-key navigation. */
  orientation?: TabsOrientation;
  /** Keep every panel in the DOM (hidden) instead of only the active one. */
  keepMounted?: boolean;
  /** Horizontal tab list scrolls with a fade mask (ignored when vertical). */
  scrollable?: boolean;
  /** `automatic` selects on focus; `manual` waits for Enter / Space. */
  activationMode?: TabsActivationMode;
}

const props = withDefaults(defineProps<PixelTabsProps>(), {
  items: undefined,
  modelValue: undefined,
  defaultValue: undefined,
  defaultTab: undefined,
  surface: undefined,
  ariaLabel: 'Tabs',
  orientation: 'horizontal',
  keepMounted: false,
  scrollable: false,
  activationMode: 'automatic',
});
const emit = defineEmits<{
  /** The newly active tab id. */
  'update:modelValue': [id: string];
}>();
defineSlots<{ default?(): VNode[] }>();

const surface = useEffectiveSurface(() => props.surface);
const sugar = computed(() => !!props.items && props.items.length > 0);
const [active, setActive] = useControllableState<string | undefined>({
  value: () => props.modelValue,
  defaultValue: () => props.defaultValue ?? props.defaultTab ?? props.items?.[0]?.id,
  onChange: (next) => {
    if (next !== undefined) emit('update:modelValue', next);
  },
});

const baseId = useId();
const triggers = new Map<string, HTMLButtonElement>();
const order = ref<string[]>([]);
const orderOf = () => (sugar.value ? props.items!.map((item) => item.id) : order.value);

provide(PIXEL_TABS, {
  baseId,
  active,
  select: (id) => setActive(id),
  registerTrigger(id, element) {
    triggers.set(id, element);
    if (!order.value.includes(id)) order.value.push(id);
    // Compositional tabs without a default: activate the first trigger so a
    // panel renders and the tablist is keyboard-reachable.
    if (!sugar.value && props.modelValue === undefined && active.value === undefined && order.value[0] === id) {
      setActive(id);
    }
  },
  unregisterTrigger(id) {
    triggers.delete(id);
    order.value = order.value.filter((x) => x !== id);
  },
  focusByOffset(currentId, offset) {
    const ids = orderOf();
    if (!ids.length) return;
    const from = Math.max(0, ids.indexOf(currentId));
    triggers.get(ids[(((from + offset) % ids.length) + ids.length) % ids.length]!)?.focus();
  },
  focusEdge(edge) {
    const ids = orderOf();
    if (!ids.length) return;
    triggers.get(edge === 'first' ? ids[0]! : ids[ids.length - 1]!)?.focus();
  },
  orientation: computed(() => props.orientation),
  activationMode: computed(() => props.activationMode),
  keepMounted: computed(() => props.keepMounted),
  surface,
});
</script>

<template>
  <div :class="cn(orientation === 'horizontal' ? 'space-y-3' : 'flex gap-3')" :data-orientation="orientation">
    <template v-if="sugar">
      <PixelTabsList :aria-label="ariaLabel" :scrollable="scrollable">
        <PixelTabsTrigger v-for="item in items" :key="item.id" :value="item.id">
          <template v-if="item.icon !== undefined" #icon><RenderNode :node="item.icon" /></template>
          {{ item.label }}
        </PixelTabsTrigger>
      </PixelTabsList>
      <div :class="cn(orientation === 'vertical' && 'flex-1 min-w-0')">
        <PixelTabsPanel v-for="item in items" :key="item.id" :value="item.id">
          <RenderNode :node="item.content" />
        </PixelTabsPanel>
      </div>
    </template>
    <slot v-else />
  </div>
</template>
