// packages/ui-kit-angular/src/lib/navigation/pixel-accordion.ts
import { ChangeDetectionStrategy, Component, computed, input, signal, type OnInit } from '@angular/core';
import {
  accordionClasses,
  accordionIds,
  accordionInitialOpen,
  accordionItemClasses,
  toggleAccordionItem,
  type Surface,
} from '@pxlkit/ui-kit-core';
import { booleanOr } from '../_internal/coercion';
import { injectId } from '../_internal/ids';
import { PxlOutlet, type PxlContent } from '../_internal/outlet';
import { PixelGlyph } from '../_internal/pixel-glyph';
import { injectEffectiveSurface } from '../overlay-foundation/pxl-kit-surface-provider';

/** One item of a `<pxl-accordion>`. A `content` template receives the item as its context (`let-item`). */
export interface AccordionItem {
  id: string;
  /** Header text. */
  title: string;
  /** Panel content: text or an `<ng-template>`. */
  content: PxlContent;
}

/**
 * Stack of disclosure items: each header is a button reporting
 * `aria-expanded` that shows and hides its panel (`aria-controls`), which
 * refers back to it. One item is open at a time unless `allowMultiple`; the
 * first starts open unless `collapsedByDefault`. A closed panel is not
 * rendered.
 *
 * @example
 * <pxl-accordion [items]="[{ id: 'faq', title: 'FAQ', content: 'Short answers.' }]" allowMultiple />
 */
@Component({
  selector: 'pxl-accordion',
  imports: [PxlOutlet, PixelGlyph],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { '[class]': 'classes' },
  template: `
    @for (row of rows(); track row.item.id) {
      <div [class]="row.classes.item">
        <button
          [id]="row.ids.header"
          type="button"
          [attr.aria-expanded]="row.open"
          [attr.aria-controls]="row.ids.panel"
          [class]="row.classes.trigger"
          (click)="toggle(row.item.id)"
        >
          <span>{{ row.item.title }}</span>
          <svg pxlGlyph="chevronDown" [class]="row.classes.chevron"></svg>
        </button>
        @if (row.open) {
          <div [id]="row.ids.panel" [attr.aria-labelledby]="row.ids.header" [class]="row.classes.panel">
            <ng-container *pxlOutlet="row.item.content; context: { $implicit: row.item }; let text">{{ text }}</ng-container>
          </div>
        }
      </div>
    }
  `,
})
export class PixelAccordion implements OnInit {
  /** The items, in order. */
  readonly items = input.required<AccordionItem[]>();
  /** Several items can be open at once. */
  readonly allowMultiple = input(false, { transform: booleanOr(false) });
  /** Every item starts closed, instead of the first one open. */
  readonly collapsedByDefault = input(false, { transform: booleanOr(false) });
  /** Surface override; defaults to the nearest provider. */
  readonly surface = input<Surface>();

  /** @internal */
  protected readonly classes = accordionClasses;
  private readonly baseId = injectId();
  private readonly effectiveSurface = injectEffectiveSurface(() => this.surface());
  private readonly open = signal<string[]>([]);
  /** @internal */
  protected readonly rows = computed(() =>
    this.items().map((item) => {
      const open = this.open().includes(item.id);
      return {
        item,
        open,
        ids: accordionIds(this.baseId, item.id),
        classes: accordionItemClasses(this.effectiveSurface(), open),
      };
    }),
  );

  // Like React's initial state, the items open on first render are read once.
  ngOnInit(): void {
    this.open.set(accordionInitialOpen(this.items(), this.collapsedByDefault()));
  }

  /** @internal */
  protected toggle(id: string): void {
    this.open.update((open) => toggleAccordionItem(open, id, this.allowMultiple()));
  }
}

// packages/ui-kit-vue/src/navigation/PixelAccordion.vue
<script setup lang="ts">
import { computed, ref, useId } from 'vue';
import {
  accordionClasses,
  accordionIds,
  accordionInitialOpen,
  accordionItemClasses,
  toggleAccordionItem,
  type Surface,
} from '@pxlkit/ui-kit-core';
import PixelGlyph from '../_internal/PixelGlyph.vue';
import { RenderNode, type PxlNode } from '../_internal/render-node.js';
import { useEffectiveSurface } from '../composables/surface.js';

/** One item of a `PixelAccordion`. */
export interface AccordionItem {
  id: string;
  /** Header text. */
  title: string;
  /** Panel content: text, a VNode or a render function. */
  content: PxlNode;
}

/**
 * Stack of disclosure items: each header is a button reporting
 * `aria-expanded` that shows and hides its panel (`aria-controls`), which
 * refers back to it. One item is open at a time unless `allow-multiple`;
 * the first starts open unless `collapsed-by-default`. A closed panel is not
 * rendered.
 *
 * @example
 * <PixelAccordion :items="[{ id: 'faq', title: 'FAQ', content: 'Short answers.' }]" allow-multiple />
 */
export interface PixelAccordionProps {
  /** The items, in order. */
  items: AccordionItem[];
  /** Several items can be open at once. */
  allowMultiple?: boolean;
  /** Every item starts closed, instead of the first one open. */
  collapsedByDefault?: boolean;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
}

const props = withDefaults(defineProps<PixelAccordionProps>(), {
  allowMultiple: false,
  collapsedByDefault: false,
  surface: undefined,
});

const surface = useEffectiveSurface(() => props.surface);
const baseId = useId();
const open = ref(accordionInitialOpen(props.items, props.collapsedByDefault));
const rows = computed(() =>
  props.items.map((item) => {
    const isOpen = open.value.includes(item.id);
    return { item, open: isOpen, ids: accordionIds(baseId, item.id), classes: accordionItemClasses(surface.value, isOpen) };
  }),
);

function toggle(id: string) {
  open.value = toggleAccordionItem(open.value, id, props.allowMultiple);
}
</script>

<template>
  <div :class="accordionClasses">
    <div v-for="row in rows" :key="row.item.id" :class="row.classes.item">
      <button
        :id="row.ids.header"
        type="button"
        :aria-expanded="row.open"
        :aria-controls="row.ids.panel"
        :class="row.classes.trigger"
        @click="toggle(row.item.id)"
      >
        <span>{{ row.item.title }}</span>
        <PixelGlyph name="chevronDown" :class="row.classes.chevron" />
      </button>
      <div v-if="row.open" :id="row.ids.panel" :aria-labelledby="row.ids.header" :class="row.classes.panel">
        <RenderNode :node="row.item.content" />
      </div>
    </div>
  </div>
</template>
