// packages/ui-kit/src/navigation/PixelTabsPanel.tsx
import React, { forwardRef } from 'react';
import { cn, focusRing, surfaceClasses } from '../common';
import { useTabsContext } from './_internal/tabsContext';

/* ─────────────────────────────────────────────────────────────────────────
   PixelTabsPanel — tabpanel content region for a single tab value.
   ───────────────────────────────────────────────────────────────────────── */

/** Public prop bag for {@link PixelTabsPanel}. */
export interface PixelTabsPanelProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'role'> {
  /** Tab id this panel belongs to — must match a {@link PixelTabsTrigger} value. */
  value: string;
  /** Override the root's keepMounted setting for this panel. */
  keepMounted?: boolean;
  /** Render with surface-aware border + radius chrome. Defaults to false (no chrome). */
  bordered?: boolean;
}

export const PixelTabsPanel = forwardRef<HTMLDivElement, PixelTabsPanelProps>(
  function PixelTabsPanel({ value, keepMounted, bordered = false, className, children, ...rest }, ref) {
    const ctx = useTabsContext('PixelTabs.Panel');
    const s = surfaceClasses(ctx.surface);
    const selected = ctx.active === value;
    const shouldMount = (keepMounted ?? ctx.keepMounted) || selected;

    if (!shouldMount) return null;

    return (
      <div
        ref={ref}
        role="tabpanel"
        id={`${ctx.baseId}-panel-${value}`}
        aria-labelledby={`${ctx.baseId}-tab-${value}`}
        hidden={!selected}
        data-state={selected ? 'active' : 'inactive'}
        tabIndex={0}
        className={cn(
          'p-3 text-sm text-retro-muted focus-visible:outline-hidden',
          bordered && 'bg-retro-bg/50',
          bordered && s.border,
          bordered && s.radius,
          bordered && 'border-retro-border/40',
          focusRing, 'focus-visible:ring-retro-cyan/30',
          className,
        )}
        {...rest}
      >
        {children}
      </div>
    );
  },
);

PixelTabsPanel.displayName = 'PixelTabs.Panel';

// packages/ui-kit-vue/src/navigation/PixelTabsPanel.vue
<script setup lang="ts">
import { computed, type VNode } from 'vue';
import { cn, focusRing, surfaceClasses } from '@pxlkit/ui-kit-core';
import { useTabsContext } from './_internal/tabs-context.js';

/**
 * The panel (`role="tabpanel"`) of one tab. Only the active panel is in the
 * DOM unless `keep-mounted` is set here or on the root.
 */
const props = withDefaults(
  defineProps<{
    /** Id of the tab — matches a `PixelTabsTrigger` value. */
    value: string;
    /** Override the root's `keep-mounted` for this panel. */
    keepMounted?: boolean;
    /** Surface-aware border and radius chrome. */
    bordered?: boolean;
  }>(),
  { keepMounted: undefined, bordered: false },
);
defineSlots<{
  /** The panel's content. */
  default?(): VNode[];
}>();

const context = useTabsContext('PixelTabsPanel');
const selected = computed(() => context.active.value === props.value);
const mounted = computed(() => (props.keepMounted ?? context.keepMounted.value) || selected.value);
const classes = computed(() => {
  const s = surfaceClasses(context.surface.value);
  return cn(
    'p-3 text-sm text-retro-muted focus-visible:outline-hidden',
    props.bordered && 'bg-retro-bg/50',
    props.bordered && s.border,
    props.bordered && s.radius,
    props.bordered && 'border-retro-border/40',
    focusRing,
    'focus-visible:ring-retro-cyan/30',
  );
});
</script>

<template>
  <div
    v-if="mounted"
    role="tabpanel"
    :id="`${context.baseId}-panel-${value}`"
    :aria-labelledby="`${context.baseId}-tab-${value}`"
    :hidden="!selected"
    :data-state="selected ? 'active' : 'inactive'"
    tabindex="0"
    :class="classes"
  >
    <slot />
  </div>
</template>
