// packages/ui-kit/src/navigation/PixelSidebar.tsx
'use client';

import React, { forwardRef } from 'react';
import {
  sidebarBadgeClasses,
  sidebarBodyClasses,
  sidebarClasses,
  sidebarFooterClasses,
  sidebarHeaderClasses,
  sidebarHeaderContentClasses,
  sidebarItemClasses,
  sidebarItemIconClasses,
  sidebarItemLabelClasses,
  sidebarListClasses,
  sidebarNestedListClasses,
  sidebarSectionClasses,
  sidebarSectionLabel,
  sidebarSectionTitleClasses,
  sidebarToggleArrow,
  sidebarToggleArrowClasses,
  sidebarToggleClasses,
  sidebarToggleLabel,
} from '@pxlkit/ui-kit-core';
import { cn, Surface, useEffectiveSurface } from '../common';
import { ToneKey } from '../tokens';

export interface PixelSidebarItemProps {
  /** Unique among its siblings. */
  id: string;
  /** Text of the item; its accessible name and tooltip while the sidebar is collapsed. */
  label: string;
  /** Icon before the label, hidden from assistive technology. */
  icon?: React.ReactNode;
  /** Badge after the label: its text and tone. */
  badge?: { label: string; tone?: ToneKey };
  /** Link target: the item is a link; without one it is a button. */
  href?: string;
  /** Called when the item is pressed; only a button calls it (an item with `href` is a link). */
  onSelect?: () => void;
  /** Marks the current page (`aria-current="page"`). */
  active?: boolean;
  /** Child items, listed below it while the sidebar is expanded. */
  nested?: PixelSidebarItemProps[];
}

export interface PixelSidebarSectionProps {
  /** Canonical section label. */
  label?: string;
  /**
   * @deprecated Use `label` instead. Retained as alias for one minor.
   */
  title?: string;
  /** The section's items. */
  items: PixelSidebarItemProps[];
}

export interface PixelSidebarProps extends React.HTMLAttributes<HTMLElement> {
  /** Shows the collapse toggle in the header row. */
  collapsible?: boolean;
  /** Initial collapsed state while uncontrolled. */
  defaultCollapsed?: boolean;
  /** Collapsed state; leave unset for an uncontrolled rail. */
  collapsed?: boolean;
  /** Called with the collapsed state the toggle asks for. */
  onCollapsedChange?: (next: boolean) => void;
  /** The sections, in order. */
  sections: PixelSidebarSectionProps[];
  /** Header content beside the toggle (hidden while collapsed). */
  header?: React.ReactNode;
  /** Footer row content. */
  footer?: React.ReactNode;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
}

function SidebarBadge({
  badge,
  surface,
  collapsed,
}: {
  badge: NonNullable<PixelSidebarItemProps['badge']>;
  surface: Surface;
  collapsed: boolean;
}) {
  if (collapsed) return null;
  return <span className={sidebarBadgeClasses(surface, badge.tone)}>{badge.label}</span>;
}

function SidebarItem({
  item,
  surface,
  collapsed,
  depth,
}: {
  item: PixelSidebarItemProps;
  surface: Surface;
  collapsed: boolean;
  depth: number;
}) {
  const hasNested = !!item.nested && item.nested.length > 0;

  const onClick = () => {
    item.onSelect?.();
  };

  const isLink = !!item.href;
  const sharedClassName = sidebarItemClasses(surface, { depth, active: !!item.active, collapsed });

  const inner = (
    <>
      {item.icon && (
        <span aria-hidden className={sidebarItemIconClasses}>
          {item.icon}
        </span>
      )}
      <span className={sidebarItemLabelClasses(collapsed)}>{item.label}</span>
      {item.badge && (
        <SidebarBadge badge={item.badge} surface={surface} collapsed={collapsed} />
      )}
    </>
  );

  return (
    // Native <li> listitem semantics — role="none" would leave the parent
    // role="list" with zero owned listitems (axe: aria-required-children).
    <li>
      {isLink ? (
        <a
          href={item.href}
          aria-current={item.active ? 'page' : undefined}
          aria-label={collapsed ? item.label : undefined}
          title={collapsed ? item.label : undefined}
          className={sharedClassName}
        >
          {inner}
        </a>
      ) : (
        <button
          type="button"
          onClick={onClick}
          aria-current={item.active ? 'page' : undefined}
          aria-label={collapsed ? item.label : undefined}
          title={collapsed ? item.label : undefined}
          className={sharedClassName}
        >
          {inner}
        </button>
      )}
      {hasNested && !collapsed && (
        <ul className={sidebarNestedListClasses}>
          {item.nested!.map((child) => (
            <SidebarItem
              key={child.id}
              item={child}
              surface={surface}
              collapsed={collapsed}
              depth={depth + 1}
            />
          ))}
        </ul>
      )}
    </li>
  );
}

export const PixelSidebar = forwardRef<HTMLElement, PixelSidebarProps>(function PixelSidebar(
  {
    collapsible,
    defaultCollapsed,
    collapsed: collapsedProp,
    onCollapsedChange,
    sections,
    header,
    footer,
    surface: surfaceProp,
    className,
    ...rest
  },
  ref,
) {
  const surface = useEffectiveSurface(surfaceProp);

  const isControlled = collapsedProp !== undefined;
  const [internalCollapsed, setInternalCollapsed] = React.useState<boolean>(
    defaultCollapsed ?? false,
  );
  const collapsed = isControlled ? !!collapsedProp : internalCollapsed;

  const toggle = () => {
    const next = !collapsed;
    if (!isControlled) setInternalCollapsed(next);
    onCollapsedChange?.(next);
  };

  return (
    <nav
      ref={ref}
      aria-label="Sidebar"
      className={cn(sidebarClasses(surface, collapsed), className)}
      {...rest}
    >
      {(header || collapsible) && (
        <div className={sidebarHeaderClasses(collapsed)}>
          {!collapsed && header && <div className={sidebarHeaderContentClasses}>{header}</div>}
          {collapsible && (
            <button
              type="button"
              onClick={toggle}
              aria-expanded={!collapsed}
              aria-label={sidebarToggleLabel(collapsed)}
              className={sidebarToggleClasses(surface)}
            >
              <span aria-hidden className={sidebarToggleArrowClasses}>{sidebarToggleArrow(collapsed)}</span>
            </button>
          )}
        </div>
      )}

      <div className={sidebarBodyClasses}>
        {sections.map((section, idx) => {
          const sectionLabel = sidebarSectionLabel(section);
          return (
          <div key={sectionLabel ?? `section-${idx}`} className={sidebarSectionClasses(idx)}>
            {sectionLabel && !collapsed && (
              <h3 className={sidebarSectionTitleClasses(surface)}>
                {sectionLabel}
              </h3>
            )}
            <ul role="list" className={sidebarListClasses}>
              {section.items.map((item) => (
                <SidebarItem
                  key={item.id}
                  item={item}
                  surface={surface}
                  collapsed={collapsed}
                  depth={0}
                />
              ))}
            </ul>
          </div>
          );
        })}
      </div>

      {footer && (
        <div className={sidebarFooterClasses(collapsed)}>
          {footer}
        </div>
      )}
    </nav>
  );
});

PixelSidebar.displayName = 'PixelSidebar';

// packages/ui-kit-vue/src/navigation/PixelSidebar.vue
<script setup lang="ts">
import type { VNode } from 'vue';
import {
  sidebarBodyClasses,
  sidebarClasses,
  sidebarFooterClasses,
  sidebarHeaderClasses,
  sidebarHeaderContentClasses,
  sidebarListClasses,
  sidebarSectionClasses,
  sidebarSectionLabel,
  sidebarSectionTitleClasses,
  sidebarToggleArrow,
  sidebarToggleArrowClasses,
  sidebarToggleClasses,
  sidebarToggleLabel,
  type Surface,
  type ToneKey,
} from '@pxlkit/ui-kit-core';
import type { PxlNode } from '../_internal/render-node.js';
import { useControllableState } from '../composables/controllable.js';
import { useEffectiveSurface } from '../composables/surface.js';
import SidebarItem from './_internal/SidebarItem.vue';

/** One item of a `PixelSidebar` section. */
export interface PixelSidebarItemProps {
  id: string;
  label: string;
  /** Icon before the label, hidden from assistive technology: text, a VNode or a render function. */
  icon?: PxlNode;
  /** Badge at the end of the row (hidden while collapsed). */
  badge?: { label: string; tone?: ToneKey };
  /** Link target: the item is an `<a>`; without one it is a `<button>`. */
  href?: string;
  /** Called when the item's button is clicked (not for links). */
  onSelect?: () => void;
  /** The current page: tinted and marked `aria-current="page"`. */
  active?: boolean;
  /** Items nested under this one (hidden while collapsed). */
  nested?: PixelSidebarItemProps[];
}

/** A titled group of sidebar items. */
export interface PixelSidebarSectionProps {
  /** Heading of the section (hidden while collapsed). */
  label?: string;
  /** @deprecated Use `label`. */
  title?: string;
  items: PixelSidebarItemProps[];
}

/**
 * Vertical navigation rail in a `<nav>` landmark named "Sidebar" (an
 * `aria-label` attribute renames it): sections of items with badges and
 * nested items, under an optional `#header` and above an optional `#footer`.
 * With `collapsible`, a toggle (`aria-expanded`) narrows the rail to its
 * icons; bind the state with `v-model:collapsed`, or leave it uncontrolled
 * with `default-collapsed`. Other attributes fall through to the `<nav>`.
 *
 * @example
 * <PixelSidebar v-model:collapsed="collapsed" collapsible :sections="sections">
 *   <template #header>pxlkit</template>
 * </PixelSidebar>
 */
export interface PixelSidebarProps {
  /** Shows the collapse toggle in the header row. */
  collapsible?: boolean;
  /** Initial collapsed state while uncontrolled. */
  defaultCollapsed?: boolean;
  /** Collapsed state (`v-model:collapsed`); leave unset for an uncontrolled rail. */
  collapsed?: boolean;
  /** The sections, in order. */
  sections: PixelSidebarSectionProps[];
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
}

const props = withDefaults(defineProps<PixelSidebarProps>(), {
  collapsible: false,
  defaultCollapsed: false,
  collapsed: undefined,
  surface: undefined,
});
const emit = defineEmits<{
  /** The collapsed state the toggle asks for, for `v-model:collapsed`. */
  'update:collapsed': [collapsed: boolean];
}>();
defineSlots<{
  /** Header content beside the toggle (hidden while collapsed). */
  header?(): VNode[];
  /** Footer row content. */
  footer?(): VNode[];
}>();

const surface = useEffectiveSurface(() => props.surface);
const [collapsed, setCollapsed] = useControllableState({
  value: () => props.collapsed,
  defaultValue: () => props.defaultCollapsed,
  onChange: (next) => emit('update:collapsed', next),
});
</script>

<template>
  <nav aria-label="Sidebar" :class="sidebarClasses(surface, collapsed)">
    <div v-if="$slots.header || collapsible" :class="sidebarHeaderClasses(collapsed)">
      <div v-if="!collapsed && $slots.header" :class="sidebarHeaderContentClasses"><slot name="header" /></div>
      <button
        v-if="collapsible"
        type="button"
        :aria-expanded="!collapsed"
        :aria-label="sidebarToggleLabel(collapsed)"
        :class="sidebarToggleClasses(surface)"
        @click="setCollapsed(!collapsed)"
      >
        <span aria-hidden="true" :class="sidebarToggleArrowClasses">{{ sidebarToggleArrow(collapsed) }}</span>
      </button>
    </div>

    <div :class="sidebarBodyClasses">
      <div
        v-for="(section, index) in sections"
        :key="sidebarSectionLabel(section) ?? `section-${index}`"
        :class="sidebarSectionClasses(index)"
      >
        <h3 v-if="sidebarSectionLabel(section) && !collapsed" :class="sidebarSectionTitleClasses(surface)">
          {{ sidebarSectionLabel(section) }}
        </h3>
        <ul role="list" :class="sidebarListClasses">
          <SidebarItem
            v-for="item in section.items"
            :key="item.id"
            :item="item"
            :surface="surface"
            :collapsed="collapsed"
            :depth="0"
          />
        </ul>
      </div>
    </div>

    <div v-if="$slots.footer" :class="sidebarFooterClasses(collapsed)"><slot name="footer" /></div>
  </nav>
</template>
