// packages/ui-kit-vue/src/navigation/PixelSidebar.vue
<script setup lang="ts">
import type { VNode } from 'vue';
import {
  sidebarBodyClasses,
  sidebarClasses,
  sidebarFooterClasses,
  sidebarHeaderClasses,
  sidebarHeaderContentClasses,
  sidebarListClasses,
  sidebarSectionClasses,
  sidebarSectionLabel,
  sidebarSectionTitleClasses,
  sidebarToggleArrow,
  sidebarToggleArrowClasses,
  sidebarToggleClasses,
  sidebarToggleLabel,
  type Surface,
  type ToneKey,
} from '@pxlkit/ui-kit-core';
import type { PxlNode } from '../_internal/render-node.js';
import { useControllableState } from '../composables/controllable.js';
import { useEffectiveSurface } from '../composables/surface.js';
import SidebarItem from './_internal/SidebarItem.vue';

/** One item of a `PixelSidebar` section. */
export interface PixelSidebarItemProps {
  id: string;
  label: string;
  /** Icon before the label, hidden from assistive technology: text, a VNode or a render function. */
  icon?: PxlNode;
  /** Badge at the end of the row (hidden while collapsed). */
  badge?: { label: string; tone?: ToneKey };
  /** Link target: the item is an `<a>`; without one it is a `<button>`. */
  href?: string;
  /** Called when the item's button is clicked (not for links). */
  onSelect?: () => void;
  /** The current page: tinted and marked `aria-current="page"`. */
  active?: boolean;
  /** Items nested under this one (hidden while collapsed). */
  nested?: PixelSidebarItemProps[];
}

/** A titled group of sidebar items. */
export interface PixelSidebarSectionProps {
  /** Heading of the section (hidden while collapsed). */
  label?: string;
  /** @deprecated Use `label`. */
  title?: string;
  items: PixelSidebarItemProps[];
}

/**
 * Vertical navigation rail in a `<nav>` landmark named "Sidebar" (an
 * `aria-label` attribute renames it): sections of items with badges and
 * nested items, under an optional `#header` and above an optional `#footer`.
 * With `collapsible`, a toggle (`aria-expanded`) narrows the rail to its
 * icons; bind the state with `v-model:collapsed`, or leave it uncontrolled
 * with `default-collapsed`. Other attributes fall through to the `<nav>`.
 *
 * @example
 * <PixelSidebar v-model:collapsed="collapsed" collapsible :sections="sections">
 *   <template #header>pxlkit</template>
 * </PixelSidebar>
 */
export interface PixelSidebarProps {
  /** Shows the collapse toggle in the header row. */
  collapsible?: boolean;
  /** Initial collapsed state while uncontrolled. */
  defaultCollapsed?: boolean;
  /** Collapsed state (`v-model:collapsed`); leave unset for an uncontrolled rail. */
  collapsed?: boolean;
  /** The sections, in order. */
  sections: PixelSidebarSectionProps[];
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
}

const props = withDefaults(defineProps<PixelSidebarProps>(), {
  collapsible: false,
  defaultCollapsed: false,
  collapsed: undefined,
  surface: undefined,
});
const emit = defineEmits<{
  /** The collapsed state the toggle asks for, for `v-model:collapsed`. */
  'update:collapsed': [collapsed: boolean];
}>();
defineSlots<{
  /** Header content beside the toggle (hidden while collapsed). */
  header?(): VNode[];
  /** Footer row content. */
  footer?(): VNode[];
}>();

const surface = useEffectiveSurface(() => props.surface);
const [collapsed, setCollapsed] = useControllableState({
  value: () => props.collapsed,
  defaultValue: () => props.defaultCollapsed,
  onChange: (next) => emit('update:collapsed', next),
});
</script>

<template>
  <nav aria-label="Sidebar" :class="sidebarClasses(surface, collapsed)">
    <div v-if="$slots.header || collapsible" :class="sidebarHeaderClasses(collapsed)">
      <div v-if="!collapsed && $slots.header" :class="sidebarHeaderContentClasses"><slot name="header" /></div>
      <button
        v-if="collapsible"
        type="button"
        :aria-expanded="!collapsed"
        :aria-label="sidebarToggleLabel(collapsed)"
        :class="sidebarToggleClasses(surface)"
        @click="setCollapsed(!collapsed)"
      >
        <span aria-hidden="true" :class="sidebarToggleArrowClasses">{{ sidebarToggleArrow(collapsed) }}</span>
      </button>
    </div>

    <div :class="sidebarBodyClasses">
      <div
        v-for="(section, index) in sections"
        :key="sidebarSectionLabel(section) ?? `section-${index}`"
        :class="sidebarSectionClasses(index)"
      >
        <h3 v-if="sidebarSectionLabel(section) && !collapsed" :class="sidebarSectionTitleClasses(surface)">
          {{ sidebarSectionLabel(section) }}
        </h3>
        <ul role="list" :class="sidebarListClasses">
          <SidebarItem
            v-for="item in section.items"
            :key="item.id"
            :item="item"
            :surface="surface"
            :collapsed="collapsed"
            :depth="0"
          />
        </ul>
      </div>
    </div>

    <div v-if="$slots.footer" :class="sidebarFooterClasses(collapsed)"><slot name="footer" /></div>
  </nav>
</template>

// packages/ui-kit-angular/src/lib/navigation/pixel-sidebar.ts
import {
  ChangeDetectionStrategy,
  Component,
  HostAttributeToken,
  computed,
  inject,
  input,
  model,
  signal,
  type OnInit,
} from '@angular/core';
import {
  sidebarBodyClasses,
  sidebarClasses,
  sidebarFooterClasses,
  sidebarHeaderClasses,
  sidebarHeaderContentClasses,
  sidebarListClasses,
  sidebarSectionClasses,
  sidebarSectionLabel,
  sidebarSectionTitleClasses,
  sidebarToggleArrow,
  sidebarToggleArrowClasses,
  sidebarToggleClasses,
  sidebarToggleLabel,
  type Surface,
  type ToneKey,
} from '@pxlkit/ui-kit-core';
import { booleanOr } from '../_internal/coercion';
import { PxlOutlet, type PxlContent } from '../_internal/outlet';
import { injectEffectiveSurface } from '../overlay-foundation/pxl-kit-surface-provider';
import { PixelSidebarItem } from './_internal/sidebar-item';

/** One item of a `<pxl-sidebar>` section. */
export interface PixelSidebarItemProps {
  id: string;
  label: string;
  /** Icon before the label, hidden from assistive technology: text or an `<ng-template>`. */
  icon?: PxlContent;
  /** Badge at the end of the row (hidden while collapsed). */
  badge?: { label: string; tone?: ToneKey };
  /** Link target: the item is an `<a>`; without one it is a `<button>`. */
  href?: string;
  /** Called when the item's button is clicked (not for links). */
  onSelect?: () => void;
  /** The current page: tinted and marked `aria-current="page"`. */
  active?: boolean;
  /** Items nested under this one (hidden while collapsed). */
  nested?: PixelSidebarItemProps[];
}

/** A titled group of sidebar items. */
export interface PixelSidebarSectionProps {
  /** Heading of the section (hidden while collapsed). */
  label?: string;
  /** @deprecated Use `label`. */
  title?: string;
  items: PixelSidebarItemProps[];
}

/**
 * Vertical navigation rail: sections of items with badges and nested items,
 * under an optional `header` and above an optional `footer` (text or an
 * `<ng-template>`). With `collapsible`, a toggle (`aria-expanded`) narrows
 * the rail to its icons; bind the state with `[(collapsed)]`, or leave it
 * uncontrolled with `defaultCollapsed`. The host is the navigation landmark
 * (`role="navigation"`), named "Sidebar" unless it has an `aria-label`.
 *
 * @example
 * <pxl-sidebar [(collapsed)]="collapsed" collapsible [sections]="sections" header="pxlkit" />
 */
@Component({
  selector: 'pxl-sidebar',
  imports: [PxlOutlet, PixelSidebarItem],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    role: 'navigation',
    '[attr.aria-label]': 'ariaLabel',
    '[class]': 'classes()',
  },
  template: `
    @if (header() || collapsible()) {
      <div [class]="headerClasses()">
        @if (!isCollapsed() && header()) {
          <div [class]="headerContentClasses"><ng-container *pxlOutlet="header(); let text">{{ text }}</ng-container></div>
        }
        @if (collapsible()) {
          <button
            type="button"
            [attr.aria-expanded]="!isCollapsed()"
            [attr.aria-label]="toggleLabel()"
            [class]="toggleClasses()"
            (click)="toggle()"
          >
            <span aria-hidden="true" [class]="toggleArrowClasses">{{ toggleArrow() }}</span>
          </button>
        }
      </div>
    }
    <div [class]="bodyClasses">
      @for (section of sections(); track sectionLabel(section) ?? 'section-' + $index) {
        <div [class]="sectionClasses($index)">
          @let label = sectionLabel(section);
          @if (label && !isCollapsed()) {
            <h3 [class]="sectionTitleClasses()">{{ label }}</h3>
          }
          <ul role="list" [class]="listClasses">
            @for (item of section.items; track item.id) {
              <li [pxlSidebarItem]="item" [surface]="effectiveSurface()" [collapsed]="isCollapsed()" [depth]="0"></li>
            }
          </ul>
        </div>
      }
    </div>
    @if (footer()) {
      <div [class]="footerClasses()"><ng-container *pxlOutlet="footer(); let text">{{ text }}</ng-container></div>
    }
  `,
})
export class PixelSidebar implements OnInit {
  /** Shows the collapse toggle in the header row. */
  readonly collapsible = input(false, { transform: booleanOr(false) });
  /** Initial collapsed state while uncontrolled. */
  readonly defaultCollapsed = input(false, { transform: booleanOr(false) });
  /** Collapsed state (`[(collapsed)]`); leave unset for an uncontrolled rail. */
  readonly collapsed = model<boolean | undefined>(undefined);
  /** The sections, in order. */
  readonly sections = input.required<PixelSidebarSectionProps[]>();
  /** Header content beside the toggle (hidden while collapsed). */
  readonly header = input<PxlContent>();
  /** Footer row content. */
  readonly footer = input<PxlContent>();
  /** Surface override; defaults to the nearest provider. */
  readonly surface = input<Surface>();

  /** @internal */
  protected readonly ariaLabel = inject(new HostAttributeToken('aria-label'), { optional: true }) ?? 'Sidebar';
  /** @internal */
  protected readonly effectiveSurface = injectEffectiveSurface(() => this.surface());
  private readonly initiallyCollapsed = signal(false);
  /** @internal */
  protected readonly isCollapsed = computed(() => this.collapsed() ?? this.initiallyCollapsed());
  /** @internal */
  protected readonly classes = computed(() => sidebarClasses(this.effectiveSurface(), this.isCollapsed()));
  /** @internal */
  protected readonly headerClasses = computed(() => sidebarHeaderClasses(this.isCollapsed()));
  /** @internal */
  protected readonly toggleClasses = computed(() => sidebarToggleClasses(this.effectiveSurface()));
  /** @internal */
  protected readonly toggleLabel = computed(() => sidebarToggleLabel(this.isCollapsed()));
  /** @internal */
  protected readonly toggleArrow = computed(() => sidebarToggleArrow(this.isCollapsed()));
  /** @internal */
  protected readonly sectionTitleClasses = computed(() => sidebarSectionTitleClasses(this.effectiveSurface()));
  /** @internal */
  protected readonly footerClasses = computed(() => sidebarFooterClasses(this.isCollapsed()));
  /** @internal */
  protected readonly headerContentClasses = sidebarHeaderContentClasses;
  /** @internal */
  protected readonly toggleArrowClasses = sidebarToggleArrowClasses;
  /** @internal */
  protected readonly bodyClasses = sidebarBodyClasses;
  /** @internal */
  protected readonly listClasses = sidebarListClasses;
  /** @internal */
  protected readonly sectionLabel = sidebarSectionLabel;
  /** @internal */
  protected readonly sectionClasses = sidebarSectionClasses;

  // Like React's uncontrolled state, the default is read once.
  ngOnInit(): void {
    this.initiallyCollapsed.set(this.defaultCollapsed());
  }

  /** @internal */
  protected toggle(): void {
    this.collapsed.set(!this.isCollapsed());
  }
}
