// packages/ui-kit/src/navigation/PixelPagination.examples.tsx
import { useState } from 'react';
import { PixelPagination } from '../navigation';

export function Default() {
  const [page, setPage] = useState(1);
  return <PixelPagination page={page} total={10} onChange={setPage} />;
}

export function ManyPages() {
  const [page, setPage] = useState(5);
  return <PixelPagination page={page} total={50} onChange={setPage} />;
}

export function MidWindow() {
  const [page, setPage] = useState(10);
  return <PixelPagination page={page} total={20} onChange={setPage} />;
}

export function MoreSiblings() {
  const [page, setPage] = useState(8);
  return <PixelPagination page={page} total={20} onChange={setPage} siblings={2} />;
}

export function PixelSurface() {
  const [page, setPage] = useState(3);
  return <PixelPagination page={page} total={12} onChange={setPage} surface="pixel" />;
}

export function LinearSurface() {
  const [page, setPage] = useState(3);
  return <PixelPagination page={page} total={12} onChange={setPage} surface="linear" />;
}

export function LocalisedLabels() {
  const [page, setPage] = useState(2);
  return (
    <PixelPagination
      page={page}
      total={8}
      onChange={setPage}
      prevLabel="Anterior"
      nextLabel="Siguiente"
      ariaLabel="Paginación"
    />
  );
}

export function FirstPage() {
  return <PixelPagination page={1} total={10} onChange={() => {}} />;
}

export function LastPage() {
  return <PixelPagination page={10} total={10} onChange={() => {}} />;
}

export function SinglePage() {
  return <PixelPagination page={1} total={1} onChange={() => {}} />;
}

// packages/ui-kit-angular/examples/navigation/pixel-pagination.examples.ts
import { Component, signal } from '@angular/core';
import { PixelPagination } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelPagination],
  template: `<pxl-pagination [(page)]="page" [total]="10" />`,
})
export class Default {
  readonly page = signal(1);
}

@Component({
  imports: [PixelPagination],
  template: `<pxl-pagination [(page)]="page" [total]="50" />`,
})
export class ManyPages {
  readonly page = signal(5);
}

@Component({
  imports: [PixelPagination],
  template: `<pxl-pagination [(page)]="page" [total]="20" />`,
})
export class MidWindow {
  readonly page = signal(10);
}

@Component({
  imports: [PixelPagination],
  template: `<pxl-pagination [(page)]="page" [total]="20" [siblings]="2" />`,
})
export class MoreSiblings {
  readonly page = signal(8);
}

@Component({
  imports: [PixelPagination],
  template: `<pxl-pagination [(page)]="page" [total]="12" surface="pixel" />`,
})
export class PixelSurface {
  readonly page = signal(3);
}

@Component({
  imports: [PixelPagination],
  template: `<pxl-pagination [(page)]="page" [total]="12" surface="linear" />`,
})
export class LinearSurface {
  readonly page = signal(3);
}

@Component({
  imports: [PixelPagination],
  template: `
    <pxl-pagination
      [(page)]="page"
      [total]="8"
      prevLabel="Anterior"
      nextLabel="Siguiente"
      ariaLabel="Paginación"
    />
  `,
})
export class LocalisedLabels {
  readonly page = signal(2);
}

@Component({
  imports: [PixelPagination],
  template: `<pxl-pagination [page]="1" [total]="10" />`,
})
export class FirstPage {}

@Component({
  imports: [PixelPagination],
  template: `<pxl-pagination [page]="10" [total]="10" />`,
})
export class LastPage {}

@Component({
  imports: [PixelPagination],
  template: `<pxl-pagination [page]="1" [total]="1" />`,
})
export class SinglePage {}
