// packages/ui-kit-vue/src/overlay-foundation/PixelPopover.vue
<script setup lang="ts">
import { computed, provide, shallowRef, watch, type VNode } from 'vue';
import {
  anchorFloating,
  anchoredMiddleware,
  floatingStyles,
  returnFocusOnRemoval,
  toPlacement,
  type Surface,
} from '@pxlkit/ui-kit-core';
import { useEventListener } from '../composables/event-listener.js';
import { useEscape } from '../composables/overlay.js';
import { useEffectiveSurface } from '../composables/surface.js';
import {
  PIXEL_POPOVER,
  refElement,
  type PopoverAlign,
  type PopoverHasPopup,
  type PopoverRole,
  type PopoverSide,
} from './_internal/popover-context.js';

/**
 * Controlled floating panel anchored to a trigger. Compose
 * `PixelPopoverTrigger` (wrapping one element), `PixelPopoverContent` and
 * optionally `PixelPopoverArrow`; bind the open state with `v-model:open`.
 * Escape and a press outside close it, and content that closes while it
 * holds focus hands focus back to the trigger. Renders no element of its own.
 *
 * @example
 * <PixelPopover v-model:open="open">
 *   <PixelPopoverTrigger><button type="button">Details</button></PixelPopoverTrigger>
 *   <PixelPopoverContent aria-labelledby="details-title">…</PixelPopoverContent>
 * </PixelPopover>
 */
export interface PixelPopoverProps {
  /** Whether the popover is open (`v-model:open`). */
  open: boolean;
  /** Side of the trigger the content opens on; flips when there is no room. */
  side?: PopoverSide;
  /** Alignment of the content along that side. */
  align?: PopoverAlign;
  /** Gap between trigger and content, in px. */
  sideOffset?: number;
  /** Close when Escape is pressed. */
  closeOnEscape?: boolean;
  /** Close on a press outside the trigger and the content. */
  closeOnOutsideClick?: boolean;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
  /**
   * `aria-haspopup` advertised on the trigger: `listbox` for combobox
   * patterns, `menu` for menus. A value set on the trigger element wins.
   */
  haspopup?: PopoverHasPopup;
  /**
   * Role of the content. Set `none` when an inner widget owns the semantics
   * (e.g. a listbox inside a combobox).
   */
  role?: PopoverRole;
}

const props = withDefaults(defineProps<PixelPopoverProps>(), {
  side: 'bottom',
  align: 'center',
  sideOffset: 8,
  closeOnEscape: true,
  closeOnOutsideClick: true,
  surface: undefined,
  haspopup: 'dialog',
  role: 'dialog',
});
const emit = defineEmits<{
  /** The requested open state. */
  'update:open': [open: boolean];
}>();
defineSlots<{ default?(): VNode[] }>();

const surface = useEffectiveSurface(() => props.surface);
const trigger = shallowRef<HTMLElement | null>(null);
const content = shallowRef<HTMLElement | null>(null);
const contentId = shallowRef<string | null>(null);
const position = shallowRef({ x: 0, y: 0 });
// True while a press outside is closing the popover: focus then follows the
// pointer instead of returning to the trigger.
let pressOutside = false;

const setOpen = (next: boolean) => emit('update:open', next);

// Keep the content anchored to the trigger while both are on the page.
watch(
  [trigger, content, () => toPlacement(props.side, props.align), () => props.sideOffset],
  ([reference, floating, placement, sideOffset], _previous, onCleanup) => {
    if (!reference || !floating) return;
    onCleanup(
      anchorFloating(reference, floating, { placement, middleware: anchoredMiddleware(sideOffset) }, ({ x, y }) => {
        position.value = { x, y };
      }),
    );
  },
);

useEscape(
  () => {
    if (props.open) setOpen(false);
  },
  () => props.open && props.closeOnEscape,
);

// The trigger sits outside the teleported content, so both are excluded —
// otherwise a trigger press would close the popover and its click reopen it.
const activeDocument = (active: boolean) => (active && typeof document !== 'undefined' ? document : null);
useEventListener(
  'pointerdown',
  (event) => {
    const target = event.target as Node | null;
    if (!target) return;
    if (content.value?.contains(target)) return;
    if (trigger.value?.contains(target)) return;
    pressOutside = true;
    setOpen(false);
  },
  () => activeDocument(props.open && props.closeOnOutsideClick),
);

// A press outside that did not close the popover (the parent kept it open)
// ends with the pointer release; a new open starts clean.
const releasePress = () => {
  pressOutside = false;
};
useEventListener('pointerup', releasePress, () => activeDocument(props.open));
useEventListener('pointercancel', releasePress, () => activeDocument(props.open));
watch(
  () => props.open,
  (open) => {
    if (open) pressOutside = false;
  },
);

provide(PIXEL_POPOVER, {
  open: computed(() => props.open),
  setOpen,
  side: computed(() => props.side),
  surface,
  haspopup: computed(() => props.haspopup),
  role: computed(() => props.role),
  floatingStyles: computed(() => floatingStyles(content.value, position.value.x, position.value.y)),
  contentId: computed(() => contentId.value),
  setContentId(id) {
    contentId.value = id;
  },
  setTrigger(target) {
    trigger.value = refElement(target);
  },
  setContent(target) {
    const element = refElement(target);
    // Called with null right before the content leaves the page.
    if (!element && content.value && !pressOutside) {
      returnFocusOnRemoval(content.value, () => trigger.value);
    }
    content.value = element;
  },
});
</script>

<template>
  <slot />
</template>

// packages/ui-kit-angular/src/lib/overlay-foundation/pixel-popover.ts
import {
  ChangeDetectionStrategy,
  Component,
  DOCUMENT,
  PLATFORM_ID,
  afterRenderEffect,
  computed,
  effect,
  inject,
  input,
  model,
  signal,
  untracked,
} from '@angular/core';
import { isPlatformBrowser } from '@angular/common';
import {
  anchorFloating,
  anchoredMiddleware,
  floatingStyles,
  returnFocusOnRemoval,
  toPlacement,
  type Surface,
} from '@pxlkit/ui-kit-core';
import { booleanOr, numberOr, withDefault } from '../_internal/coercion';
import {
  PIXEL_POPOVER,
  type PixelPopoverContext,
  type PopoverAlign,
  type PopoverHasPopup,
  type PopoverRole,
  type PopoverSide,
} from './popover-context';
import { injectEffectiveSurface } from './pxl-kit-surface-provider';

/**
 * Controlled floating panel anchored to a trigger. Put `pxlPopoverTrigger` on
 * the element that opens it and `*pxlPopoverContent` on the panel; bind the
 * open state with `[(open)]`. Escape and a press outside close it, and
 * content that closes while it holds focus hands focus back to the trigger.
 *
 * The host is layout-neutral (`display: contents`).
 *
 * @example
 * <pxl-popover [(open)]="open">
 *   <button type="button" pxlPopoverTrigger>Details</button>
 *   <div *pxlPopoverContent aria-labelledby="details-title">…</div>
 * </pxl-popover>
 */
@Component({
  selector: 'pxl-popover',
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [{ provide: PIXEL_POPOVER, useFactory: () => inject(PixelPopover).context }],
  host: {
    '[style.display]': '"contents"',
    // `role` describes the content panel; on the host it would add a stray role.
    '[attr.role]': 'null',
  },
  template: '<ng-content />',
})
export class PixelPopover {
  /** Whether the popover is open (`[(open)]`). */
  readonly open = model.required<boolean>();
  /** Side of the trigger the content opens on; flips when there is no room. */
  readonly side = input<PopoverSide, PopoverSide | undefined>('bottom', { transform: withDefault<PopoverSide>('bottom') });
  /** Alignment of the content along that side. */
  readonly align = input<PopoverAlign, PopoverAlign | undefined>('center', {
    transform: withDefault<PopoverAlign>('center'),
  });
  /** Gap between trigger and content, in px. */
  readonly sideOffset = input(8, { transform: numberOr(8) });
  /** Close when Escape is pressed. */
  readonly closeOnEscape = input(true, { transform: booleanOr(true) });
  /** Close on a press outside the trigger and the content. */
  readonly closeOnOutsideClick = input(true, { transform: booleanOr(true) });
  /** Surface override; defaults to the nearest provider. */
  readonly surface = input<Surface>();
  /**
   * `aria-haspopup` advertised on the trigger: `listbox` for combobox
   * patterns, `menu` for menus. A static `aria-haspopup` on the trigger wins.
   */
  readonly haspopup = input<PopoverHasPopup, PopoverHasPopup | undefined>('dialog', {
    transform: withDefault<PopoverHasPopup>('dialog'),
  });
  /**
   * Role of the content. Set `none` when an inner widget owns the semantics
   * (e.g. a listbox inside a combobox).
   */
  readonly role = input<PopoverRole, PopoverRole | undefined>('dialog', { transform: withDefault<PopoverRole>('dialog') });

  private readonly trigger = signal<HTMLElement | null>(null);
  private readonly content = signal<HTMLElement | null>(null);
  private readonly contentId = signal<string | null>(null);
  private readonly position = signal({ x: 0, y: 0 });
  // True while a press outside is closing the popover: focus then follows the
  // pointer instead of returning to the trigger.
  private pressOutside = false;

  /** @internal */
  readonly context: PixelPopoverContext = {
    open: this.open.asReadonly(),
    side: this.side,
    surface: injectEffectiveSurface(() => this.surface()),
    haspopup: this.haspopup,
    role: this.role,
    floatingStyles: computed(() => {
      const { x, y } = this.position();
      return floatingStyles(this.content(), x, y);
    }),
    contentId: this.contentId.asReadonly(),
    setOpen: (open) => this.open.set(open),
    setTrigger: (element) => this.trigger.set(element),
    setContent: (element) => {
      const previous = untracked(this.content);
      if (!element && previous && !this.pressOutside) {
        returnFocusOnRemoval(previous, () => untracked(this.trigger));
      }
      this.content.set(element);
    },
    setContentId: (id) => this.contentId.set(id),
  };

  constructor() {
    if (!isPlatformBrowser(inject(PLATFORM_ID))) return;
    const document = inject(DOCUMENT);

    // Keep the content anchored to the trigger while both are on the page.
    effect((onCleanup) => {
      const reference = this.trigger();
      const floating = this.content();
      if (!reference || !floating) return;
      const placement = toPlacement(this.side(), this.align());
      const middleware = anchoredMiddleware(this.sideOffset());
      onCleanup(
        anchorFloating(reference, floating, { placement, middleware }, ({ x, y }) => this.position.set({ x, y })),
      );
    });

    // Dismissal listeners, attached while open.
    afterRenderEffect((onCleanup) => {
      if (!this.open()) return;
      this.pressOutside = false;
      const view = document.defaultView;
      const onKeydown = (event: KeyboardEvent) => {
        if (event.key === 'Escape' && this.closeOnEscape()) this.open.set(false);
      };
      // The trigger sits outside the content panel, so both are excluded —
      // otherwise a trigger press would close the popover and its click reopen it.
      const onPointerDown = (event: PointerEvent) => {
        const target = event.target as Node | null;
        if (!target || !this.closeOnOutsideClick()) return;
        if (untracked(this.content)?.contains(target)) return;
        if (untracked(this.trigger)?.contains(target)) return;
        this.pressOutside = true;
        this.open.set(false);
      };
      // A press outside that did not close the popover (the parent kept it
      // open) ends with the pointer release.
      const onPointerRelease = () => {
        this.pressOutside = false;
      };
      view?.addEventListener('keydown', onKeydown);
      document.addEventListener('pointerdown', onPointerDown);
      document.addEventListener('pointerup', onPointerRelease);
      document.addEventListener('pointercancel', onPointerRelease);
      onCleanup(() => {
        view?.removeEventListener('keydown', onKeydown);
        document.removeEventListener('pointerdown', onPointerDown);
        document.removeEventListener('pointerup', onPointerRelease);
        document.removeEventListener('pointercancel', onPointerRelease);
      });
    });
  }
}
