// packages/ui-kit-vue/src/feedback/PixelSpinner.vue
<script setup lang="ts">
import { computed } from 'vue';
import {
  SPINNER_DEFAULT_LABEL,
  spinnerAnimation,
  spinnerClasses,
  type SpinnerSize,
  type Surface,
  type ToneKey,
} from '@pxlkit/ui-kit-core';
import { useReducedMotion } from '../composables/media-query.js';
import { useEffectiveSurface } from '../composables/surface.js';

/**
 * Compact loading indicator: a square blade turning in eight steps on the
 * pixel surface, a smoothly spinning ring on the linear one — frozen when the
 * user prefers reduced motion. It is a `role="status"` region named by
 * `label` (also visually hidden text), or pure decoration with `decorative`.
 * Other attributes fall through to the root `<span>`.
 *
 * @example
 * <PixelSpinner size="lg" tone="cyan" label="Loading results" />
 */
export interface PixelSpinnerProps {
  /** Box size. */
  size?: SpinnerSize;
  /** Accessible name. */
  label?: string;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
  /** Colour. */
  tone?: ToneKey;
  /**
   * Pure decoration (`aria-hidden`, no role, no label), for a parent that
   * already announces its busy state (a button with `aria-busy="true"`). A
   * standalone spinner needs `aria-busy="true"` on the container that loads.
   */
  decorative?: boolean;
}

const props = withDefaults(defineProps<PixelSpinnerProps>(), {
  size: 'md',
  label: SPINNER_DEFAULT_LABEL,
  surface: undefined,
  tone: 'cyan',
  decorative: false,
});

const surface = useEffectiveSurface(() => props.surface);
const reducedMotion = useReducedMotion();
const classes = computed(() => spinnerClasses(surface.value, props.size, props.tone));
const animation = computed(() => spinnerAnimation(surface.value, { reducedMotion: reducedMotion.value }));
// role=status already implies aria-live=polite, so it is not repeated.
const liveAttrs = computed(() =>
  props.decorative ? { 'aria-hidden': 'true' as const } : { role: 'status', 'aria-label': props.label },
);
</script>

<template>
  <span v-bind="liveAttrs" :class="classes.root">
    <span data-pxl-spinner-blade="true" aria-hidden="true" :class="classes.blade" :style="animation ? { animation } : undefined" />
    <span v-if="!decorative" class="sr-only">{{ label }}</span>
  </span>
</template>

// packages/ui-kit/src/feedback/PixelSpinner.tsx
'use client';

import React, { forwardRef } from 'react';
import { SPINNER_DEFAULT_LABEL, spinnerAnimation, spinnerClasses, type SpinnerSize } from '@pxlkit/ui-kit-core';
import { cn, Surface, useEffectiveSurface } from '../common';
import { ToneKey } from '../tokens';
import { useReducedMotion } from '../hooks/useReducedMotion';

export interface PixelSpinnerProps extends React.HTMLAttributes<HTMLSpanElement> {
  /** Box size. */
  size?: SpinnerSize;
  /** Accessible name. */
  label?: string;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
  /** Colour. */
  tone?: ToneKey;
  /**
   * When `true`, renders as pure decoration (aria-hidden, no role, no label).
   * Use inside an already-announcing parent (e.g. a `<button loading>` that
   * declares `aria-busy="true"`) to avoid double announcements.
   *
   * NOTE: when using PixelSpinner as a standalone loading indicator (not
   * decorative), the consumer MUST set `aria-busy="true"` on the loading
   * container per WAI-ARIA — the spinner alone isn't enough context.
   */
  decorative?: boolean;
}

export const PixelSpinner = forwardRef<HTMLSpanElement, PixelSpinnerProps>(function PixelSpinner(
  { size = 'md', label = SPINNER_DEFAULT_LABEL, surface: surfaceProp, tone = 'cyan', decorative = false, className, ...rest },
  ref,
) {
  const surface = useEffectiveSurface(surfaceProp);
  const reducedMotion = useReducedMotion();
  const animation = spinnerAnimation(surface, { reducedMotion });
  const classes = spinnerClasses(surface, size, tone);

  // role=status already implies aria-live=polite per WAI-ARIA. No need to
  // declare it twice — assistive tech treats the polite default identically.
  const liveAttrs: React.HTMLAttributes<HTMLSpanElement> = decorative
    ? { 'aria-hidden': true }
    : { role: 'status', 'aria-label': label };

  return (
    <span ref={ref} {...liveAttrs} className={cn(classes.root, className)} {...rest}>
      <span data-pxl-spinner-blade aria-hidden className={classes.blade} style={animation ? { animation } : undefined} />
      {!decorative && <span className="sr-only">{label}</span>}
    </span>
  );
});

PixelSpinner.displayName = 'PixelSpinner';
