// packages/ui-kit-angular/examples/overlay-foundation/pxl-kit-locale-provider.examples.ts
import { Component } from '@angular/core';
import { PxlKitLocaleProvider } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PxlKitLocaleProvider],
  template: `
    <pxl-locale-provider locale="en">
      <p>Hello, world!</p>
    </pxl-locale-provider>
  `,
})
export class Default {}

@Component({
  imports: [PxlKitLocaleProvider],
  template: `
    <pxl-locale-provider locale="tr">
      <p>İstanbul güneşli bir şehirdir</p>
    </pxl-locale-provider>
  `,
})
export class Turkish {}

// packages/ui-kit/src/overlay-foundation/PxlKitLocaleProvider.examples.tsx
import React from 'react';
import { PxlKitLocaleProvider } from './PxlKitLocaleProvider';

export function Default() {
  return (
    <PxlKitLocaleProvider locale="en">
      <p>Hello, world!</p>
    </PxlKitLocaleProvider>
  );
}

export function Turkish() {
  return (
    <PxlKitLocaleProvider locale="tr">
      <p>İstanbul güneşli bir şehirdir</p>
    </PxlKitLocaleProvider>
  );
}
