// packages/ui-kit-angular/examples/overlay-foundation/pxl-kit-surface-provider.examples.ts
import { Component } from '@angular/core';
import { PixelButton, PxlKitSurfaceProvider } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelButton, PxlKitSurfaceProvider],
  template: `
    <ng-container pxlKitSurface="pixel">
      <div class="flex flex-wrap gap-2">
        <button pxlButton>Pixel</button>
        <button pxlButton variant="outline" tone="cyan">Pixel outline</button>
      </div>
    </ng-container>
  `,
})
export class Default {}

@Component({
  imports: [PixelButton, PxlKitSurfaceProvider],
  template: `
    <ng-container pxlKitSurface="linear">
      <div class="flex flex-wrap gap-2">
        <button pxlButton>Linear</button>
        <button pxlButton variant="outline" tone="cyan">Linear outline</button>
      </div>
    </ng-container>
  `,
})
export class Linear {}

@Component({
  imports: [PixelButton, PxlKitSurfaceProvider],
  template: `
    <ng-container pxlKitSurface="linear">
      <div class="flex flex-wrap gap-2">
        <button pxlButton>From the provider</button>
        <button pxlButton surface="pixel">Own surface prop</button>
      </div>
    </ng-container>
  `,
})
export class Override {}

// packages/ui-kit/src/overlay-foundation/PxlKitSurfaceProvider.examples.tsx
import React from 'react';
import { PixelButton } from '../actions';
import { PxlKitSurfaceProvider } from './PxlKitSurfaceProvider';

export function Default() {
  return (
    <PxlKitSurfaceProvider surface="pixel">
      <div className="flex flex-wrap gap-2">
        <PixelButton>Pixel</PixelButton>
        <PixelButton variant="outline" tone="cyan">Pixel outline</PixelButton>
      </div>
    </PxlKitSurfaceProvider>
  );
}

export function Linear() {
  return (
    <PxlKitSurfaceProvider surface="linear">
      <div className="flex flex-wrap gap-2">
        <PixelButton>Linear</PixelButton>
        <PixelButton variant="outline" tone="cyan">Linear outline</PixelButton>
      </div>
    </PxlKitSurfaceProvider>
  );
}

export function Override() {
  return (
    <PxlKitSurfaceProvider surface="linear">
      <div className="flex flex-wrap gap-2">
        <PixelButton>From the provider</PixelButton>
        <PixelButton surface="pixel">Own surface prop</PixelButton>
      </div>
    </PxlKitSurfaceProvider>
  );
}
