// packages/ui-kit/src/data/PixelCarousel.tsx
'use client';

import React, { forwardRef, useCallback, useEffect, useId, useMemo, useState } from 'react';
import useEmblaCarousel from 'embla-carousel-react';
import type { EmblaCarouselType, EmblaOptionsType, EmblaPluginType } from 'embla-carousel';
import {
  CAROUSEL_DOTS_LABEL,
  CAROUSEL_NEXT_LABEL,
  CAROUSEL_PREVIOUS_LABEL,
  canRunCarousel,
  carouselArrowDisabled,
  carouselClasses,
  carouselDotClasses,
  carouselDotCount,
  carouselDotLabel,
  carouselItemClasses,
  carouselKeyStep,
  carouselOptions,
  carouselSlideLabel,
  carouselStatus,
  type CarouselOrientation,
} from '@pxlkit/ui-kit-core';
import { Surface, cn, useEffectiveSurface } from '../common';
import { useReducedMotion } from '../hooks/useReducedMotion';

export interface PixelCarouselProps extends React.HTMLAttributes<HTMLDivElement> {
  /**
   * Full embla options surface (see embla-carousel docs). Common subset:
   * `loop`, `align`, `slidesToScroll`, `startIndex`, `dragFree`,
   * `containScroll`, `inViewThreshold`. `axis` is set internally from
   * `orientation`.
   */
  opts?: Omit<EmblaOptionsType, 'axis'>;
  /** Optional embla plugins (autoplay, autoScroll, etc.). */
  plugins?: EmblaPluginType[];
  /** Receives the embla API once ready; called again with `undefined` on unmount. */
  setApi?: (api: EmblaCarouselType | undefined) => void;
  /** Slides side by side, or stacked. */
  orientation?: CarouselOrientation;
  /** Previous and next buttons. */
  showArrows?: boolean;
  /** A dot per slide, to go to it. */
  showDots?: boolean;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
  /** Accessible name for the carousel region (required for landmark navigation). */
  'aria-label'?: string;
  /** The slides (`PixelCarousel.Item`). */
  children: React.ReactNode;
}

interface PixelCarouselItemProps extends React.HTMLAttributes<HTMLDivElement> {
  /** The slide's content. */
  children: React.ReactNode;
}

interface CarouselItemCtx {
  index: number;
  total: number;
}

const CarouselItemContext = React.createContext<CarouselItemCtx | null>(null);

const PixelCarouselItem = forwardRef<HTMLDivElement, PixelCarouselItemProps>(
  function PixelCarouselItem({ children, className, ...rest }, ref) {
    const ctx = React.useContext(CarouselItemContext);
    const ariaLabel = ctx ? carouselSlideLabel(ctx.index, ctx.total) : undefined;
    return (
      <div
        ref={ref}
        role="group"
        aria-roledescription="slide"
        aria-label={ariaLabel}
        className={cn(carouselItemClasses, className)}
        {...rest}
      >
        {children}
      </div>
    );
  },
);
PixelCarouselItem.displayName = 'PixelCarousel.Item';

const PixelCarouselRoot = forwardRef<HTMLDivElement, PixelCarouselProps>(function PixelCarousel(
  {
    opts,
    plugins,
    setApi,
    orientation = 'horizontal',
    showArrows = true,
    showDots = false,
    surface: surfaceProp,
    children,
    className,
    ...rest
  },
  ref,
) {
  const surface = useEffectiveSurface(surfaceProp);
  const classes = carouselClasses(surface, orientation);
  const carouselId = useId();
  const reducedMotion = useReducedMotion();

  // Respects prefers-reduced-motion by zeroing out embla's scroll duration.
  const emblaOptions = useMemo<EmblaOptionsType>(
    () => carouselOptions(opts, { orientation, reducedMotion }),
    [opts, orientation, reducedMotion],
  );

  const [emblaRef, emblaApi] = useEmblaCarousel(emblaOptions, plugins);

  const [selectedIndex, setSelectedIndex] = useState(0);
  const [scrollSnaps, setScrollSnaps] = useState<number[]>([]);
  const [canPrev, setCanPrev] = useState(false);
  const [canNext, setCanNext] = useState(false);

  const onSelect = useCallback(() => {
    if (!emblaApi) return;
    setSelectedIndex(emblaApi.selectedScrollSnap());
    setCanPrev(emblaApi.canScrollPrev());
    setCanNext(emblaApi.canScrollNext());
  }, [emblaApi]);

  useEffect(() => {
    if (!emblaApi) return;
    setScrollSnaps(emblaApi.scrollSnapList());
    onSelect();
    emblaApi.on('select', onSelect);
    emblaApi.on('reInit', onSelect);
    return () => {
      emblaApi.off('select', onSelect);
      emblaApi.off('reInit', onSelect);
    };
  }, [emblaApi, onSelect]);

  // Expose embla API to the parent (shadcn-style escape hatch).
  useEffect(() => {
    if (!setApi) return;
    setApi(emblaApi ?? undefined);
    return () => setApi(undefined);
  }, [emblaApi, setApi]);

  const scrollPrev = useCallback(() => emblaApi?.scrollPrev(), [emblaApi]);
  const scrollNext = useCallback(() => emblaApi?.scrollNext(), [emblaApi]);
  const scrollTo = useCallback((i: number) => emblaApi?.scrollTo(i), [emblaApi]);

  const onKeyDown: React.KeyboardEventHandler<HTMLDivElement> = (e) => {
    const step = carouselKeyStep(e.key, orientation);
    if (!step) return;
    e.preventDefault();
    if (step < 0) scrollPrev();
    else scrollNext();
  };

  // Derive slide count from children for dots fallback when api hasn't reported yet.
  const childArray = React.Children.toArray(children).filter(React.isValidElement);
  const dotCount = carouselDotCount(scrollSnaps.length, childArray.length);
  const total = childArray.length;

  // Wrap each Item child in an index/total context so its aria-label can read
  // "Slide N of M". Done via a Provider per child rather than cloneElement to
  // support user-defined wrapper components around Items.
  const wrappedChildren = childArray.map((child, i) => (
    <CarouselItemContext.Provider key={(child as React.ReactElement).key ?? i} value={{ index: i, total }}>
      {child}
    </CarouselItemContext.Provider>
  ));

  return (
    <div
      ref={ref}
      role="region"
      aria-roledescription="carousel"
      tabIndex={0}
      onKeyDown={onKeyDown}
      className={cn(classes.root, className)}
      {...rest}
    >
      {/* Dedicated live region: announces only the slide index, not the slide
          content itself (APG recommendation). */}
      <span
        className="sr-only"
        role="status"
        aria-live="polite"
        aria-atomic="true"
      >
        {carouselStatus(selectedIndex, total)}
      </span>
      {/* Embla throws where the browser lacks what it needs (jsdom, old
          WebViews), unmounting the page: there the strip stays put. */}
      <div
        ref={canRunCarousel() ? emblaRef : undefined}
        className={classes.viewport}
        id={`${carouselId}-viewport`}
      >
        <div className={classes.track}>
          {wrappedChildren}
        </div>
      </div>

      {showArrows && (
        <>
          <button
            type="button"
            aria-label={CAROUSEL_PREVIOUS_LABEL}
            aria-controls={`${carouselId}-viewport`}
            disabled={carouselArrowDisabled(canPrev, opts?.loop)}
            onClick={scrollPrev}
            className={classes.previous}
          >
            <span aria-hidden="true">{'<'}</span>
          </button>
          <button
            type="button"
            aria-label={CAROUSEL_NEXT_LABEL}
            aria-controls={`${carouselId}-viewport`}
            disabled={carouselArrowDisabled(canNext, opts?.loop)}
            onClick={scrollNext}
            className={classes.next}
          >
            <span aria-hidden="true">{'>'}</span>
          </button>
        </>
      )}

      {showDots && dotCount > 0 && (
        <div
          className={classes.dots}
          role="group"
          aria-label={CAROUSEL_DOTS_LABEL}
        >
          {Array.from({ length: dotCount }).map((_, i) => {
            const active = i === selectedIndex;
            return (
              <button
                key={i}
                type="button"
                aria-label={carouselDotLabel(i)}
                aria-current={active ? 'true' : undefined}
                aria-controls={`${carouselId}-viewport`}
                onClick={() => scrollTo(i)}
                className={carouselDotClasses(surface, active)}
              />
            );
          })}
        </div>
      )}
    </div>
  );
});

PixelCarouselRoot.displayName = 'PixelCarousel';

type PixelCarouselNamespace = typeof PixelCarouselRoot & {
  Item: typeof PixelCarouselItem;
};

const PixelCarouselBase = PixelCarouselRoot as PixelCarouselNamespace;
PixelCarouselBase.Item = PixelCarouselItem;

export const PixelCarousel = PixelCarouselBase;
export { PixelCarouselItem };

// packages/ui-kit-angular/src/lib/data/pixel-carousel.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  ViewEncapsulation,
  computed,
  contentChildren,
  effect,
  inject,
  input,
  output,
  signal,
  untracked,
  viewChild,
  type OnDestroy,
} from '@angular/core';
import type { EmblaCarouselType, EmblaOptionsType, EmblaPluginType } from 'embla-carousel';
import {
  CAROUSEL_DOTS_LABEL,
  CAROUSEL_NEXT_LABEL,
  CAROUSEL_PREVIOUS_LABEL,
  carouselArrowDisabled,
  carouselClasses,
  carouselDotClasses,
  carouselDotCount,
  carouselDotLabel,
  carouselKeyStep,
  carouselOptions,
  carouselStatus,
  type CarouselOrientation,
  type Surface,
} from '@pxlkit/ui-kit-core';
import { booleanOr, withDefault } from '../_internal/coercion';
import { injectId } from '../_internal/ids';
import { injectEffectiveSurface } from '../overlay-foundation/pxl-kit-surface-provider';
import { injectReducedMotion } from '../utilities/media-query';
import { injectEmblaCarousel } from './_internal/embla';
import { PIXEL_CAROUSEL, type PixelCarouselContext } from './carousel-context';
import { PixelCarouselItem } from './pixel-carousel-item';

/** Embla options a carousel takes: all but the axis, which follows its orientation. */
export type PixelCarouselOptions = Omit<EmblaOptionsType, 'axis'>;
/** An Embla plugin (autoplay, auto scroll, …). */
export interface PixelCarouselPlugin extends EmblaPluginType {}

/**
 * Slides scrolled by Embla, with previous / next buttons, optional dots and
 * the arrow keys of its orientation (WAI-ARIA carousel pattern): a focusable
 * region (`aria-roledescription="carousel"`, name it with `aria-label`) that
 * announces the current slide politely. Each `<pxl-carousel-item>` is a
 * slide named "Slide N of M". Scrolls jump for a reader who prefers reduced
 * motion. The host is the region.
 *
 * @example
 * <pxl-carousel aria-label="Featured items" showDots (api)="carousel = $event">
 *   <pxl-carousel-item>…</pxl-carousel-item>
 *   <pxl-carousel-item>…</pxl-carousel-item>
 * </pxl-carousel>
 */
@Component({
  selector: 'pxl-carousel',
  changeDetection: ChangeDetectionStrategy.OnPush,
  // The host stands for React's <div>: a block box, in the base layer, so
  // display utilities set on it still win.
  encapsulation: ViewEncapsulation.None,
  styles: '@layer base { pxl-carousel { display: block; } }',
  providers: [{ provide: PIXEL_CAROUSEL, useFactory: () => inject(PixelCarousel).context }],
  host: {
    role: 'region',
    'aria-roledescription': 'carousel',
    tabindex: '0',
    '[class]': 'classes().root',
    '(keydown)': 'onKeydown($event)',
  },
  template: `
    <span class="sr-only" role="status" aria-live="polite" aria-atomic="true">{{ status() }}</span>
    <div #viewport [class]="classes().viewport" [attr.id]="viewportId">
      <div [class]="classes().track"><ng-content /></div>
    </div>
    @if (showArrows()) {
      <button
        type="button"
        [attr.aria-label]="previousLabel"
        [attr.aria-controls]="viewportId"
        [disabled]="previousDisabled()"
        [class]="classes().previous"
        (click)="embla()?.scrollPrev()"
      ><span aria-hidden="true">&lt;</span></button>
      <button
        type="button"
        [attr.aria-label]="nextLabel"
        [attr.aria-controls]="viewportId"
        [disabled]="nextDisabled()"
        [class]="classes().next"
        (click)="embla()?.scrollNext()"
      ><span aria-hidden="true">&gt;</span></button>
    }
    @if (showDots() && dots().length > 0) {
      <div [class]="classes().dots" role="group" [attr.aria-label]="dotsLabel">
        @for (dot of dots(); track $index) {
          <button
            type="button"
            [attr.aria-label]="dot.label"
            [attr.aria-current]="dot.active ? 'true' : null"
            [attr.aria-controls]="viewportId"
            [class]="dot.classes"
            (click)="embla()?.scrollTo($index)"
          ></button>
        }
      </div>
    }
  `,
})
export class PixelCarousel implements OnDestroy {
  /**
   * Embla options (see the embla-carousel docs): `loop`, `align`,
   * `slidesToScroll`, `startIndex`, `dragFree`, `containScroll`, … The axis
   * follows `orientation`.
   */
  readonly opts = input<PixelCarouselOptions>();
  /** Embla plugins (autoplay, auto scroll, …). */
  readonly plugins = input<PixelCarouselPlugin[]>();
  /** Slides side by side, or stacked. */
  readonly orientation = input<CarouselOrientation, CarouselOrientation | undefined>('horizontal', {
    transform: withDefault<CarouselOrientation>('horizontal'),
  });
  /** Previous and next buttons. */
  readonly showArrows = input(true, { transform: booleanOr(true) });
  /** A dot per slide, to go to it. */
  readonly showDots = input(false, { transform: booleanOr(false) });
  /** Surface override; defaults to the nearest provider. */
  readonly surface = input<Surface>();
  /** Embla's API once it runs, then `undefined` when the carousel is destroyed. */
  readonly api = output<EmblaCarouselType | undefined>();

  private readonly effectiveSurface = injectEffectiveSurface(() => this.surface());
  private readonly reducedMotion = injectReducedMotion();
  private readonly items = contentChildren(PixelCarouselItem);
  private readonly viewport = viewChild.required<ElementRef<HTMLElement>>('viewport');
  /** @internal */
  protected readonly embla = injectEmblaCarousel(
    () => this.viewport().nativeElement,
    () => carouselOptions(this.opts(), { orientation: this.orientation(), reducedMotion: this.reducedMotion() }),
    () => this.plugins() ?? [],
  );
  private readonly selectedIndex = signal(0);
  private readonly scrollSnaps = signal<number[]>([]);
  private readonly canPrev = signal(false);
  private readonly canNext = signal(false);

  /** @internal Shared with the slides. */
  readonly context: PixelCarouselContext = { items: this.items };

  /** @internal */
  protected readonly viewportId = `${injectId()}-viewport`;
  /** @internal */
  protected readonly previousLabel = CAROUSEL_PREVIOUS_LABEL;
  /** @internal */
  protected readonly nextLabel = CAROUSEL_NEXT_LABEL;
  /** @internal */
  protected readonly dotsLabel = CAROUSEL_DOTS_LABEL;
  /** @internal */
  protected readonly classes = computed(() => carouselClasses(this.effectiveSurface(), this.orientation()));
  /** @internal The live region announces the slide index, not the slide's content (APG). */
  protected readonly status = computed(() => carouselStatus(this.selectedIndex(), this.items().length));
  /** @internal */
  protected readonly previousDisabled = computed(() => carouselArrowDisabled(this.canPrev(), this.opts()?.loop));
  /** @internal */
  protected readonly nextDisabled = computed(() => carouselArrowDisabled(this.canNext(), this.opts()?.loop));
  /** @internal */
  protected readonly dots = computed(() =>
    Array.from({ length: carouselDotCount(this.scrollSnaps().length, this.items().length) }, (_, index) => {
      const active = index === this.selectedIndex();
      return { label: carouselDotLabel(index), active, classes: carouselDotClasses(this.effectiveSurface(), active) };
    }),
  );

  constructor() {
    effect((onCleanup) => {
      const embla = this.embla();
      if (!embla) return;
      const onSelect = () => {
        this.selectedIndex.set(embla.selectedScrollSnap());
        this.canPrev.set(embla.canScrollPrev());
        this.canNext.set(embla.canScrollNext());
      };
      untracked(() => {
        this.scrollSnaps.set(embla.scrollSnapList());
        onSelect();
        this.api.emit(embla);
      });
      embla.on('select', onSelect);
      embla.on('reInit', onSelect);
      onCleanup(() => {
        embla.off('select', onSelect);
        embla.off('reInit', onSelect);
      });
    });
  }

  /** @internal */
  ngOnDestroy(): void {
    if (this.embla()) this.api.emit(undefined);
  }

  /** @internal */
  protected onKeydown(event: KeyboardEvent): void {
    const step = carouselKeyStep(event.key, this.orientation());
    if (!step) return;
    event.preventDefault();
    if (step < 0) this.embla()?.scrollPrev();
    else this.embla()?.scrollNext();
  }
}
