// packages/ui-kit-vue/src/data/PixelColorSwatch.vue
<script setup lang="ts">
import { computed } from 'vue';
import { colorSwatchClasses, colorSwatchFill, type Surface } from '@pxlkit/ui-kit-core';
import { useEffectiveSurface } from '../composables/surface.js';

/**
 * Design-token preview: a square filled from a CSS custom property — so it
 * follows the active theme — beside the token name and the variable.
 */
export interface PixelColorSwatchProps {
  /** Display name of the token (e.g. "Cyan 500"). */
  name: string;
  /** CSS variable to preview (e.g. "--color-retro-cyan"). */
  cssVar: string;
  /** Visual surface override. */
  surface?: Surface;
}

const props = withDefaults(defineProps<PixelColorSwatchProps>(), { surface: undefined });

const surface = useEffectiveSurface(() => props.surface);
const classes = computed(() => colorSwatchClasses(surface.value));
</script>

<template>
  <div :class="classes.root">
    <div :class="classes.sample" :style="{ backgroundColor: colorSwatchFill(cssVar) }" />
    <div>
      <p :class="classes.name">{{ name }}</p>
      <p :class="classes.variable">{{ cssVar }}</p>
    </div>
  </div>
</template>

// packages/ui-kit-angular/src/lib/data/pixel-color-swatch.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { colorSwatchClasses, colorSwatchFill, type Surface } from '@pxlkit/ui-kit-core';
import { injectEffectiveSurface } from '../overlay-foundation/pxl-kit-surface-provider';

/**
 * Design-token preview: a square filled from a CSS custom property — so it
 * follows the active theme — beside the token name and the variable.
 *
 * @example
 * <pxl-color-swatch name="Cyan" cssVar="--color-retro-cyan" />
 */
@Component({
  selector: 'pxl-color-swatch',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { '[class]': 'classes().root' },
  template: `
    <div [class]="classes().sample" [style.background-color]="fill()"></div>
    <div>
      <p [class]="classes().name">{{ name() }}</p>
      <p [class]="classes().variable">{{ cssVar() }}</p>
    </div>
  `,
})
export class PixelColorSwatch {
  /** Display name of the token (e.g. "Cyan 500"). */
  readonly name = input.required<string>();
  /** CSS variable to preview (e.g. "--color-retro-cyan"). */
  readonly cssVar = input.required<string>();
  /** Visual surface override. */
  readonly surface = input<Surface>();

  private readonly effectiveSurface = injectEffectiveSurface(() => this.surface());

  /** @internal */
  protected readonly classes = computed(() => colorSwatchClasses(this.effectiveSurface()));
  /** @internal */
  protected readonly fill = computed(() => colorSwatchFill(this.cssVar()));
}
