// packages/ui-kit-angular/src/lib/overlays/pixel-drawer-header.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { drawerHeaderClasses, type Surface } from '@pxlkit/ui-kit-core';
import { injectEffectiveSurface } from '../overlay-foundation/pxl-kit-surface-provider';

/** Header bar of a `<pxl-drawer>`, set off from the body by a surface-aware divider. */
@Component({
  selector: 'pxl-drawer-header',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { '[class]': 'classes()' },
  template: '<ng-content />',
})
export class PixelDrawerHeader {
  /** Surface override; defaults to the nearest provider. */
  readonly surface = input<Surface>();

  private readonly effectiveSurface = injectEffectiveSurface(() => this.surface());
  /** @internal */
  protected readonly classes = computed(() => drawerHeaderClasses(this.effectiveSurface()));
}

// packages/ui-kit-vue/src/overlays/PixelDrawerHeader.vue
<script setup lang="ts">
import { computed, type VNode } from 'vue';
import { drawerHeaderClasses, type Surface } from '@pxlkit/ui-kit-core';
import { useEffectiveSurface } from '../composables/surface.js';

/** Header bar of a `PixelDrawer`, set off from the body by a surface-aware divider. */
const props = defineProps<{
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
}>();
defineSlots<{
  /** Header content, such as the title. */
  default?(): VNode[];
}>();

const surface = useEffectiveSurface(() => props.surface);
const classes = computed(() => drawerHeaderClasses(surface.value));
</script>

<template>
  <div :class="classes"><slot /></div>
</template>
