// packages/ui-kit-angular/src/lib/overlays/pixel-drawer.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  computed,
  effect,
  input,
  model,
  viewChild,
} from '@angular/core';
import {
  drawerLayerClasses,
  drawerPanelClasses,
  overlayBackdropClasses,
  type DrawerSide,
  type DrawerSize,
  type Surface,
} from '@pxlkit/ui-kit-core';
import { booleanOr, withDefault } from '../_internal/coercion';
import { injectId } from '../_internal/ids';
import { PixelPortal } from '../overlay-foundation/pixel-portal';
import { injectEffectiveSurface } from '../overlay-foundation/pxl-kit-surface-provider';
import { injectEscape, injectFocusTrap, injectScrollLock } from '../utilities/dom';

/**
 * Modal panel anchored to an edge of the viewport (right, left, top or
 * bottom), with focus trap, scroll lock and Escape / backdrop dismissal.
 * Compose its content from `<pxl-drawer-header>`, `<pxl-drawer-body>` and
 * `<pxl-drawer-footer>`. Name it with `title` or `ariaLabel`. Bind it with
 * `[(open)]`.
 *
 * The host is layout-neutral (`display: contents`); the drawer renders into
 * `document.body`.
 *
 * @example
 * <pxl-drawer [(open)]="open" title="Settings">
 *   <pxl-drawer-header>Settings</pxl-drawer-header>
 *   <pxl-drawer-body>…</pxl-drawer-body>
 *   <pxl-drawer-footer><button pxlButton (click)="open.set(false)">Done</button></pxl-drawer-footer>
 * </pxl-drawer>
 */
@Component({
  selector: 'pxl-drawer',
  imports: [PixelPortal],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[style.display]': '"contents"',
    // `title` names the dialog; on the host it would show a native tooltip.
    '[attr.title]': 'null',
  },
  template: `
    @if (open()) {
      <ng-template pxlPortal [pxlPortalContainer]="container()">
        <div [class]="layerClasses">
          @if (overlay()) {
            <div
              aria-hidden="true"
              data-pxl-overlay-backdrop=""
              data-pxl-drawer-overlay=""
              [class]="backdropClasses"
              (click)="onBackdropClick()"
            ></div>
          }
          <div
            #panel
            data-pxl-drawer-panel="true"
            role="dialog"
            aria-modal="true"
            [attr.aria-label]="title() ? null : ariaLabel()"
            [attr.aria-labelledby]="title() ? titleId : null"
            [attr.aria-describedby]="description() ? descriptionId : null"
            [class]="panelClasses()"
          >
            @if (title() || description()) {
              <div class="sr-only">
                @if (title()) {
                  <span [id]="titleId">{{ title() }}</span>
                }
                @if (description()) {
                  <span [id]="descriptionId">{{ description() }}</span>
                }
              </div>
            }
            <ng-content />
          </div>
        </div>
      </ng-template>
    }
  `,
})
export class PixelDrawer {
  /** Whether the drawer is visible (`[(open)]`). */
  readonly open = model.required<boolean>();
  /** Edge of the viewport the drawer is anchored to. */
  readonly side = input<DrawerSide, DrawerSide | undefined>('right', { transform: withDefault<DrawerSide>('right') });
  /** Width (left / right) or height (top / bottom) preset. */
  readonly size = input<DrawerSize, DrawerSize | undefined>('md', { transform: withDefault<DrawerSize>('md') });
  /** Dim the page behind the drawer. */
  readonly overlay = input(true, { transform: booleanOr(true) });
  /** Close when the backdrop is clicked. */
  readonly dismissOnOverlay = input(true, { transform: booleanOr(true) });
  /** Keep Tab focus inside the drawer while it is open. */
  readonly trapFocus = input(true, { transform: booleanOr(true) });
  /** Accessible name of the dialog (visually hidden). */
  readonly title = input<string>();
  /** Accessible description of the dialog (visually hidden). */
  readonly description = input<string>();
  /** Accessible name when there is no `title` — every dialog needs one (WCAG 4.1.2). */
  readonly ariaLabel = input<string>();
  /** Surface override; defaults to the nearest provider. */
  readonly surface = input<Surface>();
  /** Portal target; `document.body` when left out. */
  readonly container = input<HTMLElement | null>();

  private readonly effectiveSurface = injectEffectiveSurface(() => this.surface());
  private readonly panel = viewChild<ElementRef<HTMLElement>>('panel');

  /** @internal */
  protected readonly titleId = injectId();
  /** @internal */
  protected readonly descriptionId = injectId();
  /** @internal */
  protected readonly layerClasses = drawerLayerClasses;
  /** @internal */
  protected readonly backdropClasses = overlayBackdropClasses('absolute');
  /** @internal */
  protected readonly panelClasses = computed(() => drawerPanelClasses(this.effectiveSurface(), this.side(), this.size()));

  constructor() {
    injectFocusTrap(
      () => this.open() && this.trapFocus(),
      () => this.panel()?.nativeElement,
    );
    injectScrollLock(() => this.open());
    injectEscape(
      () => this.open.set(false),
      () => this.open(),
    );
    effect(() => {
      if ((typeof ngDevMode === 'undefined' || ngDevMode) && this.open() && !this.title() && !this.ariaLabel()) {
        console.warn('[PixelDrawer] role="dialog" has no accessible name. Pass either `title` or `aria-label`.');
      }
    });
  }

  /** @internal */
  protected onBackdropClick(): void {
    if (this.dismissOnOverlay()) this.open.set(false);
  }
}

// packages/ui-kit-vue/src/overlays/PixelDrawer.vue
<script setup lang="ts">
import { computed, useId, useTemplateRef, warn, watch, type VNode } from 'vue';
import {
  drawerLayerClasses,
  drawerPanelClasses,
  overlayBackdropClasses,
  type DrawerSide,
  type DrawerSize,
  type Surface,
} from '@pxlkit/ui-kit-core';
import { useEscape, useFocusTrap, useScrollLock } from '../composables/overlay.js';
import { useEffectiveSurface } from '../composables/surface.js';
import PixelPortal from '../overlay-foundation/PixelPortal.vue';

/**
 * Modal panel anchored to an edge of the viewport (right, left, top or
 * bottom), with focus trap, scroll lock and Escape / backdrop dismissal.
 * Compose its content from `PixelDrawerHeader`, `PixelDrawerBody` and
 * `PixelDrawerFooter`. Name it with `title` or `aria-label`. Bind it with
 * `v-model:open`.
 *
 * @example
 * <PixelDrawer v-model:open="open" title="Settings">
 *   <PixelDrawerHeader>Settings</PixelDrawerHeader>
 *   <PixelDrawerBody>…</PixelDrawerBody>
 *   <PixelDrawerFooter><PixelButton @click="open = false">Done</PixelButton></PixelDrawerFooter>
 * </PixelDrawer>
 */
export interface PixelDrawerProps {
  /** Whether the drawer is visible (`v-model:open`). */
  open: boolean;
  /** Edge of the viewport the drawer is anchored to. */
  side?: DrawerSide;
  /** Width (left / right) or height (top / bottom) preset. */
  size?: DrawerSize;
  /** Dim the page behind the drawer. */
  overlay?: boolean;
  /** Close when the backdrop is clicked. */
  dismissOnOverlay?: boolean;
  /** Keep Tab focus inside the drawer while it is open. */
  trapFocus?: boolean;
  /** Accessible name of the dialog (visually hidden). */
  title?: string;
  /** Accessible description of the dialog (visually hidden). */
  description?: string;
  /**
   * Accessible name when there is no `title` — every dialog needs one
   * (WCAG 4.1.2).
   */
  ariaLabel?: string;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
  /** Portal target; `document.body` when left out. */
  container?: HTMLElement | null;
}

const props = withDefaults(defineProps<PixelDrawerProps>(), {
  side: 'right',
  size: 'md',
  overlay: true,
  dismissOnOverlay: true,
  trapFocus: true,
  title: undefined,
  description: undefined,
  ariaLabel: undefined,
  surface: undefined,
  container: undefined,
});
const emit = defineEmits<{
  /** `false` when the drawer asks to close (Escape, backdrop), for `v-model:open`. */
  'update:open': [open: boolean];
}>();
defineSlots<{
  /** The drawer content — typically header, body and footer parts. */
  default?(): VNode[];
}>();

const surface = useEffectiveSurface(() => props.surface);
const titleId = useId();
const descriptionId = useId();
const panel = useTemplateRef<HTMLElement>('panel');
const panelClasses = computed(() => drawerPanelClasses(surface.value, props.side, props.size));
const backdropClasses = overlayBackdropClasses('absolute');

const close = () => emit('update:open', false);

function onBackdropClick() {
  if (props.dismissOnOverlay) close();
}

useFocusTrap(() => props.open && props.trapFocus, panel);
useScrollLock(() => props.open);
useEscape(close, () => props.open);

watch(
  () => props.open && !props.title && !props.ariaLabel,
  (unnamed) => {
    if (unnamed) warn('[PixelDrawer] role="dialog" has no accessible name. Pass either `title` or `aria-label`.');
  },
  { immediate: true },
);

defineExpose({
  /** The drawer panel while it is open. */
  element: panel,
});
</script>

<template>
  <PixelPortal v-if="open" :container="container">
    <div :class="drawerLayerClasses">
      <div
        v-if="overlay"
        aria-hidden="true"
        data-pxl-overlay-backdrop=""
        data-pxl-drawer-overlay=""
        :class="backdropClasses"
        @click="onBackdropClick"
      />
      <div
        ref="panel"
        data-pxl-drawer-panel="true"
        role="dialog"
        aria-modal="true"
        :aria-label="title ? undefined : ariaLabel"
        :aria-labelledby="title ? titleId : undefined"
        :aria-describedby="description ? descriptionId : undefined"
        :class="panelClasses"
      >
        <div v-if="title || description" class="sr-only">
          <span v-if="title" :id="titleId">{{ title }}</span>
          <span v-if="description" :id="descriptionId">{{ description }}</span>
        </div>
        <slot />
      </div>
    </div>
  </PixelPortal>
</template>
