// packages/ui-kit-vue/src/navigation/PixelPagination.vue
<script setup lang="ts">
import { computed } from 'vue';
import {
  PAGINATION_ELLIPSIS,
  paginationClasses,
  paginationEllipsisClasses,
  paginationPageClasses,
  paginationStepClasses,
  paginationSteps,
  paginationWindow,
  type Surface,
} from '@pxlkit/ui-kit-core';
import { useEffectiveSurface } from '../composables/surface.js';

/**
 * Page navigator in a `<nav>` landmark: Prev, a window of page numbers around
 * the current page (the first and last always shown, `…` for the gaps) and
 * Next, disabled at the ends. The current page carries `aria-current="page"`.
 * Bind the page with `v-model:page`.
 *
 * @example
 * <PixelPagination v-model:page="page" :total="20" />
 */
export interface PixelPaginationProps {
  /** Current page, from 1 (`v-model:page`). */
  page: number;
  /** Number of pages. */
  total: number;
  /** Pages shown on each side of the current one. */
  siblings?: number;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
  /** Accessible name of the landmark. */
  ariaLabel?: string;
  /** Label of the previous-page button. */
  prevLabel?: string;
  /** Label of the next-page button. */
  nextLabel?: string;
}

const props = withDefaults(defineProps<PixelPaginationProps>(), {
  siblings: 1,
  surface: undefined,
  ariaLabel: 'Pagination',
  prevLabel: 'Prev',
  nextLabel: 'Next',
});
const emit = defineEmits<{
  /** The page the user picked, for `v-model:page`. */
  'update:page': [page: number];
}>();

const surface = useEffectiveSurface(() => props.surface);
const pages = computed(() => paginationWindow(props.page, props.total, props.siblings));
const steps = computed(() => paginationSteps(props.page, props.total));
</script>

<template>
  <nav :aria-label="ariaLabel" :class="paginationClasses">
    <button
      type="button"
      :disabled="steps.prev.disabled"
      :aria-label="prevLabel"
      :class="paginationStepClasses(surface, steps.prev.disabled)"
      @click="emit('update:page', steps.prev.page)"
    >
      {{ prevLabel }}
    </button>
    <template v-for="(entry, index) in pages" :key="entry === PAGINATION_ELLIPSIS ? `ell-${index}` : entry">
      <span v-if="entry === PAGINATION_ELLIPSIS" aria-hidden="true" :class="paginationEllipsisClasses(surface)">
        {{ PAGINATION_ELLIPSIS }}
      </span>
      <button
        v-else
        type="button"
        :aria-current="entry === page ? 'page' : undefined"
        :class="paginationPageClasses(surface, entry === page)"
        @click="emit('update:page', entry)"
      >
        {{ entry }}
      </button>
    </template>
    <button
      type="button"
      :disabled="steps.next.disabled"
      :aria-label="nextLabel"
      :class="paginationStepClasses(surface, steps.next.disabled)"
      @click="emit('update:page', steps.next.page)"
    >
      {{ nextLabel }}
    </button>
  </nav>
</template>

// packages/ui-kit/src/navigation/PixelPagination.tsx
import React, { forwardRef, useMemo } from 'react';
import {
  PAGINATION_ELLIPSIS,
  paginationClasses,
  paginationEllipsisClasses,
  paginationPageClasses,
  paginationStepClasses,
  paginationSteps,
  paginationWindow,
} from '@pxlkit/ui-kit-core';
import { Surface, useEffectiveSurface } from '../common';

/* ─────────────────────────────────────────────────────────────────────────
   PixelPagination — windowed page-number buttons with first/last + ellipses.
   ───────────────────────────────────────────────────────────────────────── */

/** Public prop bag for {@link PixelPagination}. */
export interface PixelPaginationProps {
  /** Current page (1-indexed). */
  page: number;
  /** Total number of pages. */
  total: number;
  /** Fires when the user picks a new page. */
  onChange: (next: number) => void;
  /** Sibling pages to show around the current. Defaults to 1. */
  siblings?: number;
  /** Visual surface treatment override. */
  surface?: Surface;
  /** Accessible label for the nav region. */
  ariaLabel?: string;
  /** Localised label for the Prev button. */
  prevLabel?: string;
  /** Localised label for the Next button. */
  nextLabel?: string;
}

export const PixelPagination = forwardRef<HTMLElement, PixelPaginationProps>(function PixelPagination(
  { page, total, onChange, siblings = 1, surface: surfaceProp, ariaLabel = 'Pagination', prevLabel = 'Prev', nextLabel = 'Next' },
  ref,
) {
  const surface = useEffectiveSurface(surfaceProp);
  const pages = useMemo(() => paginationWindow(page, total, siblings), [page, total, siblings]);
  const { prev, next } = paginationSteps(page, total);

  return (
    <nav ref={ref} aria-label={ariaLabel} className={paginationClasses}>
      <button
        type="button"
        disabled={prev.disabled}
        aria-label={prevLabel}
        onClick={() => onChange(prev.page)}
        className={paginationStepClasses(surface, prev.disabled)}
      >
        {prevLabel}
      </button>
      {pages.map((p, idx) =>
        p === PAGINATION_ELLIPSIS ? (
          <span key={`ell-${idx}`} aria-hidden className={paginationEllipsisClasses(surface)}>
            {PAGINATION_ELLIPSIS}
          </span>
        ) : (
          <button
            key={p}
            type="button"
            aria-current={p === page ? 'page' : undefined}
            className={paginationPageClasses(surface, p === page)}
            onClick={() => onChange(p)}
          >
            {p}
          </button>
        ),
      )}
      <button
        type="button"
        disabled={next.disabled}
        aria-label={nextLabel}
        onClick={() => onChange(next.page)}
        className={paginationStepClasses(surface, next.disabled)}
      >
        {nextLabel}
      </button>
    </nav>
  );
});

PixelPagination.displayName = 'PixelPagination';
