// packages/ui-kit-vue/src/navigation/PixelMenubar.vue
<script setup lang="ts">
import { ref, useId, useTemplateRef, type ComponentPublicInstance } from 'vue';
import {
  MENUBAR_SUBMENU_ARROW,
  menubarClasses,
  menubarHasSubmenu,
  menubarHighlight,
  menubarIds,
  menubarItemClasses,
  menubarItemIconClasses,
  menubarItemLabelClasses,
  menubarItemSlotClasses,
  menubarKeyAction,
  menubarMenuClasses,
  menubarSeparatorClasses,
  menubarShortcutClasses,
  menubarSubmenuArrowClasses,
  menubarSubmenuClasses,
  menubarSubmenuLabel,
  menubarTabStop,
  menubarTriggerClasses,
  menubarTriggerSlotClasses,
  type MenubarMove,
  type Surface,
} from '@pxlkit/ui-kit-core';
import { RenderNode, type PxlNode } from '../_internal/render-node.js';
import { useClickOutside } from '../composables/overlay.js';
import { useEffectiveSurface } from '../composables/surface.js';

/** An item of a `PixelMenubar` menu. */
export interface PixelMenubarItem {
  /** Identity of the item. */
  value: string;
  label: string;
  /** Icon before the label: text, a VNode or a render function. */
  icon?: PxlNode;
  /** Keyboard hint shown at the end of the row (display only). */
  shortcut?: string;
  /** Called when the item is chosen; the menu closes. */
  onSelect?: () => void;
  /** Items of a submenu that the item opens. */
  submenu?: PixelMenubarItem[];
  /** Draws a separator in place of an item. */
  separator?: boolean;
  /** Skipped by the keyboard and ignores the pointer. */
  disabled?: boolean;
}

/** A top-level menu of a `PixelMenubar`. */
export interface PixelMenubarMenu {
  /** Label of the menu button. */
  label: string;
  items: PixelMenubarItem[];
}

/**
 * Application menubar (`role="menubar"`) of menu buttons, each opening a menu
 * of actions with icons, shortcut hints, separators, disabled items and
 * submenus. The open menu takes focus and points `aria-activedescendant` at
 * the highlighted item: Up and Down move round the enabled items (on a closed
 * button they open its menu on the first or last one), Home and End jump to
 * the ends, Right enters a submenu and Left leaves it, Left and Right switch
 * menus, Enter and Space choose. Escape closes the submenu, then the menu,
 * with focus back on its button; choosing an item and Tab close it too.
 * Pointing at another button while a menu is open switches to its menu; a
 * press outside closes it. Attributes and listeners go to the menubar.
 *
 * @example
 * <PixelMenubar :menus="[{ label: 'File', items: [{ value: 'new', label: 'New', shortcut: 'Ctrl+N' }] }]" />
 */
export interface PixelMenubarProps {
  /** The menus, in order. */
  menus: PixelMenubarMenu[];
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
}

const props = withDefaults(defineProps<PixelMenubarProps>(), { surface: undefined });

const surface = useEffectiveSurface(() => props.surface);
const ids = menubarIds(useId());
const root = useTemplateRef<HTMLElement>('root');
const openMenu = ref<number | null>(null);
const activeItem = ref(-1);
const openSubmenuItem = ref<number | null>(null);
const activeSubItem = ref(-1);
// The button that last had focus or a menu open keeps the tab stop.
const lastTrigger = ref(0);
const triggers: HTMLElement[] = [];
const menuElements: Array<HTMLElement | null> = [];

function setTrigger(index: number, element: Element | ComponentPublicInstance | null) {
  if (element instanceof HTMLElement) triggers[index] = element;
}

// The open menu takes focus as it appears, so screen readers follow its
// aria-activedescendant. Function refs run on every update: only a new
// element takes focus.
function setMenu(index: number, element: Element | ComponentPublicInstance | null) {
  const next = element instanceof HTMLElement ? element : null;
  if (next && next !== menuElements[index]) next.focus({ preventScroll: true });
  menuElements[index] = next;
}

function closeAll() {
  openMenu.value = null;
  activeItem.value = -1;
  openSubmenuItem.value = null;
  activeSubItem.value = -1;
}

// Closing from inside the open menu (Escape, choosing an item) hands focus
// back to its button; a press outside leaves focus to the pointer.
function closeToTrigger() {
  const open = openMenu.value;
  if (open !== null && menuElements[open]?.contains(document.activeElement)) triggers[open]?.focus();
  closeAll();
}

function openMenuAt(index: number, move: MenubarMove = 'first') {
  const menu = props.menus[index];
  if (!menu) return;
  openMenu.value = index;
  lastTrigger.value = index;
  activeItem.value = menubarHighlight(menu.items, -1, move);
  openSubmenuItem.value = null;
  activeSubItem.value = -1;
}

useClickOutside(root, () => {
  if (openMenu.value !== null) closeAll();
});

function onTriggerClick(index: number) {
  if (openMenu.value === index) closeAll();
  else openMenuAt(index);
}

function onTriggerMouseenter(index: number) {
  if (openMenu.value !== null && openMenu.value !== index) openMenuAt(index);
}

function onItemMouseenter(item: PixelMenubarItem, index: number) {
  if (item.disabled) return;
  activeItem.value = index;
  activeSubItem.value = -1;
  openSubmenuItem.value = menubarHasSubmenu(item) ? index : null;
}

function activate(item: PixelMenubarItem) {
  if (item.disabled || item.separator || menubarHasSubmenu(item)) return;
  item.onSelect?.();
  closeToTrigger();
}

function activateSub(sub: PixelMenubarItem) {
  if (sub.disabled) return;
  sub.onSelect?.();
  closeToTrigger();
}

function activeDescendant(menu: number): string | undefined {
  if (openSubmenuItem.value !== null && activeSubItem.value >= 0) {
    return ids.subitem(menu, openSubmenuItem.value, activeSubItem.value);
  }
  return activeItem.value >= 0 ? ids.item(menu, activeItem.value) : undefined;
}

function onKeydown(event: KeyboardEvent) {
  if (event.defaultPrevented) return;
  const open = openMenu.value;
  const items = open === null ? [] : (props.menus[open]?.items ?? []);
  const highlighted = items[activeItem.value];
  const submenu = openSubmenuItem.value === null ? [] : (items[openSubmenuItem.value]?.submenu ?? []);
  const action = menubarKeyAction(event.key, {
    open: open !== null,
    onSubmenuParent: menubarHasSubmenu(highlighted),
    submenuOpen: openSubmenuItem.value !== null,
    inSubmenu: openSubmenuItem.value !== null && activeSubItem.value >= 0,
  });
  if (!action) return;

  if (action.type === 'leave') {
    // Focus is back on the button before the browser's own Tab, which then
    // moves on from there.
    if (open !== null) triggers[open]?.focus();
    closeAll();
    return;
  }
  event.preventDefault();
  const focusedTrigger = triggers.indexOf(event.target as HTMLElement);
  switch (action.type) {
    case 'switch': {
      // While every menu is closed, the focused button is the current one.
      const current = open ?? Math.max(0, focusedTrigger);
      openMenuAt((current + action.step + props.menus.length) % props.menus.length);
      break;
    }
    case 'open':
      if (focusedTrigger >= 0) openMenuAt(focusedTrigger, action.move);
      break;
    case 'move':
      if (action.level === 'submenu') {
        activeSubItem.value = menubarHighlight(submenu, activeSubItem.value, action.move);
      } else {
        activeItem.value = menubarHighlight(items, activeItem.value, action.move);
        openSubmenuItem.value = null;
        activeSubItem.value = -1;
      }
      break;
    case 'enter':
      openSubmenuItem.value = activeItem.value;
      activeSubItem.value = menubarHighlight(highlighted?.submenu ?? [], -1, 'first');
      break;
    case 'exit':
      openSubmenuItem.value = null;
      activeSubItem.value = -1;
      break;
    case 'select':
      if (activeSubItem.value >= 0) {
        const sub = submenu[activeSubItem.value];
        if (sub) activateSub(sub);
      } else if (highlighted) {
        activate(highlighted);
      }
      break;
    case 'close':
      closeToTrigger();
      break;
  }
}
</script>

<template>
  <div ref="root" role="menubar" aria-orientation="horizontal" :class="menubarClasses(surface)" @keydown="onKeydown">
    <div v-for="(menu, mIdx) in menus" :key="`${menu.label}-${mIdx}`" :class="menubarTriggerSlotClasses">
      <button
        :ref="(element: Element | ComponentPublicInstance | null) => setTrigger(mIdx, element)"
        :id="ids.trigger(mIdx)"
        type="button"
        role="menuitem"
        aria-haspopup="menu"
        :aria-expanded="openMenu === mIdx"
        :aria-controls="openMenu === mIdx ? ids.menu(mIdx) : undefined"
        :tabindex="mIdx === menubarTabStop(openMenu, lastTrigger, menus.length) ? 0 : -1"
        :class="menubarTriggerClasses(surface, openMenu === mIdx)"
        @focus="lastTrigger = mIdx"
        @click="onTriggerClick(mIdx)"
        @mouseenter="onTriggerMouseenter(mIdx)"
      >
        {{ menu.label }}
      </button>

      <div
        v-if="openMenu === mIdx"
        :ref="(element: Element | ComponentPublicInstance | null) => setMenu(mIdx, element)"
        :id="ids.menu(mIdx)"
        role="menu"
        tabindex="-1"
        :aria-labelledby="ids.trigger(mIdx)"
        :aria-activedescendant="activeDescendant(mIdx)"
        :class="menubarMenuClasses(surface)"
      >
        <template v-for="(item, iIdx) in menu.items" :key="item.separator ? `sep-${iIdx}` : item.value">
          <div v-if="item.separator" role="separator" :class="menubarSeparatorClasses" />
          <div v-else :class="menubarItemSlotClasses" @mouseenter="onItemMouseenter(item, iIdx)">
            <div
              :id="ids.item(mIdx, iIdx)"
              role="menuitem"
              :aria-disabled="item.disabled || undefined"
              :aria-haspopup="menubarHasSubmenu(item) ? 'menu' : undefined"
              :aria-expanded="menubarHasSubmenu(item) ? openSubmenuItem === iIdx : undefined"
              tabindex="-1"
              :class="menubarItemClasses(surface, { highlighted: activeItem === iIdx, disabled: !!item.disabled })"
              @click="activate(item)"
            >
              <span v-if="item.icon" :class="menubarItemIconClasses"><RenderNode :node="item.icon" /></span>
              <span :class="menubarItemLabelClasses">{{ item.label }}</span>
              <kbd v-if="item.shortcut" :class="menubarShortcutClasses(surface)">{{ item.shortcut }}</kbd>
              <span v-if="menubarHasSubmenu(item)" aria-hidden="true" :class="menubarSubmenuArrowClasses">
                {{ MENUBAR_SUBMENU_ARROW }}
              </span>
            </div>

            <div
              v-if="menubarHasSubmenu(item) && openSubmenuItem === iIdx"
              role="menu"
              :aria-label="menubarSubmenuLabel(item.label)"
              :class="menubarSubmenuClasses(surface)"
            >
              <template v-for="(sub, sIdx) in item.submenu" :key="sub.separator ? `sub-sep-${sIdx}` : sub.value">
                <div v-if="sub.separator" role="separator" :class="menubarSeparatorClasses" />
                <div
                  v-else
                  :id="ids.subitem(mIdx, iIdx, sIdx)"
                  role="menuitem"
                  :aria-disabled="sub.disabled || undefined"
                  tabindex="-1"
                  :class="
                    menubarItemClasses(surface, { highlighted: activeSubItem === sIdx, disabled: !!sub.disabled, submenu: true })
                  "
                  @mouseenter="!sub.disabled && (activeSubItem = sIdx)"
                  @click.stop="activateSub(sub)"
                >
                  <span v-if="sub.icon" :class="menubarItemIconClasses"><RenderNode :node="sub.icon" /></span>
                  <span :class="menubarItemLabelClasses">{{ sub.label }}</span>
                </div>
              </template>
            </div>
          </div>
        </template>
      </div>
    </div>
  </div>
</template>

// packages/ui-kit/src/navigation/PixelMenubar.tsx
'use client';

import React, {
  forwardRef,
  useCallback,
  useEffect,
  useId,
  useRef,
  useState,
  type KeyboardEvent as ReactKeyboardEvent,
} from 'react';
import {
  MENUBAR_SUBMENU_ARROW,
  menubarClasses,
  menubarHasSubmenu,
  menubarHighlight,
  menubarIds,
  menubarItemClasses,
  menubarItemIconClasses,
  menubarItemLabelClasses,
  menubarItemSlotClasses,
  menubarKeyAction,
  menubarMenuClasses,
  menubarSeparatorClasses,
  menubarShortcutClasses,
  menubarSubmenuArrowClasses,
  menubarSubmenuClasses,
  menubarSubmenuLabel,
  menubarTabStop,
  menubarTriggerClasses,
  menubarTriggerSlotClasses,
  type MenubarMove,
} from '@pxlkit/ui-kit-core';
import {
  Surface,
  cn,
  useEffectiveSurface,
} from '../common';

export interface PixelMenubarItem {
  value: string;
  label: string;
  icon?: React.ReactNode;
  shortcut?: string;
  onSelect?: () => void;
  submenu?: PixelMenubarItem[];
  separator?: boolean;
  disabled?: boolean;
}

export interface PixelMenubarMenu {
  label: string;
  items: PixelMenubarItem[];
}

export interface PixelMenubarProps extends React.HTMLAttributes<HTMLDivElement> {
  /** The menus, in order. */
  menus: PixelMenubarMenu[];
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
}

export const PixelMenubar = forwardRef<HTMLDivElement, PixelMenubarProps>(
  function PixelMenubar(
    { menus, surface: surfaceProp, className, onKeyDown, ...rest },
    forwardedRef,
  ) {
    const surface = useEffectiveSurface(surfaceProp);
    const ids = menubarIds(useId());

    const [openMenu, setOpenMenu] = useState<number | null>(null);
    const [activeItem, setActiveItem] = useState<number>(-1);
    const [openSubmenuItem, setOpenSubmenuItem] = useState<number | null>(null);
    const [activeSubItem, setActiveSubItem] = useState<number>(-1);
    // The button that last had focus or a menu open keeps the tab stop.
    const [lastTrigger, setLastTrigger] = useState(0);

    const rootRef = useRef<HTMLDivElement | null>(null);
    const triggerRefs = useRef<Array<HTMLButtonElement | null>>([]);
    const menuRef = useRef<HTMLDivElement | null>(null);

    const setRefs = useCallback(
      (node: HTMLDivElement | null) => {
        rootRef.current = node;
        if (typeof forwardedRef === 'function') forwardedRef(node);
        else if (forwardedRef && typeof forwardedRef === 'object') {
          (forwardedRef as React.MutableRefObject<HTMLDivElement | null>).current = node;
        }
      },
      [forwardedRef],
    );

    // The open menu takes focus as it mounts, so screen readers follow its
    // aria-activedescendant; the stable callback runs once per menu.
    const setMenuRef = useCallback((node: HTMLDivElement | null) => {
      menuRef.current = node;
      node?.focus({ preventScroll: true });
    }, []);

    const closeAll = useCallback(() => {
      setOpenMenu(null);
      setActiveItem(-1);
      setOpenSubmenuItem(null);
      setActiveSubItem(-1);
    }, []);

    // Closing from inside the open menu (Escape, choosing an item) hands
    // focus back to its button; a press outside leaves focus to the pointer.
    const closeToTrigger = () => {
      if (openMenu !== null && menuRef.current?.contains(document.activeElement)) {
        triggerRefs.current[openMenu]?.focus();
      }
      closeAll();
    };

    const openMenuAt = useCallback(
      (idx: number, move: MenubarMove = 'first') => {
        const menu = menus[idx];
        if (!menu) return;
        setOpenMenu(idx);
        setLastTrigger(idx);
        setActiveItem(menubarHighlight(menu.items, -1, move));
        setOpenSubmenuItem(null);
        setActiveSubItem(-1);
      },
      [menus],
    );

    // Click outside closes all
    useEffect(() => {
      if (openMenu === null) return;
      const listener = (e: PointerEvent) => {
        const target = e.target as Node | null;
        if (!target) return;
        if (rootRef.current?.contains(target)) return;
        closeAll();
      };
      document.addEventListener('pointerdown', listener);
      return () => document.removeEventListener('pointerdown', listener);
    }, [openMenu, closeAll]);

    const handleTriggerClick = (idx: number) => {
      if (openMenu === idx) {
        closeAll();
      } else {
        openMenuAt(idx);
      }
    };

    const handleTriggerMouseEnter = (idx: number) => {
      if (openMenu !== null && openMenu !== idx) {
        openMenuAt(idx);
      }
    };

    const activateItem = (item: PixelMenubarItem) => {
      if (item.disabled || item.separator) return;
      if (menubarHasSubmenu(item)) return;
      item.onSelect?.();
      closeToTrigger();
    };

    const handleRootKeyDown = (e: ReactKeyboardEvent<HTMLDivElement>) => {
      onKeyDown?.(e);
      if (e.defaultPrevented) return;

      const items = openMenu === null ? [] : menus[openMenu]?.items ?? [];
      const highlighted = items[activeItem];
      const submenu = openSubmenuItem === null ? [] : items[openSubmenuItem]?.submenu ?? [];
      const action = menubarKeyAction(e.key, {
        open: openMenu !== null,
        onSubmenuParent: menubarHasSubmenu(highlighted),
        submenuOpen: openSubmenuItem !== null,
        inSubmenu: openSubmenuItem !== null && activeSubItem >= 0,
      });
      if (!action) return;

      if (action.type === 'leave') {
        // Focus is back on the button before the browser's own Tab, which
        // then moves on from there.
        if (openMenu !== null) triggerRefs.current[openMenu]?.focus();
        closeAll();
        return;
      }
      e.preventDefault();
      const focusedTrigger = triggerRefs.current.indexOf(e.target as HTMLButtonElement);
      switch (action.type) {
        case 'switch': {
          // While every menu is closed, the focused button is the current one.
          const current = openMenu ?? Math.max(0, focusedTrigger);
          openMenuAt((current + action.step + menus.length) % menus.length);
          break;
        }
        case 'open':
          if (focusedTrigger >= 0) openMenuAt(focusedTrigger, action.move);
          break;
        case 'move':
          if (action.level === 'submenu') {
            setActiveSubItem(menubarHighlight(submenu, activeSubItem, action.move));
          } else {
            setActiveItem(menubarHighlight(items, activeItem, action.move));
            setOpenSubmenuItem(null);
            setActiveSubItem(-1);
          }
          break;
        case 'enter':
          setOpenSubmenuItem(activeItem);
          setActiveSubItem(menubarHighlight(highlighted?.submenu ?? [], -1, 'first'));
          break;
        case 'exit':
          setOpenSubmenuItem(null);
          setActiveSubItem(-1);
          break;
        case 'select':
          if (activeSubItem >= 0) {
            const sub = submenu[activeSubItem];
            if (sub && !sub.disabled) {
              sub.onSelect?.();
              closeToTrigger();
            }
          } else if (highlighted) {
            activateItem(highlighted);
          }
          break;
        case 'close':
          closeToTrigger();
          break;
      }
    };

    return (
      <div
        ref={setRefs}
        role="menubar"
        aria-orientation="horizontal"
        onKeyDown={handleRootKeyDown}
        className={cn(menubarClasses(surface), className)}
        {...rest}
      >
        {menus.map((menu, mIdx) => {
          const isOpen = openMenu === mIdx;
          const activeDescendant =
            openSubmenuItem !== null && activeSubItem >= 0
              ? ids.subitem(mIdx, openSubmenuItem, activeSubItem)
              : activeItem >= 0
                ? ids.item(mIdx, activeItem)
                : undefined;
          return (
            <div key={`${menu.label}-${mIdx}`} className={menubarTriggerSlotClasses}>
              <button
                ref={(node) => {
                  triggerRefs.current[mIdx] = node;
                }}
                id={ids.trigger(mIdx)}
                type="button"
                role="menuitem"
                aria-haspopup="menu"
                aria-expanded={isOpen}
                aria-controls={isOpen ? ids.menu(mIdx) : undefined}
                tabIndex={mIdx === menubarTabStop(openMenu, lastTrigger, menus.length) ? 0 : -1}
                onFocus={() => setLastTrigger(mIdx)}
                onClick={() => handleTriggerClick(mIdx)}
                onMouseEnter={() => handleTriggerMouseEnter(mIdx)}
                className={menubarTriggerClasses(surface, isOpen)}
              >
                {menu.label}
              </button>

              {isOpen && (
                <div
                  ref={setMenuRef}
                  id={ids.menu(mIdx)}
                  role="menu"
                  tabIndex={-1}
                  aria-labelledby={ids.trigger(mIdx)}
                  aria-activedescendant={activeDescendant}
                  className={menubarMenuClasses(surface)}
                >
                  {menu.items.map((item, iIdx) => {
                    if (item.separator) {
                      return (
                        <div
                          key={`sep-${iIdx}`}
                          role="separator"
                          className={menubarSeparatorClasses}
                        />
                      );
                    }

                    const isActive = activeItem === iIdx;
                    const hasSub = menubarHasSubmenu(item);
                    const subOpen = hasSub && openSubmenuItem === iIdx;

                    return (
                      <div
                        key={item.value}
                        className={menubarItemSlotClasses}
                        onMouseEnter={() => {
                          if (item.disabled) return;
                          setActiveItem(iIdx);
                          setActiveSubItem(-1);
                          if (hasSub) setOpenSubmenuItem(iIdx);
                          else setOpenSubmenuItem(null);
                        }}
                      >
                        <div
                          id={ids.item(mIdx, iIdx)}
                          role="menuitem"
                          aria-disabled={item.disabled || undefined}
                          aria-haspopup={hasSub ? 'menu' : undefined}
                          aria-expanded={hasSub ? subOpen : undefined}
                          tabIndex={-1}
                          onClick={() => activateItem(item)}
                          className={menubarItemClasses(surface, { highlighted: isActive, disabled: !!item.disabled })}
                        >
                          {item.icon && (
                            <span className={menubarItemIconClasses}>
                              {item.icon}
                            </span>
                          )}
                          <span className={menubarItemLabelClasses}>{item.label}</span>
                          {item.shortcut && (
                            <kbd className={menubarShortcutClasses(surface)}>
                              {item.shortcut}
                            </kbd>
                          )}
                          {hasSub && (
                            <span aria-hidden className={menubarSubmenuArrowClasses}>
                              {MENUBAR_SUBMENU_ARROW}
                            </span>
                          )}
                        </div>

                        {subOpen && item.submenu && (
                          <div
                            role="menu"
                            aria-label={menubarSubmenuLabel(item.label)}
                            className={menubarSubmenuClasses(surface)}
                          >
                            {item.submenu.map((sub, sIdx) => {
                              if (sub.separator) {
                                return (
                                  <div
                                    key={`sub-sep-${sIdx}`}
                                    role="separator"
                                    className={menubarSeparatorClasses}
                                  />
                                );
                              }
                              return (
                                <div
                                  key={sub.value}
                                  id={ids.subitem(mIdx, iIdx, sIdx)}
                                  role="menuitem"
                                  aria-disabled={sub.disabled || undefined}
                                  tabIndex={-1}
                                  onMouseEnter={() => {
                                    if (!sub.disabled) setActiveSubItem(sIdx);
                                  }}
                                  onClick={(e) => {
                                    e.stopPropagation();
                                    if (sub.disabled) return;
                                    sub.onSelect?.();
                                    closeToTrigger();
                                  }}
                                  className={menubarItemClasses(surface, {
                                    highlighted: activeSubItem === sIdx,
                                    disabled: !!sub.disabled,
                                    submenu: true,
                                  })}
                                >
                                  {sub.icon && (
                                    <span className={menubarItemIconClasses}>
                                      {sub.icon}
                                    </span>
                                  )}
                                  <span className={menubarItemLabelClasses}>{sub.label}</span>
                                </div>
                              );
                            })}
                          </div>
                        )}
                      </div>
                    );
                  })}
                </div>
              )}
            </div>
          );
        })}
      </div>
    );
  },
);
PixelMenubar.displayName = 'PixelMenubar';
