// packages/ui-kit-vue/src/navigation/PixelAccordion.vue
<script setup lang="ts">
import { computed, ref, useId } from 'vue';
import {
  accordionClasses,
  accordionIds,
  accordionInitialOpen,
  accordionItemClasses,
  toggleAccordionItem,
  type Surface,
} from '@pxlkit/ui-kit-core';
import PixelGlyph from '../_internal/PixelGlyph.vue';
import { RenderNode, type PxlNode } from '../_internal/render-node.js';
import { useEffectiveSurface } from '../composables/surface.js';

/** One item of a `PixelAccordion`. */
export interface AccordionItem {
  id: string;
  /** Header text. */
  title: string;
  /** Panel content: text, a VNode or a render function. */
  content: PxlNode;
}

/**
 * Stack of disclosure items: each header is a button reporting
 * `aria-expanded` that shows and hides its panel (`aria-controls`), which
 * refers back to it. One item is open at a time unless `allow-multiple`;
 * the first starts open unless `collapsed-by-default`. A closed panel is not
 * rendered.
 *
 * @example
 * <PixelAccordion :items="[{ id: 'faq', title: 'FAQ', content: 'Short answers.' }]" allow-multiple />
 */
export interface PixelAccordionProps {
  /** The items, in order. */
  items: AccordionItem[];
  /** Several items can be open at once. */
  allowMultiple?: boolean;
  /** Every item starts closed, instead of the first one open. */
  collapsedByDefault?: boolean;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
}

const props = withDefaults(defineProps<PixelAccordionProps>(), {
  allowMultiple: false,
  collapsedByDefault: false,
  surface: undefined,
});

const surface = useEffectiveSurface(() => props.surface);
const baseId = useId();
const open = ref(accordionInitialOpen(props.items, props.collapsedByDefault));
const rows = computed(() =>
  props.items.map((item) => {
    const isOpen = open.value.includes(item.id);
    return { item, open: isOpen, ids: accordionIds(baseId, item.id), classes: accordionItemClasses(surface.value, isOpen) };
  }),
);

function toggle(id: string) {
  open.value = toggleAccordionItem(open.value, id, props.allowMultiple);
}
</script>

<template>
  <div :class="accordionClasses">
    <div v-for="row in rows" :key="row.item.id" :class="row.classes.item">
      <button
        :id="row.ids.header"
        type="button"
        :aria-expanded="row.open"
        :aria-controls="row.ids.panel"
        :class="row.classes.trigger"
        @click="toggle(row.item.id)"
      >
        <span>{{ row.item.title }}</span>
        <PixelGlyph name="chevronDown" :class="row.classes.chevron" />
      </button>
      <div v-if="row.open" :id="row.ids.panel" :aria-labelledby="row.ids.header" :class="row.classes.panel">
        <RenderNode :node="row.item.content" />
      </div>
    </div>
  </div>
</template>

// packages/ui-kit/src/navigation/PixelAccordion.tsx
import React, { forwardRef, useId, useState } from 'react';
import {
  accordionClasses,
  accordionIds,
  accordionInitialOpen,
  accordionItemClasses,
  toggleAccordionItem,
} from '@pxlkit/ui-kit-core';
import {
  AccordionItem,
  ChevronDownIcon,
  Surface,
  useEffectiveSurface,
} from '../common';

/* ─────────────────────────────────────────────────────────────────────────
   PixelAccordion — list of expandable items with aria-controls + id wiring.
   ───────────────────────────────────────────────────────────────────────── */

/** Public prop bag for {@link PixelAccordion}. */
export interface PixelAccordionProps {
  /** Accordion items rendered in order. First item is expanded by default. */
  items: AccordionItem[];
  /** When true, multiple items can be expanded simultaneously. */
  allowMultiple?: boolean;
  /** When set, no item is initially expanded. Defaults to expanding the first. */
  collapsedByDefault?: boolean;
  /** Visual surface treatment override. */
  surface?: Surface;
}

export const PixelAccordion = forwardRef<HTMLDivElement, PixelAccordionProps>(function PixelAccordion(
  { items, allowMultiple = false, collapsedByDefault = false, surface: surfaceProp },
  ref,
) {
  const surface = useEffectiveSurface(surfaceProp);
  const baseId = useId();
  const [openIds, setOpenIds] = useState<string[]>(() => accordionInitialOpen(items, collapsedByDefault));

  const toggle = (id: string) => {
    setOpenIds((prev) => toggleAccordionItem(prev, id, allowMultiple));
  };

  return (
    <div ref={ref} className={accordionClasses}>
      {items.map((item) => {
        const isOpen = openIds.includes(item.id);
        const ids = accordionIds(baseId, item.id);
        const classes = accordionItemClasses(surface, isOpen);
        return (
          <div key={item.id} className={classes.item}>
            <button
              id={ids.header}
              type="button"
              aria-expanded={isOpen}
              aria-controls={ids.panel}
              className={classes.trigger}
              onClick={() => toggle(item.id)}
            >
              <span>{item.title}</span>
              <ChevronDownIcon className={classes.chevron} />
            </button>
            {isOpen && (
              // No role="region": the component cannot guarantee unique panel
              // names across instances, and duplicate region landmarks trip
              // axe's landmark-unique rule (APG also discourages region here
              // to avoid landmark proliferation).
              <div id={ids.panel} aria-labelledby={ids.header} className={classes.panel}>
                {item.content}
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
});

PixelAccordion.displayName = 'PixelAccordion';
