// packages/ui-kit-angular/examples/layout/pixel-grid.examples.ts
import { Component } from '@angular/core';
import { PixelGrid } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelGrid],
  template: `
    <div pxlGrid [cols]="3" [gap]="4">
      @for (cell of cells; track cell) {
        <div class="border border-retro-border bg-retro-surface p-3 text-sm text-retro-text">{{ cell }}</div>
      }
    </div>
  `,
})
export class Default {
  readonly cells = ['One', 'Two', 'Three', 'Four', 'Five', 'Six'];
}

@Component({
  imports: [PixelGrid],
  template: `
    <div pxlGrid [cols]="{ base: 1, sm: 2, md: 3, lg: 4 }" [gap]="4">
      @for (cell of cells; track cell) {
        <div class="border border-retro-border bg-retro-surface p-3 text-sm text-retro-text">{{ cell }}</div>
      }
    </div>
  `,
})
export class Responsive {
  readonly cells = ['1', '2', '3', '4'];
}

@Component({
  imports: [PixelGrid],
  template: `
    <div pxlGrid autoFit minColWidth="12rem" [gap]="4">
      @for (cell of cells; track cell) {
        <div class="border border-retro-border bg-retro-surface p-3 text-sm text-retro-text">{{ cell }}</div>
      }
    </div>
  `,
})
export class AutoFit {
  readonly cells = ['Auto A', 'Auto B', 'Auto C', 'Auto D'];
}

@Component({
  imports: [PixelGrid],
  template: `
    <div pxlGrid [cols]="2" [colGap]="8" [rowGap]="2">
      @for (cell of cells; track cell) {
        <div class="border border-retro-border bg-retro-surface p-3 text-sm text-retro-text">{{ cell }}</div>
      }
    </div>
  `,
})
export class AsymmetricGaps {
  readonly cells = ['A', 'B', 'C', 'D'];
}

// packages/ui-kit/src/layout/PixelGrid.examples.tsx
import React from 'react';
import { PixelGrid } from './PixelGrid';

function Cell({ children }: { children: React.ReactNode }) {
  return (
    <div className="border border-retro-border bg-retro-surface p-3 text-sm text-retro-text">
      {children}
    </div>
  );
}

export function Default() {
  return (
    <PixelGrid cols={3} gap={4}>
      <Cell>One</Cell>
      <Cell>Two</Cell>
      <Cell>Three</Cell>
      <Cell>Four</Cell>
      <Cell>Five</Cell>
      <Cell>Six</Cell>
    </PixelGrid>
  );
}

export function Responsive() {
  return (
    <PixelGrid cols={{ base: 1, sm: 2, md: 3, lg: 4 }} gap={4}>
      <Cell>1</Cell>
      <Cell>2</Cell>
      <Cell>3</Cell>
      <Cell>4</Cell>
    </PixelGrid>
  );
}

export function AutoFit() {
  return (
    <PixelGrid autoFit minColWidth="12rem" gap={4}>
      <Cell>Auto A</Cell>
      <Cell>Auto B</Cell>
      <Cell>Auto C</Cell>
      <Cell>Auto D</Cell>
    </PixelGrid>
  );
}

export function AsymmetricGaps() {
  return (
    <PixelGrid cols={2} colGap={8} rowGap={2}>
      <Cell>A</Cell>
      <Cell>B</Cell>
      <Cell>C</Cell>
      <Cell>D</Cell>
    </PixelGrid>
  );
}
