// packages/ui-kit-vue/src/layout/PixelSection.vue
<script setup lang="ts">
import { computed, type VNode } from 'vue';
import {
  sectionClasses,
  type ContainerWidth,
  type PageGutter,
  type SectionRhythmKey,
  type Surface,
} from '@pxlkit/ui-kit-core';
import { usePxlKitLocale } from '../composables/locale.js';
import { useEffectiveSurface } from '../composables/surface.js';
import PixelCenter from './PixelCenter.vue';

/**
 * Page `<section>` with an optional uppercase title row and subtitle; its
 * content sits in a centred column (`PixelCenter`) or across the full width.
 */
export interface PixelSectionProps {
  /** Heading row at the top of the section, upper-cased for the locale. */
  title?: string;
  /** Line under the title. */
  subtitle?: string;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
  /** Width of the centred column (`containerWidth`), or `false` for the full width. */
  container?: ContainerWidth | false;
  /** Vertical padding (`sectionRhythm`). */
  verticalPadding?: SectionRhythmKey;
  /** Horizontal padding (`pageGutter`) of the column, or of the section without one. */
  horizontalGutter?: PageGutter;
  /** Surface border, radius and card tint. */
  bordered?: boolean;
}

const props = withDefaults(defineProps<PixelSectionProps>(), {
  title: undefined,
  subtitle: undefined,
  surface: undefined,
  container: '5xl',
  verticalPadding: 'xl',
  horizontalGutter: 'lg',
  bordered: false,
});
defineSlots<{ default?(): VNode[] }>();

const surface = useEffectiveSurface(() => props.surface);
const locale = usePxlKitLocale();
const classes = computed(() =>
  sectionClasses(surface.value, {
    bordered: props.bordered,
    verticalPadding: props.verticalPadding,
    container: props.container,
    horizontalGutter: props.horizontalGutter,
  }),
);
</script>

<template>
  <section :class="classes.section">
    <PixelCenter v-if="container" :max-width="container" :gutter="horizontalGutter" :surface="surface">
      <div v-if="title" class="mb-4">
        <h3 :class="classes.title">{{ locale.upper(title) }}</h3>
        <p v-if="subtitle" :class="classes.subtitle">{{ subtitle }}</p>
      </div>
      <slot />
    </PixelCenter>
    <template v-else>
      <div v-if="title" class="mb-4">
        <h3 :class="classes.title">{{ locale.upper(title) }}</h3>
        <p v-if="subtitle" :class="classes.subtitle">{{ subtitle }}</p>
      </div>
      <slot />
    </template>
  </section>
</template>

// packages/ui-kit/src/layout/PixelSection.tsx
'use client';

/* ─────────────────────────────────────────────────────────────────────────
   PixelSection — bordered section with optional title row and subtitle.
   ───────────────────────────────────────────────────────────────────────── */

import React, { forwardRef } from 'react';
import { sectionClasses } from '@pxlkit/ui-kit-core';
import { Surface, useEffectiveSurface } from '../common';
import { usePxlKitLocale } from '../locale';
import { PixelCenter } from './PixelCenter';
import { type ContainerWidth, type PageGutter, type SectionRhythmKey } from '../tokens';

export interface PixelSectionProps {
  /** Title rendered as an uppercase heading row at the top of the section. */
  title?: string;
  /** Optional subtitle below the title. */
  subtitle?: string;
  /** Section content. */
  children: React.ReactNode;
  /** Surface variant. Falls back to nearest <PxlKitSurface>. */
  surface?: Surface;
  /** Inner container max-width. Pass `false` to skip the centered container wrapper. */
  container?: ContainerWidth | false;
  /** Vertical padding token (margin between consecutive sections). */
  verticalPadding?: SectionRhythmKey;
  /** Horizontal gutter token (used only when `container` is `false`). */
  horizontalGutter?: PageGutter;
  /** Render with surface-aware border + radius chrome. Defaults to false (no chrome). */
  bordered?: boolean;
}

export const PixelSection = forwardRef<HTMLElement, PixelSectionProps>(function PixelSection(
  {
    title,
    subtitle,
    children,
    surface: surfaceProp,
    container = '5xl',
    verticalPadding = 'xl',
    horizontalGutter = 'lg',
    bordered = false,
  },
  ref,
) {
  const surface = useEffectiveSurface(surfaceProp);
  const c = sectionClasses(surface, { bordered, verticalPadding, container, horizontalGutter });
  const { upper } = usePxlKitLocale();

  const inner = (
    <>
      {title && (
        <div className="mb-4">
          <h3 className={c.title}>{upper(title)}</h3>
          {subtitle && <p className={c.subtitle}>{subtitle}</p>}
        </div>
      )}
      {children}
    </>
  );

  return (
    <section ref={ref} className={c.section}>
      {container ? (
        <PixelCenter maxWidth={container} gutter={horizontalGutter} surface={surface}>
          {inner}
        </PixelCenter>
      ) : (
        inner
      )}
    </section>
  );
});

PixelSection.displayName = 'PixelSection';
