// packages/ui-kit-angular/src/lib/feedback/pixel-empty-state.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { emptyStateClasses, type Surface } from '@pxlkit/ui-kit-core';
import { PxlOutlet, type PxlContent } from '../_internal/outlet';
import { injectEffectiveSurface } from '../overlay-foundation/pxl-kit-surface-provider';

/**
 * Placeholder for an empty collection or a search without results: a dashed,
 * centred block with a title (`<h4>`), a description and an optional
 * decorative icon and call to action (text or an `<ng-template>`). The host
 * is the block.
 *
 * @example
 * <pxl-empty-state title="No results found" description="Try other filters." [action]="reset" />
 * <ng-template #reset><button pxlButton size="sm">Reset filters</button></ng-template>
 */
@Component({
  selector: 'pxl-empty-state',
  imports: [PxlOutlet],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'classes().root',
    // `title` is the heading; on the host it would show a native tooltip.
    '[attr.title]': 'null',
  },
  template: `
    @if (icon()) {
      <div [class]="classes().icon" aria-hidden="true"><ng-container *pxlOutlet="icon(); let text">{{ text }}</ng-container></div>
    }
    <h4 [class]="classes().title">{{ title() }}</h4>
    <p [class]="classes().description">{{ description() }}</p>
    @if (action()) {
      <div [class]="classes().action"><ng-container *pxlOutlet="action(); let text">{{ text }}</ng-container></div>
    }
  `,
})
export class PixelEmptyState {
  /** Short title (e.g. `"No results"`). */
  readonly title = input.required<string>();
  /** Supporting description below the title. */
  readonly description = input.required<string>();
  /** Call to action under the description (a button, a link). */
  readonly action = input<PxlContent>();
  /** Decorative icon above the title (hidden from assistive tech). */
  readonly icon = input<PxlContent>();
  /** Surface override; defaults to the nearest provider. */
  readonly surface = input<Surface>();

  private readonly effectiveSurface = injectEffectiveSurface(() => this.surface());
  /** @internal */
  protected readonly classes = computed(() => emptyStateClasses(this.effectiveSurface()));
}

// packages/ui-kit-vue/src/feedback/PixelEmptyState.vue
<script setup lang="ts">
import { computed, type VNode } from 'vue';
import { emptyStateClasses, type Surface } from '@pxlkit/ui-kit-core';
import { useEffectiveSurface } from '../composables/surface.js';

/**
 * Placeholder for an empty collection or a search without results: a dashed,
 * centred block with a title (`<h4>`), a description and an optional
 * decorative icon and call to action.
 *
 * @example
 * <PixelEmptyState title="No results found" description="Try other filters.">
 *   <template #action><PixelButton size="sm">Reset filters</PixelButton></template>
 * </PixelEmptyState>
 */
export interface PixelEmptyStateProps {
  /** Short title (e.g. `"No results"`). */
  title: string;
  /** Supporting description below the title. */
  description: string;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
}

const props = withDefaults(defineProps<PixelEmptyStateProps>(), { surface: undefined });
defineSlots<{
  /** Decorative icon above the title (hidden from assistive tech). */
  icon?(): VNode[];
  /** Call to action under the description (a button, a link). */
  action?(): VNode[];
}>();

const surface = useEffectiveSurface(() => props.surface);
const classes = computed(() => emptyStateClasses(surface.value));
</script>

<template>
  <div :class="classes.root">
    <div v-if="$slots.icon" :class="classes.icon" aria-hidden="true"><slot name="icon" /></div>
    <h4 :class="classes.title">{{ title }}</h4>
    <p :class="classes.description">{{ description }}</p>
    <div v-if="$slots.action" :class="classes.action"><slot name="action" /></div>
  </div>
</template>
