// packages/ui-kit-angular/src/lib/feedback/pixel-alert.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { alertClasses, alertLive, type AlertLive, type Surface, type Tone } from '@pxlkit/ui-kit-core';
import { withDefault } from '../_internal/coercion';
import { PxlOutlet, type PxlContent } from '../_internal/outlet';
import { injectEffectiveSurface } from '../overlay-foundation/pxl-kit-surface-provider';

/**
 * Inline status banner with a label, a message, a tone and an optional icon
 * and action (text or an `<ng-template>`). It announces itself
 * (`role="alert"`): assertively for critical tones (red, gold) and politely
 * for the others, unless `live` says otherwise. The pixel surface adds a left
 * accent stripe. The host is the banner.
 *
 * @example
 * <pxl-alert tone="red" label="Connection lost" message="Check your network and retry." [action]="retry" />
 * <ng-template #retry><button pxlButton size="sm" tone="red" variant="outline">Retry</button></ng-template>
 */
@Component({
  selector: 'pxl-alert',
  imports: [PxlOutlet],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    role: 'alert',
    '[attr.aria-live]': 'ariaLive()',
    '[class]': 'classes().root',
    // `title` is the deprecated label; on the host it would show a native tooltip.
    '[attr.title]': 'null',
  },
  template: `
    @if (effectiveSurface() === 'pixel') {
      <span aria-hidden="true" [class]="classes().stripe"></span>
    }
    <div [class]="classes().row">
      @if (icon()) {
        <span [class]="classes().icon"><ng-container *pxlOutlet="icon(); let text">{{ text }}</ng-container></span>
      }
      <div [class]="classes().body">
        <p [class]="classes().label">{{ label() ?? title() ?? '' }}</p>
        <p [class]="classes().message">{{ message() }}</p>
        @if (action()) {
          <div [class]="classes().action"><ng-container *pxlOutlet="action(); let text">{{ text }}</ng-container></div>
        }
      </div>
    </div>
  `,
})
export class PixelAlert {
  /** Short label shown in the tone colour (canonical name for the title). */
  readonly label = input<string>();
  /** @deprecated Use `label` instead. Retained as alias for one minor. */
  readonly title = input<string>();
  /** Body message under the label. */
  readonly message = input.required<string>();
  /** Tone of the border, fill and texts. */
  readonly tone = input<Tone, Tone | undefined>('red', { transform: withDefault<Tone>('red') });
  /** Leading icon, in the tone colour. */
  readonly icon = input<PxlContent>();
  /** Action under the message (Retry, Dismiss, …). */
  readonly action = input<PxlContent>();
  /** Surface override; defaults to the nearest provider. */
  readonly surface = input<Surface>();
  /** `aria-live` override. Status banners ("info") should usually use `"polite"`. */
  readonly live = input<AlertLive>();

  /** @internal */
  protected readonly effectiveSurface = injectEffectiveSurface(() => this.surface());
  /** @internal */
  protected readonly classes = computed(() => alertClasses(this.effectiveSurface(), this.tone()));
  /** @internal */
  protected readonly ariaLive = computed(() => alertLive(this.tone(), this.live()));
}

// packages/ui-kit-vue/src/feedback/PixelAlert.vue
<script setup lang="ts">
import { computed, type VNode } from 'vue';
import { alertClasses, alertLive, type AlertLive, type Surface, type Tone } from '@pxlkit/ui-kit-core';
import { useEffectiveSurface } from '../composables/surface.js';

/**
 * Inline status banner with a label, a message, a tone and an optional icon
 * and action. It announces itself (`role="alert"`): assertively for critical
 * tones (red, gold) and politely for the others, unless `live` says
 * otherwise. The pixel surface adds a left accent stripe.
 *
 * @example
 * <PixelAlert tone="red" label="Connection lost" message="Check your network and retry.">
 *   <template #action><PixelButton size="sm" tone="red" variant="outline">Retry</PixelButton></template>
 * </PixelAlert>
 */
export interface PixelAlertProps {
  /** Short label shown in the tone colour (canonical name for the title). */
  label?: string;
  /** @deprecated Use `label` instead. Retained as alias for one minor. */
  title?: string;
  /** Body message under the label. */
  message: string;
  /** Tone of the border, fill and texts. */
  tone?: Tone;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
  /** `aria-live` override. Status banners ("info") should usually use `"polite"`. */
  live?: AlertLive;
}

const props = withDefaults(defineProps<PixelAlertProps>(), {
  label: undefined,
  title: undefined,
  tone: 'red',
  surface: undefined,
  live: undefined,
});
defineSlots<{
  /** Leading icon, in the tone colour. */
  icon?(): VNode[];
  /** Action under the message (Retry, Dismiss, …). */
  action?(): VNode[];
}>();

const surface = useEffectiveSurface(() => props.surface);
const classes = computed(() => alertClasses(surface.value, props.tone));
</script>

<template>
  <div role="alert" :aria-live="alertLive(tone, live)" :class="classes.root">
    <span v-if="surface === 'pixel'" aria-hidden="true" :class="classes.stripe" />
    <div :class="classes.row">
      <span v-if="$slots.icon" :class="classes.icon"><slot name="icon" /></span>
      <div :class="classes.body">
        <p :class="classes.label">{{ label ?? title ?? '' }}</p>
        <p :class="classes.message">{{ message }}</p>
        <div v-if="$slots.action" :class="classes.action"><slot name="action" /></div>
      </div>
    </div>
  </div>
</template>
