// packages/ui-kit-angular/examples/overlays/pixel-tooltip.examples.ts
import { Component, signal } from '@angular/core';
import { PixelButton, PixelTooltip } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelButton, PixelTooltip],
  template: `
    <pxl-tooltip label="Save your changes">
      <button pxlButton>Save</button>
    </pxl-tooltip>
  `,
})
export class Default {}

@Component({
  imports: [PixelButton, PixelTooltip],
  template: `
    <div class="flex flex-wrap items-center gap-6">
      <pxl-tooltip label="Top tooltip" position="top">
        <button pxlButton>Top</button>
      </pxl-tooltip>
      <pxl-tooltip label="Bottom tooltip" position="bottom">
        <button pxlButton>Bottom</button>
      </pxl-tooltip>
      <pxl-tooltip label="Left tooltip" position="left">
        <button pxlButton>Left</button>
      </pxl-tooltip>
      <pxl-tooltip label="Right tooltip" position="right">
        <button pxlButton>Right</button>
      </pxl-tooltip>
    </div>
  `,
})
export class Positions {}

@Component({
  imports: [PixelButton, PixelTooltip],
  template: `
    <div class="flex flex-wrap items-center gap-6">
      <pxl-tooltip label="Opens on hover or focus" trigger="hover">
        <button pxlButton>Hover</button>
      </pxl-tooltip>
      <pxl-tooltip label="Opens on focus only" trigger="focus">
        <button pxlButton>Focus</button>
      </pxl-tooltip>
      <pxl-tooltip label="Click to toggle, Escape to close" trigger="click">
        <button pxlButton>Click</button>
      </pxl-tooltip>
    </div>
  `,
})
export class Triggers {}

@Component({
  imports: [PixelButton, PixelTooltip],
  template: `
    <div class="flex flex-wrap items-center gap-6">
      <pxl-tooltip label="Pixel surface" surface="pixel">
        <button pxlButton surface="pixel">Pixel</button>
      </pxl-tooltip>
      <pxl-tooltip label="Linear surface" surface="linear">
        <button pxlButton surface="linear">Linear</button>
      </pxl-tooltip>
    </div>
  `,
})
export class Surfaces {}

@Component({
  imports: [PixelButton, PixelTooltip],
  template: `
    <pxl-tooltip [content]="details">
      <button pxlButton>Hover for details</button>
    </pxl-tooltip>
    <ng-template #details>
      <span class="flex flex-col gap-0.5">
        <span class="font-semibold">Keyboard shortcut</span>
        <span class="opacity-80">Press ⌘K to open the command palette</span>
      </span>
    </ng-template>
  `,
})
export class RichContent {}

@Component({
  imports: [PixelButton, PixelTooltip],
  template: `
    <div class="flex flex-wrap items-center gap-6">
      <pxl-tooltip label="Opens instantly" [delay]="{ open: 0, close: 0 }">
        <button pxlButton>Instant</button>
      </pxl-tooltip>
      <pxl-tooltip label="Slow open, fast close" [delay]="{ open: 600, close: 0 }">
        <button pxlButton>Slow open</button>
      </pxl-tooltip>
    </div>
  `,
})
export class CustomDelay {}

@Component({
  imports: [PixelButton, PixelTooltip],
  template: `
    <div class="flex items-center gap-4">
      <pxl-tooltip [(open)]="open" label="Controlled tooltip">
        <button pxlButton>Anchor</button>
      </pxl-tooltip>
      <button pxlButton tone="cyan" variant="outline" (click)="open.set(!open())">{{ open() ? 'Hide' : 'Show' }}</button>
    </div>
  `,
})
export class Controlled {
  readonly open = signal(false);
}

@Component({
  imports: [PixelButton, PixelTooltip],
  template: `
    <pxl-tooltip defaultOpen label="Open by default" trigger="click">
      <button pxlButton>Click to toggle</button>
    </pxl-tooltip>
  `,
})
export class Uncontrolled {}

@Component({
  imports: [PixelButton, PixelTooltip],
  template: `
    <div class="flex flex-wrap items-center gap-6">
      <pxl-tooltip label="Tight (2px)" [sideOffset]="2">
        <button pxlButton>Tight</button>
      </pxl-tooltip>
      <pxl-tooltip label="Roomy (16px)" [sideOffset]="16">
        <button pxlButton>Roomy</button>
      </pxl-tooltip>
    </div>
  `,
})
export class SideOffset {}

// packages/ui-kit/src/overlays/PixelTooltip.examples.tsx
import { useState } from 'react';
import { PixelTooltip } from './PixelTooltip';
import { PixelButton } from '../actions';

export function Default() {
  return (
    <PixelTooltip label="Save your changes">
      <PixelButton>Save</PixelButton>
    </PixelTooltip>
  );
}

export function Positions() {
  return (
    <div className="flex flex-wrap items-center gap-6">
      <PixelTooltip label="Top tooltip" position="top">
        <PixelButton>Top</PixelButton>
      </PixelTooltip>
      <PixelTooltip label="Bottom tooltip" position="bottom">
        <PixelButton>Bottom</PixelButton>
      </PixelTooltip>
      <PixelTooltip label="Left tooltip" position="left">
        <PixelButton>Left</PixelButton>
      </PixelTooltip>
      <PixelTooltip label="Right tooltip" position="right">
        <PixelButton>Right</PixelButton>
      </PixelTooltip>
    </div>
  );
}

export function Triggers() {
  return (
    <div className="flex flex-wrap items-center gap-6">
      <PixelTooltip label="Opens on hover or focus" trigger="hover">
        <PixelButton>Hover</PixelButton>
      </PixelTooltip>
      <PixelTooltip label="Opens on focus only" trigger="focus">
        <PixelButton>Focus</PixelButton>
      </PixelTooltip>
      <PixelTooltip label="Click to toggle, Escape to close" trigger="click">
        <PixelButton>Click</PixelButton>
      </PixelTooltip>
    </div>
  );
}

export function Surfaces() {
  return (
    <div className="flex flex-wrap items-center gap-6">
      <PixelTooltip label="Pixel surface" surface="pixel">
        <PixelButton surface="pixel">Pixel</PixelButton>
      </PixelTooltip>
      <PixelTooltip label="Linear surface" surface="linear">
        <PixelButton surface="linear">Linear</PixelButton>
      </PixelTooltip>
    </div>
  );
}

export function RichContent() {
  return (
    <PixelTooltip
      content={
        <span className="flex flex-col gap-0.5">
          <span className="font-semibold">Keyboard shortcut</span>
          <span className="opacity-80">Press ⌘K to open the command palette</span>
        </span>
      }
    >
      <PixelButton>Hover for details</PixelButton>
    </PixelTooltip>
  );
}

export function CustomDelay() {
  return (
    <div className="flex flex-wrap items-center gap-6">
      <PixelTooltip label="Opens instantly" delay={{ open: 0, close: 0 }}>
        <PixelButton>Instant</PixelButton>
      </PixelTooltip>
      <PixelTooltip label="Slow open, fast close" delay={{ open: 600, close: 0 }}>
        <PixelButton>Slow open</PixelButton>
      </PixelTooltip>
    </div>
  );
}

export function Controlled() {
  const [open, setOpen] = useState(false);
  return (
    <div className="flex items-center gap-4">
      <PixelTooltip open={open} onOpenChange={setOpen} label="Controlled tooltip">
        <PixelButton>Anchor</PixelButton>
      </PixelTooltip>
      <PixelButton tone="cyan" variant="outline" onClick={() => setOpen((v) => !v)}>
        {open ? 'Hide' : 'Show'}
      </PixelButton>
    </div>
  );
}

export function Uncontrolled() {
  return (
    <PixelTooltip defaultOpen label="Open by default" trigger="click">
      <PixelButton>Click to toggle</PixelButton>
    </PixelTooltip>
  );
}

export function SideOffset() {
  return (
    <div className="flex flex-wrap items-center gap-6">
      <PixelTooltip label="Tight (2px)" sideOffset={2}>
        <PixelButton>Tight</PixelButton>
      </PixelTooltip>
      <PixelTooltip label="Roomy (16px)" sideOffset={16}>
        <PixelButton>Roomy</PixelButton>
      </PixelTooltip>
    </div>
  );
}
