// packages/ui-kit/src/animations/PixelTypewriter.tsx
'use client';

import React, { forwardRef, useEffect, useRef, useState } from 'react';
import { TYPEWRITER_CARET, typeText, typewriterClasses, type TypewriterTone } from '@pxlkit/ui-kit-core';
import { cn } from '../common';
import type { AnimationTrigger } from './types';
import { mergeRefs, useAnimationTrigger } from './_internal/animation-hooks';

/* ─────────────────────────────────────────────────────────────────────────
   PixelTypewriter — types out a string one character at a time with a
   blinking caret while writing.
   ───────────────────────────────────────────────────────────────────────── */

export interface PixelTypewriterProps {
  /** Label (text) to type out. Canonical prop. */
  label?: string;
  /**
   * @deprecated Use `label` instead. Retained as alias for one minor.
   */
  text?: string;
  /** Milliseconds between each character. Default `60`. */
  speed?: number;
  /** Delay before typing starts, in milliseconds. Default `0`. */
  delay?: number;
  /** Show a blinking caret while writing. Default `true`. */
  cursor?: boolean;
  /**
   * Tone token applied to the text color, in monospace; `'inherit'` keeps the
   * font and colour of the text around it. Default `'green'`.
   */
  tone?: TypewriterTone;
  /** When the animation should play. Default `'mount'`. */
  trigger?: AnimationTrigger;
  /** Fires once the full string is rendered. */
  onComplete?: () => void;
  /** Extra class names applied to the wrapping `<span>`. */
  className?: string;
}

export const PixelTypewriter = forwardRef<HTMLSpanElement, PixelTypewriterProps>(function PixelTypewriter(
  {
    label,
    text,
    speed = 60,
    delay = 0,
    cursor = true,
    tone = 'green',
    trigger = 'mount',
    onComplete,
    className,
  },
  forwardedRef,
) {
  const resolvedText = label ?? text ?? '';
  const { ref, active, reducedMotion, handlers, endAnimation } = useAnimationTrigger(trigger, onComplete);
  const [displayed, setDisplayed] = useState('');
  const [done, setDone] = useState(false);
  const reducedCompleteRef = useRef(false);
  const classes = typewriterClasses(tone);

  useEffect(() => {
    if (reducedMotion) {
      /* Reduced motion: skip the typing animation — show the full text
         immediately, regardless of trigger mode. `onComplete` still fires
         (once) because its contract is "full string rendered", which is
         satisfied instantly. */
      setDisplayed(resolvedText);
      setDone(true);
      if (!reducedCompleteRef.current) {
        reducedCompleteRef.current = true;
        endAnimation();
      }
      return;
    }
    setDisplayed('');
    setDone(false);
    if (!active) return;
    return typeText(resolvedText, { speed, delay }, setDisplayed, () => {
      setDone(true);
      endAnimation();
    });
  }, [active, reducedMotion, resolvedText, speed, delay, endAnimation]);

  return (
    <span
      ref={mergeRefs(ref as unknown as React.Ref<HTMLSpanElement>, forwardedRef)}
      {...(handlers as React.DOMAttributes<HTMLSpanElement>)}
      className={cn(classes.root, className)}
    >
      {/* Screen readers get the complete string from the first render; the
          character-by-character churn below is purely visual (announcing
          each partial slice would be noise, not typing). */}
      <span className="sr-only">{resolvedText}</span>
      <span aria-hidden="true">
        {displayed}
        {cursor && !done && active && <span className={classes.caret}>{TYPEWRITER_CARET}</span>}
      </span>
    </span>
  );
});

PixelTypewriter.displayName = 'PixelTypewriter';

// packages/ui-kit-vue/src/animations/PixelTypewriter.vue
<script setup lang="ts">
import { computed, onMounted, ref, useTemplateRef, watch } from 'vue';
import { TYPEWRITER_CARET, typeText, typewriterClasses, type AnimationTrigger, type TypewriterTone } from '@pxlkit/ui-kit-core';
import { useAnimationTrigger } from './_internal/animation-trigger.js';

/**
 * Types a text out one character at a time, with a blinking caret while it
 * writes. Assistive technology reads the whole text from the first render
 * (a visually hidden copy); the typing itself is hidden from it. When the
 * user prefers reduced motion the text shows at once. Attributes fall
 * through to the wrapping `<span>`.
 *
 * @example
 * <PixelTypewriter label="Types when scrolled into view." trigger="inView" tone="purple" @complete="next" />
 */
export interface PixelTypewriterProps {
  /** Label (text) to type out. Canonical prop. */
  label?: string;
  /** @deprecated Use `label` instead. Retained as alias for one minor. */
  text?: string;
  /** Milliseconds between each character. */
  speed?: number;
  /** Delay before typing starts, in milliseconds. */
  delay?: number;
  /** Show a blinking caret while writing. */
  cursor?: boolean;
  /**
   * Tone token applied to the text color, in monospace; `'inherit'` keeps
   * the font and colour of the text around it.
   */
  tone?: TypewriterTone;
  /**
   * When the typing plays: `'mount'`, `'hover'`, `'click'`, `'focus'`,
   * `'inView'`, or `true` / `false` to control it.
   */
  trigger?: AnimationTrigger;
}

const props = withDefaults(defineProps<PixelTypewriterProps>(), {
  label: undefined,
  text: undefined,
  speed: 60,
  delay: 0,
  cursor: true,
  tone: 'green',
  trigger: 'mount',
});
const emit = defineEmits<{
  /** Once the full string is rendered (at once under reduced motion, then only once). */
  complete: [];
}>();

const element = useTemplateRef<HTMLElement>('element');
const { active, reducedMotion, listeners, end } = useAnimationTrigger(
  element,
  () => props.trigger,
  () => emit('complete'),
);
const fullText = computed(() => props.label ?? props.text ?? '');
const classes = computed(() => typewriterClasses(props.tone));
const typed = ref('');
const done = ref(false);
// The caret shows while the text is being typed.
const typing = computed(() => props.cursor && !done.value && active.value);
let completedStill = false;

// Typing runs in the browser only, once mounted, and starts over whenever
// the text, its pace or the trigger changes.
onMounted(() => {
  watch(
    [active, reducedMotion, fullText, () => props.speed, () => props.delay, () => props.trigger],
    ([playing, still, text, speed, delay], _previous, onCleanup) => {
      if (still) {
        // Reduced motion shows the whole text at once: the full string is
        // there, so complete fires — once.
        typed.value = text;
        done.value = true;
        if (!completedStill) {
          completedStill = true;
          end();
        }
        return;
      }
      typed.value = '';
      done.value = false;
      if (!playing) return;
      onCleanup(
        typeText(
          text,
          { speed, delay },
          (next) => {
            typed.value = next;
          },
          () => {
            done.value = true;
            end();
          },
        ),
      );
    },
    { immediate: true },
  );
});
</script>

<template>
  <span ref="element" :class="classes.root" v-on="listeners">
    <span class="sr-only">{{ fullText }}</span>
    <span aria-hidden="true">{{ typed }}<span v-if="typing" :class="classes.caret">{{ TYPEWRITER_CARET }}</span></span>
  </span>
</template>
