// packages/ui-kit/src/animations/PixelPulse.tsx
'use client';

import React, { forwardRef } from 'react';
import { pulseStyle } from '@pxlkit/ui-kit-core';
import type { AnimationRepeat, AnimationTrigger } from './types';
import { mergeRefs, useAnimationTrigger } from './_internal/animation-hooks';

/* ─────────────────────────────────────────────────────────────────────────
   PixelPulse — gently scales + dims children to draw attention.
   ───────────────────────────────────────────────────────────────────────── */

export interface PixelPulseProps {
  /** Content to pulse. */
  children: React.ReactNode;
  /** Animation duration in milliseconds. Default `2000`. */
  duration?: number;
  /** Iteration count: a number or `'infinite'`. Default `'infinite'`. */
  repeat?: AnimationRepeat;
  /** CSS `animation-timing-function`. Default `'ease-in-out'`. */
  easing?: string;
  /** When the animation should play. Default `'mount'`. */
  trigger?: AnimationTrigger;
  /** Fires after the final iteration. */
  onComplete?: () => void;
  /** Extra class names applied to the wrapping `<div>`. */
  className?: string;
}

export const PixelPulse = forwardRef<HTMLDivElement, PixelPulseProps>(function PixelPulse(
  {
    children,
    duration = 2000,
    repeat = 'infinite',
    easing = 'ease-in-out',
    trigger = 'mount',
    onComplete,
    className,
  },
  forwardedRef,
) {
  const { ref, active, handlers, handleAnimEnd } = useAnimationTrigger(trigger, onComplete);
  return (
    <div
      ref={mergeRefs(ref, forwardedRef)}
      className={className}
      style={active ? pulseStyle({ duration, repeat, easing }) : undefined}
      {...handlers}
      onAnimationEnd={handleAnimEnd}
    >
      {children}
    </div>
  );
});

PixelPulse.displayName = 'PixelPulse';

// packages/ui-kit-vue/src/animations/PixelPulse.vue
<script setup lang="ts">
import { computed, useTemplateRef, type VNode } from 'vue';
import { pulseStyle, type AnimationRepeat, type AnimationTrigger } from '@pxlkit/ui-kit-core';
import { useAnimationTrigger } from './_internal/animation-trigger.js';

/**
 * Gently scales and dims its content in a recurring pulse, to draw
 * attention. It plays as `trigger` says and holds still when the user
 * prefers reduced motion. Attributes fall through to the wrapping `<div>`.
 *
 * @example
 * <PixelPulse :duration="1000"><span>Quick Pulse</span></PixelPulse>
 */
export interface PixelPulseProps {
  /** Animation duration in milliseconds. */
  duration?: number;
  /** Iteration count: a number or `'infinite'`. */
  repeat?: AnimationRepeat;
  /** CSS `animation-timing-function`. */
  easing?: string;
  /**
   * When the animation plays: `'mount'`, `'hover'`, `'click'`, `'focus'`,
   * `'inView'`, or `true` / `false` to control it.
   */
  trigger?: AnimationTrigger;
}

const props = withDefaults(defineProps<PixelPulseProps>(), {
  duration: 2000,
  repeat: 'infinite',
  easing: 'ease-in-out',
  trigger: 'mount',
});
const emit = defineEmits<{
  /** After the final iteration. */
  complete: [];
}>();
defineSlots<{
  /** Content to pulse. */
  default?(): VNode[];
}>();

const element = useTemplateRef<HTMLElement>('element');
const { active, listeners, ended } = useAnimationTrigger(element, () => props.trigger, () => emit('complete'));
const style = computed(() => (active.value ? pulseStyle(props) : undefined));
</script>

<template>
  <div ref="element" :style="style" v-on="listeners" @animationend="ended">
    <slot />
  </div>
</template>
