// packages/ui-kit/src/animations/PixelShake.tsx
'use client';

import React, { forwardRef } from 'react';
import { animationInlineClasses, shakeStyle } from '@pxlkit/ui-kit-core';
import { cn } from '../common';
import type { AnimationRepeat, AnimationTrigger } from './types';
import { mergeRefs, useAnimationTrigger } from './_internal/animation-hooks';

/* ─────────────────────────────────────────────────────────────────────────
   PixelShake — quick horizontal shake. Pairs well with validation errors.
   ───────────────────────────────────────────────────────────────────────── */

export interface PixelShakeProps {
  /** Content to shake. */
  children: React.ReactNode;
  /** Animation duration in milliseconds. Default `450`. */
  duration?: number;
  /** Horizontal travel distance in pixels. Default `2`. */
  distance?: number;
  /** Iteration count: a number or `'infinite'`. Default `1`. */
  repeat?: AnimationRepeat;
  /** CSS `animation-timing-function`. Default `'linear'`. */
  easing?: string;
  /** When the animation should play. Default `'mount'`. */
  trigger?: AnimationTrigger;
  /** Fires after the final iteration. */
  onComplete?: () => void;
  /** Extra class names applied to the wrapping `<div>`. */
  className?: string;
}

export const PixelShake = forwardRef<HTMLDivElement, PixelShakeProps>(function PixelShake(
  {
    children,
    duration = 450,
    distance = 2,
    repeat = 1,
    easing = 'linear',
    trigger = 'mount',
    onComplete,
    className,
  },
  forwardedRef,
) {
  const { ref, active, handlers, handleAnimEnd } = useAnimationTrigger(trigger, onComplete);
  return (
    <div
      ref={mergeRefs(ref, forwardedRef)}
      className={cn(animationInlineClasses, className)}
      style={active ? shakeStyle({ duration, distance, repeat, easing }) : undefined}
      {...handlers}
      onAnimationEnd={handleAnimEnd}
    >
      {children}
    </div>
  );
});

PixelShake.displayName = 'PixelShake';

// packages/ui-kit-vue/src/animations/PixelShake.vue
<script setup lang="ts">
import { computed, useTemplateRef, type VNode } from 'vue';
import { animationInlineClasses, shakeStyle, type AnimationRepeat, type AnimationTrigger } from '@pxlkit/ui-kit-core';
import { useAnimationTrigger } from './_internal/animation-trigger.js';

/**
 * Quick horizontal shake, for validation errors and attention cues. It plays
 * as `trigger` says and holds still when the user prefers reduced motion.
 * Attributes fall through to the wrapping `<div>`.
 *
 * @example
 * <PixelShake :trigger="invalid" @complete="invalid = false"><span>Wrong password</span></PixelShake>
 */
export interface PixelShakeProps {
  /** Animation duration in milliseconds. */
  duration?: number;
  /** Horizontal travel distance in pixels. */
  distance?: number;
  /** Iteration count: a number or `'infinite'`. */
  repeat?: AnimationRepeat;
  /** CSS `animation-timing-function`. */
  easing?: string;
  /**
   * When the animation plays: `'mount'`, `'hover'`, `'click'`, `'focus'`,
   * `'inView'`, or `true` / `false` to control it.
   */
  trigger?: AnimationTrigger;
}

const props = withDefaults(defineProps<PixelShakeProps>(), {
  duration: 450,
  distance: 2,
  repeat: 1,
  easing: 'linear',
  trigger: 'mount',
});
const emit = defineEmits<{
  /** After the final iteration. */
  complete: [];
}>();
defineSlots<{
  /** Content to shake. */
  default?(): VNode[];
}>();

const element = useTemplateRef<HTMLElement>('element');
const { active, listeners, ended } = useAnimationTrigger(element, () => props.trigger, () => emit('complete'));
const style = computed(() => (active.value ? shakeStyle(props) : undefined));
</script>

<template>
  <div ref="element" :class="animationInlineClasses" :style="style" v-on="listeners" @animationend="ended">
    <slot />
  </div>
</template>
