// packages/ui-kit-angular/src/lib/animations/pixel-slide-in.ts
import { ChangeDetectionStrategy, Component, computed, input, output, ViewEncapsulation } from '@angular/core';
import {
  slideInStyle,
  type AnimationFillMode,
  type AnimationRepeat,
  type AnimationTrigger,
  type SlideInFrom,
} from '@pxlkit/ui-kit-core';
import { numberOr, withDefault } from '../_internal/coercion';
import { injectAnimationTrigger } from './_internal/animation-trigger';
import { repeatOr } from './_internal/repeat';

/**
 * Slides its content in from one of the four edges. It plays as `trigger`
 * says and shows the content still when the user prefers reduced motion.
 * The host is the sliding wrapper.
 *
 * @example
 * <pxl-slide-in from="left" [distance]="20"><p>Slides in from the left</p></pxl-slide-in>
 */
@Component({
  selector: 'pxl-slide-in',
  changeDetection: ChangeDetectionStrategy.OnPush,
  // The host stands for React's <div>: a block box, which transforms apply
  // to. In the base layer, so display utilities set on it still win.
  encapsulation: ViewEncapsulation.None,
  styles: '@layer base { pxl-slide-in { display: block; } }',
  host: {
    '[style]': 'style()',
    '(animationend)': 'animation.ended($event)',
  },
  template: '<ng-content />',
})
export class PixelSlideIn {
  /** Edge to slide from. */
  readonly from = input<SlideInFrom, SlideInFrom | undefined>('down', { transform: withDefault<SlideInFrom>('down') });
  /** Animation duration in milliseconds. */
  readonly duration = input(350, { transform: numberOr(350) });
  /** Animation delay in milliseconds. */
  readonly delay = input(0, { transform: numberOr(0) });
  /** Translate distance in pixels. */
  readonly distance = input(10, { transform: numberOr(10) });
  /** Iteration count: a number or `'infinite'`. */
  readonly repeat = input<AnimationRepeat, AnimationRepeat | `${number}` | undefined>(1, {
    transform: repeatOr(1),
  });
  /** CSS `animation-timing-function`. */
  readonly easing = input<string, string | undefined>('ease', { transform: withDefault('ease') });
  /** CSS `animation-fill-mode`. */
  readonly fillMode = input<AnimationFillMode, AnimationFillMode | undefined>('both', {
    transform: withDefault<AnimationFillMode>('both'),
  });
  /**
   * When the animation plays: `'mount'`, `'hover'`, `'click'`, `'focus'`,
   * `'inView'`, or `true` / `false` to control it.
   */
  readonly trigger = input<AnimationTrigger, AnimationTrigger | undefined>('mount', {
    transform: withDefault<AnimationTrigger>('mount'),
  });
  /** After the final iteration. */
  readonly complete = output<void>();

  /** @internal */
  protected readonly animation = injectAnimationTrigger(
    () => this.trigger(),
    () => this.complete.emit(),
  );
  /** @internal */
  protected readonly style = computed(() =>
    this.animation.active()
      ? slideInStyle({
          from: this.from(),
          duration: this.duration(),
          delay: this.delay(),
          distance: this.distance(),
          repeat: this.repeat(),
          easing: this.easing(),
          fillMode: this.fillMode(),
        })
      : null,
  );
}

// packages/ui-kit-vue/src/animations/PixelSlideIn.vue
<script setup lang="ts">
import { computed, useTemplateRef, type VNode } from 'vue';
import {
  slideInStyle,
  type AnimationFillMode,
  type AnimationRepeat,
  type AnimationTrigger,
  type SlideInFrom,
} from '@pxlkit/ui-kit-core';
import { useAnimationTrigger } from './_internal/animation-trigger.js';

/**
 * Slides its content in from one of the four edges. It plays as `trigger`
 * says and shows the content still when the user prefers reduced motion.
 * Attributes fall through to the wrapping `<div>`.
 *
 * @example
 * <PixelSlideIn from="left" :distance="20"><p>Slides in from the left</p></PixelSlideIn>
 */
export interface PixelSlideInProps {
  /** Edge to slide from. */
  from?: SlideInFrom;
  /** Animation duration in milliseconds. */
  duration?: number;
  /** Animation delay in milliseconds. */
  delay?: number;
  /** Translate distance in pixels. */
  distance?: number;
  /** Iteration count: a number or `'infinite'`. */
  repeat?: AnimationRepeat;
  /** CSS `animation-timing-function`. */
  easing?: string;
  /** CSS `animation-fill-mode`. */
  fillMode?: AnimationFillMode;
  /**
   * When the animation plays: `'mount'`, `'hover'`, `'click'`, `'focus'`,
   * `'inView'`, or `true` / `false` to control it.
   */
  trigger?: AnimationTrigger;
}

const props = withDefaults(defineProps<PixelSlideInProps>(), {
  from: 'down',
  duration: 350,
  delay: 0,
  distance: 10,
  repeat: 1,
  easing: 'ease',
  fillMode: 'both',
  trigger: 'mount',
});
const emit = defineEmits<{
  /** After the final iteration. */
  complete: [];
}>();
defineSlots<{
  /** Content to slide in. */
  default?(): VNode[];
}>();

const element = useTemplateRef<HTMLElement>('element');
const { active, listeners, ended } = useAnimationTrigger(element, () => props.trigger, () => emit('complete'));
const style = computed(() => (active.value ? slideInStyle(props) : undefined));
</script>

<template>
  <div ref="element" :style="style" v-on="listeners" @animationend="ended">
    <slot />
  </div>
</template>
