// packages/ui-kit/src/animations/PixelBounce.tsx
'use client';

import React, { forwardRef } from 'react';
import { animationInlineClasses, bounceStyle } from '@pxlkit/ui-kit-core';
import { cn } from '../common';
import type { AnimationRepeat, AnimationTrigger } from './types';
import { mergeRefs, useAnimationTrigger } from './_internal/animation-hooks';

/* ─────────────────────────────────────────────────────────────────────────
   PixelBounce — vertical bounce with damped follow-through.
   ───────────────────────────────────────────────────────────────────────── */

export interface PixelBounceProps {
  /** Content to bounce. */
  children: React.ReactNode;
  /** Animation duration in milliseconds. Default `800`. */
  duration?: number;
  /** Iteration count: a number or `'infinite'`. Default `'infinite'`. */
  repeat?: AnimationRepeat;
  /** Peak bounce height in pixels. Default `8`. */
  height?: number;
  /** CSS `animation-timing-function`. Default `'ease'`. */
  easing?: string;
  /** When the animation should play. Default `'mount'`. */
  trigger?: AnimationTrigger;
  /** Fires after the final iteration. */
  onComplete?: () => void;
  /** Extra class names applied to the wrapping `<div>`. */
  className?: string;
}

export const PixelBounce = forwardRef<HTMLDivElement, PixelBounceProps>(function PixelBounce(
  {
    children,
    duration = 800,
    repeat = 'infinite',
    height = 8,
    easing = 'ease',
    trigger = 'mount',
    onComplete,
    className,
  },
  forwardedRef,
) {
  const { ref, active, handlers, handleAnimEnd } = useAnimationTrigger(trigger, onComplete);
  return (
    <div
      ref={mergeRefs(ref, forwardedRef)}
      className={cn(animationInlineClasses, className)}
      style={active ? bounceStyle({ duration, repeat, height, easing }) : undefined}
      {...handlers}
      onAnimationEnd={handleAnimEnd}
    >
      {children}
    </div>
  );
});

PixelBounce.displayName = 'PixelBounce';

// packages/ui-kit-vue/src/animations/PixelBounce.vue
<script setup lang="ts">
import { computed, useTemplateRef, type VNode } from 'vue';
import { animationInlineClasses, bounceStyle, type AnimationRepeat, type AnimationTrigger } from '@pxlkit/ui-kit-core';
import { useAnimationTrigger } from './_internal/animation-trigger.js';

/**
 * Vertical bounce with damped follow-through, for any inline content. It
 * plays as `trigger` says and holds still when the user prefers reduced
 * motion. Attributes fall through to the wrapping `<div>`.
 *
 * @example
 * <PixelBounce trigger="hover" :repeat="1"><span>Hover me</span></PixelBounce>
 */
export interface PixelBounceProps {
  /** Animation duration in milliseconds. */
  duration?: number;
  /** Iteration count: a number or `'infinite'`. */
  repeat?: AnimationRepeat;
  /** Peak bounce height in pixels. */
  height?: number;
  /** CSS `animation-timing-function`. */
  easing?: string;
  /**
   * When the animation plays: `'mount'`, `'hover'`, `'click'`, `'focus'`,
   * `'inView'`, or `true` / `false` to control it.
   */
  trigger?: AnimationTrigger;
}

const props = withDefaults(defineProps<PixelBounceProps>(), {
  duration: 800,
  repeat: 'infinite',
  height: 8,
  easing: 'ease',
  trigger: 'mount',
});
const emit = defineEmits<{
  /** After the final iteration. */
  complete: [];
}>();
defineSlots<{
  /** Content to bounce. */
  default?(): VNode[];
}>();

const element = useTemplateRef<HTMLElement>('element');
const { active, listeners, ended } = useAnimationTrigger(element, () => props.trigger, () => emit('complete'));
const style = computed(() => (active.value ? bounceStyle(props) : undefined));
</script>

<template>
  <div ref="element" :class="animationInlineClasses" :style="style" v-on="listeners" @animationend="ended">
    <slot />
  </div>
</template>
