// packages/ui-kit/src/forms/PixelSegmented.examples.tsx
import { useState } from 'react';
import { PixelSegmented } from './PixelSegmented';

const VIEWS = [
  { value: 'grid', label: 'Grid' },
  { value: 'list', label: 'List' },
  { value: 'kanban', label: 'Kanban' },
];

export function Default() {
  const [value, setValue] = useState('grid');
  return (
    <PixelSegmented
      label="View"
      value={value}
      options={VIEWS}
      onChange={setValue}
    />
  );
}

export function Controlled() {
  const [value, setValue] = useState('list');
  return (
    <div className="space-y-2">
      <PixelSegmented
        label="Active view"
        value={value}
        options={VIEWS}
        onChange={setValue}
        tone="cyan"
      />
      <p className="text-xs text-retro-muted">Picked: {value}</p>
    </div>
  );
}

export function Tones() {
  const [value, setValue] = useState('grid');
  return (
    <div className="grid grid-cols-2 gap-6">
      <PixelSegmented label="Neutral" tone="neutral" value={value} options={VIEWS} onChange={setValue} />
      <PixelSegmented label="Green" tone="green" value={value} options={VIEWS} onChange={setValue} />
      <PixelSegmented label="Cyan" tone="cyan" value={value} options={VIEWS} onChange={setValue} />
      <PixelSegmented label="Gold" tone="gold" value={value} options={VIEWS} onChange={setValue} />
      <PixelSegmented label="Red" tone="red" value={value} options={VIEWS} onChange={setValue} />
      <PixelSegmented label="Purple" tone="purple" value={value} options={VIEWS} onChange={setValue} />
      <PixelSegmented label="Pink" tone="pink" value={value} options={VIEWS} onChange={setValue} />
    </div>
  );
}

export function Surfaces() {
  const [pixel, setPixel] = useState('grid');
  const [linear, setLinear] = useState('grid');
  return (
    <div className="grid grid-cols-2 gap-6">
      <PixelSegmented
        label="Pixel surface"
        surface="pixel"
        value={pixel}
        options={VIEWS}
        onChange={setPixel}
      />
      <PixelSegmented
        label="Linear surface"
        surface="linear"
        value={linear}
        options={VIEWS}
        onChange={setLinear}
      />
    </div>
  );
}

export function Disabled() {
  return (
    <PixelSegmented
      label="View (locked)"
      value="grid"
      options={VIEWS}
      onChange={() => {}}
      disabled
    />
  );
}

export function Required() {
  const [value, setValue] = useState('grid');
  return (
    <PixelSegmented
      label="Choose a view"
      value={value}
      options={VIEWS}
      onChange={setValue}
      required
    />
  );
}

export function WithFormName() {
  const [value, setValue] = useState('grid');
  return (
    <form>
      <PixelSegmented
        label="View"
        name="view"
        value={value}
        options={VIEWS}
        onChange={setValue}
        required
      />
    </form>
  );
}

// packages/ui-kit-angular/examples/forms/pixel-segmented.examples.ts
import { Component, signal } from '@angular/core';
import { PixelSegmented } from '@pxlkit/ui-kit-angular';

const VIEWS = [
  { value: 'grid', label: 'Grid' },
  { value: 'list', label: 'List' },
  { value: 'kanban', label: 'Kanban' },
];

@Component({
  imports: [PixelSegmented],
  template: `<pxl-segmented label="View" [options]="views" [(value)]="value" />`,
})
export class Default {
  readonly views = VIEWS;
  readonly value = signal('grid');
}

@Component({
  imports: [PixelSegmented],
  template: `
    <div class="space-y-2">
      <pxl-segmented label="Active view" [options]="views" [(value)]="value" tone="cyan" />
      <p class="text-xs text-retro-muted">Picked: {{ value() }}</p>
    </div>
  `,
})
export class Controlled {
  readonly views = VIEWS;
  readonly value = signal('list');
}

@Component({
  imports: [PixelSegmented],
  template: `
    <div class="grid grid-cols-1 sm:grid-cols-2 gap-6">
      <pxl-segmented label="Neutral" tone="neutral" [options]="views" [(value)]="value" />
      <pxl-segmented label="Green" tone="green" [options]="views" [(value)]="value" />
      <pxl-segmented label="Cyan" tone="cyan" [options]="views" [(value)]="value" />
      <pxl-segmented label="Gold" tone="gold" [options]="views" [(value)]="value" />
      <pxl-segmented label="Red" tone="red" [options]="views" [(value)]="value" />
      <pxl-segmented label="Purple" tone="purple" [options]="views" [(value)]="value" />
      <pxl-segmented label="Pink" tone="pink" [options]="views" [(value)]="value" />
    </div>
  `,
})
export class Tones {
  readonly views = VIEWS;
  readonly value = signal('grid');
}

@Component({
  imports: [PixelSegmented],
  template: `
    <div class="grid grid-cols-1 sm:grid-cols-2 gap-6">
      <pxl-segmented label="Pixel surface" surface="pixel" [options]="views" [(value)]="pixel" />
      <pxl-segmented label="Linear surface" surface="linear" [options]="views" [(value)]="linear" />
    </div>
  `,
})
export class Surfaces {
  readonly views = VIEWS;
  readonly pixel = signal('grid');
  readonly linear = signal('grid');
}

@Component({
  imports: [PixelSegmented],
  template: `<pxl-segmented label="View (locked)" value="grid" [options]="views" disabled />`,
})
export class Disabled {
  readonly views = VIEWS;
}

@Component({
  imports: [PixelSegmented],
  template: `<pxl-segmented label="Choose a view" [options]="views" [(value)]="value" required />`,
})
export class Required {
  readonly views = VIEWS;
  readonly value = signal('grid');
}

@Component({
  imports: [PixelSegmented],
  template: `
    <form>
      <pxl-segmented label="View" name="view" [options]="views" [(value)]="value" required />
    </form>
  `,
})
export class WithFormName {
  readonly views = VIEWS;
  readonly value = signal('grid');
}
