// packages/ui-kit/src/forms/PixelColorInput.examples.tsx
import React, { useState } from 'react';
import { PixelColorInput } from './PixelColorInput';

export function Default() {
  const [value, setValue] = useState<string>('#06b6d4');
  return (
    <PixelColorInput
      label="Brand color"
      value={value}
      onChange={setValue}
    />
  );
}

export function RgbFormat() {
  const [value, setValue] = useState<string>('rgb(34, 197, 94)');
  return (
    <PixelColorInput
      label="Accent color"
      format="rgb"
      value={value}
      onChange={setValue}
      hint="Stored as rgb()"
    />
  );
}

export function CustomPresets() {
  const [value, setValue] = useState<string>('#ef4444');
  return (
    <PixelColorInput
      label="Theme tone"
      presets={['#ef4444', '#f97316', '#eab308', '#22c55e', '#06b6d4', '#a855f7']}
      value={value}
      onChange={setValue}
    />
  );
}

export function WithError() {
  return (
    <PixelColorInput
      label="Background"
      defaultValue="not-a-color"
      error="Invalid color value"
    />
  );
}

// packages/ui-kit-angular/examples/forms/pixel-color-input.examples.ts
import { Component, signal } from '@angular/core';
import { PixelColorInput } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelColorInput],
  template: `<pxl-color-input label="Brand color" [(value)]="value" />`,
})
export class Default {
  readonly value = signal('#06b6d4');
}

@Component({
  imports: [PixelColorInput],
  template: `<pxl-color-input label="Accent color" format="rgb" hint="Stored as rgb()" [(value)]="value" />`,
})
export class RgbFormat {
  readonly value = signal('rgb(34, 197, 94)');
}

@Component({
  imports: [PixelColorInput],
  template: `<pxl-color-input label="Theme tone" [presets]="presets" [(value)]="value" />`,
})
export class CustomPresets {
  readonly presets = ['#ef4444', '#f97316', '#eab308', '#22c55e', '#06b6d4', '#a855f7'];
  readonly value = signal('#ef4444');
}

@Component({
  imports: [PixelColorInput],
  template: `<pxl-color-input label="Background" defaultValue="not-a-color" error="Invalid color value" />`,
})
export class WithError {}
