// packages/ui-kit/src/forms/PixelCalendarGrid.examples.tsx
import React, { useState } from 'react'
import { PixelCalendarGrid } from './PixelCalendarGrid'

export function Default() {
  const [value, setValue] = useState<Date | null>(null)
  return <PixelCalendarGrid value={value} onChange={setValue} />
}

export function WithSelectedDate() {
  const [value, setValue] = useState<Date | null>(new Date())
  return <PixelCalendarGrid value={value} onChange={setValue} />
}

export function WithMinMax() {
  const today = new Date()
  const min = new Date(today.getFullYear(), today.getMonth(), 1)
  const max = new Date(today.getFullYear(), today.getMonth() + 1, 0)
  const [value, setValue] = useState<Date | null>(null)
  return (
    <PixelCalendarGrid
      value={value}
      onChange={setValue}
      minDate={min}
      maxDate={max}
    />
  )
}

export function WithDisabledWeekends() {
  const [value, setValue] = useState<Date | null>(null)
  return (
    <PixelCalendarGrid
      value={value}
      onChange={setValue}
      disabledDates={(d) => d.getDay() === 0 || d.getDay() === 6}
    />
  )
}

export function RangePreview() {
  const from = new Date()
  const to = new Date(from.getFullYear(), from.getMonth(), from.getDate() + 5)
  return <PixelCalendarGrid rangePreview={{ from, to }} />
}

// packages/ui-kit-angular/examples/forms/pixel-calendar-grid.examples.ts
import { Component, signal } from '@angular/core';
import { PixelCalendarGrid } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelCalendarGrid],
  template: `<pxl-calendar-grid [(value)]="value" />`,
})
export class Default {
  readonly value = signal<Date | null>(null);
}

@Component({
  imports: [PixelCalendarGrid],
  template: `<pxl-calendar-grid [(value)]="value" />`,
})
export class WithSelectedDate {
  readonly value = signal<Date | null>(new Date());
}

@Component({
  imports: [PixelCalendarGrid],
  template: `<pxl-calendar-grid [(value)]="value" [minDate]="min" [maxDate]="max" />`,
})
export class WithMinMax {
  private readonly today = new Date();
  readonly min = new Date(this.today.getFullYear(), this.today.getMonth(), 1);
  readonly max = new Date(this.today.getFullYear(), this.today.getMonth() + 1, 0);
  readonly value = signal<Date | null>(null);
}

@Component({
  imports: [PixelCalendarGrid],
  template: `<pxl-calendar-grid [(value)]="value" [disabledDates]="isWeekend" />`,
})
export class WithDisabledWeekends {
  readonly value = signal<Date | null>(null);
  readonly isWeekend = (date: Date) => date.getDay() === 0 || date.getDay() === 6;
}

@Component({
  imports: [PixelCalendarGrid],
  template: `<pxl-calendar-grid [rangePreview]="{ from, to }" />`,
})
export class RangePreview {
  readonly from = new Date();
  readonly to = new Date(this.from.getFullYear(), this.from.getMonth(), this.from.getDate() + 5);
}
