// packages/ui-kit-vue/src/navigation/_internal/SidebarItem.vue
<script setup lang="ts">
import { computed } from 'vue';
import {
  sidebarBadgeClasses,
  sidebarItemClasses,
  sidebarItemIconClasses,
  sidebarItemLabelClasses,
  sidebarNestedListClasses,
  type Surface,
} from '@pxlkit/ui-kit-core';
import { RenderNode } from '../../_internal/render-node.js';
import type { PixelSidebarItemProps } from '../PixelSidebar.vue';

/**
 * One item of a `PixelSidebar` in its `<li>`: a link with an `href`, a button
 * otherwise, and the items nested under it. Collapsed, the label is visually
 * hidden and names the item through `aria-label` and `title`.
 */
const props = defineProps<{
  item: PixelSidebarItemProps;
  surface: Surface;
  collapsed: boolean;
  /** 0 for the items of a section. */
  depth: number;
}>();

const classes = computed(() =>
  sidebarItemClasses(props.surface, { depth: props.depth, active: !!props.item.active, collapsed: props.collapsed }),
);
const name = computed(() => (props.collapsed ? props.item.label : undefined));
</script>

<template>
  <li>
    <component
      :is="item.href ? 'a' : 'button'"
      v-bind="item.href ? { href: item.href } : { type: 'button' }"
      :aria-current="item.active ? 'page' : undefined"
      :aria-label="name"
      :title="name"
      :class="classes"
      @click="!item.href && item.onSelect?.()"
    >
      <span v-if="item.icon" aria-hidden="true" :class="sidebarItemIconClasses"><RenderNode :node="item.icon" /></span>
      <span :class="sidebarItemLabelClasses(collapsed)">{{ item.label }}</span>
      <span v-if="item.badge && !collapsed" :class="sidebarBadgeClasses(surface, item.badge.tone)">{{ item.badge.label }}</span>
    </component>
    <ul v-if="item.nested?.length && !collapsed" :class="sidebarNestedListClasses">
      <SidebarItem
        v-for="child in item.nested"
        :key="child.id"
        :item="child"
        :surface="surface"
        :collapsed="collapsed"
        :depth="depth + 1"
      />
    </ul>
  </li>
</template>

// packages/ui-kit-angular/src/lib/navigation/_internal/sidebar-item.ts
import { NgTemplateOutlet } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import {
  sidebarBadgeClasses,
  sidebarItemClasses,
  sidebarItemIconClasses,
  sidebarItemLabelClasses,
  sidebarNestedListClasses,
  type Surface,
  type ToneKey,
} from '@pxlkit/ui-kit-core';
import { PxlOutlet } from '../../_internal/outlet';
import type { PixelSidebarItemProps } from '../pixel-sidebar';

/**
 * One item of a `<pxl-sidebar>` on its `<li>`: a link with an `href`, a
 * button otherwise, and the items nested under it. Collapsed, the label is
 * visually hidden and names the item through `aria-label` and `title`.
 */
@Component({
  selector: 'li[pxlSidebarItem]',
  imports: [NgTemplateOutlet, PxlOutlet],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @let entry = pxlSidebarItem();
    @if (entry.href) {
      <a
        [attr.href]="entry.href"
        [attr.aria-current]="entry.active ? 'page' : null"
        [attr.aria-label]="name()"
        [attr.title]="name()"
        [class]="classes()"
      ><ng-container [ngTemplateOutlet]="content" /></a>
    } @else {
      <button
        type="button"
        [attr.aria-current]="entry.active ? 'page' : null"
        [attr.aria-label]="name()"
        [attr.title]="name()"
        [class]="classes()"
        (click)="entry.onSelect?.()"
      ><ng-container [ngTemplateOutlet]="content" /></button>
    }
    <ng-template #content>
      @if (entry.icon) {
        <span aria-hidden="true" [class]="iconClasses">
          <ng-container *pxlOutlet="entry.icon; let text">{{ text }}</ng-container>
        </span>
      }
      <span [class]="labelClasses()">{{ entry.label }}</span>
      @if (entry.badge && !collapsed()) {
        <span [class]="badgeClasses(entry.badge.tone)">{{ entry.badge.label }}</span>
      }
    </ng-template>
    @if (entry.nested?.length && !collapsed()) {
      <ul [class]="nestedListClasses">
        @for (child of entry.nested; track child.id) {
          <li [pxlSidebarItem]="child" [surface]="surface()" [collapsed]="collapsed()" [depth]="depth() + 1"></li>
        }
      </ul>
    }
  `,
})
export class PixelSidebarItem {
  readonly pxlSidebarItem = input.required<PixelSidebarItemProps>();
  readonly surface = input.required<Surface>();
  readonly collapsed = input.required<boolean>();
  /** 0 for the items of a section. */
  readonly depth = input.required<number>();

  /** @internal */
  protected readonly classes = computed(() =>
    sidebarItemClasses(this.surface(), {
      depth: this.depth(),
      active: !!this.pxlSidebarItem().active,
      collapsed: this.collapsed(),
    }),
  );
  /** @internal Collapsed, the label names the item. */
  protected readonly name = computed(() => (this.collapsed() ? this.pxlSidebarItem().label : null));
  /** @internal */
  protected readonly labelClasses = computed(() => sidebarItemLabelClasses(this.collapsed()));
  /** @internal */
  protected readonly iconClasses = sidebarItemIconClasses;
  /** @internal */
  protected readonly nestedListClasses = sidebarNestedListClasses;

  /** @internal */
  protected badgeClasses(tone: ToneKey | undefined): string {
    return sidebarBadgeClasses(this.surface(), tone);
  }
}
