// packages/ui-kit/src/animations/PixelPulse.examples.tsx
import { PixelPulse } from './PixelPulse';

export function Default() {
  return (
    <PixelPulse>
      <span>Pulse</span>
    </PixelPulse>
  );
}

export function FasterPulse() {
  return (
    <PixelPulse duration={1000}>
      <span>Quick Pulse</span>
    </PixelPulse>
  );
}

export function HoverTrigger() {
  return (
    <PixelPulse trigger="hover" repeat={1}>
      <span>Hover me</span>
    </PixelPulse>
  );
}

// packages/ui-kit-angular/examples/animations/pixel-pulse.examples.ts
import { Component } from '@angular/core';
import { PixelPulse } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelPulse],
  template: `
    <pxl-pulse>
      <span>Pulse</span>
    </pxl-pulse>
  `,
})
export class Default {}

@Component({
  imports: [PixelPulse],
  template: `
    <pxl-pulse [duration]="1000">
      <span>Quick Pulse</span>
    </pxl-pulse>
  `,
})
export class FasterPulse {}

@Component({
  imports: [PixelPulse],
  template: `
    <pxl-pulse trigger="hover" [repeat]="1">
      <span>Hover me</span>
    </pxl-pulse>
  `,
})
export class HoverTrigger {}
