// packages/ui-kit/src/animations/PixelGlitch.examples.tsx
import { PixelGlitch } from './PixelGlitch';

export function Default() {
  return (
    <PixelGlitch>
      <span className="text-2xl font-bold">SYSTEM ONLINE</span>
    </PixelGlitch>
  );
}

export function HighIntensity() {
  return (
    <PixelGlitch intensity={8} duration={2000}>
      <span className="text-2xl font-bold">CRITICAL ERROR</span>
    </PixelGlitch>
  );
}

export function HoverTrigger() {
  return (
    <PixelGlitch trigger="hover">
      <span className="text-2xl font-bold">HOVER ME</span>
    </PixelGlitch>
  );
}

export function HeadingLabel() {
  return (
    <h2 className="text-2xl font-bold">
      <PixelGlitch as="span" label="SIGNAL LOST" />
    </h2>
  );
}

// packages/ui-kit-angular/examples/animations/pixel-glitch.examples.ts
import { Component } from '@angular/core';
import { PixelGlitch, PixelGlitchContent } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelGlitch, PixelGlitchContent],
  template: `
    <pxl-glitch>
      <span *pxlGlitchContent class="text-2xl font-bold">SYSTEM ONLINE</span>
    </pxl-glitch>
  `,
})
export class Default {}

@Component({
  imports: [PixelGlitch, PixelGlitchContent],
  template: `
    <pxl-glitch [intensity]="8" [duration]="2000">
      <span *pxlGlitchContent class="text-2xl font-bold">CRITICAL ERROR</span>
    </pxl-glitch>
  `,
})
export class HighIntensity {}

@Component({
  imports: [PixelGlitch, PixelGlitchContent],
  template: `
    <pxl-glitch trigger="hover">
      <span *pxlGlitchContent class="text-2xl font-bold">HOVER ME</span>
    </pxl-glitch>
  `,
})
export class HoverTrigger {}

@Component({
  imports: [PixelGlitch],
  template: `
    <h2 class="text-2xl font-bold">
      <span pxlGlitch label="SIGNAL LOST"></span>
    </h2>
  `,
})
export class HeadingLabel {}
