// packages/ui-kit/src/animations/PixelZoomIn.examples.tsx
import { PixelZoomIn } from './PixelZoomIn';

export function Default() {
  return (
    <PixelZoomIn>
      <div style={{ padding: 16, background: '#0EA5E9', color: '#fff', borderRadius: 8 }}>
        Zoom in content
      </div>
    </PixelZoomIn>
  );
}

export function CustomStartScale() {
  return (
    <PixelZoomIn startScale={0.6} duration={500}>
      <div style={{ padding: 16, background: '#A855F7', color: '#fff', borderRadius: 8 }}>
        Bigger zoom from 0.6
      </div>
    </PixelZoomIn>
  );
}

export function HoverTrigger() {
  return (
    <PixelZoomIn trigger="hover" repeat="infinite" duration={600}>
      <button style={{ padding: 12, background: '#111', color: '#fff', borderRadius: 6 }}>
        Hover me
      </button>
    </PixelZoomIn>
  );
}

// packages/ui-kit-angular/examples/animations/pixel-zoom-in.examples.ts
import { Component } from '@angular/core';
import { PixelZoomIn } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelZoomIn],
  template: `
    <pxl-zoom-in>
      <div style="padding: 16px; background: #0EA5E9; color: #fff; border-radius: 8px">Zoom in content</div>
    </pxl-zoom-in>
  `,
})
export class Default {}

@Component({
  imports: [PixelZoomIn],
  template: `
    <pxl-zoom-in [startScale]="0.6" [duration]="500">
      <div style="padding: 16px; background: #A855F7; color: #fff; border-radius: 8px">Bigger zoom from 0.6</div>
    </pxl-zoom-in>
  `,
})
export class CustomStartScale {}

@Component({
  imports: [PixelZoomIn],
  template: `
    <pxl-zoom-in trigger="hover" repeat="infinite" [duration]="600">
      <button style="padding: 12px; background: #111; color: #fff; border-radius: 6px">Hover me</button>
    </pxl-zoom-in>
  `,
})
export class HoverTrigger {}
