// packages/ui-kit-vue/src/layout/PixelBento.vue
<script setup lang="ts">
import { computed, type VNode } from 'vue';
import { BENTO_AUTO_ROWS, bentoClasses, type BentoColumns, type StackGapKey } from '@pxlkit/ui-kit-core';

/**
 * Responsive bento grid for `PixelBentoCell`s: cells stack on phones and the
 * full column count applies from `lg`; rows are at least 160px tall.
 */
export interface PixelBentoProps {
  /** Column count from `lg` up. */
  columns?: BentoColumns;
  /** Gap token (`stackGap`). */
  gap?: StackGapKey;
}

const props = withDefaults(defineProps<PixelBentoProps>(), { columns: 3, gap: 4 });
defineSlots<{ default?(): VNode[] }>();

const classes = computed(() => bentoClasses(props.columns, props.gap));
</script>

<template>
  <div :data-columns="columns" :class="classes" :style="{ gridAutoRows: BENTO_AUTO_ROWS }"><slot /></div>
</template>

// packages/ui-kit-angular/src/lib/layout/pixel-bento.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { BENTO_AUTO_ROWS, bentoClasses, type BentoColumns, type StackGapKey } from '@pxlkit/ui-kit-core';

/**
 * Responsive bento grid for `<pxl-bento-cell>`s: cells stack on phones and
 * the full column count applies from `lg`; rows are at least 160px tall.
 *
 * @example
 * <pxl-bento [columns]="4" [gap]="3">
 *   <pxl-bento-cell span="2x2" variant="feature">…</pxl-bento-cell>
 * </pxl-bento>
 */
@Component({
  selector: 'pxl-bento',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'classes()',
    '[attr.data-columns]': 'columns()',
    // A default the element's own style overrides, as in React.
    style: `grid-auto-rows: ${BENTO_AUTO_ROWS}`,
  },
  template: '<ng-content />',
})
export class PixelBento {
  /** Column count from `lg` up. */
  readonly columns = input<BentoColumns, BentoColumns | `${BentoColumns}` | undefined>(3, {
    transform: (value) => (value === undefined ? 3 : (Number(value) as BentoColumns)),
  });
  /** Gap token (`stackGap`). */
  readonly gap = input<StackGapKey, StackGapKey | `${StackGapKey}` | undefined>(4, {
    transform: (value) => (value === undefined ? 4 : (Number(value) as StackGapKey)),
  });

  /** @internal */
  protected readonly classes = computed(() => bentoClasses(this.columns(), this.gap()));
}
