// packages/ui-kit-vue/src/layout/PixelContainer.vue
<script setup lang="ts">
import { computed, type VNode } from 'vue';
import {
  containerClasses,
  resolveContainerPadding,
  type ContainerElement,
  type ContainerPadding,
  type ContainerWidth,
  type Surface,
} from '@pxlkit/ui-kit-core';
import { useEffectiveSurface } from '../composables/surface.js';
import PixelCenter from './PixelCenter.vue';

/**
 * Full-width page band: vertical rhythm around a centred, width-capped
 * column (a `PixelCenter`) that holds the content.
 */
export interface PixelContainerProps {
  /** Width cap of the inner column (`containerWidth`). */
  maxWidth?: ContainerWidth;
  /**
   * Vertical rhythm (`sectionRhythm`), or `{ x, y }`: the gutter of the inner
   * column (`pageGutter`) and the rhythm. Both default to `lg`.
   */
  padding?: ContainerPadding;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
  /** Element to render — a landmark wants an `aria-label` or `aria-labelledby`. */
  as?: ContainerElement;
}

const props = withDefaults(defineProps<PixelContainerProps>(), {
  maxWidth: 'xl',
  padding: undefined,
  surface: undefined,
  as: 'section',
});
defineSlots<{ default?(): VNode[] }>();

const surface = useEffectiveSurface(() => props.surface);
const padding = computed(() => resolveContainerPadding(props.padding));
const classes = computed(() => containerClasses(surface.value, padding.value.y));
</script>

<template>
  <component :is="as" :class="classes">
    <PixelCenter :max-width="maxWidth" :gutter="padding.x" :surface="surface"><slot /></PixelCenter>
  </component>
</template>

// packages/ui-kit-angular/src/lib/layout/pixel-container.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import {
  containerClasses,
  resolveContainerPadding,
  type ContainerPadding,
  type ContainerWidth,
  type Surface,
} from '@pxlkit/ui-kit-core';
import { withDefault } from '../_internal/coercion';
import { injectEffectiveSurface } from '../overlay-foundation/pxl-kit-surface-provider';
import { PixelCenter } from './pixel-center';

/**
 * Full-width page band: vertical rhythm around a centred, width-capped
 * column (a `pxlCenter`) that holds the content. Put it on the element you
 * need — the React kit renders a `<section>` unless told otherwise; a
 * landmark wants an `aria-label` or `aria-labelledby`.
 *
 * @example
 * <section pxlContainer maxWidth="md" padding="md">…</section>
 * <main pxlContainer aria-label="Page content" [padding]="{ x: 'lg', y: 'xl' }">…</main>
 */
@Component({
  selector: '[pxlContainer]',
  imports: [PixelCenter],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { '[class]': 'classes()' },
  template: `
    <div pxlCenter [maxWidth]="maxWidth()" [gutter]="resolvedPadding().x" [surface]="effectiveSurface()">
      <ng-content />
    </div>
  `,
})
export class PixelContainer {
  /** Width cap of the inner column (`containerWidth`). */
  readonly maxWidth = input<ContainerWidth, ContainerWidth | undefined>('xl', {
    transform: withDefault<ContainerWidth>('xl'),
  });
  /**
   * Vertical rhythm (`sectionRhythm`), or `{ x, y }`: the gutter of the inner
   * column (`pageGutter`) and the rhythm. Both default to `lg`.
   */
  readonly padding = input<ContainerPadding>();
  /** Surface override; defaults to the nearest provider. */
  readonly surface = input<Surface>();

  /** @internal */
  protected readonly effectiveSurface = injectEffectiveSurface(() => this.surface());
  /** @internal */
  protected readonly resolvedPadding = computed(() => resolveContainerPadding(this.padding()));

  /** @internal */
  protected readonly classes = computed(() => containerClasses(this.effectiveSurface(), this.resolvedPadding().y));
}
