// packages/ui-kit/src/overlays/PixelCommand.examples.tsx
import { useState } from 'react';
import { PixelCommand } from './PixelCommand';

export function Default() {
  const [open, setOpen] = useState(false);
  return (
    <>
      <button type="button" onClick={() => setOpen(true)}>
        Open command palette
      </button>
      <PixelCommand
        open={open}
        onOpenChange={setOpen}
        groups={[
          {
            heading: 'Actions',
            items: [
              {
                id: 'new-file',
                label: 'New file',
                shortcut: 'Ctrl+N',
                onSelect: () => setOpen(false),
              },
              {
                id: 'open-file',
                label: 'Open file…',
                shortcut: 'Ctrl+O',
                onSelect: () => setOpen(false),
              },
              {
                id: 'save',
                label: 'Save',
                shortcut: 'Ctrl+S',
                onSelect: () => setOpen(false),
              },
            ],
          },
          {
            heading: 'Navigation',
            items: [
              {
                id: 'go-home',
                label: 'Go to home',
                keywords: ['dashboard', 'start'],
                onSelect: () => setOpen(false),
              },
              {
                id: 'go-settings',
                label: 'Go to settings',
                keywords: ['preferences', 'config'],
                onSelect: () => setOpen(false),
              },
            ],
          },
        ]}
      />
    </>
  );
}

export function WithCustomShortcut() {
  const [open, setOpen] = useState(false);
  return (
    <>
      <button type="button" onClick={() => setOpen(true)}>
        Open (or press Ctrl+Shift+P)
      </button>
      <PixelCommand
        open={open}
        onOpenChange={setOpen}
        shortcut="mod+shift+p"
        placeholder="Run a command…"
        groups={[
          {
            heading: 'Commands',
            items: [
              {
                id: 'reload',
                label: 'Reload window',
                onSelect: () => setOpen(false),
              },
              {
                id: 'toggle-theme',
                label: 'Toggle theme',
                onSelect: () => setOpen(false),
              },
            ],
          },
        ]}
      />
    </>
  );
}

export function LinearSurface() {
  const [open, setOpen] = useState(false);
  return (
    <>
      <button type="button" onClick={() => setOpen(true)}>
        Open linear palette
      </button>
      <PixelCommand
        open={open}
        onOpenChange={setOpen}
        surface="linear"
        emptyMessage="Nothing matches your search."
        groups={[
          {
            heading: 'Recent',
            items: [
              {
                id: 'doc-1',
                label: 'Project roadmap',
                onSelect: () => setOpen(false),
              },
              {
                id: 'doc-2',
                label: 'Sprint notes',
                onSelect: () => setOpen(false),
              },
            ],
          },
        ]}
      />
    </>
  );
}

// packages/ui-kit-angular/examples/overlays/pixel-command.examples.ts
import { Component, signal } from '@angular/core';
import { PixelCommand, type PixelCommandGroup } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelCommand],
  template: `
    <button type="button" (click)="open.set(true)">Open command palette</button>
    <pxl-command [(open)]="open" [groups]="groups" />
  `,
})
export class Default {
  readonly open = signal(false);
  readonly groups: PixelCommandGroup[] = [
    {
      heading: 'Actions',
      items: [
        { id: 'new-file', label: 'New file', shortcut: 'Ctrl+N', onSelect: () => this.open.set(false) },
        { id: 'open-file', label: 'Open file…', shortcut: 'Ctrl+O', onSelect: () => this.open.set(false) },
        { id: 'save', label: 'Save', shortcut: 'Ctrl+S', onSelect: () => this.open.set(false) },
      ],
    },
    {
      heading: 'Navigation',
      items: [
        { id: 'go-home', label: 'Go to home', keywords: ['dashboard', 'start'], onSelect: () => this.open.set(false) },
        {
          id: 'go-settings',
          label: 'Go to settings',
          keywords: ['preferences', 'config'],
          onSelect: () => this.open.set(false),
        },
      ],
    },
  ];
}

@Component({
  imports: [PixelCommand],
  template: `
    <button type="button" (click)="open.set(true)">Open (or press Ctrl+Shift+P)</button>
    <pxl-command [(open)]="open" shortcut="mod+shift+p" placeholder="Run a command…" [groups]="groups" />
  `,
})
export class WithCustomShortcut {
  readonly open = signal(false);
  readonly groups: PixelCommandGroup[] = [
    {
      heading: 'Commands',
      items: [
        { id: 'reload', label: 'Reload window', onSelect: () => this.open.set(false) },
        { id: 'toggle-theme', label: 'Toggle theme', onSelect: () => this.open.set(false) },
      ],
    },
  ];
}

@Component({
  imports: [PixelCommand],
  template: `
    <button type="button" (click)="open.set(true)">Open linear palette</button>
    <pxl-command [(open)]="open" surface="linear" emptyMessage="Nothing matches your search." [groups]="groups" />
  `,
})
export class LinearSurface {
  readonly open = signal(false);
  readonly groups: PixelCommandGroup[] = [
    {
      heading: 'Recent',
      items: [
        { id: 'doc-1', label: 'Project roadmap', onSelect: () => this.open.set(false) },
        { id: 'doc-2', label: 'Sprint notes', onSelect: () => this.open.set(false) },
      ],
    },
  ];
}
