// packages/ui-kit/src/overlay-foundation/PixelPortal.examples.tsx
import React from 'react'
import { PixelPortal } from './PixelPortal'

export function Default() {
  return (
    <PixelPortal>
      <div>Portaled content (renders into document.body after mount)</div>
    </PixelPortal>
  )
}

export function Disabled() {
  return (
    <PixelPortal disabled>
      <div>Rendered inline — portal disabled</div>
    </PixelPortal>
  )
}

// packages/ui-kit-angular/examples/overlay-foundation/pixel-portal.examples.ts
import { Component } from '@angular/core';
import { PixelPortal } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelPortal],
  template: `<div *pxlPortal>Portaled content (renders into document.body after mount)</div>`,
})
export class Default {}

@Component({
  imports: [PixelPortal],
  template: `
    <ng-template pxlPortal pxlPortalDisabled>
      <div>Rendered inline — portal disabled</div>
    </ng-template>
  `,
})
export class Disabled {}
