// packages/ui-kit-vue/src/actions/PixelButton.vue
<script setup lang="ts">
import { computed, ref, useTemplateRef, watch, type VNode } from 'vue';
import {
  cn,
  cornerShadowClasses,
  focusRing,
  sizeClass,
  surfaceClasses,
  toneMap,
  type Size,
  type Surface,
  type Tone,
  type Variant,
} from '@pxlkit/ui-kit-core';
import { useEffectiveSurface } from '../composables/surface.js';
import { Slot, singleElementChild } from '../_internal/Slot.js';

/**
 * Versatile button with tones, sizes, icon slots, loading state, variants
 * (`solid` | `soft` | `outline` | `ghost`), surface aesthetic and an
 * `asChild` mode that styles a single child element (e.g. a router link).
 * Every other attribute and listener falls through to the `<button>`.
 */
export interface PixelButtonProps {
  /** Color tone (maps to `toneMap`). */
  tone?: Tone;
  /** Visual size. */
  size?: Size;
  /** `solid` | `soft` | `outline` | `ghost`. */
  variant?: Variant;
  /** Surface aesthetic override; defaults to the nearest provider. */
  surface?: Surface;
  /** Swaps the left icon for a spinner and disables the button. */
  loading?: boolean;
  /** Stretch to fill the parent's inline axis (`w-full`). */
  fullWidth?: boolean;
  /**
   * Render the single element of the default slot as the root instead of a
   * `<button>`; it receives the button classes and every attribute and
   * listener. Useful for `<a>` / `<RouterLink>` wrappers.
   */
  asChild?: boolean;
  /** Native `disabled`. */
  disabled?: boolean;
}

const props = withDefaults(defineProps<PixelButtonProps>(), {
  tone: 'green',
  size: 'md',
  variant: 'solid',
  surface: undefined,
  loading: false,
  fullWidth: false,
  asChild: false,
  disabled: false,
});

defineSlots<{
  /** Button label. */
  default?(): VNode[];
  /** Leading icon; replaced by a spinner while `loading`. */
  'icon-left'?(): VNode[];
  /** Trailing icon. */
  'icon-right'?(): VNode[];
}>();

const surface = useEffectiveSurface(() => props.surface);

const classes = computed(() => {
  const s = surfaceClasses(surface.value);
  // No drop shadow on pixel, whose cut corners clip it: the nudge and press alone.
  const c = cornerShadowClasses(surface.value);
  const t = toneMap[props.tone];
  const isGhost = props.variant === 'ghost';
  const isOutline = props.variant === 'outline';
  const isSoft = props.variant === 'soft';
  // Hover and press feedback only while the button can be pressed: a disabled
  // or loading one holds still, and a disabled one drops its shadow too.
  const enabled = !props.disabled;
  const moves = enabled && !props.loading;

  const variantClasses = isGhost
    ? cn('border border-transparent bg-transparent', t.hover)
    : isOutline
      ? cn(s.border, t.border, 'bg-transparent', t.hover, enabled && c.shadow, moves && c.shadowHover)
      : isSoft
        ? cn(s.border, t.border, t.soft, t.hover, enabled && c.shadow, moves && c.shadowHover)
        : cn(s.border, t.border, t.bg, t.hover, enabled && c.shadow, moves && c.shadowHover);

  return cn(
    'inline-flex items-center justify-center font-medium focus-visible:outline-hidden disabled:opacity-50 disabled:cursor-not-allowed',
    s.font,
    s.radius,
    s.transition,
    sizeClass[props.size],
    focusRing,
    t.ring,
    t.text,
    props.fullWidth && 'w-full',
    variantClasses,
    moves && (isGhost || isOutline ? 'active:scale-[0.97]' : c.shadowActive),
  );
});

// Pin min-width to the width measured as loading starts, so the button does
// not collapse while the spinner replaces the leading icon.
const button = useTemplateRef<HTMLButtonElement>('button');
const minWidth = ref<number | null>(null);
watch(
  () => props.loading,
  (loading, wasLoading) => {
    if (!wasLoading && loading && button.value) {
      minWidth.value = button.value.getBoundingClientRect().width;
    }
    if (!loading) minWidth.value = null;
  },
  { flush: 'post' },
);
</script>

<template>
  <Slot v-if="asChild && singleElementChild($slots.default?.())" :class="classes">
    <slot />
  </Slot>
  <button
    v-else
    ref="button"
    :class="classes"
    :style="minWidth !== null ? { minWidth: `${minWidth}px` } : undefined"
    :disabled="loading || disabled"
  >
    <span
      v-if="loading"
      data-testid="pxl-button-spinner"
      aria-hidden="true"
      class="inline-block h-3.5 w-3.5 motion-safe:animate-spin rounded-full border-2 border-current border-r-transparent"
    />
    <slot v-else name="icon-left" />
    <span><slot /></span>
    <slot name="icon-right" />
  </button>
</template>

// packages/ui-kit/src/actions/PixelButton.tsx
import React, { forwardRef, useRef, useState } from 'react';
import { cornerShadowClasses } from '@pxlkit/ui-kit-core';
import { useIsomorphicLayoutEffect } from '../hooks/useIsomorphicLayoutEffect';
import {
  Tone, Size, Surface, Variant, cn,
  toneMap, sizeClass, focusRing, surfaceClasses, useEffectiveSurface,
} from '../common';
import { elementRef } from '../utils/element-ref';

/* ─────────────────────────────────────────────────────────────────────────
   PixelButton — versatile button with tones, sizes, icon slots, loading,
   variants (solid | soft | outline | ghost), surface aesthetic, asChild slot.
   ───────────────────────────────────────────────────────────────────────── */

/**
 * Public prop bag for {@link PixelButton}. Extends every native
 * `<button>` attribute, so consumers can pass `name`, `form`,
 * `formAction`, `type`, `aria-*` etc. without ceremony.
 */
export interface PixelButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  /** Color tone (maps to `toneMap`). */
  tone?: Tone;
  /** Visual size. */
  size?: Size;
  /** Full Variant union — `solid` | `soft` | `outline` | `ghost`. */
  variant?: Variant;
  /** Surface aesthetic override; defaults to nearest provider. */
  surface?: Surface;
  /** Leading icon node; replaced by a spinner while `loading` is true. */
  iconLeft?: React.ReactNode;
  /** Trailing icon node. */
  iconRight?: React.ReactNode;
  /** When true, swaps the left icon for a spinner and force-disables the button. */
  loading?: boolean;
  /** Stretch to fill the parent's inline axis (`w-full`). */
  fullWidth?: boolean;
  /**
   * Render the children as the root element (Radix Slot pattern). Expects a
   * SINGLE React element child; receives merged className, ref, and onClick.
   * Useful for `<Link>` / `<a>` wrappers without sacrificing the styling.
   */
  asChild?: boolean;
}

function mergeRefs<T>(...refs: Array<React.Ref<T> | undefined | null>): React.RefCallback<T> {
  return (node) => {
    refs.forEach((r) => {
      if (!r) return;
      if (typeof r === 'function') r(node);
      else (r as React.MutableRefObject<T | null>).current = node;
    });
  };
}

export const PixelButton = forwardRef<HTMLButtonElement, PixelButtonProps>(function PixelButton(
  {
    tone = 'green',
    size = 'md',
    variant = 'solid',
    surface: surfaceProp,
    iconLeft,
    iconRight,
    loading,
    fullWidth,
    asChild,
    className,
    children,
    onClick,
    ...rest
  },
  ref,
) {
  const surface = useEffectiveSurface(surfaceProp);
  const s = surfaceClasses(surface);
  // No drop shadow on pixel, whose cut corners clip it: the nudge and press alone.
  const c = cornerShadowClasses(surface);
  const t = toneMap[tone];
  const isGhost = variant === 'ghost';
  const isOutline = variant === 'outline';
  const isSoft = variant === 'soft';

  // Pin min-width to pre-load measurement so the button doesn't collapse when
  // the spinner replaces wider text content.
  const innerRef = useRef<HTMLButtonElement | null>(null);
  const [minWidth, setMinWidth] = useState<number | null>(null);
  const prevLoading = useRef<boolean>(!!loading);
  useIsomorphicLayoutEffect(() => {
    // Capture the rendered width the frame BEFORE we flip into loading.
    if (!prevLoading.current && loading && innerRef.current) {
      setMinWidth(innerRef.current.getBoundingClientRect().width);
    }
    if (!loading) setMinWidth(null);
    prevLoading.current = !!loading;
  }, [loading]);

  // Hover and press feedback only while the button can be pressed: a disabled
  // or loading one holds still, and a disabled one drops its shadow too.
  const enabled = !rest.disabled;
  const moves = enabled && !loading;
  const variantClasses = isGhost
    ? cn('border border-transparent bg-transparent', t.hover)
    : isOutline
      ? cn(s.border, t.border, 'bg-transparent', t.hover, enabled && c.shadow, moves && c.shadowHover)
      : isSoft
        ? cn(s.border, t.border, t.soft, t.hover, enabled && c.shadow, moves && c.shadowHover)
        : cn(s.border, t.border, t.bg, t.hover, enabled && c.shadow, moves && c.shadowHover);

  const mergedClassName = cn(
    'inline-flex items-center justify-center font-medium focus-visible:outline-hidden disabled:opacity-50 disabled:cursor-not-allowed',
    s.font, s.radius, s.transition,
    sizeClass[size],
    focusRing,
    t.ring,
    t.text,
    fullWidth && 'w-full',
    variantClasses,
    moves && (isGhost || isOutline ? 'active:scale-[0.97]' : c.shadowActive),
    className,
  );

  const callerStyle = (rest as { style?: React.CSSProperties }).style;
  const mergedStyle: React.CSSProperties | undefined =
    minWidth !== null ? { ...callerStyle, minWidth: `${minWidth}px` } : callerStyle;

  const content = (
    <>
      {loading ? (
        <span
          data-testid="pxl-button-spinner"
          aria-hidden
          className="inline-block h-3.5 w-3.5 motion-safe:animate-spin rounded-full border-2 border-current border-r-transparent"
        />
      ) : (
        iconLeft
      )}
      <span>{children}</span>
      {iconRight}
    </>
  );

  // asChild slot pattern: clone the single child, merging className/ref/onClick.
  // Useful for `<Link>`/`<a>` wrappers. Single-child only — multiple children
  // get re-routed through the regular <button> path.
  if (asChild && React.isValidElement(children)) {
    const child = children as React.ReactElement<{
      className?: string;
      onClick?: React.MouseEventHandler<HTMLElement>;
      ref?: React.Ref<HTMLElement>;
    }>;
    const childProps = child.props as {
      className?: string;
      onClick?: React.MouseEventHandler<HTMLElement>;
      ref?: React.Ref<HTMLElement>;
    };
    return React.cloneElement(child, {
      className: cn(mergedClassName, childProps.className),
      onClick: (e: React.MouseEvent<HTMLElement>) => {
        childProps.onClick?.(e);
        onClick?.(e as unknown as React.MouseEvent<HTMLButtonElement>);
      },
      ref: mergeRefs(ref as React.Ref<HTMLElement>, elementRef<HTMLElement>(child) ?? null),
    } as Partial<typeof childProps> & { ref?: React.Ref<HTMLElement> });
  }

  return (
    <button
      {...rest}
      ref={mergeRefs<HTMLButtonElement>(ref, innerRef)}
      className={mergedClassName}
      style={mergedStyle}
      disabled={loading || rest.disabled}
      onClick={onClick}
    >
      {content}
    </button>
  );
});

PixelButton.displayName = 'PixelButton';
