// packages/ui-kit-vue/src/data/PixelSparkline.vue
<script setup lang="ts">
import { computed } from 'vue';
import {
  chartShapeRendering,
  describeChart,
  sparklineClasses,
  sparklineGeometry,
  sparklineStroke,
  type ChartSize,
  type PixelChartDataPoint,
  type Surface,
  type ToneKey,
} from '@pxlkit/ui-kit-core';
import { useEffectiveSurface } from '../composables/surface.js';

/**
 * A series drawn as one polyline, with an optional area filled underneath.
 * The `<svg>` is an image (`role="img"`) named by `aria-label`, or by a
 * summary of the series (kind, point count and range); other attributes go
 * to it too.
 *
 * @example
 * <PixelSparkline :data="[{ x: 'Mon', y: 12 }, { x: 'Tue', y: 18 }]" tone="green" show-area />
 */
export interface PixelSparklineProps {
  /** The series. Points are spread evenly; `x` only labels them, and one whose `y` is not finite is left out. */
  data: PixelChartDataPoint[];
  /** Colour of the line and the area. */
  tone?: ToneKey;
  /** 120×32, 240×60 or 360×96 px. */
  size?: ChartSize;
  /** Fills the area under the line, faintly. */
  showArea?: boolean;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
  /** Surface border and radius around the chart. */
  bordered?: boolean;
  /** Accessible name; a summary of the series when unset. */
  ariaLabel?: string;
}

const props = withDefaults(defineProps<PixelSparklineProps>(), {
  tone: 'cyan',
  size: 'md',
  showArea: false,
  surface: undefined,
  bordered: false,
  ariaLabel: undefined,
});

const surface = useEffectiveSurface(() => props.surface);
const geometry = computed(() => sparklineGeometry(props.data, props.size));
const stroke = computed(() => sparklineStroke(surface.value));
const classes = computed(() => sparklineClasses(surface.value, { tone: props.tone, bordered: props.bordered }));
const label = computed(() => props.ariaLabel ?? describeChart('sparkline', props.data));
</script>

<template>
  <svg
    role="img"
    :aria-label="label"
    :width="geometry.width"
    :height="geometry.height"
    :viewBox="`0 0 ${geometry.width} ${geometry.height}`"
    preserveAspectRatio="none"
    :shape-rendering="chartShapeRendering(surface)"
    :class="classes.root"
  >
    <polygon v-if="showArea && geometry.area" :points="geometry.area" :class="classes.area" stroke="none" />
    <polyline
      :points="geometry.line"
      fill="none"
      :stroke-width="stroke.width"
      :stroke-linejoin="stroke.linejoin"
      :stroke-linecap="stroke.linecap"
      :class="classes.line"
    />
  </svg>
</template>

// packages/ui-kit/src/data/PixelSparkline.tsx
'use client';

import React, { forwardRef, useMemo } from 'react';
import {
  chartShapeRendering,
  describeChart,
  sparklineClasses,
  sparklineGeometry,
  sparklineStroke,
  type ChartSize,
  type PixelChartDataPoint,
} from '@pxlkit/ui-kit-core';
import { cn, Surface, useEffectiveSurface } from '../common';
import { ToneKey } from '../tokens';

/* ──────────────────────────────────────────────────────────────────────────
   PixelSparkline — polyline trend line. Optional filled area underneath.
   ────────────────────────────────────────────────────────────────────────── */

export interface PixelSparklineProps extends React.SVGAttributes<SVGSVGElement> {
  /**
   * The series. Points are spread evenly; `x` only labels them, and one whose `y` is not finite is
   * left out.
   */
  data: PixelChartDataPoint[];
  /** Colour of the line and the area. */
  tone?: ToneKey;
  /** 120×32, 240×60 or 360×96 px. */
  size?: ChartSize;
  /** Fills the area under the line, faintly. */
  showArea?: boolean;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
  /** Render with surface-aware border + radius chrome. Defaults to false (no chrome). */
  bordered?: boolean;
}

export const PixelSparkline = forwardRef<SVGSVGElement, PixelSparklineProps>(function PixelSparkline(
  {
    data,
    tone = 'cyan',
    size = 'md',
    showArea = false,
    surface: surfaceProp,
    bordered = false,
    className,
    'aria-label': ariaLabel,
    ...rest
  },
  ref,
) {
  const surface = useEffectiveSurface(surfaceProp);
  const { width, height, line, area } = useMemo(() => sparklineGeometry(data, size), [data, size]);
  const stroke = sparklineStroke(surface);
  const classes = sparklineClasses(surface, { tone, bordered });

  const label = ariaLabel ?? describeChart('sparkline', data);

  return (
    <svg
      ref={ref}
      role="img"
      aria-label={label}
      width={width}
      height={height}
      viewBox={`0 0 ${width} ${height}`}
      preserveAspectRatio="none"
      shapeRendering={chartShapeRendering(surface)}
      className={cn(classes.root, className)}
      {...rest}
    >
      {showArea && area && (
        <polygon
          points={area}
          className={classes.area}
          stroke="none"
        />
      )}
      <polyline
        points={line}
        fill="none"
        strokeWidth={stroke.width}
        strokeLinejoin={stroke.linejoin}
        strokeLinecap={stroke.linecap}
        className={classes.line}
      />
    </svg>
  );
});

PixelSparkline.displayName = 'PixelSparkline';
