// packages/ui-kit-angular/src/lib/data/pixel-chip-group.ts
import { NgTemplateOutlet } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  Directive,
  ElementRef,
  HostAttributeToken,
  TemplateRef,
  computed,
  contentChildren,
  inject,
  input,
  model,
  viewChildren,
} from '@angular/core';
import type { ControlValueAccessor } from '@angular/forms';
import {
  chipGroupClasses,
  chipGroupItemClasses,
  chipGroupKeyAction,
  chipGroupMove,
  chipGroupRole,
  chipGroupTabStop,
  toggleChipSelection,
  type Surface,
} from '@pxlkit/ui-kit-core';
import { booleanOr } from '../_internal/coercion';
import { FormBridge, provideValueAccessor } from '../_internal/value-accessor';
import { injectEffectiveSurface } from '../overlay-foundation/pxl-kit-surface-provider';

/**
 * Marks one chip of a `<pxl-chip-group>` with the value it stands for in the
 * selection. The group renders it inside its toggle button.
 *
 * @example
 * <pxl-chip *pxlChipGroupItem="'react'" label="React" />
 */
@Directive({ selector: '[pxlChipGroupItem]' })
export class PixelChipGroupItem {
  /** Value of the chip in the group's selection. */
  readonly pxlChipGroupItem = input.required<string>();
  /** @internal */
  readonly template = inject<TemplateRef<unknown>>(TemplateRef);
}

/**
 * Row of selectable chips, each marked with `*pxlChipGroupItem` and rendered
 * in a toggle button: a radio group for single selection (roving tabindex;
 * arrow keys, Home and End move and select), or checkboxes with `multiple`.
 * Enter and Space toggle a chip. Bind the selection with `[(value)]`, use the
 * group as a form control (`ngModel`, `formControlName`), or leave it
 * uncontrolled with `defaultValue`. A static `aria-label` or
 * `aria-labelledby` names the row — required for single selection; with
 * `multiple` it makes the row a `role="group"`.
 *
 * @example
 * <pxl-chip-group [(value)]="frameworks" multiple aria-label="Frameworks">
 *   <pxl-chip *pxlChipGroupItem="'react'" label="React" />
 *   <pxl-chip *pxlChipGroupItem="'vue'" label="Vue" />
 * </pxl-chip-group>
 */
@Component({
  selector: 'pxl-chip-group',
  imports: [NgTemplateOutlet],
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [provideValueAccessor(() => PixelChipGroup)],
  host: {
    '[attr.role]': 'role()',
    '[class]': 'classes',
  },
  template: `
    @for (item of items(); track item) {
      @let value = item.pxlChipGroupItem();
      @let selected = selection().includes(value);
      <button
        #chip
        type="button"
        [attr.role]="multiple() ? 'checkbox' : 'radio'"
        [attr.aria-checked]="selected"
        [attr.tabindex]="multiple() ? null : value === tabStop() ? 0 : -1"
        [attr.data-value]="value"
        [attr.data-selected]="selected ? 'true' : 'false'"
        [disabled]="form.disabled()"
        [class]="itemClasses(selected)"
        (click)="toggle(value)"
        (keydown)="onKeydown($event, value)"
        (blur)="form.touched()"
      >
        <ng-container [ngTemplateOutlet]="item.template" />
      </button>
    }
  `,
})
export class PixelChipGroup implements ControlValueAccessor {
  /** Selected chip values (`[(value)]`); leave unset for an uncontrolled group. */
  readonly value = model<string[] | undefined>(undefined);
  /** Initial selection while uncontrolled. */
  readonly defaultValue = input<string[]>();
  /** Any number of chips can be selected (checkboxes) instead of one (radios). */
  readonly multiple = input(false, { transform: booleanOr(false) });
  /** Surface override; defaults to the nearest provider. */
  readonly surface = input<Surface>();

  /** @internal */
  protected readonly form = new FormBridge<string[]>();
  /** @internal */
  protected readonly items = contentChildren(PixelChipGroupItem);
  private readonly chips = viewChildren<ElementRef<HTMLButtonElement>>('chip');
  private readonly effectiveSurface = injectEffectiveSurface(() => this.surface());
  private readonly ownRole = inject(new HostAttributeToken('role'), { optional: true });
  private readonly named = Boolean(
    inject(new HostAttributeToken('aria-label'), { optional: true }) ||
      inject(new HostAttributeToken('aria-labelledby'), { optional: true }),
  );

  /** @internal An own `role` wins. */
  protected readonly role = computed(() => this.ownRole ?? chipGroupRole(this.multiple(), this.named) ?? null);
  /** @internal */
  protected readonly classes = chipGroupClasses;
  /** @internal */
  protected readonly selection = computed(() => this.value() ?? this.defaultValue() ?? []);
  private readonly values = computed(() => this.items().map((item) => item.pxlChipGroupItem()));
  /** @internal The chip Tab reaches in single selection. */
  protected readonly tabStop = computed(() => chipGroupTabStop(this.values(), this.selection()));

  /** @internal */
  protected itemClasses(selected: boolean): string {
    return chipGroupItemClasses(this.effectiveSurface(), selected);
  }

  /** @internal */
  protected toggle(value: string): void {
    this.select(toggleChipSelection(this.selection(), value, this.multiple()));
  }

  /** @internal */
  protected onKeydown(event: KeyboardEvent, value: string): void {
    const action = chipGroupKeyAction(event.key, this.multiple());
    if (action === undefined) return;
    event.preventDefault();
    if (action === 'toggle') {
      this.toggle(value);
      return;
    }
    // In the radio group pattern, a move focuses and selects.
    const values = this.values();
    const move = chipGroupMove(values, this.selection(), value, action);
    if (!move) return;
    this.chips()[values.indexOf(move.focus)]?.nativeElement.focus();
    if (move.selection) this.select(move.selection);
  }

  private select(selection: string[]): void {
    this.value.set(selection);
    this.form.changed(selection);
  }

  /** @internal ControlValueAccessor */
  writeValue(value: unknown): void {
    this.value.set(Array.isArray(value) ? value : undefined);
  }

  /** @internal ControlValueAccessor */
  registerOnChange(fn: (value: string[]) => void): void {
    this.form.registerOnChange(fn);
  }

  /** @internal ControlValueAccessor */
  registerOnTouched(fn: () => void): void {
    this.form.registerOnTouched(fn);
  }

  /** @internal ControlValueAccessor */
  setDisabledState(disabled: boolean): void {
    this.form.disabled.set(disabled);
  }
}

// packages/ui-kit/src/data/PixelChipGroup.tsx
'use client';

import React, {
  Children,
  forwardRef,
  isValidElement,
  useCallback,
  useRef,
} from 'react';
import {
  chipGroupClasses,
  chipGroupItemClasses,
  chipGroupKeyAction,
  chipGroupMove,
  chipGroupRole,
  chipGroupTabStop,
  toggleChipSelection,
  type ChipGroupMove,
} from '@pxlkit/ui-kit-core';
import {
  Surface,
  cn,
  useEffectiveSurface,
} from '../common';
import { useControllableState } from '../hooks/useControllableState';

/* ──────────────────────────────────────────────────────────────────────────
   PixelChipGroup — controlled filter chip row with single/multi selection.

   Each child must declare a `value` prop. The group wraps each child in a
   role=radio (single) or role=checkbox (multi) button so the chip surface
   stays purely presentational while the wrapper owns the toggle semantics.
   Keyboard: Tab moves between chips; Space/Enter activates.
   ────────────────────────────────────────────────────────────────────────── */

interface ChipChildProps {
  value: string;
}

export interface PixelChipGroupProps
  extends Omit<React.HTMLAttributes<HTMLDivElement>, 'onChange' | 'defaultValue'> {
  /** Controlled selection. */
  value?: string[];
  /** Uncontrolled initial selection. */
  defaultValue?: string[];
  /** Called with the new selection, after each change. */
  onChange?: (next: string[]) => void;
  /** Any number of chips can be selected (checkboxes) instead of one (radios). */
  multiple?: boolean;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
  /** Accessible name (required when single-select so SR users hear the group). */
  'aria-label'?: string;
  /** Id of the element that names the group, in place of `aria-label`. */
  'aria-labelledby'?: string;
  /** The chips, each with a `value`; other content renders as is. */
  children: React.ReactNode;
}

export const PixelChipGroup = forwardRef<HTMLDivElement, PixelChipGroupProps>(
  function PixelChipGroup(
    {
      value: valueProp,
      defaultValue,
      onChange,
      multiple = false,
      surface: surfaceProp,
      className,
      children,
      ...rest
    },
    ref,
  ) {
    const surface = useEffectiveSurface(surfaceProp);
    const [value, setValue] = useControllableState<string[]>({
      value: valueProp,
      defaultValue: defaultValue ?? [],
      onChange,
    });
    const selection = value ?? [];

    const toggle = (chipValue: string) => setValue(toggleChipSelection(selection, chipValue, multiple));

    const items = Children.toArray(children).filter(isValidElement);

    // Ordered radio values for roving tabindex + arrow nav (single mode).
    const radioValues: string[] = [];
    for (const child of items) {
      const v = (child as React.ReactElement<ChipChildProps>).props?.value;
      if (typeof v === 'string') radioValues.push(v);
    }

    const btnRefs = useRef<Map<string, HTMLButtonElement>>(new Map());
    const setBtnRef = useCallback((val: string, el: HTMLButtonElement | null) => {
      if (el) btnRefs.current.set(val, el);
      else btnRefs.current.delete(val);
    }, []);
    const focusableRadio = multiple ? undefined : chipGroupTabStop(radioValues, selection);

    // In the radiogroup pattern an arrow key both focuses AND selects.
    const moveRadio = (current: string, direction: ChipGroupMove) => {
      const move = chipGroupMove(radioValues, selection, current, direction);
      if (!move) return;
      btnRefs.current.get(move.focus)?.focus();
      if (move.selection) setValue(move.selection);
    };

    const ariaLabel = (rest as { 'aria-label'?: string })['aria-label'];
    const ariaLabelledBy = (rest as { 'aria-labelledby'?: string })['aria-labelledby'];
    const hasName = !!(ariaLabel || ariaLabelledBy);

    return (
      <div
        ref={ref}
        role={chipGroupRole(multiple, hasName)}
        className={cn(chipGroupClasses, className)}
        {...rest}
      >
        {items.map((child, idx) => {
          const el = child as React.ReactElement<ChipChildProps>;
          const chipValue = el.props?.value;
          if (typeof chipValue !== 'string') {
            return (
              <React.Fragment key={el.key ?? idx}>
                {el}
              </React.Fragment>
            );
          }
          const selected = selection.includes(chipValue);
          const handleClick = () => toggle(chipValue);
          const handleKeyDown = (e: React.KeyboardEvent<HTMLButtonElement>) => {
            const action = chipGroupKeyAction(e.key, multiple);
            if (action === undefined) return;
            e.preventDefault();
            if (action === 'toggle') toggle(chipValue);
            else moveRadio(chipValue, action);
          };
          // Single-mode roving tabindex: only the selected (or first) radio is
          // Tab-reachable; others -1.
          const rovingTabIndex = !multiple
            ? (chipValue === focusableRadio ? 0 : -1)
            : undefined;
          return (
            <button
              key={el.key ?? idx}
              ref={(node) => setBtnRef(chipValue, node)}
              type="button"
              role={multiple ? 'checkbox' : 'radio'}
              aria-checked={selected}
              tabIndex={rovingTabIndex}
              data-value={chipValue}
              data-selected={selected ? 'true' : 'false'}
              onClick={handleClick}
              onKeyDown={handleKeyDown}
              className={chipGroupItemClasses(surface, selected)}
            >
              {el}
            </button>
          );
        })}
      </div>
    );
  },
);

PixelChipGroup.displayName = 'PixelChipGroup';
