// packages/ui-kit-vue/src/data/PixelChip.vue
<script setup lang="ts">
import { computed, useAttrs, type VNode } from 'vue';
import {
  chipClasses,
  chipDeleteLabel,
  type PixelBadgeVariant,
  type Size,
  type Surface,
  type Tone,
} from '@pxlkit/ui-kit-core';
import PixelGlyph from '../_internal/PixelGlyph.vue';
import { useEffectiveSurface } from '../composables/surface.js';

/**
 * Compact label tag with the badge variants, sizes and an optional leading
 * icon. With a `click` listener it renders a `<button type="button">`
 * instead of a `<span>`; with a `delete` listener it shows a delete (×)
 * button (named "Remove <label>") that does not trigger the chip's click.
 * A button cannot contain a button, so a chip with both is a `<span>` frame
 * around two sibling buttons, the label and the ×: the frame takes the
 * `class`, the label button every other attribute and listener.
 */
export interface PixelChipProps {
  /** Chip label. */
  label: string;
  /** Selection value read by a wrapping `PixelChipGroup`; never rendered. */
  value?: string;
  /** Tone tint. */
  tone?: Tone;
  /** Visual surface override. */
  surface?: Surface;
  /** Variant axis shared with PixelBadge. */
  variant?: PixelBadgeVariant;
  /** Size scale. */
  size?: Size;
  /** `false` hides the delete button even with a `delete` listener. */
  deletable?: boolean;
  /**
   * Click handler (`@click`). Declared as a prop because its presence changes
   * the element: with one the chip is a `<button type="button">`.
   */
  onClick?: (event: MouseEvent) => void;
  /**
   * Delete handler (`@delete`), called by the delete button. Declared as a
   * prop because its presence shows that button.
   */
  onDelete?: () => void;
  /** Legacy alias of `onDelete` (`@remove`). */
  onRemove?: () => void;
}

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<PixelChipProps>(), {
  value: undefined,
  tone: 'cyan',
  surface: undefined,
  variant: 'soft',
  size: 'md',
  deletable: undefined,
});
defineSlots<{
  /** Leading icon. */
  'icon-left'?(): VNode[];
}>();

const attrs = useAttrs();
const surface = useEffectiveSurface(() => props.surface);
const interactive = computed(() => props.onClick !== undefined);
const removeHandler = computed(() => props.onDelete ?? props.onRemove);
const deletes = computed(() => removeHandler.value !== undefined && props.deletable !== false);
const classes = computed(() =>
  chipClasses(surface.value, {
    tone: props.tone,
    variant: props.variant,
    size: props.size,
    interactive: interactive.value,
  }),
);
const actionAttrs = computed(() => {
  const { class: _class, ...others } = attrs;
  return others;
});

function remove(event: MouseEvent) {
  // A delete is not a click of the chip, nor of whatever holds it.
  event.stopPropagation();
  removeHandler.value?.();
}
</script>

<template>
  <span v-if="interactive && deletes" :class="[classes.frame, attrs.class]">
    <button type="button" data-chip-action="" :class="classes.action" v-bind="actionAttrs" @click="onClick">
      <span v-if="$slots['icon-left']" :class="classes.icon"><slot name="icon-left" /></span>
      <span>{{ label }}</span>
    </button>
    <button type="button" :class="classes.deleteButton" :aria-label="chipDeleteLabel(label)" @click="remove">
      <PixelGlyph name="close" :class="classes.deleteIcon" />
    </button>
  </span>
  <component
    :is="interactive ? 'button' : 'span'"
    v-else
    :type="interactive ? 'button' : undefined"
    :class="classes.root"
    v-bind="attrs"
    @click="onClick"
  >
    <span v-if="$slots['icon-left']" :class="classes.icon"><slot name="icon-left" /></span>
    <span>{{ label }}</span>
    <button v-if="deletes" type="button" :class="classes.deleteButton" :aria-label="chipDeleteLabel(label)" @click="remove">
      <PixelGlyph name="close" :class="classes.deleteIcon" />
    </button>
  </component>
</template>

// packages/ui-kit/src/data/PixelChip.tsx
import React, { forwardRef } from 'react';
import { chipClasses, chipDeleteLabel } from '@pxlkit/ui-kit-core';
import {
  Tone, Size, Surface, cn,
  useEffectiveSurface,
  CloseIcon,
} from '../common';
import { PixelBadgeVariant } from './_internal/variantClasses';

/* ─────────────────────────────────────────────────────────────────────────
   PixelChip — label tag, optionally removable / clickable.

   Upgraded additively: `variant`, `size`, `iconLeft`, `onClick` (chip becomes
   button), and `deletable` + `onDelete` (X button on the right). `onRemove`
   stays as the legacy delete handler alias. A chip that is both clickable
   and deletable is a frame around two sibling buttons, the label and the X:
   a button cannot contain a button.
   ───────────────────────────────────────────────────────────────────────── */

export interface PixelChipProps extends Omit<React.HTMLAttributes<HTMLElement>, 'onClick'> {
  /** Chip label. */
  label: string;
  /** Selection value consumed by a wrapping PixelChipGroup. Never rendered to the DOM. */
  value?: string;
  /** Tone tint. Defaults to `'cyan'`. */
  tone?: Tone;
  /** Visual surface override. */
  surface?: Surface;
  /** Variant axis shared with PixelBadge. */
  variant?: PixelBadgeVariant;
  /** Size scale. Defaults to `'md'`. */
  size?: Size;
  /** Optional leading icon. */
  iconLeft?: React.ReactNode;
  /** Legacy alias for `onDelete`. */
  onRemove?: () => void;
  /** When true (or when onDelete is provided), renders an X button on the right. */
  deletable?: boolean;
  /** Called when the X button is activated. */
  onDelete?: () => void;
  /**
   * When provided the root renders as a `<button>`. With a delete handler too,
   * a button cannot contain a button, so the label and the X become sibling
   * buttons in a `<span>` frame that draws the chip; the label button takes the
   * ref and the other props, the frame takes `className`.
   */
  onClick?: React.MouseEventHandler<HTMLElement>;
}

export const PixelChip = forwardRef<HTMLElement, PixelChipProps>(function PixelChip(
  {
    label,
    value: _value,
    tone = 'cyan',
    surface: surfaceProp,
    variant = 'soft',
    size = 'md',
    iconLeft,
    onRemove,
    deletable,
    onDelete,
    onClick,
    className,
    ...rest
  },
  ref,
) {
  const surface = useEffectiveSurface(surfaceProp);
  const removeHandler = onDelete ?? onRemove;
  const showDelete = !!removeHandler && (deletable !== false);
  const classes = chipClasses(surface, { tone, variant, size, interactive: !!onClick });
  const cls = cn(classes.root, className);

  const content = (
    <>
      {iconLeft && <span className={classes.icon}>{iconLeft}</span>}
      <span>{label}</span>
    </>
  );
  const deleteButton = showDelete && (
    <button
      type="button"
      className={classes.deleteButton}
      onClick={(e) => {
        e.stopPropagation();
        removeHandler!();
      }}
      aria-label={chipDeleteLabel(label)}
    >
      <CloseIcon className={classes.deleteIcon} />
    </button>
  );

  if (onClick && showDelete) {
    return (
      <span className={cn(classes.frame, className)}>
        <button
          ref={ref as React.Ref<HTMLButtonElement>}
          type="button"
          data-chip-action=""
          className={classes.action}
          onClick={onClick as React.MouseEventHandler<HTMLButtonElement>}
          {...(rest as React.ButtonHTMLAttributes<HTMLButtonElement>)}
        >
          {content}
        </button>
        {deleteButton}
      </span>
    );
  }

  if (onClick) {
    return (
      <button
        ref={ref as React.Ref<HTMLButtonElement>}
        type="button"
        className={cls}
        onClick={onClick as React.MouseEventHandler<HTMLButtonElement>}
        {...(rest as React.ButtonHTMLAttributes<HTMLButtonElement>)}
      >
        {content}
      </button>
    );
  }

  return (
    <span
      ref={ref as React.Ref<HTMLSpanElement>}
      className={cls}
      {...rest}
    >
      {content}
      {deleteButton}
    </span>
  );
});
PixelChip.displayName = 'PixelChip';
