// packages/ui-kit-angular/examples/data/pixel-text-link.examples.ts
import { Component } from '@angular/core';
import { PixelTextLink } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelTextLink],
  template: `<a pxlTextLink href="https://pxlkit.dev">Read the docs</a>`,
})
export class Default {}

@Component({
  imports: [PixelTextLink],
  template: `
    <div class="flex flex-wrap gap-4">
      <a pxlTextLink href="#" tone="cyan">Cyan link</a>
      <a pxlTextLink href="#" tone="green">Green link</a>
      <a pxlTextLink href="#" tone="gold">Gold link</a>
      <a pxlTextLink href="#" tone="red">Red link</a>
      <a pxlTextLink href="#" tone="purple">Purple link</a>
      <a pxlTextLink href="#" tone="pink">Pink link</a>
      <a pxlTextLink href="#" tone="neutral">Neutral link</a>
    </div>
  `,
})
export class Tones {}

@Component({
  imports: [PixelTextLink],
  template: `<button pxlTextLink tone="cyan" (click)="onClick()">Trigger an action</button>`,
})
export class AsButton {
  onClick(): void {
    console.log('clicked');
  }
}

@Component({
  imports: [PixelTextLink],
  template: `
    <div class="flex flex-col gap-3">
      <a pxlTextLink href="#" surface="pixel">Pixel surface</a>
      <a pxlTextLink href="#" surface="linear">Linear surface</a>
    </div>
  `,
})
export class Surfaces {}

@Component({
  imports: [PixelTextLink],
  template: `<a pxlTextLink href="https://pxlkit.dev" target="_blank" rel="noopener noreferrer">Open in new tab</a>`,
})
export class ExternalLink {}

@Component({
  imports: [PixelTextLink],
  template: `
    <p class="max-w-md">
      Built with <a pxlTextLink href="https://pxlkit.dev" tone="green">pxlkit</a>, a tone-coloured component library for
      retro interfaces.
    </p>
  `,
})
export class InlineInProse {}

// packages/ui-kit/src/data/PixelTextLink.examples.tsx
import { PixelTextLink } from './PixelTextLink';

export function Default() {
  return <PixelTextLink href="https://pxlkit.dev">Read the docs</PixelTextLink>;
}

export function Tones() {
  return (
    <div className="flex flex-wrap gap-4">
      <PixelTextLink href="#" tone="cyan">Cyan link</PixelTextLink>
      <PixelTextLink href="#" tone="green">Green link</PixelTextLink>
      <PixelTextLink href="#" tone="gold">Gold link</PixelTextLink>
      <PixelTextLink href="#" tone="red">Red link</PixelTextLink>
      <PixelTextLink href="#" tone="purple">Purple link</PixelTextLink>
      <PixelTextLink href="#" tone="pink">Pink link</PixelTextLink>
      <PixelTextLink href="#" tone="neutral">Neutral link</PixelTextLink>
    </div>
  );
}

export function AsButton() {
  return (
    <PixelTextLink tone="cyan" onClick={() => console.log('clicked')}>
      Trigger an action
    </PixelTextLink>
  );
}

export function Surfaces() {
  return (
    <div className="flex flex-col gap-3">
      <PixelTextLink href="#" surface="pixel">Pixel surface</PixelTextLink>
      <PixelTextLink href="#" surface="linear">Linear surface</PixelTextLink>
    </div>
  );
}

export function ExternalLink() {
  return (
    <PixelTextLink
      href="https://pxlkit.dev"
      target="_blank"
      rel="noopener noreferrer"
    >
      Open in new tab
    </PixelTextLink>
  );
}

export function InlineInProse() {
  return (
    <p className="max-w-md">
      Built with{' '}
      <PixelTextLink href="https://pxlkit.dev" tone="green">
        pxlkit
      </PixelTextLink>
      , a tone-coloured component library for retro interfaces.
    </p>
  );
}
