// packages/ui-kit-angular/examples/data/pixel-badge.examples.ts
import { Component } from '@angular/core';
import { PixelBadge } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelBadge],
  template: `<pxl-badge>NEW</pxl-badge>`,
})
export class Default {}

@Component({
  imports: [PixelBadge],
  template: `
    <div class="flex flex-wrap items-center gap-2">
      <pxl-badge tone="neutral">neutral</pxl-badge>
      <pxl-badge tone="green">green</pxl-badge>
      <pxl-badge tone="cyan">cyan</pxl-badge>
      <pxl-badge tone="gold">gold</pxl-badge>
      <pxl-badge tone="red">red</pxl-badge>
      <pxl-badge tone="purple">purple</pxl-badge>
      <pxl-badge tone="pink">pink</pxl-badge>
    </div>
  `,
})
export class Tones {}

@Component({
  imports: [PixelBadge],
  template: `
    <div class="flex flex-wrap items-center gap-2">
      <pxl-badge size="sm" tone="cyan">small</pxl-badge>
      <pxl-badge size="md" tone="cyan">medium</pxl-badge>
      <pxl-badge size="lg" tone="cyan">large</pxl-badge>
    </div>
  `,
})
export class Sizes {}

@Component({
  imports: [PixelBadge],
  template: `
    <div class="flex flex-wrap items-center gap-2">
      <pxl-badge variant="soft" tone="green">soft</pxl-badge>
      <pxl-badge variant="solid" tone="green">solid</pxl-badge>
      <pxl-badge variant="outline" tone="green">outline</pxl-badge>
      <pxl-badge variant="ghost" tone="green">ghost</pxl-badge>
    </div>
  `,
})
export class Variants {}

@Component({
  imports: [PixelBadge],
  template: `
    <div class="flex flex-wrap items-center gap-3">
      <pxl-badge surface="pixel" tone="gold">pixel</pxl-badge>
      <pxl-badge surface="linear" tone="gold">linear</pxl-badge>
    </div>
  `,
})
export class Surfaces {}

@Component({
  imports: [PixelBadge],
  template: `
    <div class="flex flex-wrap items-center gap-2">
      <pxl-badge tone="green" [iconLeft]="dot">online</pxl-badge>
      <pxl-badge tone="red" [iconLeft]="dot">error</pxl-badge>
      <pxl-badge tone="gold" [iconLeft]="dot">warn</pxl-badge>
    </div>
    <ng-template #dot>
      <span
        aria-hidden="true"
        style="width: 6px; height: 6px; border-radius: 9999px; background: currentColor; display: inline-block"
      ></span>
    </ng-template>
  `,
})
export class WithIcon {}

@Component({
  imports: [PixelBadge],
  template: `<button pxlBadge tone="cyan" variant="outline" (click)="onClick()">click me</button>`,
})
export class Clickable {
  onClick(): void {}
}

// packages/ui-kit/src/data/PixelBadge.examples.tsx
import React from 'react';
import { PixelBadge } from './PixelBadge';

export function Default() {
  return <PixelBadge>NEW</PixelBadge>;
}

export function Tones() {
  return (
    <div className="flex flex-wrap items-center gap-2">
      <PixelBadge tone="neutral">neutral</PixelBadge>
      <PixelBadge tone="green">green</PixelBadge>
      <PixelBadge tone="cyan">cyan</PixelBadge>
      <PixelBadge tone="gold">gold</PixelBadge>
      <PixelBadge tone="red">red</PixelBadge>
      <PixelBadge tone="purple">purple</PixelBadge>
      <PixelBadge tone="pink">pink</PixelBadge>
    </div>
  );
}

export function Sizes() {
  return (
    <div className="flex flex-wrap items-center gap-2">
      <PixelBadge size="sm" tone="cyan">small</PixelBadge>
      <PixelBadge size="md" tone="cyan">medium</PixelBadge>
      <PixelBadge size="lg" tone="cyan">large</PixelBadge>
    </div>
  );
}

export function Variants() {
  return (
    <div className="flex flex-wrap items-center gap-2">
      <PixelBadge variant="soft" tone="green">soft</PixelBadge>
      <PixelBadge variant="solid" tone="green">solid</PixelBadge>
      <PixelBadge variant="outline" tone="green">outline</PixelBadge>
      <PixelBadge variant="ghost" tone="green">ghost</PixelBadge>
    </div>
  );
}

export function Surfaces() {
  return (
    <div className="flex flex-wrap items-center gap-3">
      <PixelBadge surface="pixel" tone="gold">pixel</PixelBadge>
      <PixelBadge surface="linear" tone="gold">linear</PixelBadge>
    </div>
  );
}

const DotIcon = () => (
  <span
    aria-hidden
    style={{ width: 6, height: 6, borderRadius: 9999, background: 'currentColor', display: 'inline-block' }}
  />
);

export function WithIcon() {
  return (
    <div className="flex flex-wrap items-center gap-2">
      <PixelBadge tone="green" iconLeft={<DotIcon />}>online</PixelBadge>
      <PixelBadge tone="red" iconLeft={<DotIcon />}>error</PixelBadge>
      <PixelBadge tone="gold" iconLeft={<DotIcon />}>warn</PixelBadge>
    </div>
  );
}

export function Clickable() {
  return (
    <PixelBadge tone="cyan" variant="outline" onClick={() => undefined}>
      click me
    </PixelBadge>
  );
}
