// packages/ui-kit-angular/examples/data/pixel-bar-chart.examples.ts
import { Component } from '@angular/core';
import { PixelBarChart, type PixelChartDataPoint } from '@pxlkit/ui-kit-angular';

const SAMPLE: PixelChartDataPoint[] = [
  { x: 'Mon', y: 12 },
  { x: 'Tue', y: 18 },
  { x: 'Wed', y: 9 },
  { x: 'Thu', y: 24 },
  { x: 'Fri', y: 16 },
  { x: 'Sat', y: 21 },
  { x: 'Sun', y: 14 },
];

@Component({
  imports: [PixelBarChart],
  template: `<svg pxlBarChart [data]="sample"></svg>`,
})
export class Default {
  readonly sample = SAMPLE;
}

@Component({
  imports: [PixelBarChart],
  template: `
    <div class="flex flex-wrap items-end gap-4">
      <svg pxlBarChart [data]="sample" tone="cyan"></svg>
      <svg pxlBarChart [data]="sample" tone="green"></svg>
      <svg pxlBarChart [data]="sample" tone="gold"></svg>
      <svg pxlBarChart [data]="sample" tone="red"></svg>
      <svg pxlBarChart [data]="sample" tone="purple"></svg>
      <svg pxlBarChart [data]="sample" tone="pink"></svg>
    </div>
  `,
})
export class Tones {
  readonly sample = SAMPLE;
}

@Component({
  imports: [PixelBarChart],
  template: `
    <div class="flex flex-wrap items-end gap-4">
      <svg pxlBarChart [data]="sample" size="sm" tone="cyan"></svg>
      <svg pxlBarChart [data]="sample" size="md" tone="cyan"></svg>
      <svg pxlBarChart [data]="sample" size="lg" tone="cyan"></svg>
    </div>
  `,
})
export class Sizes {
  readonly sample = SAMPLE;
}

@Component({
  imports: [PixelBarChart],
  template: `<svg pxlBarChart [data]="sample" orientation="horizontal" tone="green"></svg>`,
})
export class Horizontal {
  readonly sample = SAMPLE;
}

@Component({
  imports: [PixelBarChart],
  template: `<svg pxlBarChart [data]="sample" tone="gold" showValues></svg>`,
})
export class WithValues {
  readonly sample = SAMPLE;
}

@Component({
  imports: [PixelBarChart],
  template: `
    <div class="flex flex-wrap items-end gap-4">
      <svg pxlBarChart [data]="sample" surface="pixel" tone="purple"></svg>
      <svg pxlBarChart [data]="sample" surface="linear" tone="purple"></svg>
    </div>
  `,
})
export class Surfaces {
  readonly sample = SAMPLE;
}

// packages/ui-kit/src/data/PixelBarChart.examples.tsx
import React from 'react';
import { PixelBarChart } from './PixelBarChart';

const sample = [
  { x: 'Mon', y: 12 },
  { x: 'Tue', y: 18 },
  { x: 'Wed', y: 9 },
  { x: 'Thu', y: 24 },
  { x: 'Fri', y: 16 },
  { x: 'Sat', y: 21 },
  { x: 'Sun', y: 14 },
];

export function Default() {
  return <PixelBarChart data={sample} />;
}

export function Tones() {
  return (
    <div className="flex flex-wrap items-end gap-4">
      <PixelBarChart data={sample} tone="cyan" />
      <PixelBarChart data={sample} tone="green" />
      <PixelBarChart data={sample} tone="gold" />
      <PixelBarChart data={sample} tone="red" />
      <PixelBarChart data={sample} tone="purple" />
      <PixelBarChart data={sample} tone="pink" />
    </div>
  );
}

export function Sizes() {
  return (
    <div className="flex flex-wrap items-end gap-4">
      <PixelBarChart data={sample} size="sm" tone="cyan" />
      <PixelBarChart data={sample} size="md" tone="cyan" />
      <PixelBarChart data={sample} size="lg" tone="cyan" />
    </div>
  );
}

export function Horizontal() {
  return <PixelBarChart data={sample} orientation="horizontal" tone="green" />;
}

export function WithValues() {
  return <PixelBarChart data={sample} tone="gold" showValues />;
}

export function Surfaces() {
  return (
    <div className="flex flex-wrap items-end gap-4">
      <PixelBarChart data={sample} surface="pixel" tone="purple" />
      <PixelBarChart data={sample} surface="linear" tone="purple" />
    </div>
  );
}
