// packages/ui-kit/src/forms/PixelSlider.tsx
/* ─────────────────────────────────────────────────────────────────────────
   PixelSlider — single OR range slider, with marks, tooltips, and ticks.
   - Single mode (default): value is a number, one thumb.
   - Range mode: value is [number, number], two thumbs, fill between.
   ───────────────────────────────────────────────────────────────────────── */

import React, { forwardRef, useCallback, useMemo, useRef, useState } from 'react';
import {
  isSliderRange,
  moveSliderThumb,
  nearestSliderThumb,
  sliderClasses,
  sliderFill,
  sliderKeyValue,
  sliderPercent,
  sliderThumbLabel,
  sliderThumbLeft,
  sliderThumbValues,
  sliderTicks,
  sliderTooltipVisible,
  sliderValueAt,
  sliderValueText,
  type SliderThumb,
  type SliderTooltipMode,
} from '@pxlkit/ui-kit-core';
import {
  Tone, Surface,
  useEffectiveSurface,
} from '../common';

export type PixelSliderTooltip = SliderTooltipMode;

/** A labeled mark on the track. */
export interface PixelSliderMark {
  /** Value at which to position the mark on the track. */
  value: number;
  /** Rendered label content. */
  label: React.ReactNode;
}

/** Shared base props for {@link PixelSlider}. */
interface PixelSliderBaseProps {
  /** Visible label rendered above the track. */
  label: string;
  /** Minimum value. Default: `0`. */
  min?: number;
  /** Maximum value. Default: `100`. */
  max?: number;
  /**
   * Distance between two values, counted from `min`: the slider takes `min`,
   * `min + step`, `min + 2 * step`… up to `max`. Default: `1`.
   */
  step?: number;
  /** Disables interaction + grays out the track. */
  disabled?: boolean;
  /** Visual tone for the active fill + thumb. Default: `'cyan'`. */
  tone?: Tone;
  /** Render `min` / `max` numbers under the track. */
  showMinMax?: boolean;
  /** Surface variant. Inherits from `PxlKitSurfaceProvider` when omitted. */
  surface?: Surface;
  /** Form-serialization name (range mode emits `name[0]` / `name[1]`). */
  name?: string;
  /** Marks the field as required for native form validation. */
  required?: boolean;
  /** DOM `id` forwarded to the single / lower thumb. */
  id?: string;
  /** Labeled marks plotted on the track. */
  marks?: PixelSliderMark[];
  /**
   * When/how to show a value tooltip on each thumb.
   * - `'always'`: visible all the time
   * - `'drag'`: visible while dragging or focused
   * - `'never'`: hidden (default)
   */
  showTooltip?: PixelSliderTooltip;
  /** Render tick marks under the track for every discrete `step`. */
  ticks?: boolean;
}

/** Single-thumb variant. */
export interface PixelSliderSingleProps extends PixelSliderBaseProps {
  /** Controlled scalar value. */
  value: number;
  /** Fires with the next scalar value. */
  onChange: (next: number) => void;
}

/** Range (two-thumb) variant. */
export interface PixelSliderRangeProps extends PixelSliderBaseProps {
  /** Controlled `[lo, hi]` tuple. */
  value: [number, number];
  /** Fires with the next `[lo, hi]` tuple. */
  onChange: (next: [number, number]) => void;
}

/** Public prop bag for {@link PixelSlider}. */
export type PixelSliderProps = PixelSliderSingleProps | PixelSliderRangeProps;

export const PixelSlider = forwardRef<HTMLDivElement, PixelSliderProps>(function PixelSlider(
  {
    label,
    min = 0, max = 100, step = 1,
    value, onChange,
    disabled = false,
    tone = 'cyan',
    showMinMax = false,
    surface: surfaceProp,
    name, required, id,
    marks,
    showTooltip = 'never',
    ticks = false,
  },
  ref,
) {
  const surface = useEffectiveSurface(surfaceProp);
  const c = sliderClasses(surface, { tone, disabled });
  const trackRef = useRef<HTMLDivElement>(null);

  const range = isSliderRange(value);
  const [v0, v1] = sliderThumbValues(value);

  // Which thumb is being dragged (0 = single/lower, 1 = upper). null = idle.
  const draggingIdx = useRef<SliderThumb | null>(null);
  const [activeIdx, setActiveIdx] = useState<SliderThumb | null>(null);

  // In a range the moved thumb stops at the other one: lower stays ≤ upper.
  const emit = useCallback(
    (idx: SliderThumb, next: number) =>
      (onChange as (n: number | [number, number]) => void)(moveSliderThumb(value, idx, next, { min, max, step })),
    [onChange, value, min, max, step],
  );

  const valueFromClientX = useCallback(
    (clientX: number) => {
      const track = trackRef.current;
      if (!track) return min;
      return sliderValueAt(clientX, track.getBoundingClientRect(), min, max);
    },
    [min, max],
  );

  const pickNearestIdx = useCallback(
    (clientX: number): SliderThumb => (range ? nearestSliderThumb(value, valueFromClientX(clientX)) : 0),
    [range, value, valueFromClientX],
  );

  const handlePointerDown = useCallback(
    (e: React.PointerEvent) => {
      if (disabled) return;
      e.preventDefault();
      const idx = pickNearestIdx(e.clientX);
      draggingIdx.current = idx;
      setActiveIdx(idx);
      // Capture on the actual element receiving the event so subsequent
      // moves keep firing even when the pointer leaves the track.
      (e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);
      emit(idx, valueFromClientX(e.clientX));
    },
    [disabled, pickNearestIdx, emit, valueFromClientX],
  );

  const handlePointerMove = useCallback(
    (e: React.PointerEvent) => {
      if (draggingIdx.current === null || disabled) return;
      emit(draggingIdx.current, valueFromClientX(e.clientX));
    },
    [disabled, emit, valueFromClientX],
  );

  const handlePointerUp = useCallback(() => {
    draggingIdx.current = null;
    setActiveIdx(null);
  }, []);

  const makeKeyDown = (idx: SliderThumb) =>
    (e: React.KeyboardEvent) => {
      if (disabled) return;
      const next = sliderKeyValue(e.key, idx === 0 ? v0 : v1, { min, max, step });
      if (next === undefined) return;
      e.preventDefault();
      emit(idx, next);
    };

  const pctOf = (n: number) => sliderPercent(n, min, max);
  const p0 = pctOf(v0);
  const p1 = pctOf(v1);
  const fill = sliderFill(value, min, max);

  const renderThumb = (idx: SliderThumb, pct: number, val: number) => (
    <React.Fragment key={idx}>
      <div
        role="slider"
        tabIndex={disabled ? -1 : 0}
        aria-valuemin={min}
        aria-valuemax={max}
        aria-valuenow={val}
        aria-label={sliderThumbLabel(label, range, idx)}
        aria-disabled={disabled}
        aria-required={range ? undefined : required || undefined}
        id={idx === 0 ? id : undefined}
        onKeyDown={makeKeyDown(idx)}
        onFocus={() => setActiveIdx(idx)}
        onBlur={() => setActiveIdx((cur) => (cur === idx ? null : cur))}
        className={c.thumb}
        style={{ left: sliderThumbLeft(pct) }}
      >
        {sliderTooltipVisible(showTooltip, activeIdx, idx) && (
          <span
            role="tooltip"
            className={c.tooltip}
          >
            {val}
          </span>
        )}
      </div>
    </React.Fragment>
  );

  // Tick positions — every step inside [min,max]. Cap at 50 to avoid
  // pathological DOM bloat when step is too small.
  const tickValues = useMemo(
    () => (ticks ? sliderTicks({ min, max, step }) : []),
    [ticks, min, max, step],
  );

  const trackBody = (
    <div
      ref={trackRef}
      role={range ? 'group' : undefined}
      aria-label={range ? label : undefined}
      className={c.track}
      onPointerDown={handlePointerDown}
      onPointerMove={handlePointerMove}
      onPointerUp={handlePointerUp}
      onPointerCancel={handlePointerUp}
    >
      <div
        className={c.fill}
        style={{ left: `${fill.left}%`, width: `${fill.width}%`, opacity: 0.8 }}
      />
      {renderThumb(0, p0, v0)}
      {range && renderThumb(1, p1, v1)}
    </div>
  );

  return (
    <div ref={ref} className={c.root}>
      {name && (
        range ? (
          <>
            <input type="hidden" name={`${name}[0]`} value={v0} required={required} />
            <input type="hidden" name={`${name}[1]`} value={v1} required={required} />
          </>
        ) : (
          <input type="hidden" name={name} value={v0} required={required} />
        )
      )}
      <div className={c.header}>
        <span>{label}</span>
        <span className={c.value}>{sliderValueText(value)}</span>
      </div>
      {trackBody}
      {ticks && tickValues.length > 0 && (
        <div className={c.ticks} aria-hidden>
          {tickValues.map((tv, i) => (
            <span
              key={i}
              data-testid="pxl-slider-tick"
              className={c.tick}
              style={{ left: `${pctOf(tv)}%` }}
            />
          ))}
        </div>
      )}
      {marks && marks.length > 0 && (
        <div className={c.marks} data-testid="pxl-slider-marks">
          {marks.map((m, i) => (
            <span
              key={i}
              className={c.mark}
              style={{ left: `${pctOf(m.value)}%` }}
            >
              {m.label}
            </span>
          ))}
        </div>
      )}
      {showMinMax && (
        <div className={c.bounds}>
          <span>{min}</span>
          <span>{max}</span>
        </div>
      )}
    </div>
  );
});

// packages/ui-kit-vue/src/forms/PixelSlider.vue
<script setup lang="ts" generic="T extends SliderValue">
import { computed, ref, useTemplateRef } from 'vue';
import {
  isSliderRange,
  moveSliderThumb,
  nearestSliderThumb,
  sliderClasses,
  sliderFill,
  sliderKeyValue,
  sliderPercent,
  sliderThumbLabel,
  sliderThumbLeft,
  sliderThumbValues,
  sliderTicks,
  sliderTooltipVisible,
  sliderValueAt,
  sliderValueText,
  type SliderThumb,
  type SliderTooltipMode,
  type SliderValue,
  type Surface,
  type Tone,
} from '@pxlkit/ui-kit-core';
import { RenderNode, type PxlNode } from '../_internal/render-node.js';
import { useEffectiveSurface } from '../composables/surface.js';

/** A labelled mark on the track. */
export interface PixelSliderMark {
  /** Value the mark sits at. */
  value: number;
  /** Its label: text, a VNode or a render function. */
  label: PxlNode;
}

/**
 * Slider with one thumb, or two bounding a range when its value is a
 * `[low, high]` pair — the lower thumb never passes the upper one. Drag the
 * thumbs or use the arrows (one step), PageUp / PageDown (ten steps), Home
 * and End. Optional marks, a tick per step and the values above the thumbs.
 * Bind the value with `v-model`; with a `name` hidden inputs submit it
 * (`name[0]` and `name[1]` for a range).
 */
export interface PixelSliderProps<T extends SliderValue = number> {
  /** Label above the track; also names the thumbs. */
  label: string;
  /** Value (`v-model`): a number, or a `[low, high]` pair for a range. */
  modelValue: T;
  /** Lowest value. */
  min?: number;
  /** Highest value. */
  max?: number;
  /** Distance between two values, counted from `min`: the slider takes `min`, `min + step`… up to `max`. */
  step?: number;
  /** Disables dragging and the keys and greys out the track. */
  disabled?: boolean;
  /** Tone of the fill and thumbs. */
  tone?: Tone;
  /** Shows `min` and `max` under the track. */
  showMinMax?: boolean;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
  /** Form field name of the hidden inputs. */
  name?: string;
  /** Marks the field as required for native form validation. */
  required?: boolean;
  /** `id` of the single (or lower) thumb. */
  id?: string;
  /** Labelled marks under the track. */
  marks?: PixelSliderMark[];
  /** When a thumb shows its value: `always`, while dragged or focused (`drag`), or `never`. */
  showTooltip?: SliderTooltipMode;
  /** Draws a tick under the track for every step. */
  ticks?: boolean;
}

const props = withDefaults(defineProps<PixelSliderProps<T>>(), {
  min: 0,
  max: 100,
  step: 1,
  disabled: false,
  tone: 'cyan',
  showMinMax: false,
  surface: undefined,
  name: undefined,
  required: false,
  id: undefined,
  marks: undefined,
  showTooltip: 'never',
  ticks: false,
});

const emit = defineEmits<{
  /** The new value, as a thumb is dragged or moved with the keys. */
  'update:modelValue': [value: T];
}>();

const surface = useEffectiveSurface(() => props.surface);
const classes = computed(() => sliderClasses(surface.value, { tone: props.tone, disabled: props.disabled }));
const bounds = computed(() => ({ min: props.min, max: props.max, step: props.step }));
const range = computed(() => isSliderRange(props.modelValue));
const thumbValues = computed(() => sliderThumbValues(props.modelValue));
const thumbs = computed<SliderThumb[]>(() => (range.value ? [0, 1] : [0]));
const fill = computed(() => sliderFill(props.modelValue, props.min, props.max));
const tickValues = computed(() => (props.ticks ? sliderTicks(bounds.value) : []));
const percent = (value: number) => sliderPercent(value, props.min, props.max);

const track = useTemplateRef<HTMLDivElement>('track');
// The thumb being dragged; the one dragged or focused shows a `drag` tooltip.
let dragging: SliderThumb | null = null;
const active = ref<SliderThumb | null>(null);

function moveThumb(thumb: SliderThumb, next: number) {
  emit('update:modelValue', moveSliderThumb(props.modelValue, thumb, next, bounds.value) as T);
}

function valueAt(clientX: number): number {
  if (!track.value) return props.min;
  return sliderValueAt(clientX, track.value.getBoundingClientRect(), props.min, props.max);
}

function onPointerDown(event: PointerEvent) {
  if (props.disabled) return;
  event.preventDefault();
  const thumb = range.value ? nearestSliderThumb(props.modelValue, valueAt(event.clientX)) : 0;
  dragging = thumb;
  active.value = thumb;
  // Captured, the track keeps getting the moves when the pointer leaves it.
  (event.currentTarget as HTMLElement).setPointerCapture(event.pointerId);
  moveThumb(thumb, valueAt(event.clientX));
}

function onPointerMove(event: PointerEvent) {
  if (dragging === null || props.disabled) return;
  moveThumb(dragging, valueAt(event.clientX));
}

function onPointerUp() {
  dragging = null;
  active.value = null;
}

function onKeydown(thumb: SliderThumb, event: KeyboardEvent) {
  if (props.disabled) return;
  const next = sliderKeyValue(event.key, thumbValues.value[thumb], bounds.value);
  if (next === undefined) return;
  event.preventDefault();
  moveThumb(thumb, next);
}

function onBlur(thumb: SliderThumb) {
  if (active.value === thumb) active.value = null;
}
</script>

<template>
  <div :class="classes.root">
    <template v-if="name">
      <template v-if="range">
        <input type="hidden" :name="`${name}[0]`" :value="thumbValues[0]" :required="required" />
        <input type="hidden" :name="`${name}[1]`" :value="thumbValues[1]" :required="required" />
      </template>
      <input v-else type="hidden" :name="name" :value="thumbValues[0]" :required="required" />
    </template>
    <div :class="classes.header">
      <span>{{ label }}</span>
      <span :class="classes.value">{{ sliderValueText(modelValue) }}</span>
    </div>
    <div
      ref="track"
      :role="range ? 'group' : undefined"
      :aria-label="range ? label : undefined"
      :class="classes.track"
      @pointerdown="onPointerDown"
      @pointermove="onPointerMove"
      @pointerup="onPointerUp"
      @pointercancel="onPointerUp"
    >
      <div :class="classes.fill" :style="{ left: `${fill.left}%`, width: `${fill.width}%`, opacity: 0.8 }" />
      <div
        v-for="thumb in thumbs"
        :id="thumb === 0 ? id : undefined"
        :key="thumb"
        role="slider"
        :tabindex="disabled ? -1 : 0"
        :aria-valuemin="min"
        :aria-valuemax="max"
        :aria-valuenow="thumbValues[thumb]"
        :aria-label="sliderThumbLabel(label, range, thumb)"
        :aria-disabled="disabled"
        :aria-required="range ? undefined : required || undefined"
        :class="classes.thumb"
        :style="{ left: sliderThumbLeft(percent(thumbValues[thumb])) }"
        @keydown="onKeydown(thumb, $event)"
        @focus="active = thumb"
        @blur="onBlur(thumb)"
      >
        <span v-if="sliderTooltipVisible(showTooltip, active, thumb)" role="tooltip" :class="classes.tooltip">
          {{ thumbValues[thumb] }}
        </span>
      </div>
    </div>
    <div v-if="ticks && tickValues.length > 0" :class="classes.ticks" aria-hidden="true">
      <span
        v-for="(tick, i) in tickValues"
        :key="i"
        data-testid="pxl-slider-tick"
        :class="classes.tick"
        :style="{ left: `${percent(tick)}%` }"
      />
    </div>
    <div v-if="marks && marks.length > 0" :class="classes.marks" data-testid="pxl-slider-marks">
      <span v-for="(mark, i) in marks" :key="i" :class="classes.mark" :style="{ left: `${percent(mark.value)}%` }">
        <RenderNode :node="mark.label" />
      </span>
    </div>
    <div v-if="showMinMax" :class="classes.bounds">
      <span>{{ min }}</span>
      <span>{{ max }}</span>
    </div>
  </div>
</template>
