// packages/ui-kit/src/forms/PixelToggle.tsx
'use client';

import React, {
  forwardRef,
  useCallback,
  useContext,
  useRef,
} from 'react';
import { toggleClasses } from '@pxlkit/ui-kit-core';
import {
  Surface,
  cn,
  useEffectiveSurface,
} from '../common';
import { useControllableState } from '../hooks/useControllableState';
import { ToggleGroupContext } from './PixelToggleGroup';

/** Public prop bag for {@link PixelToggle}. */
export interface PixelToggleProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  /** Identifies the toggle within its group; also exposed as `data-pxl-toggle-value`. */
  value: string;
  /** Standalone (uncontrolled) toggle: pressed state. */
  pressed?: boolean;
  /** Standalone (uncontrolled) toggle: notified on press change. */
  onPressedChange?: (next: boolean) => void;
  /** Surface override; defaults to the group's, then to the nearest provider. */
  surface?: Surface;
}

export const PixelToggle = forwardRef<HTMLButtonElement, PixelToggleProps>(
  function PixelToggle(
    {
      value,
      pressed,
      onPressedChange,
      surface: surfaceProp,
      className,
      children,
      onClick,
      onKeyDown,
      disabled,
      type: htmlType,
      ...rest
    },
    ref,
  ) {
    const group = useContext(ToggleGroupContext);

    const effectiveSurface = useEffectiveSurface(surfaceProp ?? group?.surface);

    // Controlled-by-group OR standalone (uses internal state via useControllableState)
    const [standalonePressed, setStandalonePressed] = useControllableState<boolean>({
      value: pressed,
      defaultValue: false,
      onChange: onPressedChange,
    });

    const isPressed = group ? group.isPressed(value) : standalonePressed;

    const localRef = useRef<HTMLButtonElement | null>(null);
    const setRefs = useCallback(
      (node: HTMLButtonElement | null) => {
        localRef.current = node;
        if (group) group.registerItem(node, value);
        if (typeof ref === 'function') ref(node);
        else if (ref) (ref as React.MutableRefObject<HTMLButtonElement | null>).current = node;
      },
      [ref, group, value],
    );

    // Unregister on unmount
    React.useEffect(() => {
      return () => {
        if (group) group.unregisterItem(value);
      };
      // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [value]);

    const handleClick = useCallback(
      (e: React.MouseEvent<HTMLButtonElement>) => {
        if (disabled) return;
        if (group) {
          group.toggleValue(value);
        } else {
          setStandalonePressed(!isPressed);
        }
        onClick?.(e);
      },
      [disabled, group, value, isPressed, setStandalonePressed, onClick],
    );

    const handleKeyDown = useCallback(
      (e: React.KeyboardEvent<HTMLButtonElement>) => {
        if (group) group.onItemKeyDown(e, value);
        onKeyDown?.(e);
      },
      [group, value, onKeyDown],
    );

    // Roving tabindex: only the focused item is tab-reachable when rovingFocus is on
    let tabIndex: number | undefined = rest.tabIndex;
    if (group?.rovingFocus) {
      const focused = group.focusedValue ?? null;
      tabIndex = focused === value ? 0 : -1;
    }

    // Single-select groups expose radio semantics; multi-select uses
    // aria-pressed button toggles. role on a <button> would normally be
    // redundant, but for single mode we MUST override to role="radio" so SR
    // users hear "one of N" semantics.
    const isSingleInGroup = group?.type === 'single';
    const ariaProps: React.AriaAttributes & { role?: 'radio' } = isSingleInGroup
      ? { role: 'radio', 'aria-checked': isPressed }
      : { 'aria-pressed': isPressed };

    return (
      <button
        ref={setRefs}
        type={htmlType ?? 'button'}
        {...ariaProps}
        data-state={isPressed ? 'on' : 'off'}
        data-pxl-toggle-value={value}
        disabled={disabled}
        tabIndex={tabIndex}
        onClick={handleClick}
        onKeyDown={handleKeyDown}
        className={cn(
          toggleClasses(effectiveSurface, {
            pressed: isPressed,
            size: group?.size ?? 'md',
            variant: group?.variant ?? 'soft',
          }),
          className,
        )}
        {...rest}
      >
        {children}
      </button>
    );
  },
);

PixelToggle.displayName = 'PixelToggle';

// packages/ui-kit-vue/src/forms/PixelToggle.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, useTemplateRef, type VNode } from 'vue';
import { toggleClasses, type Surface } from '@pxlkit/ui-kit-core';
import { useControllableState } from '../composables/controllable.js';
import { useEffectiveSurface } from '../composables/surface.js';
import { useToggleGroupContext } from './_internal/toggle-group-context.js';

/**
 * Two-state toggle `<button>` with `aria-pressed`. Standalone, bind its state
 * with `v-model:pressed` or leave it uncontrolled (starting unpressed). Inside
 * a `PixelToggleGroup` the group owns the state and the toggle takes on its
 * size, variant and surface — a radio of a single-select group, with roving
 * focus when the group asks for it. Extra attributes and listeners go to the
 * `<button>`.
 */
export interface PixelToggleProps {
  /** Identifies the toggle within its group; also exposed as `data-pxl-toggle-value`. */
  value: string;
  /** Pressed state of a standalone toggle (`v-model:pressed`); leave unset for an uncontrolled one. */
  pressed?: boolean;
  /** Surface override; defaults to the group's, then to the nearest provider. */
  surface?: Surface;
  /** Native `disabled`. */
  disabled?: boolean;
}

const props = withDefaults(defineProps<PixelToggleProps>(), {
  pressed: undefined,
  surface: undefined,
  disabled: false,
});

const emit = defineEmits<{
  /** The new pressed state of a standalone toggle, after each press. */
  'update:pressed': [pressed: boolean];
}>();
defineSlots<{ default?(): VNode[] }>();

const group = useToggleGroupContext();
const surface = useEffectiveSurface(() => props.surface ?? group?.surface.value);
const button = useTemplateRef<HTMLButtonElement>('button');
const [standalonePressed, setPressed] = useControllableState({
  value: () => props.pressed,
  defaultValue: () => false,
  onChange: (next) => emit('update:pressed', next),
});

const isPressed = computed(() => (group ? group.isPressed(props.value) : standalonePressed.value));
// A single-select group is a radiogroup: its toggles announce "one of N".
const radio = computed(() => group?.type.value === 'single');
const tabindex = computed(() => {
  if (!group?.rovingFocus.value) return undefined;
  return group.focusedValue.value === props.value ? 0 : -1;
});
const classes = computed(() =>
  toggleClasses(surface.value, {
    pressed: isPressed.value,
    size: group?.size.value ?? 'md',
    variant: group?.variant.value ?? 'soft',
  }),
);

onMounted(() => group?.registerItem(props.value, button.value!));
onBeforeUnmount(() => group?.unregisterItem(props.value));

function onClick() {
  if (props.disabled) return;
  if (group) group.toggle(props.value);
  else setPressed(!isPressed.value);
}

function onKeydown(event: KeyboardEvent) {
  group?.onItemKeydown(event, props.value);
}
</script>

<template>
  <button
    ref="button"
    type="button"
    :role="radio ? 'radio' : undefined"
    :aria-checked="radio ? isPressed : undefined"
    :aria-pressed="radio ? undefined : isPressed"
    :data-state="isPressed ? 'on' : 'off'"
    :data-pxl-toggle-value="value"
    :disabled="disabled"
    :tabindex="tabindex"
    :class="classes"
    @click="onClick"
    @keydown="onKeydown"
  >
    <slot />
  </button>
</template>
