// packages/ui-kit-angular/src/lib/forms/pixel-form-label.ts
import { Directive, computed, input } from '@angular/core';
import { formLabelClasses, type Surface } from '@pxlkit/ui-kit-core';
import { injectEffectiveSurface } from '../overlay-foundation/pxl-kit-surface-provider';
import { injectFormItem } from './form-context';

/**
 * The `<label>` of a `<pxl-form-item>`, pointing at its control.
 *
 * @example
 * <label pxlFormLabel>Email</label>
 */
@Directive({
  selector: 'label[pxlFormLabel]',
  host: {
    '[attr.for]': 'item.id',
    '[class]': 'classes()',
  },
})
export class PixelFormLabel {
  /** Surface override; defaults to the nearest provider. */
  readonly surface = input<Surface>();

  /** @internal */
  protected readonly item = injectFormItem('PixelFormLabel');
  private readonly effectiveSurface = injectEffectiveSurface(() => this.surface());
  /** @internal */
  protected readonly classes = computed(() => formLabelClasses(this.effectiveSurface()));
}

// packages/ui-kit-vue/src/forms/PixelFormLabel.vue
<script setup lang="ts">
import { computed, type VNode } from 'vue';
import { formLabelClasses, type Surface } from '@pxlkit/ui-kit-core';
import { useEffectiveSurface } from '../composables/surface.js';
import { useFormItem } from './_internal/form-context.js';

/** The `<label>` of a `PixelFormItem`, pointing at its control. Attributes go to the `<label>`. */
export interface PixelFormLabelProps {
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
}

const props = withDefaults(defineProps<PixelFormLabelProps>(), { surface: undefined });

defineSlots<{
  /** The label text. */
  default?(): VNode[];
}>();

const item = useFormItem('PixelFormLabel');
const surface = useEffectiveSurface(() => props.surface);
const classes = computed(() => formLabelClasses(surface.value));
</script>

<template>
  <label :for="item.id" :class="classes"><slot /></label>
</template>
