// packages/ui-kit/src/forms/PixelInputGroup.tsx
'use client';

import React, { forwardRef } from 'react';
import {
  INPUT_GROUP_UNNAMED_WARNING,
  inputGroupClasses,
  inputGroupItemClasses,
  inputGroupRole,
} from '@pxlkit/ui-kit-core';
import {
  Surface,
  cn,
  useEffectiveSurface,
} from '../common';

export interface PixelInputGroupProps extends React.HTMLAttributes<HTMLDivElement> {
  /** Height of the shell. */
  size?: 'sm' | 'md' | 'lg';
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
  /**
   * Accessible name for the group. Strongly recommended since this primitive
   * visually joins multiple form controls (e.g. country code + phone) — without
   * an accessible name a screen reader user has no idea what the group represents.
   * In development, a group of more than one child without a name logs a
   * warning.
   */
  'aria-label'?: string;
  /** Id of the element that names the group, in place of `aria-label`. */
  'aria-labelledby'?: string;
  /** The controls to join; each element is joined, text is dropped. */
  children: React.ReactNode;
}

export const PixelInputGroup = forwardRef<HTMLDivElement, PixelInputGroupProps>(
  function PixelInputGroup(
    { size = 'md', surface: surfaceProp, className, children, role, ...rest },
    ref,
  ) {
    const ariaLabel = (rest as { 'aria-label'?: string })['aria-label'];
    const ariaLabelledBy = (rest as { 'aria-labelledby'?: string })['aria-labelledby'];
    const hasName = !!(ariaLabel || ariaLabelledBy);
    const childCount = React.Children.count(children);

    if (process.env.NODE_ENV !== 'production' && childCount > 1 && !hasName) {
      // eslint-disable-next-line no-console
      console.warn(INPUT_GROUP_UNNAMED_WARNING);
    }
    const surface = useEffectiveSurface(surfaceProp);

    const items = React.Children.toArray(children).filter(React.isValidElement);
    const last = items.length - 1;

    const joined = items.map((child, i) => {
      const el = child as React.ReactElement<{
        className?: string;
        style?: React.CSSProperties;
      }>;
      return React.cloneElement(el, {
        ...(el.props as object),
        // Keep the original child className last so consumer styles win where needed.
        className: cn(inputGroupItemClasses(i === last), el.props.className),
      });
    });

    return (
      <div
        ref={ref}
        role={inputGroupRole(role, hasName)}
        className={cn(inputGroupClasses(surface, size), className)}
        {...rest}
      >
        {joined}
      </div>
    );
  },
);

PixelInputGroup.displayName = 'PixelInputGroup';

// packages/ui-kit-vue/src/forms/PixelInputGroup.vue
<script setup lang="ts">
import { computed, warn, type VNode } from 'vue';
import {
  INPUT_GROUP_UNNAMED_WARNING,
  inputGroupClasses,
  inputGroupItemClasses,
  inputGroupRole,
  type Size,
  type Surface,
} from '@pxlkit/ui-kit-core';
import { slotNodes } from '../_internal/Slot.js';
import { useEffectiveSurface } from '../composables/surface.js';

/**
 * Joins the form controls of its default slot (inputs, buttons, selects) into
 * one shell: each loses its own border and corners and gains a divider. Name
 * the group with `aria-label` or `aria-labelledby` — it is a `group` only
 * then. Extra attributes go to the shell `<div>`.
 */
export interface PixelInputGroupProps {
  /** Height of the shell. */
  size?: Size;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
  /** Role of the shell; `group` when named and left out. */
  role?: string;
  /** Accessible name of the group — strongly recommended. */
  ariaLabel?: string;
  /** Id of the element that names the group. */
  ariaLabelledby?: string;
}

const props = withDefaults(defineProps<PixelInputGroupProps>(), {
  size: 'md',
  surface: undefined,
  role: undefined,
  ariaLabel: undefined,
  ariaLabelledby: undefined,
});
const slots = defineSlots<{
  /** The controls to join; each element is joined, text is dropped. */
  default?(): VNode[];
}>();

const surface = useEffectiveSurface(() => props.surface);
const named = computed(() => !!(props.ariaLabel || props.ariaLabelledby));

// Read while rendering, like the React kit's cloneElement: each element of
// the slot is rendered with the join classes merged into its own.
function controls() {
  const nodes = slotNodes(slots.default?.());
  if (nodes.length > 1 && !named.value) warn(INPUT_GROUP_UNNAMED_WARNING);
  const elements = nodes.filter((node) => typeof node.type !== 'symbol');
  return elements.map((node, index) => ({
    node,
    class: inputGroupItemClasses(index === elements.length - 1),
  }));
}
</script>

<template>
  <div
    :role="inputGroupRole(role, named)"
    :aria-label="ariaLabel"
    :aria-labelledby="ariaLabelledby"
    :class="inputGroupClasses(surface, size)"
  >
    <component :is="control.node" v-for="(control, index) in controls()" :key="index" :class="control.class" />
  </div>
</template>
