// packages/ui-kit/src/forms/PixelNumberInput.tsx
'use client';

import React, { forwardRef, useCallback, useEffect, useId, useRef, useState } from 'react';
import {
  clampNumber,
  fieldDescribedBy,
  fieldMessageId,
  formatNumberInput,
  numberInputAtLimit,
  numberInputClasses,
  parseNumberInput,
  settleNumberInput,
  stepNumberInput,
} from '@pxlkit/ui-kit-core';
import {
  Surface,
  Tone,
  cn,
  useEffectiveSurface,
  FieldShell,
} from '../common';
import { useControllableState } from '../hooks/useControllableState';

type NumSize = 'sm' | 'md' | 'lg';

export interface PixelNumberInputProps
  extends Omit<
    React.InputHTMLAttributes<HTMLInputElement>,
    'value' | 'defaultValue' | 'onChange' | 'type' | 'size'
  > {
  /** Value; leave unset for an uncontrolled field. */
  value?: number;
  /** Initial value while uncontrolled. */
  defaultValue?: number;
  /**
   * Called with the new number, after each step, edit that reads as a number, or settle on blur.
   */
  onChange?: (next: number) => void;
  /** Lowest value. */
  min?: number;
  /** Highest value. */
  max?: number;
  /** Amount each step adds or removes. */
  step?: number;
  /** Decimals shown, and the value is rounded to. */
  precision?: number;
  /** When a value outside `min` / `max` is pulled back: while typing, on blur, or never. */
  clampBehavior?: 'strict' | 'blur' | 'none';
  /** Text inside the field on the left (`$`). */
  prefix?: string;
  /** Text inside the field on the right (`USD`). */
  suffix?: string;
  /** Groups the integer digits (`,` shows `1,500,000`). */
  thousandsSeparator?: string;
  /** Accepts negative numbers. */
  allowNegative?: boolean;
  /** Hides the stepper buttons. */
  hideControls?: boolean;
  /** Field height. */
  size?: NumSize;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
  /** Tone of the focus ring. */
  tone?: Tone;
  /** Label rendered above the field. */
  label?: string;
  /** Helper text below the field; hidden while `error` is set. */
  hint?: string;
  /** Error message below the field; marks the input invalid. */
  error?: string;
}

export const PixelNumberInput = forwardRef<HTMLInputElement, PixelNumberInputProps>(
  function PixelNumberInput(
    {
      value,
      defaultValue,
      onChange,
      min,
      max,
      step = 1,
      precision,
      clampBehavior = 'blur',
      prefix,
      suffix,
      thousandsSeparator,
      allowNegative = true,
      hideControls = false,
      size = 'md',
      surface: surfaceProp,
      tone = 'neutral',
      label,
      hint,
      error,
      className,
      disabled,
      name,
      id,
      placeholder,
      onBlur,
      onFocus,
      onKeyDown,
      'aria-describedby': ariaDescribedBy,
      ...rest
    },
    ref,
  ) {
    const surface = useEffectiveSurface(surfaceProp);

    const initial: number | undefined =
      value !== undefined ? value : defaultValue;

    // Single source-of-truth for the numeric model.
    const [current, setCurrent] = useControllableState<number | undefined>({
      value,
      defaultValue: initial,
      onChange: (next) => {
        if (typeof next === 'number' && !Number.isNaN(next)) onChange?.(next);
      },
    });

    // Display string — what the user actually sees. Decoupled while focused
    // so partial inputs like "" or "-" don't snap back.
    const [display, setDisplay] = useState<string>(() =>
      formatNumberInput(current, precision, thousandsSeparator),
    );
    const focusedRef = useRef(false);

    // Keep display in sync with controlled `current` when not focused.
    useEffect(() => {
      if (!focusedRef.current) {
        setDisplay(formatNumberInput(current, precision, thousandsSeparator));
      }
    }, [current, precision, thousandsSeparator]);

    const commit = useCallback(
      (next: number | undefined) => {
        setCurrent(next as number);
      },
      [setCurrent],
    );

    const bump = useCallback(
      (direction: 1 | -1) => {
        if (disabled) return;
        const next = stepNumberInput(current, direction, step, { min, max, precision });
        commit(next);
        // The display does not follow the value while focused, so a step
        // taken from the keyboard shows its result itself.
        if (focusedRef.current) setDisplay(formatNumberInput(next, precision, thousandsSeparator));
      },
      [current, disabled, step, min, max, precision, thousandsSeparator, commit],
    );

    const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
      const { text, num } = parseNumberInput(e.target.value, thousandsSeparator, allowNegative);
      // Always reflect what the user typed (after minus-strip / separator-strip)
      setDisplay(text);

      if (num === undefined) {
        // partial input — don't fire onChange yet
        return;
      }

      let next = num;
      if (clampBehavior === 'strict') {
        next = clampNumber(next, min, max);
        // sync display if clamp actually moved the value
        if (next !== num) {
          setDisplay(formatNumberInput(next, precision, thousandsSeparator));
        }
      }
      commit(next);
    };

    const handleBlur = (e: React.FocusEvent<HTMLInputElement>) => {
      focusedRef.current = false;
      if (typeof current === 'number') {
        const next = settleNumberInput(current, clampBehavior, { min, max, precision });
        if (next !== current) commit(next);
        setDisplay(formatNumberInput(next, precision, thousandsSeparator));
      } else {
        setDisplay('');
      }
      onBlur?.(e);
    };

    const handleFocus = (e: React.FocusEvent<HTMLInputElement>) => {
      focusedRef.current = true;
      onFocus?.(e);
    };

    const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
      if (e.key === 'ArrowUp') {
        e.preventDefault();
        bump(1);
      } else if (e.key === 'ArrowDown') {
        e.preventDefault();
        bump(-1);
      }
      onKeyDown?.(e);
    };

    const reactId = useId();
    const inputId = id ?? `pxl-number-${reactId}`;
    const c = numberInputClasses(surface, {
      tone,
      size,
      invalid: !!error,
      prefix: !!prefix,
      suffix: !!suffix,
      hideControls,
    });

    return (
      <FieldShell label={label} hint={hint} error={error} surface={surface} htmlFor={inputId} messageId={fieldMessageId(inputId)}>
        <span className={c.shell}>
          {prefix && (
            <span aria-hidden className={c.prefix}>
              {prefix}
            </span>
          )}
          <input
            ref={ref}
            id={inputId}
            type="text"
            inputMode="decimal"
            role="spinbutton"
            aria-valuemin={typeof min === 'number' ? min : undefined}
            aria-valuemax={typeof max === 'number' ? max : undefined}
            aria-valuenow={typeof current === 'number' ? current : undefined}
            aria-invalid={error ? true : undefined}
            aria-describedby={fieldDescribedBy(inputId, { hint, error }, ariaDescribedBy)}
            disabled={disabled}
            placeholder={placeholder}
            value={display}
            onChange={handleChange}
            onBlur={handleBlur}
            onFocus={handleFocus}
            onKeyDown={handleKeyDown}
            className={cn(c.input, className)}
            {...rest}
          />
          {suffix && (
            <span aria-hidden className={c.suffix}>
              {suffix}
            </span>
          )}
          {!hideControls && (
            <span className={c.controls}>
              <button
                type="button"
                tabIndex={-1}
                aria-label="Increment"
                disabled={disabled || numberInputAtLimit(current, 1, { min, max })}
                onClick={() => bump(1)}
                className={c.stepper}
              >
                ▲
              </button>
              <button
                type="button"
                tabIndex={-1}
                aria-label="Decrement"
                disabled={disabled || numberInputAtLimit(current, -1, { min, max })}
                onClick={() => bump(-1)}
                className={c.stepper}
              >
                ▼
              </button>
            </span>
          )}
          {/* Hidden mirror for native form serialization. */}
          {name && (
            <input
              type="hidden"
              name={name}
              value={typeof current === 'number' ? String(current) : ''}
            />
          )}
        </span>
      </FieldShell>
    );
  },
);

PixelNumberInput.displayName = 'PixelNumberInput';

// packages/ui-kit-vue/src/forms/PixelNumberInput.vue
<script setup lang="ts">
import { computed, ref, useId, useTemplateRef, watch } from 'vue';
import {
  clampNumber,
  formatNumberInput,
  numberInputAtLimit,
  numberInputClasses,
  parseNumberInput,
  settleNumberInput,
  stepNumberInput,
  type NumberInputClampBehavior,
  type Size,
  type Surface,
  type Tone,
} from '@pxlkit/ui-kit-core';
import FieldShell from '../_internal/FieldShell.vue';
import { useControllableState } from '../composables/controllable.js';
import { useEffectiveSurface } from '../composables/surface.js';

/**
 * Numeric field (`role="spinbutton"`) with ArrowUp / ArrowDown and stepper
 * buttons, min / max clamping, precision, a prefix and suffix, and a
 * thousands separator. Bind its value with `v-model`, or leave it
 * uncontrolled with `default-value`. With a `name` a hidden input submits the
 * number in forms. Extra attributes and listeners go to the `<input>`.
 */
export interface PixelNumberInputProps {
  /** Value (`v-model`); leave unset for an uncontrolled field. */
  modelValue?: number;
  /** Initial value while uncontrolled. */
  defaultValue?: number;
  /** Lowest value. */
  min?: number;
  /** Highest value. */
  max?: number;
  /** Amount each step adds or removes. */
  step?: number;
  /** Decimals shown, and the value is rounded to. */
  precision?: number;
  /** When a value outside `min` / `max` is pulled back: while typing, on blur, or never. */
  clampBehavior?: NumberInputClampBehavior;
  /** Text inside the field on the left (`$`). */
  prefix?: string;
  /** Text inside the field on the right (`USD`). */
  suffix?: string;
  /** Groups the integer digits (`,` shows `1,500,000`). */
  thousandsSeparator?: string;
  /** Accepts negative numbers. */
  allowNegative?: boolean;
  /** Hides the stepper buttons. */
  hideControls?: boolean;
  /** Field height. */
  size?: Size;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
  /** Tone of the focus ring. */
  tone?: Tone;
  /** Label rendered above the field. */
  label?: string;
  /** Helper text below the field; hidden while `error` is set. */
  hint?: string;
  /** Error message below the field; marks the input invalid. */
  error?: string;
  /** Disables the field and its steppers. */
  disabled?: boolean;
  /** Form field name — a hidden input submits the number. */
  name?: string;
  /** `id` of the input; generated when left out. */
  id?: string;
  /** Text shown while the field is empty. */
  placeholder?: string;
}

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<PixelNumberInputProps>(), {
  modelValue: undefined,
  defaultValue: undefined,
  min: undefined,
  max: undefined,
  step: 1,
  precision: undefined,
  clampBehavior: 'blur',
  prefix: undefined,
  suffix: undefined,
  thousandsSeparator: undefined,
  allowNegative: true,
  hideControls: false,
  size: 'md',
  surface: undefined,
  tone: 'neutral',
  label: undefined,
  hint: undefined,
  error: undefined,
  disabled: false,
  name: undefined,
  id: undefined,
  placeholder: undefined,
});

const emit = defineEmits<{
  /** The new number, after each step, edit that reads as a number, or settle on blur. */
  'update:modelValue': [value: number];
}>();

const surface = useEffectiveSurface(() => props.surface);
const generatedId = useId();
const inputId = computed(() => props.id ?? `pxl-number-${generatedId}`);
const input = useTemplateRef<HTMLInputElement>('input');

const [current, setCurrent] = useControllableState<number | undefined>({
  value: () => props.modelValue,
  defaultValue: () => props.modelValue ?? props.defaultValue,
  onChange: (next) => {
    if (typeof next === 'number' && !Number.isNaN(next)) emit('update:modelValue', next);
  },
});

const limits = computed(() => ({ min: props.min, max: props.max, precision: props.precision }));
const format = (value: number | undefined) => formatNumberInput(value, props.precision, props.thousandsSeparator);

// What the field shows. It does not follow the value while focused, so
// partial input such as "" or "-" survives typing.
const display = ref(format(current.value));
let focused = false;
watch([current, () => props.precision, () => props.thousandsSeparator], () => {
  if (!focused) display.value = format(current.value);
});

const classes = computed(() =>
  numberInputClasses(surface.value, {
    tone: props.tone,
    size: props.size,
    invalid: !!props.error,
    prefix: !!props.prefix,
    suffix: !!props.suffix,
    hideControls: props.hideControls,
  }),
);

function bump(direction: 1 | -1) {
  if (props.disabled) return;
  const next = stepNumberInput(current.value, direction, props.step, limits.value);
  setCurrent(next);
  // A step taken from the keyboard shows its result itself.
  if (focused) display.value = format(next);
}

// A stepper at its bound is disabled: like any disabled button, it ignores clicks.
function stepFromButton(direction: 1 | -1) {
  if (!numberInputAtLimit(current.value, direction, limits.value)) bump(direction);
}

function onInput(event: Event) {
  const { text, num } = parseNumberInput((event.target as HTMLInputElement).value, props.thousandsSeparator, props.allowNegative);
  display.value = text;
  if (num === undefined) return;
  let next = num;
  if (props.clampBehavior === 'strict') {
    next = clampNumber(next, props.min, props.max);
    if (next !== num) display.value = format(next);
  }
  setCurrent(next);
}

function onFocus() {
  focused = true;
}

function onBlur() {
  focused = false;
  const value = current.value;
  if (typeof value === 'number') {
    const next = settleNumberInput(value, props.clampBehavior, limits.value);
    if (next !== value) setCurrent(next);
    display.value = format(next);
  } else {
    display.value = '';
  }
}

function onKeydown(event: KeyboardEvent) {
  if (event.key === 'ArrowUp') {
    event.preventDefault();
    bump(1);
  } else if (event.key === 'ArrowDown') {
    event.preventDefault();
    bump(-1);
  }
}

defineExpose({
  /** The native input. */
  element: input,
});
</script>

<template>
  <FieldShell :label="label" :hint="hint" :error="error" :surface="surface" :html-for="inputId">
    <span :class="classes.shell">
      <span v-if="prefix" aria-hidden="true" :class="classes.prefix">{{ prefix }}</span>
      <input
        :id="inputId"
        ref="input"
        type="text"
        inputmode="decimal"
        role="spinbutton"
        :aria-valuemin="min"
        :aria-valuemax="max"
        :aria-valuenow="current"
        :aria-invalid="error ? true : undefined"
        :disabled="disabled"
        :placeholder="placeholder"
        :value="display"
        :class="classes.input"
        v-bind="$attrs"
        @input="onInput"
        @blur="onBlur"
        @focus="onFocus"
        @keydown="onKeydown"
      />
      <span v-if="suffix" aria-hidden="true" :class="classes.suffix">{{ suffix }}</span>
      <span v-if="!hideControls" :class="classes.controls">
        <button
          type="button"
          tabindex="-1"
          aria-label="Increment"
          :disabled="disabled || numberInputAtLimit(current, 1, limits)"
          :class="classes.stepper"
          @click="stepFromButton(1)"
        >
          ▲
        </button>
        <button
          type="button"
          tabindex="-1"
          aria-label="Decrement"
          :disabled="disabled || numberInputAtLimit(current, -1, limits)"
          :class="classes.stepper"
          @click="stepFromButton(-1)"
        >
          ▼
        </button>
      </span>
      <input v-if="name" type="hidden" :name="name" :value="typeof current === 'number' ? String(current) : ''" />
    </span>
  </FieldShell>
</template>
