// packages/ui-kit-angular/src/lib/forms/pixel-form.ts
import { Directive, computed, inject, input, output, signal } from '@angular/core';
import type { FormGroup } from '@angular/forms';
import { formClasses, type Surface } from '@pxlkit/ui-kit-core';
import { injectEffectiveSurface } from '../overlay-foundation/pxl-kit-surface-provider';
import { PIXEL_FORM, type PixelFormContext, type PixelFormFieldEntry } from './form-context';

/**
 * Validated form on Angular reactive forms: give the `<form>` its
 * `FormGroup` — validators live on its controls — and compose
 * `[pxlFormField]`, `<pxl-form-item>`, `label[pxlFormLabel]`,
 * `[pxlFormControl]`, `p[pxlFormDescription]` and `<pxl-form-message>`
 * inside. The parts bind the controls themselves: no `formGroup` or
 * `formControlName` (whose status classes the React kit does not render).
 * Submitting shows every field's error and focuses the first field with
 * one; without errors, `(submitted)` emits the form's value. After the first
 * submission errors follow the values as they change, never blur.
 *
 * @example
 * <form [pxlForm]="form" (submitted)="save($event)">…</form>
 */
@Directive({
  selector: 'form[pxlForm]',
  exportAs: 'pxlForm',
  providers: [{ provide: PIXEL_FORM, useFactory: () => inject(PixelForm).context }],
  host: {
    novalidate: '',
    '[class]': 'classes()',
    '(submit)': 'onSubmit($event)',
  },
})
export class PixelForm<TGroup extends FormGroup = FormGroup> {
  /** The form's model. */
  readonly group = input.required<TGroup>({ alias: 'pxlForm' });
  /** Surface override; defaults to the nearest provider. */
  readonly surface = input<Surface>();
  /** The form's value, once a submission finds no error (pending validators are waited for). */
  readonly submitted = output<TGroup['value']>();

  private readonly effectiveSurface = injectEffectiveSurface(() => this.surface());
  /** @internal */
  protected readonly classes = computed(() => formClasses(this.effectiveSurface()));
  private readonly wasSubmitted = signal(false);
  private readonly fields: PixelFormFieldEntry[] = [];

  /** @internal Shared with the fields. */
  readonly context: PixelFormContext = {
    group: this.group,
    submitted: this.wasSubmitted.asReadonly(),
    register: (field) => {
      this.fields.push(field);
      return () => {
        const index = this.fields.indexOf(field);
        if (index >= 0) this.fields.splice(index, 1);
      };
    },
  };

  /** Resets the form's values (to `value`, or the initial ones) and hides its errors until the next submission. */
  reset(value?: unknown): void {
    this.group().reset(value);
    this.wasSubmitted.set(false);
  }

  /** @internal */
  protected onSubmit(event: Event): void {
    event.preventDefault();
    this.wasSubmitted.set(true);
    const group = this.group();
    if (!group.pending) {
      this.settle(group);
      return;
    }
    const subscription = group.statusChanges.subscribe((status) => {
      if (status === 'PENDING') return;
      subscription.unsubscribe();
      this.settle(group);
    });
  }

  private settle(group: TGroup): void {
    if (!group.invalid) {
      this.submitted.emit(group.value);
      return;
    }
    // The first field with an error that has a control takes focus.
    for (const field of this.fields) {
      if (field.control()?.invalid && field.focus()) return;
    }
  }
}

// packages/ui-kit-vue/src/forms/PixelForm.vue
<script setup lang="ts" generic="TValues extends GenericObject">
import { computed, provide, useTemplateRef, type VNode } from 'vue';
import type { FormContext, GenericObject } from 'vee-validate';
import { formClasses, type Surface } from '@pxlkit/ui-kit-core';
import { useEffectiveSurface } from '../composables/surface.js';
import { PIXEL_FORM, type PixelFormFieldEntry } from './_internal/form-context.js';

/**
 * Validated form on VeeValidate: pass it the form `useForm` returns, and
 * compose `PixelFormField` / `PixelFormItem` / `PixelFormLabel` /
 * `PixelFormControl` / `PixelFormDescription` / `PixelFormMessage` inside.
 * Submitting validates every field: with errors, they show and the first
 * field with one takes focus; without, `@submit` gets the values. After the
 * first submission a field validates again as it changes, never on blur.
 * Call `useForm` in the component that renders the form, so its fields find
 * it. Extra attributes and listeners go to the `<form>`.
 *
 * @example
 * const form = useForm({ initialValues: { email: '' } });
 * <PixelForm :form="form" @submit="save">…</PixelForm>
 */
export interface PixelFormProps<TValues extends GenericObject = GenericObject> {
  /** The form: what VeeValidate's `useForm` returns. */
  form: FormContext<TValues>;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
}

const props = withDefaults(defineProps<PixelFormProps<TValues>>(), { surface: undefined });

const emit = defineEmits<{
  /** The form's values, once a submission finds no error. */
  submit: [values: TValues];
}>();

defineSlots<{
  /** The fields. */
  default?(): VNode[];
}>();

const surface = useEffectiveSurface(() => props.surface);
const classes = computed(() => formClasses(surface.value));
const element = useTemplateRef<HTMLFormElement>('element');

const fields: PixelFormFieldEntry[] = [];
provide(PIXEL_FORM, {
  register(field) {
    fields.push(field);
    return () => {
      const index = fields.indexOf(field);
      if (index >= 0) fields.splice(index, 1);
    };
  },
});

/** Focuses the control of the first field with an error, in the order the fields were set up. */
function focusFirstError(hasError: (name: string) => boolean) {
  for (const field of fields) {
    const id = field.controlId();
    if (!id || !hasError(field.name())) continue;
    const control = element.value?.querySelector<HTMLElement>(`[id="${id}"]`);
    if (!control) continue;
    control.focus();
    return;
  }
}

function onSubmit(event: Event) {
  event.preventDefault();
  void props.form.handleSubmit(
    (values) => emit('submit', values as TValues),
    ({ errors }) => focusFirstError((name) => !!errors[name as keyof typeof errors]),
  )();
}
</script>

<template>
  <form ref="element" novalidate :class="classes" @submit="onSubmit">
    <slot />
  </form>
</template>
