// packages/ui-kit/src/data/PixelTimeline.examples.tsx
import React from 'react';
import { PixelTimeline, PixelTimelineItem } from './PixelTimeline';

export function Default() {
  return (
    <PixelTimeline active={1}>
      <PixelTimelineItem title="Order placed" time="09:00">
        Confirmation email sent.
      </PixelTimelineItem>
      <PixelTimelineItem title="Packed" time="11:20">
        At the warehouse.
      </PixelTimelineItem>
      <PixelTimelineItem title="Shipped" time="—">
        Awaiting carrier pickup.
      </PixelTimelineItem>
    </PixelTimeline>
  );
}

export function Dashed() {
  return (
    <PixelTimeline active={0} bulletSize="lg">
      <PixelTimelineItem title="Draft" lineVariant="dashed">
        Currently editing.
      </PixelTimelineItem>
      <PixelTimelineItem title="Review" lineVariant="dashed">
        Pending approval.
      </PixelTimelineItem>
      <PixelTimelineItem title="Published" lineVariant="dashed" />
    </PixelTimeline>
  );
}

export function RightAligned() {
  return (
    <PixelTimeline active={2} align="right">
      <PixelTimelineItem title="Step 1" time="Mon" />
      <PixelTimelineItem title="Step 2" time="Tue" />
      <PixelTimelineItem title="Step 3" time="Wed" />
    </PixelTimeline>
  );
}

// packages/ui-kit-angular/examples/data/pixel-timeline.examples.ts
import { Component } from '@angular/core';
import { PixelTimeline, PixelTimelineItem } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelTimeline, PixelTimelineItem],
  template: `
    <ol pxlTimeline [active]="1">
      <li pxlTimelineItem title="Order placed" time="09:00" description="Confirmation email sent."></li>
      <li pxlTimelineItem title="Packed" time="11:20" description="At the warehouse."></li>
      <li pxlTimelineItem title="Shipped" time="—" description="Awaiting carrier pickup."></li>
    </ol>
  `,
})
export class Default {}

@Component({
  imports: [PixelTimeline, PixelTimelineItem],
  template: `
    <ol pxlTimeline [active]="0" bulletSize="lg">
      <li pxlTimelineItem title="Draft" lineVariant="dashed" description="Currently editing."></li>
      <li pxlTimelineItem title="Review" lineVariant="dashed" description="Pending approval."></li>
      <li pxlTimelineItem title="Published" lineVariant="dashed"></li>
    </ol>
  `,
})
export class Dashed {}

@Component({
  imports: [PixelTimeline, PixelTimelineItem],
  template: `
    <ol pxlTimeline [active]="2" align="right">
      <li pxlTimelineItem title="Step 1" time="Mon"></li>
      <li pxlTimelineItem title="Step 2" time="Tue"></li>
      <li pxlTimelineItem title="Step 3" time="Wed"></li>
    </ol>
  `,
})
export class RightAligned {}
