// packages/ui-kit-vue/src/animations/PixelPulse.vue
<script setup lang="ts">
import { computed, useTemplateRef, type VNode } from 'vue';
import { pulseStyle, type AnimationRepeat, type AnimationTrigger } from '@pxlkit/ui-kit-core';
import { useAnimationTrigger } from './_internal/animation-trigger.js';

/**
 * Gently scales and dims its content in a recurring pulse, to draw
 * attention. It plays as `trigger` says and holds still when the user
 * prefers reduced motion. Attributes fall through to the wrapping `<div>`.
 *
 * @example
 * <PixelPulse :duration="1000"><span>Quick Pulse</span></PixelPulse>
 */
export interface PixelPulseProps {
  /** Animation duration in milliseconds. */
  duration?: number;
  /** Iteration count: a number or `'infinite'`. */
  repeat?: AnimationRepeat;
  /** CSS `animation-timing-function`. */
  easing?: string;
  /**
   * When the animation plays: `'mount'`, `'hover'`, `'click'`, `'focus'`,
   * `'inView'`, or `true` / `false` to control it.
   */
  trigger?: AnimationTrigger;
}

const props = withDefaults(defineProps<PixelPulseProps>(), {
  duration: 2000,
  repeat: 'infinite',
  easing: 'ease-in-out',
  trigger: 'mount',
});
const emit = defineEmits<{
  /** After the final iteration. */
  complete: [];
}>();
defineSlots<{
  /** Content to pulse. */
  default?(): VNode[];
}>();

const element = useTemplateRef<HTMLElement>('element');
const { active, listeners, ended } = useAnimationTrigger(element, () => props.trigger, () => emit('complete'));
const style = computed(() => (active.value ? pulseStyle(props) : undefined));
</script>

<template>
  <div ref="element" :style="style" v-on="listeners" @animationend="ended">
    <slot />
  </div>
</template>

// packages/ui-kit-angular/src/lib/animations/pixel-pulse.ts
import { ChangeDetectionStrategy, Component, computed, input, output, ViewEncapsulation } from '@angular/core';
import { pulseStyle, type AnimationRepeat, type AnimationTrigger } from '@pxlkit/ui-kit-core';
import { numberOr, withDefault } from '../_internal/coercion';
import { injectAnimationTrigger } from './_internal/animation-trigger';
import { repeatOr } from './_internal/repeat';

/**
 * Gently scales and dims its content in a recurring pulse, to draw
 * attention. It plays as `trigger` says and holds still when the user
 * prefers reduced motion. The host is the pulsing wrapper.
 *
 * @example
 * <pxl-pulse [duration]="1000"><span>Quick Pulse</span></pxl-pulse>
 */
@Component({
  selector: 'pxl-pulse',
  changeDetection: ChangeDetectionStrategy.OnPush,
  // The host stands for React's <div>: a block box, which transforms apply
  // to. In the base layer, so display utilities set on it still win.
  encapsulation: ViewEncapsulation.None,
  styles: '@layer base { pxl-pulse { display: block; } }',
  host: {
    '[style]': 'style()',
    '(animationend)': 'animation.ended($event)',
  },
  template: '<ng-content />',
})
export class PixelPulse {
  /** Animation duration in milliseconds. */
  readonly duration = input(2000, { transform: numberOr(2000) });
  /** Iteration count: a number or `'infinite'`. */
  readonly repeat = input<AnimationRepeat, AnimationRepeat | `${number}` | undefined>('infinite', {
    transform: repeatOr('infinite'),
  });
  /** CSS `animation-timing-function`. */
  readonly easing = input<string, string | undefined>('ease-in-out', { transform: withDefault('ease-in-out') });
  /**
   * When the animation plays: `'mount'`, `'hover'`, `'click'`, `'focus'`,
   * `'inView'`, or `true` / `false` to control it.
   */
  readonly trigger = input<AnimationTrigger, AnimationTrigger | undefined>('mount', {
    transform: withDefault<AnimationTrigger>('mount'),
  });
  /** After the final iteration. */
  readonly complete = output<void>();

  /** @internal */
  protected readonly animation = injectAnimationTrigger(
    () => this.trigger(),
    () => this.complete.emit(),
  );
  /** @internal */
  protected readonly style = computed(() =>
    this.animation.active()
      ? pulseStyle({ duration: this.duration(), repeat: this.repeat(), easing: this.easing() })
      : null,
  );
}
