// packages/ui-kit/src/data-display/PixelStatCard.tsx
import React from 'react';
import {
  Tone, Surface, cn,
  toneMap, surfaceClasses, useEffectiveSurface,
} from '../common';

/* ─────────────────────────────────────────────────────────────────────────
   PixelStatCard — compact metric card.

   Upgraded (Ola 2) additively: optional `size` (sm/md/lg) scales padding +
   font sizes; optional `iconPosition` (left/right/top/bottom-left) controls
   where the icon renders. Defaults preserve the legacy layout.
   ───────────────────────────────────────────────────────────────────────── */

export type PixelStatCardSize = 'sm' | 'md' | 'lg';
export type PixelStatCardIconPosition = 'left' | 'right' | 'top' | 'bottom-left';

export interface PixelStatCardProps {
  /** Caption rendered above the value. */
  label: string;
  /** Primary metric value. */
  value: string;
  /** Optional leading icon. */
  icon?: React.ReactNode;
  /** Tone tint for border, soft background, and icon color. */
  tone?: Tone;
  /** Optional trend/delta line rendered under the value. */
  trend?: string;
  /** Visual surface override. */
  surface?: Surface;
  /** Padding + typography scale. Defaults to `'md'`. */
  size?: PixelStatCardSize;
  /** Icon placement relative to label/value. Defaults to `'top'`. */
  iconPosition?: PixelStatCardIconPosition;
  /** Render with surface-aware border + radius chrome. Defaults to true — a stat card needs visible chrome. */
  bordered?: boolean;
}

export function PixelStatCard({
  label,
  value,
  icon,
  tone = 'gold',
  trend,
  surface: surfaceProp,
  size = 'md',
  iconPosition = 'top',
  bordered = true,
}: PixelStatCardProps) {
  const surface = useEffectiveSurface(surfaceProp);
  const s = surfaceClasses(surface);

  const padding = size === 'sm' ? 'p-3' : size === 'lg' ? 'p-6' : 'p-4';
  const labelSize = size === 'sm' ? 'text-[10px]' : size === 'lg' ? 'text-sm' : 'text-xs';
  const valueSize =
    surface === 'pixel'
      ? (size === 'sm' ? 'text-xs font-pixel' : size === 'lg' ? 'text-lg font-pixel' : 'text-sm font-pixel')
      : (size === 'sm' ? 'text-sm font-semibold' : size === 'lg' ? 'text-2xl font-semibold' : 'text-base font-semibold');
  const trendSize = size === 'sm' ? 'text-[10px]' : size === 'lg' ? 'text-sm' : 'text-xs';
  const iconBoxSize = size === 'sm' ? 'text-xs' : size === 'lg' ? 'text-lg' : 'text-sm';
  const valueGap = size === 'sm' ? 'mt-1.5' : size === 'lg' ? 'mt-3' : 'mt-2';
  const trendGap = size === 'sm' ? 'mt-1.5' : size === 'lg' ? 'mt-3' : 'mt-2';

  const labelEl = <p className={cn(labelSize, 'text-retro-muted', s.font)}>{label}</p>;
  const valueEl = <p className={cn('text-retro-text', valueSize)}>{value}</p>;
  const iconEl = icon ? (
    <span className={cn('inline-flex items-center justify-center shrink-0', iconBoxSize, toneMap[tone].text)}>{icon}</span>
  ) : null;
  const trendEl = trend ? <p className={cn(trendGap, trendSize, 'text-retro-muted', s.font)}>{trend}</p> : null;

  const baseClass = cn(
    padding,
    bordered && s.border,
    bordered && s.radiusLg,
    bordered && toneMap[tone].border,
    bordered && toneMap[tone].soft,
  );

  if (iconPosition === 'right') {
    return (
      <div className={cn(baseClass, 'grid grid-cols-[1fr_auto] items-center gap-3')}>
        <div>
          {labelEl}
          <div className={valueGap}>{valueEl}</div>
          {trendEl}
        </div>
        {iconEl}
      </div>
    );
  }

  if (iconPosition === 'left') {
    return (
      <div className={cn(baseClass, 'flex items-center gap-3')}>
        {iconEl}
        <div className="flex-1">
          {labelEl}
          <div className={valueGap}>{valueEl}</div>
          {trendEl}
        </div>
      </div>
    );
  }

  if (iconPosition === 'bottom-left') {
    return (
      <div className={cn(baseClass, 'relative')}>
        <div className="mb-3 flex items-center justify-between">{labelEl}</div>
        {valueEl}
        {trendEl}
        {iconEl && (
          <span className={cn('absolute bottom-0 left-0 inline-flex items-center justify-center', padding, iconBoxSize, toneMap[tone].text)}>
            {icon}
          </span>
        )}
      </div>
    );
  }

  return (
    <div className={baseClass}>
      <div className="mb-3 flex items-center justify-between">
        {labelEl}
        {iconEl}
      </div>
      {valueEl}
      {trendEl}
    </div>
  );
}

// packages/ui-kit-angular/src/lib/cards/pixel-stat-card.ts
import { NgTemplateOutlet } from '@angular/common';
import { ChangeDetectionStrategy, Component, ViewEncapsulation, computed, input } from '@angular/core';
import {
  statCardClasses,
  type PixelStatCardIconPosition,
  type PixelStatCardSize,
  type Surface,
  type Tone,
} from '@pxlkit/ui-kit-core';
import { booleanOr, withDefault } from '../_internal/coercion';
import { PxlOutlet, type PxlContent } from '../_internal/outlet';
import { injectEffectiveSurface } from '../overlay-foundation/pxl-kit-surface-provider';

/**
 * Compact metric card: a label, the value, an optional trend line and an
 * icon (text or an `<ng-template>`) above, beside or in the bottom-left
 * corner, in three sizes. The host is the card.
 *
 * @example
 * <pxl-stat-card label="Revenue" value="$12,480" trend="+8.2% vs last week" tone="green" iconPosition="right" icon="$" />
 */
@Component({
  selector: 'pxl-stat-card',
  imports: [NgTemplateOutlet, PxlOutlet],
  changeDetection: ChangeDetectionStrategy.OnPush,
  // The host stands for React's <div>: a block box, as the top and
  // bottom-left layouts set no display. In the base layer, so the grid and
  // flex of the others still win.
  encapsulation: ViewEncapsulation.None,
  styles: '@layer base { pxl-stat-card { display: block; } }',
  host: { '[class]': 'classes().root' },
  template: `
    @switch (iconPosition()) {
      @case ('right') {
        <div [class]="classes().content">
          <p [class]="classes().label">{{ label() }}</p>
          <div [class]="classes().valueRow"><p [class]="classes().value">{{ value() }}</p></div>
          <ng-container [ngTemplateOutlet]="trendLine" />
        </div>
        <ng-container [ngTemplateOutlet]="iconBox" [ngTemplateOutletContext]="{ $implicit: classes().icon }" />
      }
      @case ('left') {
        <ng-container [ngTemplateOutlet]="iconBox" [ngTemplateOutletContext]="{ $implicit: classes().icon }" />
        <div [class]="classes().content">
          <p [class]="classes().label">{{ label() }}</p>
          <div [class]="classes().valueRow"><p [class]="classes().value">{{ value() }}</p></div>
          <ng-container [ngTemplateOutlet]="trendLine" />
        </div>
      }
      @case ('bottom-left') {
        <div [class]="classes().header"><p [class]="classes().label">{{ label() }}</p></div>
        <p [class]="classes().value">{{ value() }}</p>
        <ng-container [ngTemplateOutlet]="trendLine" />
        <ng-container [ngTemplateOutlet]="iconBox" [ngTemplateOutletContext]="{ $implicit: classes().cornerIcon }" />
      }
      @default {
        <div [class]="classes().header">
          <p [class]="classes().label">{{ label() }}</p>
          <ng-container [ngTemplateOutlet]="iconBox" [ngTemplateOutletContext]="{ $implicit: classes().icon }" />
        </div>
        <p [class]="classes().value">{{ value() }}</p>
        <ng-container [ngTemplateOutlet]="trendLine" />
      }
    }
    <ng-template #trendLine>
      @if (trend(); as trend) {
        <p [class]="classes().trend">{{ trend }}</p>
      }
    </ng-template>
    <ng-template #iconBox let-boxClasses>
      @if (icon()) {
        <span [class]="boxClasses"><ng-container *pxlOutlet="icon(); let text">{{ text }}</ng-container></span>
      }
    </ng-template>
  `,
})
export class PixelStatCard {
  /** Caption above the value. */
  readonly label = input.required<string>();
  /** The metric. */
  readonly value = input.required<string>();
  /** The icon, in the tone. */
  readonly icon = input<PxlContent>();
  /** Tone of the border, background and icon. */
  readonly tone = input<Tone, Tone | undefined>('gold', { transform: withDefault<Tone>('gold') });
  /** Trend or delta line under the value. */
  readonly trend = input<string>();
  /** Surface override; defaults to the nearest provider. */
  readonly surface = input<Surface>();
  /** Padding and type scale. */
  readonly size = input<PixelStatCardSize, PixelStatCardSize | undefined>('md', {
    transform: withDefault<PixelStatCardSize>('md'),
  });
  /** Where the icon sits: above, beside or in the bottom-left corner. */
  readonly iconPosition = input<PixelStatCardIconPosition, PixelStatCardIconPosition | undefined>('top', {
    transform: withDefault<PixelStatCardIconPosition>('top'),
  });
  /** Colours the value with the tone. */
  readonly valueTone = input(false, { transform: booleanOr(false) });
  /** Alignment of the label, value and trend. */
  readonly align = input<'start' | 'center', 'start' | 'center' | undefined>('start', {
    transform: withDefault<'start' | 'center'>('start'),
  });
  /** Surface border, radius and tone tint. */
  readonly bordered = input(true, { transform: booleanOr(true) });

  private readonly effectiveSurface = injectEffectiveSurface(() => this.surface());

  /** @internal */
  protected readonly classes = computed(() =>
    statCardClasses(this.effectiveSurface(), {
      tone: this.tone(),
      size: this.size(),
      iconPosition: this.iconPosition(),
      valueTone: this.valueTone(),
      align: this.align(),
      bordered: this.bordered(),
    }),
  );
}
