// packages/ui-kit-vue/src/animations/PixelFlicker.vue
<script setup lang="ts">
import { computed, useTemplateRef, type VNode } from 'vue';
import { flickerStyle, type AnimationRepeat, type AnimationTrigger } from '@pxlkit/ui-kit-core';
import { useAnimationTrigger } from './_internal/animation-trigger.js';

/**
 * Broken-neon-sign opacity flicker, for retro signage and emphasis. It plays
 * as `trigger` says and holds still when the user prefers reduced motion.
 * Attributes fall through to the wrapping `<div>`.
 *
 * @example
 * <PixelFlicker :duration="900"><span>NEON</span></PixelFlicker>
 */
export interface PixelFlickerProps {
  /** Animation duration in milliseconds. */
  duration?: number;
  /** Iteration count: a number or `'infinite'`. */
  repeat?: AnimationRepeat;
  /**
   * When the animation plays: `'mount'`, `'hover'`, `'click'`, `'focus'`,
   * `'inView'`, or `true` / `false` to control it.
   */
  trigger?: AnimationTrigger;
}

const props = withDefaults(defineProps<PixelFlickerProps>(), {
  duration: 2200,
  repeat: 'infinite',
  trigger: 'mount',
});
const emit = defineEmits<{
  /** After the final iteration. */
  complete: [];
}>();
defineSlots<{
  /** Content to flicker. */
  default?(): VNode[];
}>();

const element = useTemplateRef<HTMLElement>('element');
const { active, listeners, ended } = useAnimationTrigger(element, () => props.trigger, () => emit('complete'));
const style = computed(() => (active.value ? flickerStyle(props) : undefined));
</script>

<template>
  <div ref="element" :style="style" v-on="listeners" @animationend="ended">
    <slot />
  </div>
</template>

// packages/ui-kit/src/animations/PixelFlicker.tsx
'use client';

import React, { forwardRef } from 'react';
import { flickerStyle } from '@pxlkit/ui-kit-core';
import type { AnimationRepeat, AnimationTrigger } from './types';
import { mergeRefs, useAnimationTrigger } from './_internal/animation-hooks';

/* ─────────────────────────────────────────────────────────────────────────
   PixelFlicker — broken-neon-sign opacity flicker loop.
   ───────────────────────────────────────────────────────────────────────── */

export interface PixelFlickerProps {
  /** Content to flicker. */
  children: React.ReactNode;
  /** Animation duration in milliseconds. Default `2200`. */
  duration?: number;
  /** Iteration count: a number or `'infinite'`. Default `'infinite'`. */
  repeat?: AnimationRepeat;
  /** When the animation should play. Default `'mount'`. */
  trigger?: AnimationTrigger;
  /** Fires after the final iteration. */
  onComplete?: () => void;
  /** Extra class names applied to the wrapping `<div>`. */
  className?: string;
}

export const PixelFlicker = forwardRef<HTMLDivElement, PixelFlickerProps>(function PixelFlicker(
  {
    children,
    duration = 2200,
    repeat = 'infinite',
    trigger = 'mount',
    onComplete,
    className,
  },
  forwardedRef,
) {
  const { ref, active, handlers, handleAnimEnd } = useAnimationTrigger(trigger, onComplete);
  return (
    <div
      ref={mergeRefs(ref, forwardedRef)}
      className={className}
      style={active ? flickerStyle({ duration, repeat }) : undefined}
      {...handlers}
      onAnimationEnd={handleAnimEnd}
    >
      {children}
    </div>
  );
});

PixelFlicker.displayName = 'PixelFlicker';
