// packages/ui-kit-vue/src/animations/PixelRotate.vue
<script setup lang="ts">
import { computed, useTemplateRef, type VNode } from 'vue';
import {
  animationInlineClasses,
  rotateStyle,
  type AnimationDirection,
  type AnimationRepeat,
  type AnimationTrigger,
} from '@pxlkit/ui-kit-core';
import { useAnimationTrigger } from './_internal/animation-trigger.js';

/**
 * Full 360° rotation loop in the direction asked for. It plays as `trigger`
 * says and holds still when the user prefers reduced motion. Attributes
 * fall through to the wrapping `<div>`.
 *
 * @example
 * <PixelRotate direction="reverse" :duration="2400"><span>Reverse</span></PixelRotate>
 */
export interface PixelRotateProps {
  /** Animation duration in milliseconds. */
  duration?: number;
  /** Iteration count: a number or `'infinite'`. */
  repeat?: AnimationRepeat;
  /** CSS `animation-direction`. */
  direction?: AnimationDirection;
  /** CSS `animation-timing-function`. */
  easing?: string;
  /**
   * When the animation plays: `'mount'`, `'hover'`, `'click'`, `'focus'`,
   * `'inView'`, or `true` / `false` to control it.
   */
  trigger?: AnimationTrigger;
}

const props = withDefaults(defineProps<PixelRotateProps>(), {
  duration: 1800,
  repeat: 'infinite',
  direction: 'normal',
  easing: 'linear',
  trigger: 'mount',
});
const emit = defineEmits<{
  /** After the final iteration. */
  complete: [];
}>();
defineSlots<{
  /** Content to rotate. */
  default?(): VNode[];
}>();

const element = useTemplateRef<HTMLElement>('element');
const { active, listeners, ended } = useAnimationTrigger(element, () => props.trigger, () => emit('complete'));
const style = computed(() => (active.value ? rotateStyle(props) : undefined));
</script>

<template>
  <div ref="element" :class="animationInlineClasses" :style="style" v-on="listeners" @animationend="ended">
    <slot />
  </div>
</template>

// packages/ui-kit/src/animations/PixelRotate.tsx
'use client';

import React, { forwardRef } from 'react';
import { animationInlineClasses, rotateStyle } from '@pxlkit/ui-kit-core';
import { cn } from '../common';
import type { AnimationRepeat, AnimationTrigger } from './types';
import { mergeRefs, useAnimationTrigger } from './_internal/animation-hooks';

/* ─────────────────────────────────────────────────────────────────────────
   PixelRotate — full 360° rotation loop, configurable direction.
   ───────────────────────────────────────────────────────────────────────── */

export interface PixelRotateProps {
  /** Content to rotate. */
  children: React.ReactNode;
  /** Animation duration in milliseconds. Default `1800`. */
  duration?: number;
  /** Iteration count: a number or `'infinite'`. Default `'infinite'`. */
  repeat?: AnimationRepeat;
  /** CSS `animation-direction`. Default `'normal'`. */
  direction?: 'normal' | 'reverse' | 'alternate' | 'alternate-reverse';
  /** CSS `animation-timing-function`. Default `'linear'`. */
  easing?: string;
  /** When the animation should play. Default `'mount'`. */
  trigger?: AnimationTrigger;
  /** Fires after the final iteration. */
  onComplete?: () => void;
  /** Extra class names applied to the wrapping `<div>`. */
  className?: string;
}

export const PixelRotate = forwardRef<HTMLDivElement, PixelRotateProps>(function PixelRotate(
  {
    children,
    duration = 1800,
    repeat = 'infinite',
    direction = 'normal',
    easing = 'linear',
    trigger = 'mount',
    onComplete,
    className,
  },
  forwardedRef,
) {
  const { ref, active, handlers, handleAnimEnd } = useAnimationTrigger(trigger, onComplete);
  return (
    <div
      ref={mergeRefs(ref, forwardedRef)}
      className={cn(animationInlineClasses, className)}
      style={active ? rotateStyle({ duration, repeat, direction, easing }) : undefined}
      {...handlers}
      onAnimationEnd={handleAnimEnd}
    >
      {children}
    </div>
  );
});

PixelRotate.displayName = 'PixelRotate';
