// packages/ui-kit-angular/examples/animations/pixel-rotate.examples.ts
import { Component } from '@angular/core';
import { PixelRotate } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelRotate],
  template: `
    <pxl-rotate>
      <span>Rotate</span>
    </pxl-rotate>
  `,
})
export class Default {}

@Component({
  imports: [PixelRotate],
  template: `
    <pxl-rotate direction="reverse" [duration]="2400">
      <span>Reverse</span>
    </pxl-rotate>
  `,
})
export class ReverseDirection {}

@Component({
  imports: [PixelRotate],
  template: `
    <pxl-rotate trigger="hover" [repeat]="1" [duration]="900">
      <span>Hover me</span>
    </pxl-rotate>
  `,
})
export class HoverTrigger {}

// packages/ui-kit/src/animations/PixelRotate.examples.tsx
import { PixelRotate } from './PixelRotate';

export function Default() {
  return (
    <PixelRotate>
      <span>Rotate</span>
    </PixelRotate>
  );
}

export function ReverseDirection() {
  return (
    <PixelRotate direction="reverse" duration={2400}>
      <span>Reverse</span>
    </PixelRotate>
  );
}

export function HoverTrigger() {
  return (
    <PixelRotate trigger="hover" repeat={1} duration={900}>
      <span>Hover me</span>
    </PixelRotate>
  );
}
