// packages/ui-kit-vue/src/actions/PixelBareButton.vue
<script setup lang="ts">
import type { VNode } from 'vue';

/**
 * Unstyled `<button>` for composing your own: it adds no classes, and every
 * attribute and listener falls through to it. Its `type` defaults to
 * `"button"`, so it never submits a form by accident.
 */
export interface PixelBareButtonProps {
  /** Native `type`; `button` unless set. */
  type?: 'button' | 'submit' | 'reset';
}

withDefaults(defineProps<PixelBareButtonProps>(), { type: 'button' });
defineSlots<{ default?(): VNode[] }>();
</script>

<template>
  <button :type="type"><slot /></button>
</template>

// packages/ui-kit-angular/src/lib/actions/pixel-bare-button.ts
import { Directive, input } from '@angular/core';
import { withDefault } from '../_internal/coercion';

type BareButtonType = 'button' | 'submit' | 'reset';

/**
 * Unstyled `<button>` for composing your own: it adds no classes, and only
 * defaults the `type` to `"button"`, so it never submits a form by accident.
 *
 * @example
 * <button pxlBareButton class="rounded-md border px-3 py-1" (click)="go()">Go</button>
 * <button pxlBareButton type="submit">Send</button>
 */
@Directive({
  selector: 'button[pxlBareButton]',
  host: { '[attr.type]': 'type()' },
})
export class PixelBareButton {
  /** Native `type`; `button` unless set. */
  readonly type = input<BareButtonType, BareButtonType | undefined>('button', {
    transform: withDefault<BareButtonType>('button'),
  });
}
