// packages/ui-kit-angular/examples/forms/pixel-input-group.examples.ts
import { Component } from '@angular/core';
import { PixelInputGroup, PixelInputGroupItem } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelInputGroup, PixelInputGroupItem],
  template: `
    <pxl-input-group aria-label="Website URL">
      <input pxlInputGroupItem aria-label="Protocol" value="https://" class="bg-transparent px-2 outline-none" />
      <input pxlInputGroupItem aria-label="Domain name" value="pxlkit" class="bg-transparent px-2 outline-none" />
      <input pxlInputGroupItem aria-label="Top-level domain" value=".xyz" class="bg-transparent px-2 outline-none" />
    </pxl-input-group>
  `,
})
export class Default {}

@Component({
  imports: [PixelInputGroup, PixelInputGroupItem],
  template: `
    <div class="flex flex-col gap-3">
      <pxl-input-group size="sm" aria-label="Small group">
        <input pxlInputGroupItem aria-label="First segment" value="small" class="bg-transparent px-2 outline-none" />
        <input pxlInputGroupItem aria-label="Second segment" value="size" class="bg-transparent px-2 outline-none" />
      </pxl-input-group>
      <pxl-input-group size="md" aria-label="Medium group">
        <input pxlInputGroupItem aria-label="First segment" value="medium" class="bg-transparent px-2 outline-none" />
        <input pxlInputGroupItem aria-label="Second segment" value="size" class="bg-transparent px-2 outline-none" />
      </pxl-input-group>
      <pxl-input-group size="lg" aria-label="Large group">
        <input pxlInputGroupItem aria-label="First segment" value="large" class="bg-transparent px-2 outline-none" />
        <input pxlInputGroupItem aria-label="Second segment" value="size" class="bg-transparent px-2 outline-none" />
      </pxl-input-group>
    </div>
  `,
})
export class Sizes {}

@Component({
  imports: [PixelInputGroup, PixelInputGroupItem],
  template: `
    <div class="flex flex-col gap-3">
      <pxl-input-group surface="pixel" aria-label="Pixel surface group">
        <input pxlInputGroupItem aria-label="First segment" value="pixel" class="bg-transparent px-2 outline-none" />
        <input pxlInputGroupItem aria-label="Second segment" value="surface" class="bg-transparent px-2 outline-none" />
      </pxl-input-group>
      <pxl-input-group surface="linear" aria-label="Linear surface group">
        <input pxlInputGroupItem aria-label="First segment" value="linear" class="bg-transparent px-2 outline-none" />
        <input pxlInputGroupItem aria-label="Second segment" value="surface" class="bg-transparent px-2 outline-none" />
      </pxl-input-group>
    </div>
  `,
})
export class Surfaces {}

@Component({
  imports: [PixelInputGroup, PixelInputGroupItem],
  template: `
    <pxl-input-group aria-label="Phone number with country code">
      <input
        pxlInputGroupItem
        aria-label="Country code"
        value="+58"
        class="bg-transparent px-2 outline-none"
        style="max-width: 5rem"
      />
      <input pxlInputGroupItem aria-label="Phone number" placeholder="412 555 0123" class="bg-transparent px-2 outline-none" />
    </pxl-input-group>
  `,
})
export class PhoneWithCountryCode {}

// packages/ui-kit/src/forms/PixelInputGroup.examples.tsx
import { PixelInputGroup } from './PixelInputGroup';

export function Default() {
  return (
    <PixelInputGroup aria-label="Website URL">
      <input aria-label="Protocol" defaultValue="https://" className="bg-transparent px-2 outline-none" />
      <input aria-label="Domain name" defaultValue="pxlkit" className="bg-transparent px-2 outline-none" />
      <input aria-label="Top-level domain" defaultValue=".xyz" className="bg-transparent px-2 outline-none" />
    </PixelInputGroup>
  );
}

export function Sizes() {
  return (
    <div className="flex flex-col gap-3">
      <PixelInputGroup size="sm" aria-label="Small group">
        <input aria-label="First segment" defaultValue="small" className="bg-transparent px-2 outline-none" />
        <input aria-label="Second segment" defaultValue="size" className="bg-transparent px-2 outline-none" />
      </PixelInputGroup>
      <PixelInputGroup size="md" aria-label="Medium group">
        <input aria-label="First segment" defaultValue="medium" className="bg-transparent px-2 outline-none" />
        <input aria-label="Second segment" defaultValue="size" className="bg-transparent px-2 outline-none" />
      </PixelInputGroup>
      <PixelInputGroup size="lg" aria-label="Large group">
        <input aria-label="First segment" defaultValue="large" className="bg-transparent px-2 outline-none" />
        <input aria-label="Second segment" defaultValue="size" className="bg-transparent px-2 outline-none" />
      </PixelInputGroup>
    </div>
  );
}

export function Surfaces() {
  return (
    <div className="flex flex-col gap-3">
      <PixelInputGroup surface="pixel" aria-label="Pixel surface group">
        <input aria-label="First segment" defaultValue="pixel" className="bg-transparent px-2 outline-none" />
        <input aria-label="Second segment" defaultValue="surface" className="bg-transparent px-2 outline-none" />
      </PixelInputGroup>
      <PixelInputGroup surface="linear" aria-label="Linear surface group">
        <input aria-label="First segment" defaultValue="linear" className="bg-transparent px-2 outline-none" />
        <input aria-label="Second segment" defaultValue="surface" className="bg-transparent px-2 outline-none" />
      </PixelInputGroup>
    </div>
  );
}

export function PhoneWithCountryCode() {
  return (
    <PixelInputGroup aria-label="Phone number with country code">
      <input
        aria-label="Country code"
        defaultValue="+58"
        className="bg-transparent px-2 outline-none"
        style={{ maxWidth: '5rem' }}
      />
      <input
        aria-label="Phone number"
        placeholder="412 555 0123"
        className="bg-transparent px-2 outline-none"
      />
    </PixelInputGroup>
  );
}
