// packages/ui-kit-angular/examples/forms/pixel-input.examples.ts
import { Component, signal } from '@angular/core';
import { PixelInput } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelInput],
  template: `<pxl-input label="Username" placeholder="hero@pxlkit.xyz" hint="Your retro alias" />`,
})
export class Default {}

@Component({
  imports: [PixelInput],
  template: `<pxl-input label="Email" type="email" placeholder="hero@pxlkit.xyz" [(value)]="value" tone="cyan" />`,
})
export class Controlled {
  readonly value = signal('');
}

@Component({
  imports: [PixelInput],
  template: `<pxl-input label="Display name" defaultValue="Pixel Hero" hint="Edit me — uncontrolled" />`,
})
export class Uncontrolled {}

@Component({
  imports: [PixelInput],
  template: `
    <div class="flex flex-col gap-3">
      <pxl-input label="Neutral" tone="neutral" defaultValue="neutral" />
      <pxl-input label="Cyan" tone="cyan" defaultValue="cyan" />
      <pxl-input label="Green" tone="green" defaultValue="green" />
      <pxl-input label="Gold" tone="gold" defaultValue="gold" />
      <pxl-input label="Purple" tone="purple" defaultValue="purple" />
      <pxl-input label="Pink" tone="pink" defaultValue="pink" />
    </div>
  `,
})
export class Tones {}

@Component({
  imports: [PixelInput],
  template: `
    <div class="flex flex-col gap-3">
      <pxl-input label="Small" size="sm" placeholder="sm" />
      <pxl-input label="Medium" size="md" placeholder="md" />
      <pxl-input label="Large" size="lg" placeholder="lg" />
    </div>
  `,
})
export class Sizes {}

@Component({
  imports: [PixelInput],
  template: `
    <div class="flex flex-col gap-3">
      <pxl-input label="Pixel" surface="pixel" placeholder="pixel surface" />
      <pxl-input label="Linear" surface="linear" placeholder="linear surface" />
    </div>
  `,
})
export class Surfaces {}

@Component({
  imports: [PixelInput],
  template: `
    <div class="flex flex-col gap-3">
      <pxl-input label="Amount" [prefix]="dollar" [suffix]="usd" defaultValue="42" />
      <pxl-input label="Search" [prefix]="search" placeholder="Find anything" />
    </div>
    <ng-template #dollar><span class="text-xs">$</span></ng-template>
    <ng-template #usd><span class="text-xs">USD</span></ng-template>
    <ng-template #search><span aria-hidden="true">?</span></ng-template>
  `,
})
export class WithPrefixSuffix {}

@Component({
  imports: [PixelInput],
  template: `
    <pxl-input label="Website" [addonLeft]="protocol" [addonRight]="tld" defaultValue="pxlkit" />
    <ng-template #protocol><span class="text-xs">https://</span></ng-template>
    <ng-template #tld><span class="text-xs">.xyz</span></ng-template>
  `,
})
export class WithAddons {}

@Component({
  imports: [PixelInput],
  template: `<pxl-input label="Clearable" clearable [(value)]="value" />`,
})
export class Clearable {
  readonly value = signal('clear me');
}

@Component({
  imports: [PixelInput],
  template: `<pxl-input label="Verifying handle" defaultValue="pxlhero" loading />`,
})
export class Loading {}

@Component({
  imports: [PixelInput],
  template: `<pxl-input label="Disabled" defaultValue="cannot edit" disabled />`,
})
export class Disabled {}

@Component({
  imports: [PixelInput],
  template: `
    <pxl-input label="Email" defaultValue="not-an-email" error="Please enter a valid email address" tone="red" />
  `,
})
export class WithError {}

@Component({
  imports: [PixelInput],
  template: `<pxl-input label="Bio" [(value)]="value" [showCount]="{ max: 80 }" hint="Keep it short" />`,
})
export class WithCharCount {
  readonly value = signal('Hello');
}

// packages/ui-kit/src/forms/PixelInput.examples.tsx
import { useState } from 'react';
import { PixelInput } from './PixelInput';

export function Default() {
  return (
    <PixelInput
      label="Username"
      placeholder="hero@pxlkit.xyz"
      hint="Your retro alias"
    />
  );
}

export function Controlled() {
  const [value, setValue] = useState('');
  return (
    <PixelInput
      label="Email"
      type="email"
      placeholder="hero@pxlkit.xyz"
      value={value}
      onChange={(e) => setValue(e.target.value)}
      tone="cyan"
    />
  );
}

export function Uncontrolled() {
  return (
    <PixelInput
      label="Display name"
      defaultValue="Pixel Hero"
      hint="Edit me — uncontrolled"
    />
  );
}

export function Tones() {
  return (
    <div className="flex flex-col gap-3">
      <PixelInput label="Neutral" tone="neutral" defaultValue="neutral" />
      <PixelInput label="Cyan" tone="cyan" defaultValue="cyan" />
      <PixelInput label="Green" tone="green" defaultValue="green" />
      <PixelInput label="Gold" tone="gold" defaultValue="gold" />
      <PixelInput label="Purple" tone="purple" defaultValue="purple" />
      <PixelInput label="Pink" tone="pink" defaultValue="pink" />
    </div>
  );
}

export function Sizes() {
  return (
    <div className="flex flex-col gap-3">
      <PixelInput label="Small" size="sm" placeholder="sm" />
      <PixelInput label="Medium" size="md" placeholder="md" />
      <PixelInput label="Large" size="lg" placeholder="lg" />
    </div>
  );
}

export function Surfaces() {
  return (
    <div className="flex flex-col gap-3">
      <PixelInput label="Pixel" surface="pixel" placeholder="pixel surface" />
      <PixelInput label="Linear" surface="linear" placeholder="linear surface" />
    </div>
  );
}

export function WithPrefixSuffix() {
  return (
    <div className="flex flex-col gap-3">
      <PixelInput
        label="Amount"
        prefix={<span className="text-xs">$</span>}
        suffix={<span className="text-xs">USD</span>}
        defaultValue="42"
      />
      <PixelInput
        label="Search"
        prefix={<span aria-hidden>?</span>}
        placeholder="Find anything"
      />
    </div>
  );
}

export function WithAddons() {
  return (
    <PixelInput
      label="Website"
      addonLeft={<span className="text-xs">https://</span>}
      addonRight={<span className="text-xs">.xyz</span>}
      defaultValue="pxlkit"
    />
  );
}

export function Clearable() {
  const [value, setValue] = useState('clear me');
  return (
    <PixelInput
      label="Clearable"
      clearable
      value={value}
      onChange={(e) => setValue(e.target.value)}
      onClear={() => setValue('')}
    />
  );
}

export function Loading() {
  return (
    <PixelInput
      label="Verifying handle"
      defaultValue="pxlhero"
      loading
    />
  );
}

export function Disabled() {
  return (
    <PixelInput
      label="Disabled"
      defaultValue="cannot edit"
      disabled
    />
  );
}

export function WithError() {
  return (
    <PixelInput
      label="Email"
      defaultValue="not-an-email"
      error="Please enter a valid email address"
      tone="red"
    />
  );
}

export function WithCharCount() {
  const [value, setValue] = useState('Hello');
  return (
    <PixelInput
      label="Bio"
      value={value}
      onChange={(e) => setValue(e.target.value)}
      showCount={{ max: 80 }}
      hint="Keep it short"
    />
  );
}
