// packages/ui-kit-vue/src/forms/PixelCheckbox.vue
<script setup lang="ts">
import { computed, useTemplateRef } from 'vue';
import { checkboxClasses, type Surface, type Tone } from '@pxlkit/ui-kit-core';
import PixelGlyph from '../_internal/PixelGlyph.vue';
import { useControllableState } from '../composables/controllable.js';
import { useEffectiveSurface } from '../composables/surface.js';

/**
 * Checkbox (`role="checkbox"`) with a chunky pixel check mark, tones and
 * surfaces. Bind its state with `v-model:checked`, or leave it uncontrolled
 * with `default-checked`. With a `name` it submits `value` in forms while
 * checked. Extra attributes and listeners go to the checkbox `<button>`.
 */
export interface PixelCheckboxProps {
  /** Label rendered next to the box. */
  label: string;
  /** Checked state (`v-model:checked`); leave unset for an uncontrolled checkbox. */
  checked?: boolean;
  /** Initial checked state while uncontrolled. */
  defaultChecked?: boolean;
  /** Disables interaction and greys out the control. */
  disabled?: boolean;
  /** Tone of the checked box. */
  tone?: Tone;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
  /** Form field name — a hidden input submits `value` while checked. */
  name?: string;
  /** Form value while checked. */
  value?: string;
  /** Marks the field as required for native form validation. */
  required?: boolean;
  /** `id` of the checkbox button. */
  id?: string;
}

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<PixelCheckboxProps>(), {
  checked: undefined,
  defaultChecked: false,
  disabled: false,
  tone: 'green',
  surface: undefined,
  name: undefined,
  value: 'on',
  required: false,
  id: undefined,
});

const emit = defineEmits<{
  /** The new checked state, after each toggle. */
  'update:checked': [checked: boolean];
}>();

const surface = useEffectiveSurface(() => props.surface);
const button = useTemplateRef<HTMLButtonElement>('button');
const [isChecked, setChecked] = useControllableState({
  value: () => props.checked,
  defaultValue: () => props.defaultChecked,
  onChange: (next) => emit('update:checked', next),
});

function toggle() {
  if (!props.disabled) setChecked(!isChecked.value);
}

const classes = computed(() =>
  checkboxClasses(surface.value, { tone: props.tone, checked: isChecked.value, disabled: props.disabled }),
);

defineExpose({
  /** The checkbox button. */
  element: button,
});
</script>

<template>
  <input v-if="name && isChecked" type="hidden" :name="name" :value="value" :required="required" />
  <button
    v-bind="$attrs"
    :id="id"
    ref="button"
    type="button"
    role="checkbox"
    :aria-checked="isChecked"
    :aria-disabled="disabled"
    :aria-required="required || undefined"
    :disabled="disabled"
    :class="classes.button"
    @click="toggle"
  >
    <span :class="classes.box"><PixelGlyph v-if="isChecked" name="check" :class="classes.check" /></span>
    <span :class="classes.label">{{ label }}</span>
  </button>
</template>

// packages/ui-kit/src/inputs/PixelCheckbox.tsx
/* ─────────────────────────────────────────────────────────────────────────
   PixelCheckbox — chunky pixel check mark.
   ───────────────────────────────────────────────────────────────────────── */

import React, { forwardRef } from 'react';
import {
  Tone, Surface, cn,
  toneMap, surfaceClasses, useEffectiveSurface,
  CheckIcon,
} from '../common';

/** Public prop bag for {@link PixelCheckbox}. */
export interface PixelCheckboxProps {
  /** Label rendered next to the box. */
  label: string;
  /** Controlled checked state. */
  checked: boolean;
  /** Fires with the next checked value when clicked. */
  onChange: (next: boolean) => void;
  /** Disables interaction + grays out the control. */
  disabled?: boolean;
  /** Visual tone for the checked state. Default: `'green'`. */
  tone?: Tone;
  /** Surface variant. Inherits from `PxlKitSurfaceProvider` when omitted. */
  surface?: Surface;
  /** Form-serialization name. Hidden mirror input sends `'on'` / `''`. */
  name?: string;
  /** HTML form value when checked. Defaults to `'on'`. */
  value?: string;
  /** Marks the field as required for native form validation. */
  required?: boolean;
  /** DOM `id` forwarded to the trigger. */
  id?: string;
}

export const PixelCheckbox = forwardRef<HTMLButtonElement, PixelCheckboxProps>(function PixelCheckbox(
  {
    label, checked, onChange,
    disabled = false,
    tone = 'green',
    surface: surfaceProp,
    name, value = 'on', required, id,
  },
  ref,
) {
  const surface = useEffectiveSurface(surfaceProp);
  const s = surfaceClasses(surface);
  return (
    <>
      {name && checked && <input type="hidden" name={name} value={value} required={required} />}
      <button
        ref={ref}
        id={id}
        type="button"
        role="checkbox"
        aria-checked={checked}
        aria-disabled={disabled}
        aria-required={required || undefined}
        disabled={disabled}
        onClick={() => onChange(!checked)}
        className={cn(
          'group flex items-center gap-2.5 text-sm outline-none',
          s.font,
          disabled ? 'opacity-50 cursor-not-allowed' : 'cursor-pointer',
        )}
      >
        <span
          className={cn(
            'flex h-[18px] w-[18px] shrink-0 items-center justify-center transition-all',
            s.border, s.radius,
            checked ? cn(toneMap[tone].border, toneMap[tone].bg) : 'border-retro-border-strong bg-retro-bg',
            !disabled && 'group-hover:border-retro-muted',
            'group-focus-visible:ring-2 group-focus-visible:ring-retro-green/40 group-focus-visible:ring-offset-2 group-focus-visible:ring-offset-retro-bg',
          )}
        >
          {checked && <CheckIcon className={toneMap[tone].text} />}
        </span>
        <span className="text-retro-text select-none">{label}</span>
      </button>
    </>
  );
});
