// packages/ui-kit/src/layout/PixelCluster.examples.tsx
import React from 'react';
import { PixelCluster } from './PixelCluster';

function Chip({ children }: { children: React.ReactNode }) {
  return (
    <span className="rounded border border-retro-border px-2 py-1 text-xs text-retro-fg">
      {children}
    </span>
  );
}

export function Default() {
  return (
    <PixelCluster>
      <Chip>react</Chip>
      <Chip>typescript</Chip>
      <Chip>tailwind</Chip>
      <Chip>next</Chip>
      <Chip>vite</Chip>
    </PixelCluster>
  );
}

export function Justified() {
  return (
    <PixelCluster justify="between" gap={6}>
      <Chip>left</Chip>
      <Chip>middle</Chip>
      <Chip>right</Chip>
    </PixelCluster>
  );
}

export function PixelSurface() {
  return (
    <PixelCluster surface="pixel" gap={3}>
      <Chip>alpha</Chip>
      <Chip>beta</Chip>
      <Chip>gamma</Chip>
    </PixelCluster>
  );
}

// packages/ui-kit-angular/examples/layout/pixel-cluster.examples.ts
import { Component } from '@angular/core';
import { PixelCluster } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelCluster],
  template: `
    <div pxlCluster>
      @for (tag of tags; track tag) {
        <span class="rounded border border-retro-border px-2 py-1 text-xs text-retro-text">{{ tag }}</span>
      }
    </div>
  `,
})
export class Default {
  readonly tags = ['react', 'typescript', 'tailwind', 'next', 'vite'];
}

@Component({
  imports: [PixelCluster],
  template: `
    <div pxlCluster justify="between" [gap]="6">
      @for (tag of tags; track tag) {
        <span class="rounded border border-retro-border px-2 py-1 text-xs text-retro-text">{{ tag }}</span>
      }
    </div>
  `,
})
export class Justified {
  readonly tags = ['left', 'middle', 'right'];
}

@Component({
  imports: [PixelCluster],
  template: `
    <div pxlCluster surface="pixel" [gap]="3">
      @for (tag of tags; track tag) {
        <span class="rounded border border-retro-border px-2 py-1 text-xs text-retro-text">{{ tag }}</span>
      }
    </div>
  `,
})
export class PixelSurface {
  readonly tags = ['alpha', 'beta', 'gamma'];
}
