// packages/ui-kit/src/layout/PixelCenter.examples.tsx
import React from 'react';
import { PixelCenter } from './PixelCenter';

export function Default() {
  return (
    <PixelCenter>
      <p className="text-sm text-retro-muted">
        Centered content with the default max-width and page gutter.
      </p>
    </PixelCenter>
  );
}

export function NarrowProse() {
  return (
    <PixelCenter maxWidth="2xl" text="left">
      <p className="text-sm text-retro-muted">
        A narrower max-width is useful for long-form reading flows where measure matters.
      </p>
    </PixelCenter>
  );
}

export function TextCentered() {
  return (
    <PixelCenter maxWidth="3xl" text="center" gutter="md">
      <p className="text-sm text-retro-muted">
        Both the wrapper and the inner text are centered.
      </p>
    </PixelCenter>
  );
}

export function AsSection() {
  return (
    <PixelCenter as="section" maxWidth="4xl" gutter="lg" surface="pixel">
      <p className="text-sm text-retro-muted">
        Polymorphic: renders as a semantic &lt;section&gt; on the pixel surface.
      </p>
    </PixelCenter>
  );
}

// packages/ui-kit-angular/examples/layout/pixel-center.examples.ts
import { Component } from '@angular/core';
import { PixelCenter } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelCenter],
  template: `
    <div pxlCenter>
      <p class="text-sm text-retro-muted">
        Centered content with the default max-width and page gutter.
      </p>
    </div>
  `,
})
export class Default {}

@Component({
  imports: [PixelCenter],
  template: `
    <div pxlCenter maxWidth="2xl" text="left">
      <p class="text-sm text-retro-muted">
        A narrower max-width is useful for long-form reading flows where measure matters.
      </p>
    </div>
  `,
})
export class NarrowProse {}

@Component({
  imports: [PixelCenter],
  template: `
    <div pxlCenter maxWidth="3xl" text="center" gutter="md">
      <p class="text-sm text-retro-muted">
        Both the wrapper and the inner text are centered.
      </p>
    </div>
  `,
})
export class TextCentered {}

@Component({
  imports: [PixelCenter],
  template: `
    <section pxlCenter maxWidth="4xl" gutter="lg" surface="pixel">
      <p class="text-sm text-retro-muted">
        Polymorphic: renders as a semantic &lt;section&gt; on the pixel surface.
      </p>
    </section>
  `,
})
export class AsSection {}
