// packages/ui-kit/src/layout/PixelDivider.examples.tsx
import React from 'react';
import { PixelDivider } from '../layout';

export function Default() {
  return <PixelDivider />;
}

export function WithLabel() {
  return <PixelDivider label="Section" />;
}

export function Tones() {
  return (
    <div className="flex flex-col gap-4">
      <PixelDivider label="Neutral" tone="neutral" />
      <PixelDivider label="Green" tone="green" />
      <PixelDivider label="Cyan" tone="cyan" />
      <PixelDivider label="Gold" tone="gold" />
      <PixelDivider label="Red" tone="red" />
      <PixelDivider label="Purple" tone="purple" />
      <PixelDivider label="Pink" tone="pink" />
    </div>
  );
}

export function Spacings() {
  return (
    <div>
      <PixelDivider label="None" spacing="none" />
      <PixelDivider label="Small" spacing="sm" />
      <PixelDivider label="Medium" spacing="md" />
      <PixelDivider label="Large" spacing="lg" />
    </div>
  );
}

export function Surfaces() {
  return (
    <div className="flex flex-col gap-6">
      <PixelDivider label="Pixel surface" surface="pixel" />
      <PixelDivider label="Linear surface" surface="linear" />
    </div>
  );
}

export function PlainRule() {
  return (
    <div className="flex flex-col gap-6">
      <PixelDivider surface="pixel" />
      <PixelDivider surface="linear" />
    </div>
  );
}

// packages/ui-kit-angular/examples/layout/pixel-divider.examples.ts
import { Component } from '@angular/core';
import { PixelDivider } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelDivider],
  template: `<pxl-divider />`,
})
export class Default {}

@Component({
  imports: [PixelDivider],
  template: `<pxl-divider label="Section" />`,
})
export class WithLabel {}

@Component({
  imports: [PixelDivider],
  template: `
    <div class="flex flex-col gap-4">
      <pxl-divider label="Neutral" tone="neutral" />
      <pxl-divider label="Green" tone="green" />
      <pxl-divider label="Cyan" tone="cyan" />
      <pxl-divider label="Gold" tone="gold" />
      <pxl-divider label="Red" tone="red" />
      <pxl-divider label="Purple" tone="purple" />
      <pxl-divider label="Pink" tone="pink" />
    </div>
  `,
})
export class Tones {}

@Component({
  imports: [PixelDivider],
  template: `
    <div>
      <pxl-divider label="None" spacing="none" />
      <pxl-divider label="Small" spacing="sm" />
      <pxl-divider label="Medium" spacing="md" />
      <pxl-divider label="Large" spacing="lg" />
    </div>
  `,
})
export class Spacings {}

@Component({
  imports: [PixelDivider],
  template: `
    <div class="flex flex-col gap-6">
      <pxl-divider label="Pixel surface" surface="pixel" />
      <pxl-divider label="Linear surface" surface="linear" />
    </div>
  `,
})
export class Surfaces {}

@Component({
  imports: [PixelDivider],
  template: `
    <div class="flex flex-col gap-6">
      <pxl-divider surface="pixel" />
      <pxl-divider surface="linear" />
    </div>
  `,
})
export class PlainRule {}
