// packages/ui-kit-vue/src/overlays/PixelAlertDialog.vue
<script setup lang="ts">
import { computed, ref, useId, useTemplateRef, watch } from 'vue';
import {
  alertDialogClasses,
  alertDialogLayerClasses,
  overlayBackdropClasses,
  type Surface,
} from '@pxlkit/ui-kit-core';
import { useReducedMotion } from '../composables/media-query.js';
import { useEscape, useFocusTrap, useScrollLock } from '../composables/overlay.js';
import { useEffectiveSurface } from '../composables/surface.js';
import PixelPortal from '../overlay-foundation/PixelPortal.vue';

/**
 * Modal confirmation dialog (`role="alertdialog"`) for destructive or
 * irreversible actions. Focus starts on Cancel; the dialog traps focus, locks
 * page scrolling and closes on Escape and on the backdrop. An action that
 * returns a promise keeps the dialog open, with a busy action button, until
 * it settles. Bind it with `v-model:open`.
 *
 * @example
 * <PixelAlertDialog
 *   v-model:open="open"
 *   title="Delete this item?"
 *   destructive
 *   @action="remove"
 *   @error="(error) => (message = String(error))"
 * />
 */
export interface PixelAlertDialogProps {
  /** Whether the dialog is visible (`v-model:open`). */
  open: boolean;
  /** Title; it names the dialog. */
  title: string;
  /** Text under the title, wired via `aria-describedby`. */
  description?: string;
  /** Label of the button that dismisses the dialog. */
  cancelLabel?: string;
  /** Label of the button that confirms. */
  actionLabel?: string;
  /**
   * The confirmed action (`@action`). Declared as a prop because its result
   * matters: the dialog closes once it returns, or once the promise it
   * returns resolves — and stays open, busy, until then.
   */
  onAction: (() => void) | (() => Promise<void>);
  /**
   * Receives what the action threw or rejected with (`@error`); the dialog
   * stays open so you can show the error. Declared as a prop because its
   * presence matters: without one a thrown error propagates and a rejection
   * is logged to the console.
   */
  onError?: (error: unknown) => void;
  /** Red accent for a destructive action (cyan otherwise). */
  destructive?: boolean;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
}

const props = withDefaults(defineProps<PixelAlertDialogProps>(), {
  description: undefined,
  cancelLabel: 'Cancel',
  actionLabel: 'Confirm',
  onError: undefined,
  destructive: false,
  surface: undefined,
});
const emit = defineEmits<{
  /** `false` when the dialog asks to close (Cancel, Escape, backdrop, a completed action), for `v-model:open`. */
  'update:open': [open: boolean];
}>();

const surface = useEffectiveSurface(() => props.surface);
const reducedMotion = useReducedMotion();
const titleId = useId();
const descriptionId = useId();
const panel = useTemplateRef<HTMLElement>('panel');
const cancelButton = useTemplateRef<HTMLButtonElement>('cancelButton');
const pending = ref(false);

const classes = computed(() =>
  alertDialogClasses(surface.value, { destructive: props.destructive, reducedMotion: reducedMotion.value }),
);

const close = () => emit('update:open', false);

function cancel() {
  if (!pending.value) close();
}

async function confirm() {
  if (pending.value) return;
  let result: void | Promise<void>;
  try {
    result = props.onAction();
  } catch (error) {
    // A synchronous throw keeps the dialog open so the error can be shown.
    if (!props.onError) throw error;
    props.onError(error);
    return;
  }
  if (!result || typeof (result as Promise<void>).then !== 'function') {
    close();
    return;
  }
  pending.value = true;
  try {
    await result;
    close();
  } catch (error) {
    if (props.onError) props.onError(error);
    else console.error('[PixelAlertDialog] onAction rejected:', error);
  } finally {
    pending.value = false;
  }
}

useScrollLock(() => props.open);
useFocusTrap(() => props.open, panel);
useEscape(cancel, () => props.open);

watch(
  () => props.open,
  (open, _previous, onCleanup) => {
    // Closed from outside while an action was pending: start over next time.
    if (!open) {
      pending.value = false;
      return;
    }
    // Cancel holds the initial focus — the safe default for destructive flows.
    const timer = setTimeout(() => cancelButton.value?.focus(), 0);
    onCleanup(() => clearTimeout(timer));
  },
  { immediate: true },
);

defineExpose({
  /** The dialog panel while it is open. */
  element: panel,
});
</script>

<template>
  <PixelPortal v-if="open">
    <div :class="alertDialogLayerClasses">
      <div aria-hidden="true" data-pxl-overlay-backdrop="" :class="overlayBackdropClasses('fixed')" @click="cancel" />
      <div
        ref="panel"
        role="alertdialog"
        aria-modal="true"
        :aria-labelledby="titleId"
        :aria-describedby="description ? descriptionId : undefined"
        :class="classes.panel"
      >
        <!-- The pixel window's body holds the description and the buttons. -->
        <template v-if="surface === 'pixel'">
          <div :class="classes.header">
            <span aria-hidden="true" :class="classes.accent" />
            <h2 :id="titleId" :class="classes.title">{{ title }}</h2>
          </div>
          <div :class="classes.body">
            <p v-if="description" :id="descriptionId" :class="classes.description">{{ description }}</p>
            <div :class="classes.actions">
              <button ref="cancelButton" type="button" :disabled="pending" :class="classes.cancel" @click="cancel">
                {{ cancelLabel }}
              </button>
              <button type="button" :disabled="pending" :class="classes.action" @click="confirm">
                <span v-if="pending" aria-hidden="true" :class="classes.spinner" />
                <span>{{ actionLabel }}</span>
              </button>
            </div>
          </div>
        </template>
        <template v-else>
          <div :class="classes.header">
            <span aria-hidden="true" :class="classes.accent" />
            <div :class="classes.texts">
              <h2 :id="titleId" :class="classes.title">{{ title }}</h2>
              <p v-if="description" :id="descriptionId" :class="classes.description">{{ description }}</p>
            </div>
          </div>
          <div :class="classes.actions">
            <button ref="cancelButton" type="button" :disabled="pending" :class="classes.cancel" @click="cancel">
              {{ cancelLabel }}
            </button>
            <button type="button" :disabled="pending" :class="classes.action" @click="confirm">
              <span v-if="pending" aria-hidden="true" :class="classes.spinner" />
              <span>{{ actionLabel }}</span>
            </button>
          </div>
        </template>
      </div>
    </div>
  </PixelPortal>
</template>

// packages/ui-kit-angular/src/lib/overlays/pixel-alert-dialog.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  PLATFORM_ID,
  computed,
  effect,
  inject,
  input,
  model,
  signal,
  viewChild,
} from '@angular/core';
import { NgTemplateOutlet, isPlatformBrowser } from '@angular/common';
import {
  alertDialogClasses,
  alertDialogLayerClasses,
  overlayBackdropClasses,
  type Surface,
} from '@pxlkit/ui-kit-core';
import { booleanOr, withDefault } from '../_internal/coercion';
import { injectId } from '../_internal/ids';
import { PixelPortal } from '../overlay-foundation/pixel-portal';
import { injectEffectiveSurface } from '../overlay-foundation/pxl-kit-surface-provider';
import { injectEscape, injectFocusTrap, injectScrollLock } from '../utilities/dom';
import { injectReducedMotion } from '../utilities/media-query';

/**
 * Modal confirmation dialog (`role="alertdialog"`) for destructive or
 * irreversible actions. Focus starts on Cancel; the dialog traps focus, locks
 * page scrolling and closes on Escape and on the backdrop. An action that
 * returns a promise keeps the dialog open, with a busy action button, until
 * it settles. Bind it with `[(open)]`.
 *
 * The host is layout-neutral (`display: contents`); the dialog renders into
 * `document.body`.
 *
 * @example
 * <pxl-alert-dialog
 *   [(open)]="open"
 *   title="Delete this item?"
 *   destructive
 *   [onAction]="remove"
 *   [onError]="showError"
 * />
 */
@Component({
  selector: 'pxl-alert-dialog',
  imports: [NgTemplateOutlet, PixelPortal],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[style.display]': '"contents"',
    // `title` names the dialog; on the host it would show a native tooltip.
    '[attr.title]': 'null',
  },
  template: `
    @if (open()) {
      <ng-template pxlPortal>
        <div [class]="layerClasses">
          <div aria-hidden="true" data-pxl-overlay-backdrop="" [class]="backdropClasses" (click)="cancel()"></div>
          <div
            #panel
            role="alertdialog"
            aria-modal="true"
            [attr.aria-labelledby]="titleId"
            [attr.aria-describedby]="description() ? descriptionId : null"
            [class]="classes().panel"
          >
            @if (effectiveSurface() === 'pixel') {
              <div [class]="classes().header">
                <span aria-hidden="true" [class]="classes().accent"></span>
                <h2 [id]="titleId" [class]="classes().title">{{ title() }}</h2>
              </div>
              <!-- The pixel window's body holds the description and the buttons. -->
              <div [class]="classes().body">
                <ng-container *ngTemplateOutlet="descriptionBlock" />
                <ng-container *ngTemplateOutlet="actions" />
              </div>
            } @else {
              <div [class]="classes().header">
                <span aria-hidden="true" [class]="classes().accent"></span>
                <div [class]="classes().texts">
                  <h2 [id]="titleId" [class]="classes().title">{{ title() }}</h2>
                  <ng-container *ngTemplateOutlet="descriptionBlock" />
                </div>
              </div>
              <ng-container *ngTemplateOutlet="actions" />
            }
          </div>
        </div>
      </ng-template>
    }
    <ng-template #descriptionBlock>
      @if (description()) {
        <p [id]="descriptionId" [class]="classes().description">{{ description() }}</p>
      }
    </ng-template>
    <ng-template #actions>
      <div [class]="classes().actions">
        <button #cancelButton type="button" [disabled]="pending()" [class]="classes().cancel" (click)="cancel()">
          {{ cancelLabel() }}
        </button>
        <button type="button" [disabled]="pending()" [class]="classes().action" (click)="confirm()">
          @if (pending()) {
            <span aria-hidden="true" [class]="classes().spinner"></span>
          }
          <span>{{ actionLabel() }}</span>
        </button>
      </div>
    </ng-template>
  `,
})
export class PixelAlertDialog {
  /** Whether the dialog is visible (`[(open)]`). */
  readonly open = model.required<boolean>();
  /** Title; it names the dialog. */
  readonly title = input.required<string>();
  /** Text under the title, wired via `aria-describedby`. */
  readonly description = input<string>();
  /** Label of the button that dismisses the dialog. */
  readonly cancelLabel = input<string, string | undefined>('Cancel', { transform: withDefault('Cancel') });
  /** Label of the button that confirms. */
  readonly actionLabel = input<string, string | undefined>('Confirm', { transform: withDefault('Confirm') });
  /**
   * The confirmed action. Its result matters: the dialog closes once it
   * returns, or once the promise it returns resolves — and stays open, busy,
   * until then.
   */
  readonly onAction = input.required<() => void | Promise<void>>();
  /**
   * Receives what the action threw or rejected with; the dialog stays open
   * so you can show the error. Without one a thrown error propagates and a
   * rejection is logged to the console.
   */
  readonly onError = input<(error: unknown) => void>();
  /** Red accent for a destructive action (cyan otherwise). */
  readonly destructive = input(false, { transform: booleanOr(false) });
  /** Surface override; defaults to the nearest provider. */
  readonly surface = input<Surface>();

  /** @internal */
  protected readonly effectiveSurface = injectEffectiveSurface(() => this.surface());
  private readonly reducedMotion = injectReducedMotion();
  private readonly panel = viewChild<ElementRef<HTMLElement>>('panel');
  private readonly cancelButton = viewChild<ElementRef<HTMLButtonElement>>('cancelButton');

  /** @internal */
  protected readonly titleId = injectId();
  /** @internal */
  protected readonly descriptionId = injectId();
  /** @internal */
  protected readonly pending = signal(false);
  /** @internal */
  protected readonly layerClasses = alertDialogLayerClasses;
  /** @internal */
  protected readonly backdropClasses = overlayBackdropClasses('fixed');
  /** @internal */
  protected readonly classes = computed(() =>
    alertDialogClasses(this.effectiveSurface(), { destructive: this.destructive(), reducedMotion: this.reducedMotion() }),
  );

  constructor() {
    injectScrollLock(() => this.open());
    injectFocusTrap(
      () => this.open(),
      () => this.panel()?.nativeElement,
    );
    injectEscape(
      () => this.cancel(),
      () => this.open(),
    );
    const browser = isPlatformBrowser(inject(PLATFORM_ID));
    effect((onCleanup) => {
      // Closed from outside while an action was pending: start over next time.
      if (!this.open()) {
        this.pending.set(false);
        return;
      }
      if (!browser) return;
      // Cancel holds the initial focus — the safe default for destructive flows.
      const timer = setTimeout(() => this.cancelButton()?.nativeElement.focus(), 0);
      onCleanup(() => clearTimeout(timer));
    });
  }

  /** @internal */
  protected cancel(): void {
    if (!this.pending()) this.open.set(false);
  }

  /** @internal */
  protected confirm(): void {
    if (this.pending()) return;
    const onError = this.onError();
    let result: void | Promise<void>;
    try {
      result = this.onAction()();
    } catch (error) {
      // A synchronous throw keeps the dialog open so the error can be shown;
      // unhandled, it reaches the ErrorHandler from this click listener.
      if (!onError) throw error;
      onError(error);
      return;
    }
    if (!result || typeof (result as Promise<void>).then !== 'function') {
      this.open.set(false);
      return;
    }
    void this.await(result, onError);
  }

  private async await(result: Promise<void>, onError: ((error: unknown) => void) | undefined): Promise<void> {
    this.pending.set(true);
    try {
      await result;
      this.open.set(false);
    } catch (error) {
      if (onError) onError(error);
      else console.error('[PixelAlertDialog] onAction rejected:', error);
    } finally {
      this.pending.set(false);
    }
  }
}
