// packages/ui-kit-vue/src/overlays/PixelDrawerFooter.vue
<script setup lang="ts">
import { computed, type VNode } from 'vue';
import { drawerFooterClasses, type Surface } from '@pxlkit/ui-kit-core';
import { useEffectiveSurface } from '../composables/surface.js';

/** Footer bar of a `PixelDrawer` for its actions, set off by a surface-aware divider. */
const props = defineProps<{
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
}>();
defineSlots<{
  /** Footer content, such as the actions. */
  default?(): VNode[];
}>();

const surface = useEffectiveSurface(() => props.surface);
const classes = computed(() => drawerFooterClasses(surface.value));
</script>

<template>
  <div :class="classes"><slot /></div>
</template>

// packages/ui-kit-angular/src/lib/overlays/pixel-drawer-footer.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { drawerFooterClasses, type Surface } from '@pxlkit/ui-kit-core';
import { injectEffectiveSurface } from '../overlay-foundation/pxl-kit-surface-provider';

/** Footer bar of a `<pxl-drawer>` for its actions, set off by a surface-aware divider. */
@Component({
  selector: 'pxl-drawer-footer',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { '[class]': 'classes()' },
  template: '<ng-content />',
})
export class PixelDrawerFooter {
  /** Surface override; defaults to the nearest provider. */
  readonly surface = input<Surface>();

  private readonly effectiveSurface = injectEffectiveSurface(() => this.surface());
  /** @internal */
  protected readonly classes = computed(() => drawerFooterClasses(this.effectiveSurface()));
}
