// packages/ui-kit/src/cards/PixelFeatureCard.tsx
'use client';

import React, { forwardRef } from 'react';
import {
  featureCardClasses,
  isCardActivationKey,
  type FeatureCardDescriptionLines as DescLines,
  type FeatureCardIconSize as IconSize,
  type FeatureCardOrientation as Orientation,
} from '@pxlkit/ui-kit-core';
import { cn, Surface, useEffectiveSurface } from '../common';
import { ToneKey } from '../tokens';

export interface PixelFeatureCardProps extends React.HTMLAttributes<HTMLElement> {
  /** Icon in the toned frame. */
  icon?: React.ReactNode;
  /** Width of the icon frame, in px. */
  iconSize?: IconSize;
  /** Badge above the icon: its label and tone (cyan by default). */
  badge?: { label: string; tone?: ToneKey };
  /** The heading, clamped to two lines. */
  title: string;
  /** Muted paragraph rendered under the title. */
  description?: string;
  /** Apply `line-clamp-N` + `min-h-[N lh]` to the description. */
  descriptionLines?: DescLines;
  /** @deprecated Use `description` for consistency with PixelCard / PixelPricingCard. */
  desc?: string;
  /** @deprecated Use `descriptionLines` for consistency with PixelCard / PixelPricingCard. */
  descLines?: DescLines;
  /** Footer under the description. */
  footer?: React.ReactNode;
  /** Tone of the icon frame. */
  tone?: ToneKey;
  /** Hover lift and focus ring; without an `href` the card is a button: give it an `onClick`. */
  interactive?: boolean;
  /**
   * When provided, the card renders as `<a href>` and accepts anchor-specific
   * attributes via the spread. Nesting interactive children inside the card
   * (e.g. PixelButton, PixelTextLink) is invalid HTML in this mode.
   */
  href?: string;
  /** Anchor target — only meaningful when `href` is set. */
  target?: React.AnchorHTMLAttributes<HTMLAnchorElement>['target'];
  /** Anchor rel — only meaningful when `href` is set. */
  rel?: React.AnchorHTMLAttributes<HTMLAnchorElement>['rel'];
  /** Anchor download — only meaningful when `href` is set. */
  download?: React.AnchorHTMLAttributes<HTMLAnchorElement>['download'];
  /** When `interactive=true` without `href`, an onClick is REQUIRED for accessibility. */
  onClick?: React.MouseEventHandler<HTMLElement>;
  /** Icon above the text, or beside it. */
  orientation?: Orientation;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
  /** Render with surface-aware border + radius chrome. Defaults to true — a feature card needs visible chrome. */
  bordered?: boolean;
}

export const PixelFeatureCard = forwardRef<HTMLElement, PixelFeatureCardProps>(
  function PixelFeatureCard(
    {
      icon,
      iconSize = 56,
      badge,
      title,
      description,
      descriptionLines,
      desc,
      descLines,
      footer,
      tone = 'neutral',
      interactive = false,
      href,
      target,
      rel,
      download,
      onClick,
      onKeyDown,
      orientation = 'vertical',
      surface: surfaceProp,
      bordered = true,
      className,
      children,
      ...rest
    },
    ref,
  ) {
    const surface = useEffectiveSurface(surfaceProp);
    const isLink = typeof href === 'string';
    const isInteractive = interactive || isLink;
    const isHorizontal = orientation === 'horizontal';
    const resolvedDescription = description ?? desc;
    const classes = featureCardClasses(surface, {
      tone,
      orientation,
      bordered,
      interactive: isInteractive,
      iconSize,
      badge,
      descriptionLines: descriptionLines ?? descLines,
    });

    const handleKeyDown: React.KeyboardEventHandler<HTMLElement> = (e) => {
      onKeyDown?.(e);
      if (e.defaultPrevented) return;
      if (!interactive || isLink) return;
      if (isCardActivationKey(e.key)) {
        e.preventDefault();
        onClick?.(e as unknown as React.MouseEvent<HTMLElement>);
      }
    };

    const root = cn(classes.root, className);

    const badgeSlot = (
      <div data-pxl-badge-slot className={classes.badgeRow}>
        {badge && <span className={classes.badge}>{badge.label}</span>}
      </div>
    );

    const iconSlot = icon ? (
      <div data-pxl-icon-frame className={classes.icon}>
        {icon}
      </div>
    ) : null;

    const titleSlot = <h3 className={classes.title}>{title}</h3>;

    const descSlot = resolvedDescription ? (
      <p className={classes.description}>{resolvedDescription}</p>
    ) : null;

    const spacer = !isHorizontal ? <div className={classes.spacer} /> : null;

    const footerSlot = footer ? <div className={classes.footer}>{footer}</div> : null;

    const body = isHorizontal ? (
      <>
        {badgeSlot}
        {iconSlot}
        <div className={classes.column}>
          {titleSlot}
          {descSlot}
          {footerSlot}
        </div>
      </>
    ) : (
      <>
        {badgeSlot}
        {iconSlot}
        {titleSlot}
        {descSlot}
        {spacer}
        {footerSlot}
      </>
    );

    if (isLink) {
      const anchorRest = rest as React.AnchorHTMLAttributes<HTMLAnchorElement>;
      return (
        <a
          ref={ref as React.Ref<HTMLAnchorElement>}
          href={href}
          target={target}
          rel={rel}
          download={download}
          onClick={onClick as React.MouseEventHandler<HTMLAnchorElement> | undefined}
          onKeyDown={onKeyDown}
          className={root}
          {...anchorRest}
        >
          {body}
          {children}
        </a>
      );
    }

    if (interactive) {
      // <article> does not permit role="button" (axe: aria-allowed-role), so
      // the interactive variant renders a generic <div> instead.
      return (
        <div
          ref={ref as React.Ref<HTMLDivElement>}
          className={root}
          role="button"
          tabIndex={0}
          onClick={onClick}
          onKeyDown={handleKeyDown}
          {...rest}
        >
          {body}
          {children}
        </div>
      );
    }

    return (
      <article
        ref={ref as React.Ref<HTMLElement>}
        className={root}
        onKeyDown={onKeyDown}
        {...rest}
      >
        {body}
        {children}
      </article>
    );
  },
);

PixelFeatureCard.displayName = 'PixelFeatureCard';

// packages/ui-kit-vue/src/cards/PixelFeatureCard.vue
<script setup lang="ts">
import { computed, type VNode } from 'vue';
import {
  featureCardClasses,
  isCardActivationKey,
  type CardBadge,
  type FeatureCardDescriptionLines,
  type FeatureCardIconSize,
  type FeatureCardOrientation,
  type Surface,
  type ToneKey,
} from '@pxlkit/ui-kit-core';
import { useEffectiveSurface } from '../composables/surface.js';

/**
 * Feature highlight card: a badge row, a toned icon frame, a title clamped to
 * two lines, a clamped description and a footer, stacked or with the icon
 * beside the text. The badge row keeps its height without a badge and the
 * clamps reserve their lines, so cards in a grid line up. It is an
 * `<article>`; with an `href` an `<a>` (the whole card is the link: keep
 * buttons and links out of it), and `interactive` without one a
 * `<div role="button">` in the tab order, which Enter and Space activate.
 * Attributes and listeners go to the card, and a `keydown` listener that
 * calls `preventDefault()` keeps Enter or Space from activating it.
 *
 * @example
 * <PixelFeatureCard title="Realtime sync" description="Push every keystroke to peers." tone="cyan">
 *   <template #icon><SyncIcon /></template>
 * </PixelFeatureCard>
 */
export interface PixelFeatureCardProps {
  /** The heading, clamped to two lines. */
  title: string;
  /** Muted paragraph under the title. */
  description?: string;
  /** Lines the description is clamped to; 3 when unset. */
  descriptionLines?: FeatureCardDescriptionLines;
  /** @deprecated Use `description`. */
  desc?: string;
  /** @deprecated Use `descriptionLines`. */
  descLines?: FeatureCardDescriptionLines;
  /** Width of the icon frame, in px. */
  iconSize?: FeatureCardIconSize;
  /** Badge above the icon: its label and tone (cyan by default). */
  badge?: CardBadge;
  /** Tone of the icon frame. */
  tone?: ToneKey;
  /** Hover lift and focus ring; without an `href` the card is a button: give it a `click` listener. */
  interactive?: boolean;
  /** Makes the card a link. */
  href?: string;
  /** Link target, with `href`. */
  target?: string;
  /** Link relationship, with `href`. */
  rel?: string;
  /** Downloads the link target, with `href`. */
  download?: string;
  /** Icon above the text, or beside it. */
  orientation?: FeatureCardOrientation;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
  /** Surface border, radius and background. */
  bordered?: boolean;
  /**
   * Click handler (`@click`). Declared as a prop because an interactive card
   * calls it on Enter and Space too, with the keyboard event.
   */
  onClick?: (event: MouseEvent | KeyboardEvent) => void;
}

// The attributes are bound between the card's own attributes and listeners:
// the consumer's attributes win, and its keydown listener runs first, so it
// can keep the card from activating.
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<PixelFeatureCardProps>(), {
  description: undefined,
  descriptionLines: undefined,
  desc: undefined,
  descLines: undefined,
  iconSize: 56,
  badge: undefined,
  tone: 'neutral',
  interactive: false,
  href: undefined,
  target: undefined,
  rel: undefined,
  download: undefined,
  orientation: 'vertical',
  surface: undefined,
  bordered: true,
});
defineSlots<{
  /** Content after the card's own, inside the card. */
  default?(): VNode[];
  /** Icon in the toned frame. */
  icon?(): VNode[];
  /** Footer under the description. */
  footer?(): VNode[];
}>();

const surface = useEffectiveSurface(() => props.surface);
const link = computed(() => props.href !== undefined);
const button = computed(() => props.interactive && !link.value);
const horizontal = computed(() => props.orientation === 'horizontal');
const description = computed(() => props.description ?? props.desc);
const classes = computed(() =>
  featureCardClasses(surface.value, {
    tone: props.tone,
    orientation: props.orientation,
    bordered: props.bordered,
    interactive: props.interactive || link.value,
    iconSize: props.iconSize,
    badge: props.badge,
    descriptionLines: props.descriptionLines ?? props.descLines,
  }),
);

function activate(event: KeyboardEvent) {
  if (event.defaultPrevented || !button.value || !isCardActivationKey(event.key)) return;
  event.preventDefault();
  props.onClick?.(event);
}
</script>

<template>
  <component
    :is="link ? 'a' : button ? 'div' : 'article'"
    :href="link ? href : undefined"
    :target="link ? target : undefined"
    :rel="link ? rel : undefined"
    :download="link ? download : undefined"
    :role="button ? 'button' : undefined"
    :tabindex="button ? 0 : undefined"
    :class="classes.root"
    v-bind="$attrs"
    @click="onClick"
    @keydown="activate"
  >
    <div data-pxl-badge-slot="true" :class="classes.badgeRow">
      <span v-if="badge" :class="classes.badge">{{ badge.label }}</span>
    </div>
    <div v-if="$slots.icon" data-pxl-icon-frame="true" :class="classes.icon"><slot name="icon" /></div>
    <div v-if="horizontal" :class="classes.column">
      <h3 :class="classes.title">{{ title }}</h3>
      <p v-if="description" :class="classes.description">{{ description }}</p>
      <div v-if="$slots.footer" :class="classes.footer"><slot name="footer" /></div>
    </div>
    <template v-else>
      <h3 :class="classes.title">{{ title }}</h3>
      <p v-if="description" :class="classes.description">{{ description }}</p>
      <div :class="classes.spacer" />
      <div v-if="$slots.footer" :class="classes.footer"><slot name="footer" /></div>
    </template>
    <slot />
  </component>
</template>
