// packages/ui-kit/src/cards/PixelPricingCard.tsx
'use client';

import React, { forwardRef } from 'react';
import {
  PRICING_PREVIOUS_PRICE_LABEL,
  pricingCardClasses,
  pricingFeature,
  pricingPopularLabel,
} from '@pxlkit/ui-kit-core';
import {
  cn,
  Surface,
  CheckIcon,
  CloseIcon,
  useEffectiveSurface,
} from '../common';
import { type ToneKey } from '../tokens';

export interface PixelPricingCardProps extends React.HTMLAttributes<HTMLElement> {
  /** Tone of the price, the feature marks and, highlighted, the chrome. */
  tone?: ToneKey;
  /** Icon above the name, in the tone. */
  icon?: React.ReactNode;
  /** Plan name. */
  name: string;
  /** Muted line under the name. */
  description?: string;
  /** Clamp the description to N lines. Defaults to 2; use 'none' to let long copy flow. */
  descriptionLines?: 2 | 3 | 'none';
  /** Price, billing period and old price. */
  price: { amount: string | number; period?: string; strikethrough?: string | number };
  /** Promo badge rendered beside the price (e.g. a discount PixelBadge). */
  priceBadge?: React.ReactNode;
  /** Ribbon over the top edge: its label (`POPULAR`) and tone (gold). */
  popular?: { label?: string; tone?: ToneKey };
  /** The feature list. */
  features?: { label: string; tooltip?: string; included?: boolean; highlight?: boolean }[];
  /** Call to action under the features. */
  cta?: React.ReactNode;
  /** Tints the border and background and adds a glow. */
  highlight?: boolean;
  /** Fine print under the call to action. */
  footer?: React.ReactNode;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
  /** Render with surface-aware border + radius chrome. Defaults to true — a pricing card needs visible chrome. */
  bordered?: boolean;
}

export const PixelPricingCard = forwardRef<HTMLElement, PixelPricingCardProps>(
  function PixelPricingCard(
    {
      tone = 'neutral',
      icon,
      name,
      description,
      descriptionLines = 2,
      price,
      priceBadge,
      popular,
      features,
      cta,
      highlight = false,
      footer,
      surface: surfaceProp,
      bordered = true,
      className,
      ...rest
    },
    ref,
  ) {
    const surface = useEffectiveSurface(surfaceProp);
    const classes = pricingCardClasses(surface, {
      tone,
      highlight,
      bordered,
      descriptionLines,
      popularTone: popular?.tone,
    });

    const Article = 'article' as 'article';

    return (
      <Article
        ref={ref as React.Ref<HTMLElement>}
        className={cn(classes.root, className)}
        {...rest}
      >
        <div data-pxl-ribbon-slot className={classes.ribbonRow}>
          {popular && <span className={classes.popular}>{pricingPopularLabel(popular)}</span>}
        </div>

        <div className={classes.head}>
          {icon && (
            <span className={classes.icon} aria-hidden>
              {icon}
            </span>
          )}
          <h3 className={classes.name}>{name}</h3>
          <p data-pxl-description-slot className={classes.description}>
            {description ?? ''}
          </p>
        </div>

        <div className={classes.priceRow}>
          {price.strikethrough !== undefined && (
            <s className={classes.previousPrice}>
              <span className="sr-only">{PRICING_PREVIOUS_PRICE_LABEL}</span>
              {price.strikethrough}
            </s>
          )}
          <span className={classes.amount}>{price.amount}</span>
          {price.period && <span className={classes.period}>{price.period}</span>}
          {priceBadge && (
            <span data-pxl-price-badge-slot className={classes.priceBadge}>
              {priceBadge}
            </span>
          )}
        </div>

        {features && features.length > 0 && (
          <ul className={classes.features}>
            {features.map((f, i) => {
              const feature = pricingFeature(f, tone);
              return (
                <li key={i} className={classes.feature}>
                  <span className={feature.markClasses} aria-hidden>
                    {feature.included ? <CheckIcon /> : <CloseIcon />}
                  </span>
                  <span title={f.tooltip} className={feature.labelClasses}>
                    <span className="sr-only">{feature.srLabel}</span>
                    {f.label}
                  </span>
                </li>
              );
            })}
          </ul>
        )}

        <div className={classes.spacer} aria-hidden />

        {cta && <div className={classes.cta}>{cta}</div>}
        {footer && <div className={classes.footer}>{footer}</div>}
      </Article>
    );
  },
);

PixelPricingCard.displayName = 'PixelPricingCard';

// packages/ui-kit-vue/src/cards/PixelPricingCard.vue
<script setup lang="ts">
import { computed, type VNode } from 'vue';
import {
  PRICING_PREVIOUS_PRICE_LABEL,
  pricingCardClasses,
  pricingFeature,
  pricingPopularLabel,
  type PricingCardDescriptionLines,
  type PricingCardFeature,
  type PricingCardPopular,
  type PricingCardPrice,
  type Surface,
  type ToneKey,
} from '@pxlkit/ui-kit-core';
import PixelGlyph from '../_internal/PixelGlyph.vue';
import { useEffectiveSurface } from '../composables/surface.js';

/**
 * Pricing tier card (`<article>`): an optional popular ribbon over the top
 * edge, the plan name and description, the price with an optional old price
 * struck through and a badge beside it, the feature list — included features
 * checked, excluded ones crossed out, both announced as such — and a call to
 * action. The ribbon row and the description keep their height when empty,
 * so tiers side by side line up. Attributes go to the article.
 *
 * @example
 * <PixelPricingCard name="Pro" tone="gold" highlight :price="{ amount: '$49', period: '/mo' }" :popular="{}">
 *   <template #cta><PixelButton tone="gold" full-width>Upgrade</PixelButton></template>
 * </PixelPricingCard>
 */
export interface PixelPricingCardProps {
  /** Plan name. */
  name: string;
  /** Price, billing period and old price. */
  price: PricingCardPrice;
  /** Muted line under the name. */
  description?: string;
  /** Lines the description is clamped to, or `none` to let it flow. */
  descriptionLines?: PricingCardDescriptionLines;
  /** Ribbon over the top edge: its label (`POPULAR`) and tone (gold). */
  popular?: PricingCardPopular;
  /** The feature list. */
  features?: PricingCardFeature[];
  /** Tone of the price, the feature marks and, highlighted, the chrome. */
  tone?: ToneKey;
  /** Tints the border and background and adds a glow. */
  highlight?: boolean;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
  /** Surface border, radius and background. */
  bordered?: boolean;
}

const props = withDefaults(defineProps<PixelPricingCardProps>(), {
  description: undefined,
  descriptionLines: 2,
  popular: undefined,
  features: undefined,
  tone: 'neutral',
  highlight: false,
  surface: undefined,
  bordered: true,
});
defineSlots<{
  /** Icon above the name, in the tone. */
  icon?(): VNode[];
  /** Badge beside the price (a discount). */
  'price-badge'?(): VNode[];
  /** Call to action under the features. */
  cta?(): VNode[];
  /** Fine print under the call to action. */
  footer?(): VNode[];
}>();

const surface = useEffectiveSurface(() => props.surface);
const classes = computed(() =>
  pricingCardClasses(surface.value, {
    tone: props.tone,
    highlight: props.highlight,
    bordered: props.bordered,
    descriptionLines: props.descriptionLines,
    popularTone: props.popular?.tone,
  }),
);
const featureRows = computed(() =>
  (props.features ?? []).map((feature) => ({ feature, view: pricingFeature(feature, props.tone) })),
);
</script>

<template>
  <article :class="classes.root">
    <div data-pxl-ribbon-slot="true" :class="classes.ribbonRow">
      <span v-if="popular" :class="classes.popular">{{ pricingPopularLabel(popular) }}</span>
    </div>
    <div :class="classes.head">
      <span v-if="$slots.icon" :class="classes.icon" aria-hidden="true"><slot name="icon" /></span>
      <h3 :class="classes.name">{{ name }}</h3>
      <p data-pxl-description-slot="true" :class="classes.description">{{ description ?? '' }}</p>
    </div>
    <div :class="classes.priceRow">
      <s v-if="price.strikethrough !== undefined" :class="classes.previousPrice">
        <span class="sr-only">{{ PRICING_PREVIOUS_PRICE_LABEL }}</span>{{ price.strikethrough }}
      </s>
      <span :class="classes.amount">{{ price.amount }}</span>
      <span v-if="price.period" :class="classes.period">{{ price.period }}</span>
      <span v-if="$slots['price-badge']" data-pxl-price-badge-slot="true" :class="classes.priceBadge">
        <slot name="price-badge" />
      </span>
    </div>
    <ul v-if="featureRows.length > 0" :class="classes.features">
      <li v-for="({ feature, view }, index) in featureRows" :key="index" :class="classes.feature">
        <span :class="view.markClasses" aria-hidden="true"><PixelGlyph :name="view.glyph" /></span>
        <span :title="feature.tooltip" :class="view.labelClasses">
          <span class="sr-only">{{ view.srLabel }}</span>{{ feature.label }}
        </span>
      </li>
    </ul>
    <div :class="classes.spacer" aria-hidden="true" />
    <div v-if="$slots.cta" :class="classes.cta"><slot name="cta" /></div>
    <div v-if="$slots.footer" :class="classes.footer"><slot name="footer" /></div>
  </article>
</template>
