// packages/ui-kit-vue/src/forms/PixelRadioGroup.vue
<script setup lang="ts">
import { computed } from 'vue';
import { radioGroupClasses, radioIndicatorClasses, type Surface, type Tone } from '@pxlkit/ui-kit-core';
import { useControllableState } from '../composables/controllable.js';
import { useEffectiveSurface } from '../composables/surface.js';
import type { Option } from './_internal/option.js';

/**
 * Single-select radios in a `<fieldset role="radiogroup">` whose `<legend>`
 * is the label, with a pixel dot indicator, tones and surfaces. Bind the
 * selected value with `v-model`; left unbound, the group keeps its own
 * selection, starting with none. With a `name` a hidden input submits the
 * value in forms.
 */
export interface PixelRadioGroupProps {
  /** Legend rendered above the radios. */
  label: string;
  /** Selected value (`v-model`); leave unset for an uncontrolled group. */
  modelValue?: string;
  /** The radios. */
  options: Option[];
  /** Disables every radio. */
  disabled?: boolean;
  /** Tone of the selected radio. */
  tone?: Tone;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
  /** Form field name — a hidden input submits the value. */
  name?: string;
  /** Marks the field as required for native form validation. */
  required?: boolean;
}

const props = withDefaults(defineProps<PixelRadioGroupProps>(), {
  modelValue: undefined,
  disabled: false,
  tone: 'cyan',
  surface: undefined,
  name: undefined,
  required: false,
});

const emit = defineEmits<{
  /** The value of the radio the user picked. */
  'update:modelValue': [value: string];
}>();

const surface = useEffectiveSurface(() => props.surface);
const [value, setValue] = useControllableState<string>({
  value: () => props.modelValue,
  defaultValue: () => '',
  onChange: (next) => emit('update:modelValue', next),
});

const classes = computed(() => radioGroupClasses(surface.value, props.disabled));
const radios = computed(() =>
  props.options.map((option) => {
    const checked = value.value === option.value;
    return {
      option,
      checked,
      ...radioIndicatorClasses(surface.value, { tone: props.tone, checked, disabled: props.disabled }),
    };
  }),
);

function select(option: Option) {
  if (!props.disabled) setValue(option.value);
}
</script>

<template>
  <fieldset :class="classes.group" role="radiogroup" :aria-disabled="disabled" :aria-required="required || undefined">
    <input v-if="name" type="hidden" :name="name" :value="value" :required="required" />
    <legend :class="classes.legend">{{ label }}</legend>
    <button
      v-for="radio in radios"
      :key="radio.option.value"
      type="button"
      role="radio"
      :aria-checked="radio.checked"
      :aria-disabled="disabled"
      :disabled="disabled"
      :class="classes.radio"
      @click="select(radio.option)"
    >
      <span :class="radio.indicator"><span v-if="radio.checked" :class="radio.dot" /></span>
      <span :class="classes.label">{{ radio.option.label }}</span>
    </button>
  </fieldset>
</template>

// packages/ui-kit-angular/src/lib/forms/pixel-radio-group.ts
import { ChangeDetectionStrategy, Component, computed, input, model } from '@angular/core';
import type { ControlValueAccessor } from '@angular/forms';
import { radioGroupClasses, radioIndicatorClasses, type Surface, type Tone } from '@pxlkit/ui-kit-core';
import { booleanOr, withDefault } from '../_internal/coercion';
import { FormBridge, provideValueAccessor } from '../_internal/value-accessor';
import { injectEffectiveSurface } from '../overlay-foundation/pxl-kit-surface-provider';
import type { Option } from './option';

/**
 * Single-select radios with a pixel dot indicator, tones and surfaces. Apply
 * it to a `<fieldset>` — it becomes the `radiogroup`, and its `<legend>` the
 * label. Bind the selected value with `[(value)]`, use it as a form control
 * (`ngModel`, `formControlName`), or leave it uncontrolled. With a `name` a
 * hidden input submits the value in native forms.
 *
 * @example
 * <fieldset pxlRadioGroup label="Plan" [options]="plans" [(value)]="plan"></fieldset>
 */
@Component({
  selector: 'fieldset[pxlRadioGroup]',
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [provideValueAccessor(() => PixelRadioGroup)],
  host: {
    role: 'radiogroup',
    '[class]': 'classes().group',
    '[attr.aria-disabled]': 'isDisabled()',
    '[attr.aria-required]': 'required() || null',
    // A native `disabled` or `name` on the fieldset would disable or name it
    // as a form control; the radios and the hidden input carry these.
    '[attr.disabled]': 'null',
    '[attr.name]': 'null',
    '[attr.value]': 'null',
    '[attr.required]': 'null',
  },
  template: `
    @if (name()) {
      <input type="hidden" [attr.name]="name()" [value]="value() ?? ''" [required]="required()" />
    }
    <legend [class]="classes().legend">{{ label() }}</legend>
    @for (radio of radios(); track radio.option.value) {
      <button
        type="button"
        role="radio"
        [attr.aria-checked]="radio.checked"
        [attr.aria-disabled]="isDisabled()"
        [disabled]="isDisabled()"
        [class]="classes().radio"
        (click)="select(radio.option)"
        (blur)="form.touched()"
      >
        <span [class]="radio.indicator">
          @if (radio.checked) {
            <span [class]="radio.dot"></span>
          }
        </span>
        <span [class]="classes().label">{{ radio.option.label }}</span>
      </button>
    }
  `,
})
export class PixelRadioGroup implements ControlValueAccessor {
  /** Legend rendered above the radios. */
  readonly label = input.required<string>();
  /** Selected value (`[(value)]`); leave unset for an uncontrolled group. */
  readonly value = model<string | undefined>(undefined);
  /** The radios. */
  readonly options = input.required<Option[]>();
  /** Disables every radio. */
  readonly disabled = input(false, { transform: booleanOr(false) });
  /** Tone of the selected radio. */
  readonly tone = input<Tone, Tone | undefined>('cyan', { transform: withDefault<Tone>('cyan') });
  /** Surface override; defaults to the nearest provider. */
  readonly surface = input<Surface>();
  /** Form field name — a hidden input submits the value. */
  readonly name = input<string>();
  /** Marks the field as required for native form validation. */
  readonly required = input(false, { transform: booleanOr(false) });

  /** @internal */
  protected readonly form = new FormBridge<string>();
  private readonly effectiveSurface = injectEffectiveSurface(() => this.surface());

  /** @internal */
  protected readonly isDisabled = computed(() => this.disabled() || this.form.disabled());
  /** @internal */
  protected readonly classes = computed(() => radioGroupClasses(this.effectiveSurface(), this.isDisabled()));
  /** @internal */
  protected readonly radios = computed(() =>
    this.options().map((option) => {
      const checked = this.value() === option.value;
      return {
        option,
        checked,
        ...radioIndicatorClasses(this.effectiveSurface(), { tone: this.tone(), checked, disabled: this.isDisabled() }),
      };
    }),
  );

  /** @internal */
  protected select(option: Option): void {
    if (this.isDisabled()) return;
    this.value.set(option.value);
    this.form.changed(option.value);
  }

  /** @internal ControlValueAccessor */
  writeValue(value: unknown): void {
    this.value.set(value == null ? undefined : String(value));
  }

  /** @internal ControlValueAccessor */
  registerOnChange(fn: (value: string) => void): void {
    this.form.registerOnChange(fn);
  }

  /** @internal ControlValueAccessor */
  registerOnTouched(fn: () => void): void {
    this.form.registerOnTouched(fn);
  }

  /** @internal ControlValueAccessor */
  setDisabledState(disabled: boolean): void {
    this.form.disabled.set(disabled);
  }
}
