// packages/ui-kit-vue/src/forms/PixelSegmented.vue
<script setup lang="ts">
import { computed } from 'vue';
import { segmentClasses, segmentedClasses, segmentedGroupName, type Surface, type Tone } from '@pxlkit/ui-kit-core';
import { useControllableState } from '../composables/controllable.js';
import { useEffectiveSurface } from '../composables/surface.js';
import type { Option } from './_internal/option.js';

/**
 * Single-select segmented control: a row of `aria-pressed` buttons under an
 * optional caption, named by `label` or `aria-label`. Bind the selected
 * value with `v-model`; left unbound, the control keeps its own selection,
 * starting with none. With a `name` a hidden input submits the value in
 * forms.
 */
export interface PixelSegmentedProps {
  /** Caption above the segments; omitted when empty. */
  label?: string;
  /** Selected value (`v-model`); leave unset for an uncontrolled control. */
  modelValue?: string;
  /** The segments. */
  options: Option[];
  /** Disables every segment. */
  disabled?: boolean;
  /** Tone of the selected segment. */
  tone?: Tone;
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
  /** Form field name — a hidden input submits the value. */
  name?: string;
  /** Marks the field as required for native form validation. */
  required?: boolean;
  /** Accessible name of the segments when no visible `label` is shown. */
  ariaLabel?: string;
}

const props = withDefaults(defineProps<PixelSegmentedProps>(), {
  label: undefined,
  modelValue: undefined,
  disabled: false,
  tone: 'green',
  surface: undefined,
  name: undefined,
  required: false,
  ariaLabel: undefined,
});

const emit = defineEmits<{
  /** The value of the segment the user picked. */
  'update:modelValue': [value: string];
}>();

const surface = useEffectiveSurface(() => props.surface);
const [value, setValue] = useControllableState<string>({
  value: () => props.modelValue,
  defaultValue: () => '',
  onChange: (next) => emit('update:modelValue', next),
});

const classes = computed(() => segmentedClasses(surface.value, props.disabled));
const groupName = computed(() => segmentedGroupName(props.ariaLabel, props.label));
const segments = computed(() =>
  props.options.map((option) => {
    const active = value.value === option.value;
    return {
      option,
      active,
      class: segmentClasses(surface.value, { tone: props.tone, active, disabled: props.disabled }),
    };
  }),
);

function select(option: Option) {
  if (!props.disabled) setValue(option.value);
}
</script>

<template>
  <div :class="classes.root">
    <input v-if="name" type="hidden" :name="name" :value="value" :required="required" />
    <p v-if="label" :class="classes.label">{{ label }}</p>
    <div :role="groupName ? 'group' : undefined" :aria-label="groupName" :class="classes.track">
      <button
        v-for="segment in segments"
        :key="segment.option.value"
        type="button"
        :aria-pressed="segment.active"
        :aria-disabled="disabled"
        :disabled="disabled"
        :class="segment.class"
        @click="select(segment.option)"
      >
        {{ segment.option.label }}
      </button>
    </div>
  </div>
</template>

// packages/ui-kit-angular/src/lib/forms/pixel-segmented.ts
import { ChangeDetectionStrategy, Component, computed, input, model } from '@angular/core';
import type { ControlValueAccessor } from '@angular/forms';
import { segmentClasses, segmentedClasses, segmentedGroupName, type Surface, type Tone } from '@pxlkit/ui-kit-core';
import { booleanOr, withDefault } from '../_internal/coercion';
import { FormBridge, provideValueAccessor } from '../_internal/value-accessor';
import { injectEffectiveSurface } from '../overlay-foundation/pxl-kit-surface-provider';
import type { Option } from './option';

/**
 * Single-select segmented control: a row of `aria-pressed` buttons under an
 * optional caption, named by `label` or `aria-label`. Bind the selected
 * value with `[(value)]`, use it as a form control (`ngModel`,
 * `formControlName`), or leave it uncontrolled. With a `name` a hidden input
 * submits the value in native forms. The host is the control's root.
 *
 * @example
 * <pxl-segmented label="View" [options]="views" [(value)]="view" />
 */
@Component({
  selector: 'pxl-segmented',
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [provideValueAccessor(() => PixelSegmented)],
  host: {
    '[class]': 'classes().root',
    // These inputs describe the segments and the hidden input; on the host
    // `aria-label` would name a role-less element and the form attributes
    // would mislead form tooling.
    '[attr.aria-label]': 'null',
    '[attr.name]': 'null',
    '[attr.value]': 'null',
    '[attr.disabled]': 'null',
    '[attr.required]': 'null',
  },
  template: `
    @if (name()) {
      <input type="hidden" [attr.name]="name()" [value]="value() ?? ''" [required]="required()" />
    }
    @if (label()) {
      <p [class]="classes().label">{{ label() }}</p>
    }
    <div [attr.role]="groupName() ? 'group' : null" [attr.aria-label]="groupName() ?? null" [class]="classes().track">
      @for (segment of segments(); track segment.option.value) {
        <button
          type="button"
          [attr.aria-pressed]="segment.active"
          [attr.aria-disabled]="isDisabled()"
          [disabled]="isDisabled()"
          [class]="segment.class"
          (click)="select(segment.option)"
          (blur)="form.touched()"
        >{{ segment.option.label }}</button>
      }
    </div>
  `,
})
export class PixelSegmented implements ControlValueAccessor {
  /** Caption above the segments; omitted when empty. */
  readonly label = input<string>();
  /** Selected value (`[(value)]`); leave unset for an uncontrolled control. */
  readonly value = model<string | undefined>(undefined);
  /** The segments. */
  readonly options = input.required<Option[]>();
  /** Disables every segment. */
  readonly disabled = input(false, { transform: booleanOr(false) });
  /** Tone of the selected segment. */
  readonly tone = input<Tone, Tone | undefined>('green', { transform: withDefault<Tone>('green') });
  /** Surface override; defaults to the nearest provider. */
  readonly surface = input<Surface>();
  /** Form field name — a hidden input submits the value. */
  readonly name = input<string>();
  /** Marks the field as required for native form validation. */
  readonly required = input(false, { transform: booleanOr(false) });
  /** Accessible name of the segments when no visible `label` is shown. */
  readonly ariaLabel = input<string | undefined>(undefined, { alias: 'aria-label' });

  /** @internal */
  protected readonly form = new FormBridge<string>();
  private readonly effectiveSurface = injectEffectiveSurface(() => this.surface());

  /** @internal */
  protected readonly isDisabled = computed(() => this.disabled() || this.form.disabled());
  /** @internal */
  protected readonly classes = computed(() => segmentedClasses(this.effectiveSurface(), this.isDisabled()));
  /** @internal */
  protected readonly groupName = computed(() => segmentedGroupName(this.ariaLabel(), this.label()));
  /** @internal */
  protected readonly segments = computed(() =>
    this.options().map((option) => {
      const active = this.value() === option.value;
      return {
        option,
        active,
        class: segmentClasses(this.effectiveSurface(), { tone: this.tone(), active, disabled: this.isDisabled() }),
      };
    }),
  );

  /** @internal */
  protected select(option: Option): void {
    if (this.isDisabled()) return;
    this.value.set(option.value);
    this.form.changed(option.value);
  }

  /** @internal ControlValueAccessor */
  writeValue(value: unknown): void {
    this.value.set(value == null ? undefined : String(value));
  }

  /** @internal ControlValueAccessor */
  registerOnChange(fn: (value: string) => void): void {
    this.form.registerOnChange(fn);
  }

  /** @internal ControlValueAccessor */
  registerOnTouched(fn: () => void): void {
    this.form.registerOnTouched(fn);
  }

  /** @internal ControlValueAccessor */
  setDisabledState(disabled: boolean): void {
    this.form.disabled.set(disabled);
  }
}
