// packages/ui-kit-vue/src/forms/PixelDatePicker.vue
<script setup lang="ts">
import { computed, nextTick, ref, useAttrs, useId, useTemplateRef, watch } from 'vue';
import {
  calendarClasses,
  calendarDayClasses,
  calendarKeydown,
  calendarLocale,
  calendarTabStop,
  calendarTitle,
  calendarWeekdays,
  calendarWeeks,
  datePickerClasses,
  fieldDescribedBy,
  fieldMessageId,
  isDayDisabled,
  isSameDay,
  monthOf,
  shiftMonth,
  startOfDay,
  toIsoDate,
  type Size,
  type Surface,
} from '@pxlkit/ui-kit-core';
import FieldShell from '../_internal/FieldShell.vue';
import { useControllableState } from '../composables/controllable.js';
import { usePxlKitLocale } from '../composables/locale.js';
import { useEffectiveSurface } from '../composables/surface.js';
import PixelPopover from '../overlay-foundation/PixelPopover.vue';
import PixelPopoverContent from '../overlay-foundation/PixelPopoverContent.vue';
import PixelPopoverTrigger from '../overlay-foundation/PixelPopoverTrigger.js';

/** A quick pick shown above the grid. */
export interface PixelDatePickerPreset {
  label: string;
  value: Date;
}

/**
 * Date field: a trigger that shows the picked day and opens a month's grid
 * in a popover dialog, with optional quick-pick presets and a Clear button.
 * Focus moves to the picked day (today's without one) as it opens; the grid
 * takes the arrows (by day and week), Home / End (the week), PageUp /
 * PageDown (the month, the year with Shift) and Enter / Space to pick, which
 * closes it with focus back on the trigger. `min`, `max` and
 * `disabled-dates` rule days out; the week and names follow
 * `PxlKitLocaleProvider`. Bind the day with `v-model`, or leave it
 * uncontrolled with `default-value`; with a `name` a hidden input submits it
 * as `YYYY-MM-DD`. Extra attributes and listeners go to the trigger.
 *
 * @example
 * <PixelDatePicker v-model="due" label="Due date" clearable />
 */
export interface PixelDatePickerProps {
  /** The picked day (`v-model`), `null` for none; leave unset for an uncontrolled picker. */
  modelValue?: Date | null;
  /** Initial day while uncontrolled. */
  defaultValue?: Date;
  /** First day that can be picked. */
  min?: Date;
  /** Last day that can be picked. */
  max?: Date;
  /** Days that cannot be picked: a list, or a test of each day. */
  disabledDates?: Date[] | ((date: Date) => boolean);
  /** The trigger's text for the picked day; the locale's long date by default. */
  format?: (date: Date) => string;
  /** Text shown while no day is picked. */
  placeholder?: string;
  /** Shows a Clear button under the grid while a day is picked. */
  clearable?: boolean;
  /** Quick picks shown above the grid. */
  presets?: PixelDatePickerPreset[];
  /** Surface override; defaults to the nearest provider. */
  surface?: Surface;
  /** Trigger height. */
  size?: Size;
  /** Label rendered above the trigger. */
  label?: string;
  /** Helper text below the field; hidden while `error` is set. */
  hint?: string;
  /** Error message below the field; marks the trigger invalid. */
  error?: string;
  /** Form field name — a hidden input submits the day as `YYYY-MM-DD`. */
  name?: string;
  /** `id` of the trigger; generated when left out. */
  id?: string;
}

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<PixelDatePickerProps>(), {
  modelValue: undefined,
  defaultValue: undefined,
  min: undefined,
  max: undefined,
  disabledDates: undefined,
  format: undefined,
  placeholder: 'Select date',
  clearable: false,
  presets: undefined,
  surface: undefined,
  size: 'md',
  label: undefined,
  hint: undefined,
  error: undefined,
  name: undefined,
  id: undefined,
});

const emit = defineEmits<{
  /** The day picked, at its start, or `null` once cleared. */
  'update:modelValue': [date: Date | null];
}>();

const surface = useEffectiveSurface(() => props.surface);
const locale = usePxlKitLocale();
// Week start, month and weekday names follow the kit's locale.
const calendar = computed(() => calendarLocale(locale.value.locale));
const generatedId = useId();
const triggerId = computed(() => props.id ?? `pxl-date-${generatedId}`);
const attrs = useAttrs();
// Attributes are not reactive: the consumer's `aria-describedby` is read while
// rendering, and the hint / error is added to it while one shows.
const describedBy = () =>
  fieldDescribedBy(triggerId.value, props, attrs['aria-describedby'] as string | undefined);
const trigger = useTemplateRef<HTMLButtonElement>('trigger');
const grid = useTemplateRef<HTMLElement>('grid');

const [current, setCurrent] = useControllableState<Date | null>({
  value: () => props.modelValue,
  defaultValue: () => props.defaultValue ?? null,
  onChange: (next) => emit('update:modelValue', next),
});

const open = ref(false);
// The month on show in the grid.
const view = ref(monthOf(current.value ?? props.defaultValue ?? new Date()));
// Roving tabindex anchor: the day that should own focus.
const focusedDate = ref<Date>(current.value ?? new Date());

// Follow a value that changes from outside to its month.
watch(
  () => current.value?.getTime(),
  () => {
    if (current.value) view.value = monthOf(current.value);
  },
);
// A value cleared or replaced while open resets the focused day.
watch(current, (day) => {
  if (open.value) focusedDate.value = day ?? new Date();
});

const isDisabled = (date: Date) =>
  isDayDisabled(date, { min: props.min, max: props.max, disabledDates: props.disabledDates });

// Today as of the latest opening, for the current-date mark.
const today = ref(startOfDay(new Date()));
const title = computed(() => calendarTitle(calendar.value, view.value));
const weeks = computed(() => calendarWeeks(view.value, calendar.value.weekStartsOn));
// One day of the grid is in the tab order: the focused one, or the month's
// first enabled day while that one is not on show.
const tabStop = computed(() => calendarTabStop(weeks.value.flat(), focusedDate.value, isDisabled));
const cells = computed(() =>
  weeks.value.map((week) =>
    week.map((day) => {
      const disabled = isDisabled(day.date);
      const isToday = isSameDay(day.date, today.value);
      const selected = current.value ? isSameDay(day.date, current.value) : false;
      return {
        day,
        disabled,
        today: isToday,
        selected,
        class: calendarDayClasses(surface.value, { inMonth: day.inMonth, selected, today: isToday, disabled }),
      };
    }),
  ),
);

const classes = computed(() =>
  datePickerClasses(surface.value, { size: props.size, invalid: !!props.error, placeholder: !current.value }),
);
const gridClasses = computed(() => calendarClasses(surface.value));
const text = computed(() => (current.value ? (props.format ?? calendar.value.formatDay)(current.value) : props.placeholder));

async function focusTabStop() {
  await nextTick();
  grid.value?.querySelector<HTMLElement>('[role="gridcell"][tabindex="0"]')?.focus();
}

// Each opening shows the value's month with focus on its day (today's
// without a value).
function onOpenChange(next: boolean) {
  if (next) {
    if (current.value) view.value = monthOf(current.value);
    today.value = startOfDay(new Date());
    focusedDate.value = current.value ?? new Date();
  }
  open.value = next;
  if (next) void focusTabStop();
}

function pick(date: Date) {
  if (isDisabled(date)) return;
  setCurrent(startOfDay(date));
  open.value = false;
}

function showMonth(count: number) {
  view.value = shiftMonth(view.value, count);
}

function onKeydown(event: KeyboardEvent) {
  const action = calendarKeydown(event.key, focusedDate.value, {
    weekStartsOn: calendar.value.weekStartsOn,
    shiftKey: event.shiftKey,
    isDisabled,
  });
  if (!action) return;
  event.preventDefault();
  if (action.select) {
    pick(focusedDate.value);
  } else if (action.focus) {
    focusedDate.value = action.focus;
    // Page the view to the new day's month so its cell exists.
    view.value = monthOf(action.focus);
    void focusTabStop();
  }
}

defineExpose({
  /** The trigger button. */
  element: trigger,
});
</script>

<template>
  <FieldShell
    :label="label"
    :hint="hint"
    :error="error"
    :surface="surface"
    :html-for="triggerId"
    :message-id="fieldMessageId(triggerId)"
  >
    <span :class="classes.anchor">
      <PixelPopover :open="open" side="bottom" align="start" :surface="surface" @update:open="onOpenChange">
        <PixelPopoverTrigger>
          <button
            v-bind="$attrs"
            :id="triggerId"
            ref="trigger"
            type="button"
            aria-haspopup="dialog"
            :aria-invalid="error ? true : undefined"
            :aria-describedby="describedBy()"
            :class="classes.trigger"
          >
            <span :class="classes.value">{{ text }}</span>
            <span aria-hidden="true" :class="classes.mark">{{ current ? '×' : '▾' }}</span>
          </button>
        </PixelPopoverTrigger>
        <PixelPopoverContent :surface="surface" aria-label="Choose date" :class="classes.content">
          <div v-if="presets && presets.length > 0" :class="classes.presets">
            <button
              v-for="preset in presets"
              :key="preset.label"
              type="button"
              :class="classes.preset"
              @click="pick(preset.value)"
            >
              {{ preset.label }}
            </button>
          </div>
          <div :class="gridClasses.header">
            <button type="button" aria-label="Previous month" :class="gridClasses.nav" @click="showMonth(-1)">‹</button>
            <span :class="gridClasses.title" aria-live="polite">{{ title }}</span>
            <button type="button" aria-label="Next month" :class="gridClasses.nav" @click="showMonth(1)">›</button>
          </div>
          <div ref="grid" role="grid" :aria-label="title" :class="gridClasses.grid" @keydown="onKeydown">
            <div role="row" :class="gridClasses.row">
              <div
                v-for="weekday in calendarWeekdays(calendar)"
                :key="weekday"
                role="columnheader"
                :class="gridClasses.weekday"
              >
                {{ weekday }}
              </div>
            </div>
            <div v-for="(week, row) in cells" :key="row" role="row" :class="gridClasses.row">
              <button
                v-for="cell in week"
                :key="cell.day.iso"
                type="button"
                role="gridcell"
                :aria-label="calendar.formatDay(cell.day.date)"
                :aria-selected="cell.selected || undefined"
                :aria-current="cell.today ? 'date' : undefined"
                :aria-disabled="cell.disabled || undefined"
                :disabled="cell.disabled"
                :tabindex="cell.day === tabStop ? 0 : -1"
                :class="cell.class"
                @click="pick(cell.day.date)"
                @focus="focusedDate = cell.day.date"
              >
                {{ cell.day.date.getDate() }}
              </button>
            </div>
          </div>
          <div v-if="clearable && current" :class="classes.footer">
            <button type="button" :class="classes.clear" @click="setCurrent(null)">Clear</button>
          </div>
        </PixelPopoverContent>
      </PixelPopover>
      <input v-if="name" type="hidden" :name="name" :value="current ? toIsoDate(current) : ''" readonly />
    </span>
  </FieldShell>
</template>

// packages/ui-kit-angular/src/lib/forms/pixel-date-picker.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  Injector,
  afterNextRender,
  computed,
  effect,
  inject,
  input,
  linkedSignal,
  model,
  signal,
  untracked,
  viewChild,
} from '@angular/core';
import type { ControlValueAccessor } from '@angular/forms';
import {
  calendarClasses,
  calendarDayClasses,
  calendarKeydown,
  calendarLocale,
  calendarTabStop,
  calendarTitle,
  calendarWeekdays,
  calendarWeeks,
  datePickerClasses,
  fieldDescribedBy,
  fieldMessageId,
  isDayDisabled,
  isSameDay,
  monthOf,
  shiftMonth,
  startOfDay,
  toIsoDate,
  type Size,
  type Surface,
} from '@pxlkit/ui-kit-core';
import { booleanOr, withDefault } from '../_internal/coercion';
import { PixelFieldShell } from '../_internal/field-shell';
import { injectId } from '../_internal/ids';
import { FormBridge, provideValueAccessor } from '../_internal/value-accessor';
import { PixelPopover } from '../overlay-foundation/pixel-popover';
import { PixelPopoverContent } from '../overlay-foundation/pixel-popover-content';
import { PixelPopoverTrigger } from '../overlay-foundation/pixel-popover-trigger';
import { injectPxlKitLocale } from '../overlay-foundation/pxl-kit-locale-provider';
import { injectEffectiveSurface } from '../overlay-foundation/pxl-kit-surface-provider';

/** A quick pick shown above the grid. */
export interface PixelDatePickerPreset {
  label: string;
  value: Date;
}

/**
 * Date field: a trigger that shows the picked day and opens a month's grid
 * in a popover dialog, with optional quick-pick presets and a Clear button.
 * Focus moves to the picked day (today's without one) as it opens; the grid
 * takes the arrows (by day and week), Home / End (the week), PageUp /
 * PageDown (the month, the year with Shift) and Enter / Space to pick, which
 * closes it with focus back on the trigger. `min`, `max` and `disabledDates`
 * rule days out; the week and names follow `<pxl-locale-provider>`. Bind the
 * day with `[(value)]`, use it as a form control (`ngModel`,
 * `formControlName`), or leave it uncontrolled with `defaultValue`; with a
 * `name` a hidden input submits it as `YYYY-MM-DD`.
 *
 * The host is layout-neutral (`display: contents`).
 *
 * @example
 * <pxl-date-picker label="Due date" clearable [(value)]="due" />
 */
@Component({
  selector: 'pxl-date-picker',
  imports: [PixelFieldShell, PixelPopover, PixelPopoverTrigger, PixelPopoverContent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [provideValueAccessor(() => PixelDatePicker)],
  host: {
    '[style.display]': '"contents"',
    // These inputs describe the trigger and the hidden input; as attributes
    // on the host they would duplicate the id, describe the wrong element or
    // mislead form tooling and tests.
    '[attr.id]': 'null',
    '[attr.name]': 'null',
    '[attr.aria-describedby]': 'null',
    '[attr.data-testid]': 'null',
  },
  template: `
    <pxl-field-shell
      [label]="label()"
      [hint]="hint()"
      [error]="error()"
      [surface]="effectiveSurface()"
      [htmlFor]="triggerId()"
      [messageId]="messageId()"
    >
      <span [class]="classes().anchor">
        <pxl-popover
          [open]="open()"
          (openChange)="onOpenChange($event)"
          side="bottom"
          align="start"
          [surface]="effectiveSurface()"
        >
          <button
            pxlPopoverTrigger
            type="button"
            [id]="triggerId()"
            [attr.data-testid]="dataTestid() ?? null"
            aria-haspopup="dialog"
            [attr.aria-invalid]="error() ? true : null"
            [attr.aria-describedby]="describedBy() ?? null"
            [disabled]="form.disabled()"
            [class]="classes().trigger"
            (blur)="form.touched()"
          >
            <span [class]="classes().value">{{ text() }}</span>
            <span aria-hidden="true" [class]="classes().mark">{{ current() ? '×' : '▾' }}</span>
          </button>
          <div *pxlPopoverContent="effectiveSurface()" aria-label="Choose date" [class]="classes().content">
            @if (presets()?.length) {
              <div [class]="classes().presets">
                @for (preset of presets(); track preset.label) {
                  <button type="button" [class]="classes().preset" (click)="pick(preset.value)">{{ preset.label }}</button>
                }
              </div>
            }
            <div [class]="gridClasses().header">
              <button type="button" aria-label="Previous month" [class]="gridClasses().nav" (click)="showMonth(-1)">‹</button>
              <span [class]="gridClasses().title" aria-live="polite">{{ title() }}</span>
              <button type="button" aria-label="Next month" [class]="gridClasses().nav" (click)="showMonth(1)">›</button>
            </div>
            <div #grid role="grid" [attr.aria-label]="title()" [class]="gridClasses().grid" (keydown)="onKeydown($event)">
              <div role="row" [class]="gridClasses().row">
                @for (weekday of weekdays(); track weekday) {
                  <div role="columnheader" [class]="gridClasses().weekday">{{ weekday }}</div>
                }
              </div>
              @for (week of cells(); track $index) {
                <div role="row" [class]="gridClasses().row">
                  @for (cell of week; track cell.day.iso) {
                    <button
                      type="button"
                      role="gridcell"
                      [attr.aria-label]="cell.label"
                      [attr.aria-selected]="cell.selected || null"
                      [attr.aria-current]="cell.today ? 'date' : null"
                      [attr.aria-disabled]="cell.disabled || null"
                      [disabled]="cell.disabled"
                      [attr.tabindex]="cell.day === tabStop() ? 0 : -1"
                      [class]="cell.class"
                      (click)="pick(cell.day.date)"
                      (focus)="focusedDate.set(cell.day.date)"
                    >
                      {{ cell.day.date.getDate() }}
                    </button>
                  }
                </div>
              }
            </div>
            @if (clearable() && current()) {
              <div [class]="classes().footer">
                <button type="button" [class]="classes().clear" (click)="clear()">Clear</button>
              </div>
            }
          </div>
        </pxl-popover>
        @if (name()) {
          <input type="hidden" [attr.name]="name()" [value]="hiddenValue()" readonly />
        }
      </span>
    </pxl-field-shell>
  `,
})
export class PixelDatePicker implements ControlValueAccessor {
  /** The picked day (`[(value)]`), `null` for none; leave unset for an uncontrolled picker. */
  readonly value = model<Date | null | undefined>(undefined);
  /** Initial day while uncontrolled. */
  readonly defaultValue = input<Date>();
  /** First day that can be picked. */
  readonly min = input<Date>();
  /** Last day that can be picked. */
  readonly max = input<Date>();
  /** Days that cannot be picked: a list, or a test of each day. */
  readonly disabledDates = input<Date[] | ((date: Date) => boolean)>();
  /** The trigger's text for the picked day; the locale's long date by default. */
  readonly format = input<(date: Date) => string>();
  /** Text shown while no day is picked. */
  readonly placeholder = input<string, string | undefined>('Select date', { transform: withDefault('Select date') });
  /** Shows a Clear button under the grid while a day is picked. */
  readonly clearable = input(false, { transform: booleanOr(false) });
  /** Quick picks shown above the grid. */
  readonly presets = input<PixelDatePickerPreset[]>();
  /** Surface override; defaults to the nearest provider. */
  readonly surface = input<Surface>();
  /** Trigger height. */
  readonly size = input<Size, Size | undefined>('md', { transform: withDefault<Size>('md') });
  /** Label rendered above the trigger. */
  readonly label = input<string>();
  /** Helper text below the field; hidden while `error` is set. */
  readonly hint = input<string>();
  /** Error message below the field; marks the trigger invalid. */
  readonly error = input<string>();
  /** Form field name — a hidden input submits the day as `YYYY-MM-DD`. */
  readonly name = input<string>();
  /** `id` of the trigger; generated when left out. */
  readonly id = input<string>();
  /** Ids of more elements that describe the trigger; its hint / error is added while one shows. */
  readonly ariaDescribedby = input<string | undefined>(undefined, { alias: 'aria-describedby' });
  /** `data-testid` of the trigger. */
  readonly dataTestid = input<string | undefined>(undefined, { alias: 'data-testid' });

  /** @internal */
  protected readonly form = new FormBridge<Date | null>();
  /** @internal */
  protected readonly effectiveSurface = injectEffectiveSurface(() => this.surface());
  private readonly locale = injectPxlKitLocale();
  // Week start, month and weekday names follow the kit's locale.
  private readonly calendar = computed(() => calendarLocale(this.locale().locale));
  private readonly generatedId = injectId();
  private readonly injector = inject(Injector);
  private readonly grid = viewChild<ElementRef<HTMLElement>>('grid');

  /** @internal */
  protected readonly open = signal(false);
  /** @internal */
  protected readonly current = computed(() => {
    const value = this.value();
    return value === undefined ? (this.defaultValue() ?? null) : value;
  });
  /** @internal The month on show: it follows the value to its month whenever that changes. */
  protected readonly view = linkedSignal<number | undefined, { year: number; month: number }>({
    source: () => this.current()?.getTime(),
    computation: (time, previous) =>
      time !== undefined ? monthOf(new Date(time)) : (previous?.value ?? monthOf(this.defaultValue() ?? new Date())),
  });
  /** @internal Roving tabindex anchor: the day that should own focus, set as the grid opens. */
  protected readonly focusedDate = signal<Date>(new Date());
  // Today as of the latest opening, for the current-date mark.
  private readonly today = signal(startOfDay(new Date()));

  /** @internal */
  protected readonly triggerId = computed(() => this.id() ?? `pxl-date-${this.generatedId}`);
  /** @internal */
  protected readonly messageId = computed(() => fieldMessageId(this.triggerId()));
  /** @internal */
  protected readonly describedBy = computed(() =>
    fieldDescribedBy(this.triggerId(), { hint: this.hint(), error: this.error() }, this.ariaDescribedby()),
  );
  /** @internal */
  protected readonly text = computed(() => {
    const current = this.current();
    return current ? (this.format() ?? this.calendar().formatDay)(current) : this.placeholder();
  });
  /** @internal */
  protected readonly hiddenValue = computed(() => {
    const current = this.current();
    return current ? toIsoDate(current) : '';
  });
  /** @internal */
  protected readonly classes = computed(() =>
    datePickerClasses(this.effectiveSurface(), { size: this.size(), invalid: !!this.error(), placeholder: !this.current() }),
  );
  /** @internal */
  protected readonly gridClasses = computed(() => calendarClasses(this.effectiveSurface()));
  /** @internal */
  protected readonly title = computed(() => calendarTitle(this.calendar(), this.view()));
  /** @internal */
  protected readonly weekdays = computed(() => calendarWeekdays(this.calendar()));
  private readonly weeks = computed(() => calendarWeeks(this.view(), this.calendar().weekStartsOn));
  private readonly isDisabled = (date: Date) =>
    isDayDisabled(date, { min: this.min(), max: this.max(), disabledDates: this.disabledDates() });
  /**
   * @internal One day of the grid is in the tab order: the focused one, or the
   * month's first enabled day while that one is not on show.
   */
  protected readonly tabStop = computed(() => calendarTabStop(this.weeks().flat(), this.focusedDate(), this.isDisabled));
  /** @internal */
  protected readonly cells = computed(() => {
    const surface = this.effectiveSurface();
    const current = this.current();
    return this.weeks().map((week) =>
      week.map((day) => {
        const disabled = this.isDisabled(day.date);
        const today = isSameDay(day.date, this.today());
        const selected = current ? isSameDay(day.date, current) : false;
        return {
          day,
          label: this.calendar().formatDay(day.date),
          disabled,
          today,
          selected,
          class: calendarDayClasses(surface, { inMonth: day.inMonth, selected, today, disabled }),
        };
      }),
    );
  });

  constructor() {
    // A value cleared or replaced while open resets the focused day.
    effect(() => {
      const current = this.current();
      if (untracked(this.open)) this.focusedDate.set(current ?? new Date());
    });
  }

  /** @internal Each opening shows the value's month with focus on its day (today's without a value). */
  protected onOpenChange(open: boolean): void {
    if (open) {
      const current = this.current();
      if (current) this.view.set(monthOf(current));
      this.today.set(startOfDay(new Date()));
      this.focusedDate.set(current ?? new Date());
      this.focusTabStop();
    }
    this.open.set(open);
  }

  /** @internal */
  protected pick(date: Date): void {
    if (this.isDisabled(date)) return;
    this.setValue(startOfDay(date));
    this.open.set(false);
  }

  /** @internal */
  protected clear(): void {
    this.setValue(null);
  }

  /** @internal */
  protected showMonth(count: number): void {
    this.view.set(shiftMonth(this.view(), count));
  }

  /** @internal */
  protected onKeydown(event: KeyboardEvent): void {
    const action = calendarKeydown(event.key, this.focusedDate(), {
      weekStartsOn: this.calendar().weekStartsOn,
      shiftKey: event.shiftKey,
      isDisabled: this.isDisabled,
    });
    if (!action) return;
    event.preventDefault();
    if (action.select) {
      this.pick(this.focusedDate());
      return;
    }
    const next = action.focus;
    if (!next) return;
    this.focusedDate.set(next);
    // Page the view to the new day's month so its cell exists.
    this.view.set(monthOf(next));
    this.focusTabStop();
  }

  private setValue(value: Date | null): void {
    this.value.set(value);
    this.form.changed(value);
  }

  private focusTabStop(): void {
    afterNextRender(
      () => this.grid()?.nativeElement.querySelector<HTMLElement>('[role="gridcell"][tabindex="0"]')?.focus(),
      { injector: this.injector },
    );
  }

  /** @internal ControlValueAccessor */
  writeValue(value: unknown): void {
    this.value.set(value instanceof Date ? value : null);
  }

  /** @internal ControlValueAccessor */
  registerOnChange(fn: (value: Date | null) => void): void {
    this.form.registerOnChange(fn);
  }

  /** @internal ControlValueAccessor */
  registerOnTouched(fn: () => void): void {
    this.form.registerOnTouched(fn);
  }

  /** @internal ControlValueAccessor: the trigger is disabled with the form control. */
  setDisabledState(disabled: boolean): void {
    this.form.disabled.set(disabled);
  }
}
